//! Readline's built-in tables, as osh reports them.
//!
//! These are readline's *compiled-in* defaults, captured from the reference
//! bash (here bash 5.2.37(1)-release) under `INPUTRC=/dev/null` so that no
//! `/etc/inputrc` or `~/.inputrc` on the capturing machine is baked in as if it
//! were a default — see known-issues TD-OILS-NO-BIND-BUILTIN, which records
//! that the two differ: 493 emacs bindings with `/etc/inputrc` loaded versus
//! 488 without.
//!
//! They live in their own module rather than in `interp.rs` because that file
//! is already one translation unit big enough to run rustc out of memory when
//! built with `--test`.
//!
//! **Generated — do not edit by hand.** Run `scripts/gen-oils-bind-tables.py`
//! against a reference bash to rebuild it.

/// One of readline's keymaps: the names `bind -m` accepts for it, and every
/// key sequence bound in it paired with the function it runs.
///
/// The bindings are in `bind -p` order, which is the funmap order the listings
/// are expected to keep — grouped by function name, and by key sequence within
/// a function.
pub struct Keymap {
    /// Every name `bind -m` accepts for this map; several are aliases.
    pub names: &'static [&'static str],
    /// `(key sequence, function name)`, in `bind -p` order.
    pub bindings: &'static [(&'static str, &'static str)],
}

/// Every function name readline knows, in the order `bind -l` prints them
/// (sorted, which is the order the listing is expected to keep).
pub const FUNCTION_NAMES: [&str; 174] = [
    "abort",
    "accept-line",
    "alias-expand-line",
    "arrow-key-prefix",
    "backward-byte",
    "backward-char",
    "backward-delete-char",
    "backward-kill-line",
    "backward-kill-word",
    "backward-word",
    "beginning-of-history",
    "beginning-of-line",
    "bracketed-paste-begin",
    "call-last-kbd-macro",
    "capitalize-word",
    "character-search",
    "character-search-backward",
    "clear-display",
    "clear-screen",
    "complete",
    "complete-command",
    "complete-filename",
    "complete-hostname",
    "complete-into-braces",
    "complete-username",
    "complete-variable",
    "copy-backward-word",
    "copy-forward-word",
    "copy-region-as-kill",
    "dabbrev-expand",
    "delete-char",
    "delete-char-or-list",
    "delete-horizontal-space",
    "digit-argument",
    "display-shell-version",
    "do-lowercase-version",
    "downcase-word",
    "dump-functions",
    "dump-macros",
    "dump-variables",
    "dynamic-complete-history",
    "edit-and-execute-command",
    "emacs-editing-mode",
    "end-kbd-macro",
    "end-of-history",
    "end-of-line",
    "exchange-point-and-mark",
    "fetch-history",
    "forward-backward-delete-char",
    "forward-byte",
    "forward-char",
    "forward-search-history",
    "forward-word",
    "glob-complete-word",
    "glob-expand-word",
    "glob-list-expansions",
    "history-and-alias-expand-line",
    "history-expand-line",
    "history-search-backward",
    "history-search-forward",
    "history-substring-search-backward",
    "history-substring-search-forward",
    "insert-comment",
    "insert-completions",
    "insert-last-argument",
    "kill-line",
    "kill-region",
    "kill-whole-line",
    "kill-word",
    "magic-space",
    "menu-complete",
    "menu-complete-backward",
    "next-history",
    "next-screen-line",
    "non-incremental-forward-search-history",
    "non-incremental-forward-search-history-again",
    "non-incremental-reverse-search-history",
    "non-incremental-reverse-search-history-again",
    "old-menu-complete",
    "operate-and-get-next",
    "overwrite-mode",
    "paste-from-clipboard",
    "possible-command-completions",
    "possible-completions",
    "possible-filename-completions",
    "possible-hostname-completions",
    "possible-username-completions",
    "possible-variable-completions",
    "previous-history",
    "previous-screen-line",
    "print-last-kbd-macro",
    "quoted-insert",
    "re-read-init-file",
    "redraw-current-line",
    "reverse-search-history",
    "revert-line",
    "self-insert",
    "set-mark",
    "shell-backward-kill-word",
    "shell-backward-word",
    "shell-expand-line",
    "shell-forward-word",
    "shell-kill-word",
    "shell-transpose-words",
    "skip-csi-sequence",
    "spell-correct-word",
    "start-kbd-macro",
    "tab-insert",
    "tilde-expand",
    "transpose-chars",
    "transpose-words",
    "tty-status",
    "undo",
    "universal-argument",
    "unix-filename-rubout",
    "unix-line-discard",
    "unix-word-rubout",
    "upcase-word",
    "vi-append-eol",
    "vi-append-mode",
    "vi-arg-digit",
    "vi-bWord",
    "vi-back-to-indent",
    "vi-backward-bigword",
    "vi-backward-word",
    "vi-bword",
    "vi-change-case",
    "vi-change-char",
    "vi-change-to",
    "vi-char-search",
    "vi-column",
    "vi-complete",
    "vi-delete",
    "vi-delete-to",
    "vi-eWord",
    "vi-edit-and-execute-command",
    "vi-editing-mode",
    "vi-end-bigword",
    "vi-end-word",
    "vi-eof-maybe",
    "vi-eword",
    "vi-fWord",
    "vi-fetch-history",
    "vi-first-print",
    "vi-forward-bigword",
    "vi-forward-word",
    "vi-fword",
    "vi-goto-mark",
    "vi-insert-beg",
    "vi-insertion-mode",
    "vi-match",
    "vi-movement-mode",
    "vi-next-word",
    "vi-overstrike",
    "vi-overstrike-delete",
    "vi-prev-word",
    "vi-put",
    "vi-redo",
    "vi-replace",
    "vi-rubout",
    "vi-search",
    "vi-search-again",
    "vi-set-mark",
    "vi-subst",
    "vi-tilde-expand",
    "vi-undo",
    "vi-unix-word-rubout",
    "vi-yank-arg",
    "vi-yank-pop",
    "vi-yank-to",
    "yank",
    "yank-last-arg",
    "yank-nth-arg",
    "yank-pop",
];

/// readline's keymaps, in no particular order — `bind -m` looks up by name.
pub const KEYMAPS: [Keymap; 5] = [
    Keymap {
        names: &["emacs", "emacs-standard"],
        bindings: &[
            ("\\C-g", "abort"),
            ("\\C-x\\C-g", "abort"),
            ("\\M-\\C-g", "abort"),
            ("\\C-j", "accept-line"),
            ("\\C-m", "accept-line"),
            ("\\C-b", "backward-char"),
            ("\\M-OD", "backward-char"),
            ("\\M-[D", "backward-char"),
            ("\\C-h", "backward-delete-char"),
            ("\\C-?", "backward-delete-char"),
            ("\\C-x\\C-?", "backward-kill-line"),
            ("\\M-\\C-h", "backward-kill-word"),
            ("\\M-\\C-?", "backward-kill-word"),
            ("\\M-[1;3D", "backward-word"),
            ("\\M-[1;5D", "backward-word"),
            ("\\M-b", "backward-word"),
            ("\\M-<", "beginning-of-history"),
            ("\\C-a", "beginning-of-line"),
            ("\\M-OH", "beginning-of-line"),
            ("\\M-[H", "beginning-of-line"),
            ("\\M-[200~", "bracketed-paste-begin"),
            ("\\C-xe", "call-last-kbd-macro"),
            ("\\M-c", "capitalize-word"),
            ("\\C-]", "character-search"),
            ("\\M-\\C-]", "character-search-backward"),
            ("\\M-\\C-l", "clear-display"),
            ("\\C-l", "clear-screen"),
            ("\\C-i", "complete"),
            ("\\M-\\e", "complete"),
            ("\\M-!", "complete-command"),
            ("\\M-/", "complete-filename"),
            ("\\M-@", "complete-hostname"),
            ("\\M-{", "complete-into-braces"),
            ("\\M-~", "complete-username"),
            ("\\M-$", "complete-variable"),
            ("\\C-d", "delete-char"),
            ("\\M-[3~", "delete-char"),
            ("\\M-\\\\", "delete-horizontal-space"),
            ("\\M--", "digit-argument"),
            ("\\M-0", "digit-argument"),
            ("\\M-1", "digit-argument"),
            ("\\M-2", "digit-argument"),
            ("\\M-3", "digit-argument"),
            ("\\M-4", "digit-argument"),
            ("\\M-5", "digit-argument"),
            ("\\M-6", "digit-argument"),
            ("\\M-7", "digit-argument"),
            ("\\M-8", "digit-argument"),
            ("\\M-9", "digit-argument"),
            ("\\C-x\\C-v", "display-shell-version"),
            ("\\C-xA", "do-lowercase-version"),
            ("\\C-xB", "do-lowercase-version"),
            ("\\C-xC", "do-lowercase-version"),
            ("\\C-xD", "do-lowercase-version"),
            ("\\C-xE", "do-lowercase-version"),
            ("\\C-xF", "do-lowercase-version"),
            ("\\C-xG", "do-lowercase-version"),
            ("\\C-xH", "do-lowercase-version"),
            ("\\C-xI", "do-lowercase-version"),
            ("\\C-xJ", "do-lowercase-version"),
            ("\\C-xK", "do-lowercase-version"),
            ("\\C-xL", "do-lowercase-version"),
            ("\\C-xM", "do-lowercase-version"),
            ("\\C-xN", "do-lowercase-version"),
            ("\\C-xO", "do-lowercase-version"),
            ("\\C-xP", "do-lowercase-version"),
            ("\\C-xQ", "do-lowercase-version"),
            ("\\C-xR", "do-lowercase-version"),
            ("\\C-xS", "do-lowercase-version"),
            ("\\C-xT", "do-lowercase-version"),
            ("\\C-xU", "do-lowercase-version"),
            ("\\C-xV", "do-lowercase-version"),
            ("\\C-xW", "do-lowercase-version"),
            ("\\C-xX", "do-lowercase-version"),
            ("\\C-xY", "do-lowercase-version"),
            ("\\C-xZ", "do-lowercase-version"),
            ("\\M-A", "do-lowercase-version"),
            ("\\M-B", "do-lowercase-version"),
            ("\\M-C", "do-lowercase-version"),
            ("\\M-D", "do-lowercase-version"),
            ("\\M-E", "do-lowercase-version"),
            ("\\M-F", "do-lowercase-version"),
            ("\\M-G", "do-lowercase-version"),
            ("\\M-H", "do-lowercase-version"),
            ("\\M-I", "do-lowercase-version"),
            ("\\M-J", "do-lowercase-version"),
            ("\\M-K", "do-lowercase-version"),
            ("\\M-L", "do-lowercase-version"),
            ("\\M-M", "do-lowercase-version"),
            ("\\M-N", "do-lowercase-version"),
            ("\\M-P", "do-lowercase-version"),
            ("\\M-Q", "do-lowercase-version"),
            ("\\M-R", "do-lowercase-version"),
            ("\\M-S", "do-lowercase-version"),
            ("\\M-T", "do-lowercase-version"),
            ("\\M-U", "do-lowercase-version"),
            ("\\M-V", "do-lowercase-version"),
            ("\\M-W", "do-lowercase-version"),
            ("\\M-X", "do-lowercase-version"),
            ("\\M-Y", "do-lowercase-version"),
            ("\\M-Z", "do-lowercase-version"),
            ("\\M-l", "downcase-word"),
            ("\\M-\\C-i", "dynamic-complete-history"),
            ("\\C-x\\C-e", "edit-and-execute-command"),
            ("\\C-x)", "end-kbd-macro"),
            ("\\M->", "end-of-history"),
            ("\\C-e", "end-of-line"),
            ("\\M-OF", "end-of-line"),
            ("\\M-[F", "end-of-line"),
            ("\\C-x\\C-x", "exchange-point-and-mark"),
            ("\\C-f", "forward-char"),
            ("\\M-OC", "forward-char"),
            ("\\M-[C", "forward-char"),
            ("\\C-s", "forward-search-history"),
            ("\\M-[1;3C", "forward-word"),
            ("\\M-[1;5C", "forward-word"),
            ("\\M-f", "forward-word"),
            ("\\M-g", "glob-complete-word"),
            ("\\C-x*", "glob-expand-word"),
            ("\\C-xg", "glob-list-expansions"),
            ("\\M-^", "history-expand-line"),
            ("\\M-[5~", "history-search-backward"),
            ("\\M-[6~", "history-search-forward"),
            ("\\M-#", "insert-comment"),
            ("\\M-*", "insert-completions"),
            ("\\M-.", "insert-last-argument"),
            ("\\M-_", "insert-last-argument"),
            ("\\C-k", "kill-line"),
            ("\\M-[3;5~", "kill-word"),
            ("\\M-d", "kill-word"),
            ("\\C-n", "next-history"),
            ("\\M-OB", "next-history"),
            ("\\M-[B", "next-history"),
            ("\\M-n", "non-incremental-forward-search-history"),
            ("\\M-p", "non-incremental-reverse-search-history"),
            ("\\C-o", "operate-and-get-next"),
            ("\\M-[2~", "overwrite-mode"),
            ("\\C-x!", "possible-command-completions"),
            ("\\M-=", "possible-completions"),
            ("\\M-?", "possible-completions"),
            ("\\C-x/", "possible-filename-completions"),
            ("\\C-x@", "possible-hostname-completions"),
            ("\\C-x~", "possible-username-completions"),
            ("\\C-x$", "possible-variable-completions"),
            ("\\C-p", "previous-history"),
            ("\\M-OA", "previous-history"),
            ("\\M-[A", "previous-history"),
            ("\\C-q", "quoted-insert"),
            ("\\C-v", "quoted-insert"),
            ("\\C-x\\C-r", "re-read-init-file"),
            ("\\C-r", "reverse-search-history"),
            ("\\M-\\C-r", "revert-line"),
            ("\\M-r", "revert-line"),
            (" ", "self-insert"),
            ("!", "self-insert"),
            ("\\\"", "self-insert"),
            ("#", "self-insert"),
            ("$", "self-insert"),
            ("%", "self-insert"),
            ("&", "self-insert"),
            ("'", "self-insert"),
            ("(", "self-insert"),
            (")", "self-insert"),
            ("*", "self-insert"),
            ("+", "self-insert"),
            (",", "self-insert"),
            ("-", "self-insert"),
            (".", "self-insert"),
            ("/", "self-insert"),
            ("0", "self-insert"),
            ("1", "self-insert"),
            ("2", "self-insert"),
            ("3", "self-insert"),
            ("4", "self-insert"),
            ("5", "self-insert"),
            ("6", "self-insert"),
            ("7", "self-insert"),
            ("8", "self-insert"),
            ("9", "self-insert"),
            (":", "self-insert"),
            (";", "self-insert"),
            ("<", "self-insert"),
            ("=", "self-insert"),
            (">", "self-insert"),
            ("?", "self-insert"),
            ("@", "self-insert"),
            ("A", "self-insert"),
            ("B", "self-insert"),
            ("C", "self-insert"),
            ("D", "self-insert"),
            ("E", "self-insert"),
            ("F", "self-insert"),
            ("G", "self-insert"),
            ("H", "self-insert"),
            ("I", "self-insert"),
            ("J", "self-insert"),
            ("K", "self-insert"),
            ("L", "self-insert"),
            ("M", "self-insert"),
            ("N", "self-insert"),
            ("O", "self-insert"),
            ("P", "self-insert"),
            ("Q", "self-insert"),
            ("R", "self-insert"),
            ("S", "self-insert"),
            ("T", "self-insert"),
            ("U", "self-insert"),
            ("V", "self-insert"),
            ("W", "self-insert"),
            ("X", "self-insert"),
            ("Y", "self-insert"),
            ("Z", "self-insert"),
            ("[", "self-insert"),
            ("\\\\", "self-insert"),
            ("]", "self-insert"),
            ("^", "self-insert"),
            ("_", "self-insert"),
            ("`", "self-insert"),
            ("a", "self-insert"),
            ("b", "self-insert"),
            ("c", "self-insert"),
            ("d", "self-insert"),
            ("e", "self-insert"),
            ("f", "self-insert"),
            ("g", "self-insert"),
            ("h", "self-insert"),
            ("i", "self-insert"),
            ("j", "self-insert"),
            ("k", "self-insert"),
            ("l", "self-insert"),
            ("m", "self-insert"),
            ("n", "self-insert"),
            ("o", "self-insert"),
            ("p", "self-insert"),
            ("q", "self-insert"),
            ("r", "self-insert"),
            ("s", "self-insert"),
            ("t", "self-insert"),
            ("u", "self-insert"),
            ("v", "self-insert"),
            ("w", "self-insert"),
            ("x", "self-insert"),
            ("y", "self-insert"),
            ("z", "self-insert"),
            ("{", "self-insert"),
            ("|", "self-insert"),
            ("}", "self-insert"),
            ("~", "self-insert"),
            ("\\200", "self-insert"),
            ("\\201", "self-insert"),
            ("\\202", "self-insert"),
            ("\\203", "self-insert"),
            ("\\204", "self-insert"),
            ("\\205", "self-insert"),
            ("\\206", "self-insert"),
            ("\\207", "self-insert"),
            ("\\210", "self-insert"),
            ("\\211", "self-insert"),
            ("\\212", "self-insert"),
            ("\\213", "self-insert"),
            ("\\214", "self-insert"),
            ("\\215", "self-insert"),
            ("\\216", "self-insert"),
            ("\\217", "self-insert"),
            ("\\220", "self-insert"),
            ("\\221", "self-insert"),
            ("\\222", "self-insert"),
            ("\\223", "self-insert"),
            ("\\224", "self-insert"),
            ("\\225", "self-insert"),
            ("\\226", "self-insert"),
            ("\\227", "self-insert"),
            ("\\230", "self-insert"),
            ("\\231", "self-insert"),
            ("\\232", "self-insert"),
            ("\\233", "self-insert"),
            ("\\234", "self-insert"),
            ("\\235", "self-insert"),
            ("\\236", "self-insert"),
            ("\\237", "self-insert"),
            ("\\240", "self-insert"),
            ("\\241", "self-insert"),
            ("\\242", "self-insert"),
            ("\\243", "self-insert"),
            ("\\244", "self-insert"),
            ("\\245", "self-insert"),
            ("\\246", "self-insert"),
            ("\\247", "self-insert"),
            ("\\250", "self-insert"),
            ("\\251", "self-insert"),
            ("\\252", "self-insert"),
            ("\\253", "self-insert"),
            ("\\254", "self-insert"),
            ("\\255", "self-insert"),
            ("\\256", "self-insert"),
            ("\\257", "self-insert"),
            ("\\260", "self-insert"),
            ("\\261", "self-insert"),
            ("\\262", "self-insert"),
            ("\\263", "self-insert"),
            ("\\264", "self-insert"),
            ("\\265", "self-insert"),
            ("\\266", "self-insert"),
            ("\\267", "self-insert"),
            ("\\270", "self-insert"),
            ("\\271", "self-insert"),
            ("\\272", "self-insert"),
            ("\\273", "self-insert"),
            ("\\274", "self-insert"),
            ("\\275", "self-insert"),
            ("\\276", "self-insert"),
            ("\\277", "self-insert"),
            ("\\300", "self-insert"),
            ("\\301", "self-insert"),
            ("\\302", "self-insert"),
            ("\\303", "self-insert"),
            ("\\304", "self-insert"),
            ("\\305", "self-insert"),
            ("\\306", "self-insert"),
            ("\\307", "self-insert"),
            ("\\310", "self-insert"),
            ("\\311", "self-insert"),
            ("\\312", "self-insert"),
            ("\\313", "self-insert"),
            ("\\314", "self-insert"),
            ("\\315", "self-insert"),
            ("\\316", "self-insert"),
            ("\\317", "self-insert"),
            ("\\320", "self-insert"),
            ("\\321", "self-insert"),
            ("\\322", "self-insert"),
            ("\\323", "self-insert"),
            ("\\324", "self-insert"),
            ("\\325", "self-insert"),
            ("\\326", "self-insert"),
            ("\\327", "self-insert"),
            ("\\330", "self-insert"),
            ("\\331", "self-insert"),
            ("\\332", "self-insert"),
            ("\\333", "self-insert"),
            ("\\334", "self-insert"),
            ("\\335", "self-insert"),
            ("\\336", "self-insert"),
            ("\\337", "self-insert"),
            ("\\340", "self-insert"),
            ("\\341", "self-insert"),
            ("\\342", "self-insert"),
            ("\\343", "self-insert"),
            ("\\344", "self-insert"),
            ("\\345", "self-insert"),
            ("\\346", "self-insert"),
            ("\\347", "self-insert"),
            ("\\350", "self-insert"),
            ("\\351", "self-insert"),
            ("\\352", "self-insert"),
            ("\\353", "self-insert"),
            ("\\354", "self-insert"),
            ("\\355", "self-insert"),
            ("\\356", "self-insert"),
            ("\\357", "self-insert"),
            ("\\360", "self-insert"),
            ("\\361", "self-insert"),
            ("\\362", "self-insert"),
            ("\\363", "self-insert"),
            ("\\364", "self-insert"),
            ("\\365", "self-insert"),
            ("\\366", "self-insert"),
            ("\\367", "self-insert"),
            ("\\370", "self-insert"),
            ("\\371", "self-insert"),
            ("\\372", "self-insert"),
            ("\\373", "self-insert"),
            ("\\374", "self-insert"),
            ("\\375", "self-insert"),
            ("\\376", "self-insert"),
            ("\\377", "self-insert"),
            ("\\C-@", "set-mark"),
            ("\\M- ", "set-mark"),
            ("\\M-\\C-b", "shell-backward-word"),
            ("\\M-\\C-e", "shell-expand-line"),
            ("\\M-\\C-f", "shell-forward-word"),
            ("\\M-\\C-d", "shell-kill-word"),
            ("\\M-\\C-t", "shell-transpose-words"),
            ("\\C-xs", "spell-correct-word"),
            ("\\C-x(", "start-kbd-macro"),
            ("\\M-&", "tilde-expand"),
            ("\\C-t", "transpose-chars"),
            ("\\M-t", "transpose-words"),
            ("\\C-x\\C-u", "undo"),
            ("\\C-_", "undo"),
            ("\\C-u", "unix-line-discard"),
            ("\\C-w", "unix-word-rubout"),
            ("\\M-u", "upcase-word"),
            ("\\C-y", "yank"),
            ("\\M-.", "yank-last-arg"),
            ("\\M-_", "yank-last-arg"),
            ("\\M-\\C-y", "yank-nth-arg"),
            ("\\M-y", "yank-pop"),
        ],
    },
    Keymap {
        names: &["emacs-meta"],
        bindings: &[
            ("\\C-g", "abort"),
            ("OD", "backward-char"),
            ("[D", "backward-char"),
            ("\\C-h", "backward-kill-word"),
            ("\\C-?", "backward-kill-word"),
            ("[1;3D", "backward-word"),
            ("[1;5D", "backward-word"),
            ("b", "backward-word"),
            ("<", "beginning-of-history"),
            ("OH", "beginning-of-line"),
            ("[H", "beginning-of-line"),
            ("[200~", "bracketed-paste-begin"),
            ("c", "capitalize-word"),
            ("\\C-]", "character-search-backward"),
            ("\\C-l", "clear-display"),
            ("\\e", "complete"),
            ("!", "complete-command"),
            ("/", "complete-filename"),
            ("@", "complete-hostname"),
            ("{", "complete-into-braces"),
            ("~", "complete-username"),
            ("$", "complete-variable"),
            ("[3~", "delete-char"),
            ("\\\\", "delete-horizontal-space"),
            ("-", "digit-argument"),
            ("0", "digit-argument"),
            ("1", "digit-argument"),
            ("2", "digit-argument"),
            ("3", "digit-argument"),
            ("4", "digit-argument"),
            ("5", "digit-argument"),
            ("6", "digit-argument"),
            ("7", "digit-argument"),
            ("8", "digit-argument"),
            ("9", "digit-argument"),
            ("A", "do-lowercase-version"),
            ("B", "do-lowercase-version"),
            ("C", "do-lowercase-version"),
            ("D", "do-lowercase-version"),
            ("E", "do-lowercase-version"),
            ("F", "do-lowercase-version"),
            ("G", "do-lowercase-version"),
            ("H", "do-lowercase-version"),
            ("I", "do-lowercase-version"),
            ("J", "do-lowercase-version"),
            ("K", "do-lowercase-version"),
            ("L", "do-lowercase-version"),
            ("M", "do-lowercase-version"),
            ("N", "do-lowercase-version"),
            ("P", "do-lowercase-version"),
            ("Q", "do-lowercase-version"),
            ("R", "do-lowercase-version"),
            ("S", "do-lowercase-version"),
            ("T", "do-lowercase-version"),
            ("U", "do-lowercase-version"),
            ("V", "do-lowercase-version"),
            ("W", "do-lowercase-version"),
            ("X", "do-lowercase-version"),
            ("Y", "do-lowercase-version"),
            ("Z", "do-lowercase-version"),
            ("l", "downcase-word"),
            ("\\C-i", "dynamic-complete-history"),
            (">", "end-of-history"),
            ("OF", "end-of-line"),
            ("[F", "end-of-line"),
            ("OC", "forward-char"),
            ("[C", "forward-char"),
            ("[1;3C", "forward-word"),
            ("[1;5C", "forward-word"),
            ("f", "forward-word"),
            ("g", "glob-complete-word"),
            ("^", "history-expand-line"),
            ("[5~", "history-search-backward"),
            ("[6~", "history-search-forward"),
            ("#", "insert-comment"),
            ("*", "insert-completions"),
            (".", "insert-last-argument"),
            ("_", "insert-last-argument"),
            ("[3;5~", "kill-word"),
            ("d", "kill-word"),
            ("OB", "next-history"),
            ("[B", "next-history"),
            ("n", "non-incremental-forward-search-history"),
            ("p", "non-incremental-reverse-search-history"),
            ("[2~", "overwrite-mode"),
            ("=", "possible-completions"),
            ("?", "possible-completions"),
            ("OA", "previous-history"),
            ("[A", "previous-history"),
            ("\\C-r", "revert-line"),
            ("r", "revert-line"),
            (" ", "set-mark"),
            ("\\C-b", "shell-backward-word"),
            ("\\C-e", "shell-expand-line"),
            ("\\C-f", "shell-forward-word"),
            ("\\C-d", "shell-kill-word"),
            ("\\C-t", "shell-transpose-words"),
            ("&", "tilde-expand"),
            ("t", "transpose-words"),
            ("u", "upcase-word"),
            (".", "yank-last-arg"),
            ("_", "yank-last-arg"),
            ("\\C-y", "yank-nth-arg"),
            ("y", "yank-pop"),
        ],
    },
    Keymap {
        names: &["emacs-ctlx"],
        bindings: &[
            ("\\C-g", "abort"),
            ("\\C-?", "backward-kill-line"),
            ("e", "call-last-kbd-macro"),
            ("\\C-v", "display-shell-version"),
            ("A", "do-lowercase-version"),
            ("B", "do-lowercase-version"),
            ("C", "do-lowercase-version"),
            ("D", "do-lowercase-version"),
            ("E", "do-lowercase-version"),
            ("F", "do-lowercase-version"),
            ("G", "do-lowercase-version"),
            ("H", "do-lowercase-version"),
            ("I", "do-lowercase-version"),
            ("J", "do-lowercase-version"),
            ("K", "do-lowercase-version"),
            ("L", "do-lowercase-version"),
            ("M", "do-lowercase-version"),
            ("N", "do-lowercase-version"),
            ("O", "do-lowercase-version"),
            ("P", "do-lowercase-version"),
            ("Q", "do-lowercase-version"),
            ("R", "do-lowercase-version"),
            ("S", "do-lowercase-version"),
            ("T", "do-lowercase-version"),
            ("U", "do-lowercase-version"),
            ("V", "do-lowercase-version"),
            ("W", "do-lowercase-version"),
            ("X", "do-lowercase-version"),
            ("Y", "do-lowercase-version"),
            ("Z", "do-lowercase-version"),
            ("\\C-e", "edit-and-execute-command"),
            (")", "end-kbd-macro"),
            ("\\C-x", "exchange-point-and-mark"),
            ("*", "glob-expand-word"),
            ("g", "glob-list-expansions"),
            ("!", "possible-command-completions"),
            ("/", "possible-filename-completions"),
            ("@", "possible-hostname-completions"),
            ("~", "possible-username-completions"),
            ("$", "possible-variable-completions"),
            ("\\C-r", "re-read-init-file"),
            ("s", "spell-correct-word"),
            ("(", "start-kbd-macro"),
            ("\\C-u", "undo"),
        ],
    },
    Keymap {
        names: &["vi", "vi-move", "vi-command"],
        bindings: &[
            ("\\C-g", "abort"),
            ("\\C-j", "accept-line"),
            ("\\C-m", "accept-line"),
            ("\\C-h", "backward-char"),
            ("\\M-OD", "backward-char"),
            ("\\M-[D", "backward-char"),
            ("h", "backward-char"),
            ("\\M-[1;3D", "backward-word"),
            ("\\M-[1;5D", "backward-word"),
            ("\\M-OH", "beginning-of-line"),
            ("\\M-[H", "beginning-of-line"),
            ("0", "beginning-of-line"),
            ("\\C-l", "clear-screen"),
            ("\\M-[3~", "delete-char"),
            ("\\M-OF", "end-of-line"),
            ("\\M-[F", "end-of-line"),
            ("$", "end-of-line"),
            ("\\M-OC", "forward-char"),
            ("\\M-[C", "forward-char"),
            (" ", "forward-char"),
            ("l", "forward-char"),
            ("\\C-s", "forward-search-history"),
            ("\\M-[1;3C", "forward-word"),
            ("\\M-[1;5C", "forward-word"),
            ("\\M-[5~", "history-search-backward"),
            ("\\M-[6~", "history-search-forward"),
            ("#", "insert-comment"),
            ("\\C-k", "kill-line"),
            ("\\M-[3;5~", "kill-word"),
            ("\\C-n", "next-history"),
            ("\\M-OB", "next-history"),
            ("\\M-[B", "next-history"),
            ("+", "next-history"),
            ("j", "next-history"),
            ("\\M-[2~", "overwrite-mode"),
            ("\\C-p", "previous-history"),
            ("\\M-OA", "previous-history"),
            ("\\M-[A", "previous-history"),
            ("-", "previous-history"),
            ("k", "previous-history"),
            ("\\C-q", "quoted-insert"),
            ("\\C-v", "quoted-insert"),
            ("\\C-r", "reverse-search-history"),
            ("U", "revert-line"),
            ("\\C-t", "transpose-chars"),
            ("\\C-u", "unix-line-discard"),
            ("A", "vi-append-eol"),
            ("a", "vi-append-mode"),
            ("1", "vi-arg-digit"),
            ("2", "vi-arg-digit"),
            ("3", "vi-arg-digit"),
            ("4", "vi-arg-digit"),
            ("5", "vi-arg-digit"),
            ("6", "vi-arg-digit"),
            ("7", "vi-arg-digit"),
            ("8", "vi-arg-digit"),
            ("9", "vi-arg-digit"),
            ("~", "vi-change-case"),
            ("r", "vi-change-char"),
            ("C", "vi-change-to"),
            ("c", "vi-change-to"),
            (",", "vi-char-search"),
            (";", "vi-char-search"),
            ("F", "vi-char-search"),
            ("T", "vi-char-search"),
            ("f", "vi-char-search"),
            ("t", "vi-char-search"),
            ("|", "vi-column"),
            ("x", "vi-delete"),
            ("D", "vi-delete-to"),
            ("d", "vi-delete-to"),
            ("v", "vi-edit-and-execute-command"),
            ("E", "vi-end-word"),
            ("e", "vi-end-word"),
            ("\\C-d", "vi-eof-maybe"),
            ("G", "vi-fetch-history"),
            ("^", "vi-first-print"),
            ("`", "vi-goto-mark"),
            ("I", "vi-insert-beg"),
            ("i", "vi-insertion-mode"),
            ("%", "vi-match"),
            ("W", "vi-next-word"),
            ("w", "vi-next-word"),
            ("B", "vi-prev-word"),
            ("b", "vi-prev-word"),
            ("P", "vi-put"),
            ("p", "vi-put"),
            (".", "vi-redo"),
            ("R", "vi-replace"),
            ("X", "vi-rubout"),
            ("/", "vi-search"),
            ("?", "vi-search"),
            ("N", "vi-search-again"),
            ("n", "vi-search-again"),
            ("m", "vi-set-mark"),
            ("S", "vi-subst"),
            ("s", "vi-subst"),
            ("&", "vi-tilde-expand"),
            ("\\C-_", "vi-undo"),
            ("u", "vi-undo"),
            ("\\C-w", "vi-unix-word-rubout"),
            ("_", "vi-yank-arg"),
            ("Y", "vi-yank-to"),
            ("y", "vi-yank-to"),
            ("\\C-y", "yank"),
        ],
    },
    Keymap {
        names: &["vi-insert"],
        bindings: &[
            ("\\C-j", "accept-line"),
            ("\\C-m", "accept-line"),
            ("\\M-OD", "backward-char"),
            ("\\M-[D", "backward-char"),
            ("\\C-h", "backward-delete-char"),
            ("\\C-?", "backward-delete-char"),
            ("\\M-[1;3D", "backward-word"),
            ("\\M-[1;5D", "backward-word"),
            ("\\M-OH", "beginning-of-line"),
            ("\\M-[H", "beginning-of-line"),
            ("\\M-[200~", "bracketed-paste-begin"),
            ("\\C-i", "complete"),
            ("\\M-[3~", "delete-char"),
            ("\\M-OF", "end-of-line"),
            ("\\M-[F", "end-of-line"),
            ("\\M-OC", "forward-char"),
            ("\\M-[C", "forward-char"),
            ("\\C-s", "forward-search-history"),
            ("\\M-[1;3C", "forward-word"),
            ("\\M-[1;5C", "forward-word"),
            ("\\M-[5~", "history-search-backward"),
            ("\\M-[6~", "history-search-forward"),
            ("\\M-[3;5~", "kill-word"),
            ("\\C-n", "menu-complete"),
            ("\\C-p", "menu-complete-backward"),
            ("\\M-OB", "next-history"),
            ("\\M-[B", "next-history"),
            ("\\M-[2~", "overwrite-mode"),
            ("\\M-OA", "previous-history"),
            ("\\M-[A", "previous-history"),
            ("\\C-v", "quoted-insert"),
            ("\\C-r", "reverse-search-history"),
            ("\\C-a", "self-insert"),
            ("\\C-b", "self-insert"),
            ("\\C-c", "self-insert"),
            ("\\C-e", "self-insert"),
            ("\\C-f", "self-insert"),
            ("\\C-g", "self-insert"),
            ("\\C-k", "self-insert"),
            ("\\C-l", "self-insert"),
            ("\\C-o", "self-insert"),
            ("\\C-q", "self-insert"),
            ("\\C-x", "self-insert"),
            ("\\C-z", "self-insert"),
            ("\\C-\\\\", "self-insert"),
            ("\\C-]", "self-insert"),
            ("\\C-^", "self-insert"),
            (" ", "self-insert"),
            ("!", "self-insert"),
            ("\\\"", "self-insert"),
            ("#", "self-insert"),
            ("$", "self-insert"),
            ("%", "self-insert"),
            ("&", "self-insert"),
            ("'", "self-insert"),
            ("(", "self-insert"),
            (")", "self-insert"),
            ("*", "self-insert"),
            ("+", "self-insert"),
            (",", "self-insert"),
            ("-", "self-insert"),
            (".", "self-insert"),
            ("/", "self-insert"),
            ("0", "self-insert"),
            ("1", "self-insert"),
            ("2", "self-insert"),
            ("3", "self-insert"),
            ("4", "self-insert"),
            ("5", "self-insert"),
            ("6", "self-insert"),
            ("7", "self-insert"),
            ("8", "self-insert"),
            ("9", "self-insert"),
            (":", "self-insert"),
            (";", "self-insert"),
            ("<", "self-insert"),
            ("=", "self-insert"),
            (">", "self-insert"),
            ("?", "self-insert"),
            ("@", "self-insert"),
            ("A", "self-insert"),
            ("B", "self-insert"),
            ("C", "self-insert"),
            ("D", "self-insert"),
            ("E", "self-insert"),
            ("F", "self-insert"),
            ("G", "self-insert"),
            ("H", "self-insert"),
            ("I", "self-insert"),
            ("J", "self-insert"),
            ("K", "self-insert"),
            ("L", "self-insert"),
            ("M", "self-insert"),
            ("N", "self-insert"),
            ("O", "self-insert"),
            ("P", "self-insert"),
            ("Q", "self-insert"),
            ("R", "self-insert"),
            ("S", "self-insert"),
            ("T", "self-insert"),
            ("U", "self-insert"),
            ("V", "self-insert"),
            ("W", "self-insert"),
            ("X", "self-insert"),
            ("Y", "self-insert"),
            ("Z", "self-insert"),
            ("[", "self-insert"),
            ("\\\\", "self-insert"),
            ("]", "self-insert"),
            ("^", "self-insert"),
            ("_", "self-insert"),
            ("`", "self-insert"),
            ("a", "self-insert"),
            ("b", "self-insert"),
            ("c", "self-insert"),
            ("d", "self-insert"),
            ("e", "self-insert"),
            ("f", "self-insert"),
            ("g", "self-insert"),
            ("h", "self-insert"),
            ("i", "self-insert"),
            ("j", "self-insert"),
            ("k", "self-insert"),
            ("l", "self-insert"),
            ("m", "self-insert"),
            ("n", "self-insert"),
            ("o", "self-insert"),
            ("p", "self-insert"),
            ("q", "self-insert"),
            ("r", "self-insert"),
            ("s", "self-insert"),
            ("t", "self-insert"),
            ("u", "self-insert"),
            ("v", "self-insert"),
            ("w", "self-insert"),
            ("x", "self-insert"),
            ("y", "self-insert"),
            ("z", "self-insert"),
            ("{", "self-insert"),
            ("|", "self-insert"),
            ("}", "self-insert"),
            ("~", "self-insert"),
            ("\\200", "self-insert"),
            ("\\201", "self-insert"),
            ("\\202", "self-insert"),
            ("\\203", "self-insert"),
            ("\\204", "self-insert"),
            ("\\205", "self-insert"),
            ("\\206", "self-insert"),
            ("\\207", "self-insert"),
            ("\\210", "self-insert"),
            ("\\211", "self-insert"),
            ("\\212", "self-insert"),
            ("\\213", "self-insert"),
            ("\\214", "self-insert"),
            ("\\215", "self-insert"),
            ("\\216", "self-insert"),
            ("\\217", "self-insert"),
            ("\\220", "self-insert"),
            ("\\221", "self-insert"),
            ("\\222", "self-insert"),
            ("\\223", "self-insert"),
            ("\\224", "self-insert"),
            ("\\225", "self-insert"),
            ("\\226", "self-insert"),
            ("\\227", "self-insert"),
            ("\\230", "self-insert"),
            ("\\231", "self-insert"),
            ("\\232", "self-insert"),
            ("\\233", "self-insert"),
            ("\\234", "self-insert"),
            ("\\235", "self-insert"),
            ("\\236", "self-insert"),
            ("\\237", "self-insert"),
            ("\\240", "self-insert"),
            ("\\241", "self-insert"),
            ("\\242", "self-insert"),
            ("\\243", "self-insert"),
            ("\\244", "self-insert"),
            ("\\245", "self-insert"),
            ("\\246", "self-insert"),
            ("\\247", "self-insert"),
            ("\\250", "self-insert"),
            ("\\251", "self-insert"),
            ("\\252", "self-insert"),
            ("\\253", "self-insert"),
            ("\\254", "self-insert"),
            ("\\255", "self-insert"),
            ("\\256", "self-insert"),
            ("\\257", "self-insert"),
            ("\\260", "self-insert"),
            ("\\261", "self-insert"),
            ("\\262", "self-insert"),
            ("\\263", "self-insert"),
            ("\\264", "self-insert"),
            ("\\265", "self-insert"),
            ("\\266", "self-insert"),
            ("\\267", "self-insert"),
            ("\\270", "self-insert"),
            ("\\271", "self-insert"),
            ("\\272", "self-insert"),
            ("\\273", "self-insert"),
            ("\\274", "self-insert"),
            ("\\275", "self-insert"),
            ("\\276", "self-insert"),
            ("\\277", "self-insert"),
            ("\\300", "self-insert"),
            ("\\301", "self-insert"),
            ("\\302", "self-insert"),
            ("\\303", "self-insert"),
            ("\\304", "self-insert"),
            ("\\305", "self-insert"),
            ("\\306", "self-insert"),
            ("\\307", "self-insert"),
            ("\\310", "self-insert"),
            ("\\311", "self-insert"),
            ("\\312", "self-insert"),
            ("\\313", "self-insert"),
            ("\\314", "self-insert"),
            ("\\315", "self-insert"),
            ("\\316", "self-insert"),
            ("\\317", "self-insert"),
            ("\\320", "self-insert"),
            ("\\321", "self-insert"),
            ("\\322", "self-insert"),
            ("\\323", "self-insert"),
            ("\\324", "self-insert"),
            ("\\325", "self-insert"),
            ("\\326", "self-insert"),
            ("\\327", "self-insert"),
            ("\\330", "self-insert"),
            ("\\331", "self-insert"),
            ("\\332", "self-insert"),
            ("\\333", "self-insert"),
            ("\\334", "self-insert"),
            ("\\335", "self-insert"),
            ("\\336", "self-insert"),
            ("\\337", "self-insert"),
            ("\\340", "self-insert"),
            ("\\341", "self-insert"),
            ("\\342", "self-insert"),
            ("\\343", "self-insert"),
            ("\\344", "self-insert"),
            ("\\345", "self-insert"),
            ("\\346", "self-insert"),
            ("\\347", "self-insert"),
            ("\\350", "self-insert"),
            ("\\351", "self-insert"),
            ("\\352", "self-insert"),
            ("\\353", "self-insert"),
            ("\\354", "self-insert"),
            ("\\355", "self-insert"),
            ("\\356", "self-insert"),
            ("\\357", "self-insert"),
            ("\\360", "self-insert"),
            ("\\361", "self-insert"),
            ("\\362", "self-insert"),
            ("\\363", "self-insert"),
            ("\\364", "self-insert"),
            ("\\365", "self-insert"),
            ("\\366", "self-insert"),
            ("\\367", "self-insert"),
            ("\\370", "self-insert"),
            ("\\371", "self-insert"),
            ("\\372", "self-insert"),
            ("\\373", "self-insert"),
            ("\\374", "self-insert"),
            ("\\375", "self-insert"),
            ("\\376", "self-insert"),
            ("\\377", "self-insert"),
            ("\\C-t", "transpose-chars"),
            ("\\C-u", "unix-line-discard"),
            ("\\C-d", "vi-eof-maybe"),
            ("\\M-\\000", "vi-movement-mode"),
            ("\\C-_", "vi-undo"),
            ("\\C-w", "vi-unix-word-rubout"),
            ("\\C-y", "yank"),
        ],
    },
];

/// readline's variables and their default values, in `bind -v` order.
pub const VARIABLES: [(&str, &str); 46] = [
    ("bind-tty-special-chars", "on"),
    ("blink-matching-paren", "off"),
    ("byte-oriented", "off"),
    ("colored-completion-prefix", "off"),
    ("colored-stats", "off"),
    ("completion-ignore-case", "off"),
    ("completion-map-case", "off"),
    ("convert-meta", "on"),
    ("disable-completion", "off"),
    ("echo-control-characters", "on"),
    ("enable-active-region", "on"),
    ("enable-bracketed-paste", "on"),
    ("enable-keypad", "off"),
    ("enable-meta-key", "on"),
    ("expand-tilde", "off"),
    ("history-preserve-point", "off"),
    ("horizontal-scroll-mode", "off"),
    ("input-meta", "off"),
    ("mark-directories", "on"),
    ("mark-modified-lines", "off"),
    ("mark-symlinked-directories", "off"),
    ("match-hidden-files", "on"),
    ("menu-complete-display-prefix", "off"),
    ("meta-flag", "off"),
    ("output-meta", "off"),
    ("page-completions", "on"),
    ("prefer-visible-bell", "on"),
    ("print-completions-horizontally", "off"),
    ("revert-all-at-newline", "off"),
    ("show-all-if-ambiguous", "off"),
    ("show-all-if-unmodified", "off"),
    ("show-mode-in-prompt", "off"),
    ("skip-completed-text", "off"),
    ("visible-stats", "off"),
    ("bell-style", "audible"),
    ("comment-begin", "#"),
    ("completion-display-width", "-1"),
    ("completion-prefix-display-length", "0"),
    ("completion-query-items", "100"),
    ("editing-mode", "emacs"),
    ("emacs-mode-string", "@"),
    ("history-size", "0"),
    ("keymap", "emacs"),
    ("keyseq-timeout", "500"),
    ("vi-cmd-mode-string", "(cmd)"),
    ("vi-ins-mode-string", "(ins)"),
];
