//! Terminal display widths — the `wcwidth`/`wcswidth` a shell needs to lay out
//! a `select` menu in columns.
//!
//! bash measures a menu item with `displen` (`execute_cmd.c`), which decodes
//! the item and returns `wcswidth` of the result. That is the only place a
//! width is observable from outside the shell, and it is what
//! [`display_width`] reproduces — including both of `displen`'s fallbacks,
//! which are not the same as each other:
//!
//! ```c
//! slen = mbstowcs (wcstr, s, 0);
//! if (slen == -1)
//!   slen = 0;
//! wcstr = (wchar_t *)xmalloc (sizeof (wchar_t) * (slen + 1));
//! mbstowcs (wcstr, s, slen + 1);
//! wclen = wcswidth (wcstr, slen);
//! free (wcstr);
//! return (wclen < 0 ? STRLEN(s) : wclen);
//! ```
//!
//! A string that will not decode takes `slen = 0`, so the `wcswidth` call is
//! over *no* characters and returns 0 — the `STRLEN` fallback is never reached
//! and the item measures **zero columns**. The `STRLEN` fallback belongs to the
//! other case: the string decoded, but `wcswidth` refused it because one of its
//! characters has no printable width, and then the item measures its **byte
//! length**. Both were measured against bash 5.2.37 under `LC_ALL=C.UTF-8`
//! (see `tests/probe_displen.py`, which recovers the width bash used from the
//! menu's column arithmetic): `$'\xff'` and `$'\xffX'` measure 0 whatever
//! follows the bad byte, while `$'\x01'` followed by ten U+4E00 measures 31,
//! the byte length, not the 21 columns those characters occupy.
//!
//! The per-character half — `wcwidth` itself and the two Unicode range tables
//! generated by `tests/gen_display_width.py` — lives in the `charwidth` crate,
//! and is re-exported here so this module still reads as one subject. It moved
//! because `wc -L`, `expand`, `fold` and `column` are laying text out on the
//! *same* terminal as `select`, so a second copy of the tables would be a
//! second opinion about where a column ends. What stays here is the part that
//! is *bash's* and nobody else's: the two `displen` fallbacks above.

use crate::bytes::{self, BStr, Ch};
pub use charwidth::char_width;

/// bash's `displen` (`execute_cmd.c`): the number of terminal columns `s`
/// occupies, with both of that function's fallbacks — see the module docs.
#[must_use]
pub fn display_width(s: BStr<'_>) -> usize {
    let mut cols = 0usize;
    for c in bytes::chars(s) {
        match c {
            // `mbstowcs` gave up on the string, so bash measured no characters
            // at all. Nothing after the bad byte can change that.
            Ch::B(_) => return 0,
            // `wcswidth` refused the string, so bash fell back to its length in
            // bytes — which is *not* the same as counting this character as one
            // column, since the characters around it may be wide.
            Ch::U(u) => match char_width(u) {
                None => return s.len(),
                Some(w) => cols = cols.saturating_add(w),
            },
        }
    }
    cols
}

#[cfg(test)]
mod tests {
    use super::display_width;
    /// bash's `displen` has two different fallbacks, and the difference between
    /// them is the whole reason this is not just a sum.
    #[test]
    fn a_string_that_will_not_decode_measures_nothing() {
        // Measured: `$'\xff'` and `$'a\xffb'` both measure 0 columns, because
        // `mbstowcs` fails and bash then calls `wcswidth` over no characters.
        assert_eq!(display_width(b"\xff"), 0);
        assert_eq!(display_width(b"a\xffb"), 0);
        assert_eq!(display_width("\u{4e00}\u{4e00}".as_bytes()), 4);
        let mut bad = b"\xff".to_vec();
        bad.extend_from_slice("\u{4e00}".repeat(10).as_bytes());
        assert_eq!(display_width(&bad), 0);
    }

    #[test]
    fn a_string_with_no_width_measures_its_bytes() {
        // Measured: a control character followed by ten U+4E00 measures 31 —
        // the byte length — and not the 21 columns the characters occupy.
        let mut s = b"\x01".to_vec();
        s.extend_from_slice("\u{4e00}".repeat(10).as_bytes());
        assert_eq!(s.len(), 31);
        assert_eq!(display_width(&s), 31);
        // The C1 controls do it too, and they are two bytes each.
        let mut c1 = "\u{85}".as_bytes().to_vec();
        c1.extend_from_slice("\u{4e00}".repeat(10).as_bytes());
        assert_eq!(display_width(&c1), 32);
    }

    #[test]
    fn a_decodable_printable_string_is_the_sum_of_its_columns() {
        assert_eq!(display_width(b""), 0);
        assert_eq!(display_width(b"abc"), 3);
        assert_eq!(display_width("\u{65e5}\u{672c}\u{8a9e}".as_bytes()), 6);
        // A base character and its combining mark occupy one column together.
        assert_eq!(display_width("a\u{0300}".as_bytes()), 1);
        assert_eq!(display_width("\u{1100}\u{1161}\u{11a8}".as_bytes()), 2);
    }
}
