//! FreeType's auto-hinter tables: its scripts, their styles' alignment
//! zones, and which code points belong to which.
//!
//! Generated by `gui/font/tools/gen_autofit_tables.py` from FreeType
//! 2.13.2's `src/autofit/afscript.h`, `afstyles.h`, `afranges.c` and
//! `afblue.dat`. Do not edit: run the script instead. See that script for
//! what each table is for.
//!
//! Portions of this file are copyright (C) 2013-2023 The FreeType Project
//! (www.freetype.org). All rights reserved. Used under the FreeType
//! License: see `gui/font/licenses/FTL.TXT`.

use super::{Blue, Script, Style, System};

/// FreeType's scripts, in its order.
pub(super) static SCRIPTS: [Script; 60] = [
    Script {
        name: "adlm",
        ot: &[*b"adlm"],
        top_to_bottom: false,
        standard: "𞤌 𞤮",
    },
    Script {
        name: "arab",
        ot: &[*b"arab"],
        top_to_bottom: false,
        standard: "ل ح ـ",
    },
    Script {
        name: "armn",
        ot: &[*b"armn"],
        top_to_bottom: false,
        standard: "ս Ս",
    },
    Script {
        name: "avst",
        ot: &[*b"avst"],
        top_to_bottom: false,
        standard: "𐬚",
    },
    Script {
        name: "bamu",
        ot: &[*b"bamu"],
        top_to_bottom: false,
        standard: "ꛁ ꛯ",
    },
    Script {
        name: "beng",
        ot: &[*b"bng3", *b"bng2", *b"beng"],
        top_to_bottom: true,
        standard: "০ ৪",
    },
    Script {
        name: "buhd",
        ot: &[*b"buhd"],
        top_to_bottom: false,
        standard: "ᝋ ᝏ",
    },
    Script {
        name: "cakm",
        ot: &[*b"cakm"],
        top_to_bottom: false,
        standard: "𑄤 𑄉 𑄛",
    },
    Script {
        name: "cans",
        ot: &[*b"cans"],
        top_to_bottom: false,
        standard: "ᑌ ᓚ",
    },
    Script {
        name: "cari",
        ot: &[*b"cari"],
        top_to_bottom: false,
        standard: "𐊫 𐋉",
    },
    Script {
        name: "cher",
        ot: &[*b"cher"],
        top_to_bottom: false,
        standard: "Ꭴ Ꮕ ꮕ",
    },
    Script {
        name: "copt",
        ot: &[*b"copt"],
        top_to_bottom: false,
        standard: "Ⲟ ⲟ",
    },
    Script {
        name: "cprt",
        ot: &[*b"cprt"],
        top_to_bottom: false,
        standard: "𐠅 𐠣",
    },
    Script {
        name: "cyrl",
        ot: &[*b"cyrl"],
        top_to_bottom: false,
        standard: "о О",
    },
    Script {
        name: "deva",
        ot: &[*b"dev3", *b"dev2", *b"deva"],
        top_to_bottom: true,
        standard: "ठ व ट",
    },
    Script {
        name: "dsrt",
        ot: &[*b"dsrt"],
        top_to_bottom: false,
        standard: "𐐄 𐐬",
    },
    Script {
        name: "ethi",
        ot: &[*b"ethi"],
        top_to_bottom: false,
        standard: "ዐ",
    },
    Script {
        name: "geor",
        ot: &[*b"geor"],
        top_to_bottom: false,
        standard: "ი ე ა Ჿ",
    },
    Script {
        name: "geok",
        ot: &[],
        top_to_bottom: false,
        standard: "Ⴖ Ⴑ ⴙ",
    },
    Script {
        name: "glag",
        ot: &[*b"glag"],
        top_to_bottom: false,
        standard: "Ⱅ ⱅ",
    },
    Script {
        name: "goth",
        ot: &[*b"goth"],
        top_to_bottom: true,
        standard: "𐌴 𐌾 𐍃",
    },
    Script {
        name: "grek",
        ot: &[*b"grek"],
        top_to_bottom: false,
        standard: "ο Ο",
    },
    Script {
        name: "gujr",
        ot: &[*b"gjr3", *b"gjr2", *b"gujr"],
        top_to_bottom: false,
        standard: "ટ ૦",
    },
    Script {
        name: "guru",
        ot: &[*b"gur3", *b"gur2", *b"guru"],
        top_to_bottom: true,
        standard: "ਠ ਰ ੦",
    },
    Script {
        name: "hebr",
        ot: &[*b"hebr"],
        top_to_bottom: false,
        standard: "ם",
    },
    Script {
        name: "kali",
        ot: &[*b"kali"],
        top_to_bottom: false,
        standard: "ꤍ ꤀",
    },
    Script {
        name: "khmr",
        ot: &[*b"khmr"],
        top_to_bottom: false,
        standard: "០",
    },
    Script {
        name: "khms",
        ot: &[],
        top_to_bottom: false,
        standard: "᧡ ᧪",
    },
    Script {
        name: "knda",
        ot: &[*b"knd3", *b"knd2", *b"knda"],
        top_to_bottom: false,
        standard: "೦ ಬ",
    },
    Script {
        name: "lao",
        ot: &[*b"lao "],
        top_to_bottom: false,
        standard: "໐",
    },
    Script {
        name: "latn",
        ot: &[*b"latn"],
        top_to_bottom: false,
        standard: "o O 0",
    },
    Script {
        name: "latb",
        ot: &[],
        top_to_bottom: false,
        standard: "ₒ ₀",
    },
    Script {
        name: "latp",
        ot: &[],
        top_to_bottom: false,
        standard: "ᵒ ᴼ ⁰",
    },
    Script {
        name: "lisu",
        ot: &[*b"lisu"],
        top_to_bottom: false,
        standard: "ꓳ",
    },
    Script {
        name: "mlym",
        ot: &[*b"mlm3", *b"mlm2", *b"mlym"],
        top_to_bottom: false,
        standard: "ഠ റ",
    },
    Script {
        name: "medf",
        ot: &[*b"medf"],
        top_to_bottom: false,
        standard: "𖹡 𖹛 𖹯",
    },
    Script {
        name: "mong",
        ot: &[*b"mong"],
        top_to_bottom: true,
        standard: "ᡂ ᠪ",
    },
    Script {
        name: "mymr",
        ot: &[*b"mym2", *b"mymr"],
        top_to_bottom: false,
        standard: "ဝ င ဂ",
    },
    Script {
        name: "nkoo",
        ot: &[*b"nko "],
        top_to_bottom: false,
        standard: "ߋ ߀",
    },
    Script {
        name: "none",
        ot: &[],
        top_to_bottom: false,
        standard: "",
    },
    Script {
        name: "olck",
        ot: &[*b"olck"],
        top_to_bottom: false,
        standard: "ᱛ",
    },
    Script {
        name: "orkh",
        ot: &[*b"orkh"],
        top_to_bottom: false,
        standard: "𐰗",
    },
    Script {
        name: "osge",
        ot: &[*b"osge"],
        top_to_bottom: false,
        standard: "𐓂 𐓪",
    },
    Script {
        name: "osma",
        ot: &[*b"osma"],
        top_to_bottom: false,
        standard: "𐒆 𐒠",
    },
    Script {
        name: "rohg",
        ot: &[*b"rohg"],
        top_to_bottom: false,
        standard: "𐴰",
    },
    Script {
        name: "saur",
        ot: &[*b"saur"],
        top_to_bottom: false,
        standard: "ꢝ ꣐",
    },
    Script {
        name: "shaw",
        ot: &[*b"shaw"],
        top_to_bottom: false,
        standard: "𐑴",
    },
    Script {
        name: "sinh",
        ot: &[*b"sinh"],
        top_to_bottom: false,
        standard: "ට",
    },
    Script {
        name: "sund",
        ot: &[*b"sund"],
        top_to_bottom: false,
        standard: "᮰",
    },
    Script {
        name: "taml",
        ot: &[*b"tml3", *b"tml2", *b"taml"],
        top_to_bottom: false,
        standard: "௦",
    },
    Script {
        name: "tavt",
        ot: &[*b"tavt"],
        top_to_bottom: false,
        standard: "ꪒ ꪫ",
    },
    Script {
        name: "telu",
        ot: &[*b"tel3", *b"tel2", *b"telu"],
        top_to_bottom: false,
        standard: "౦ ౧",
    },
    Script {
        name: "tfng",
        ot: &[*b"tfng"],
        top_to_bottom: false,
        standard: "ⵔ",
    },
    Script {
        name: "thai",
        ot: &[*b"thai"],
        top_to_bottom: false,
        standard: "า ๅ ๐",
    },
    Script {
        name: "vaii",
        ot: &[*b"vai "],
        top_to_bottom: false,
        standard: "ꘓ ꖜ ꖴ",
    },
    Script {
        name: "limb",
        ot: &[*b"limb"],
        top_to_bottom: false,
        standard: "o",
    },
    Script {
        name: "orya",
        ot: &[*b"ory3", *b"ory2", *b"orya"],
        top_to_bottom: false,
        standard: "o",
    },
    Script {
        name: "sylo",
        ot: &[*b"sylo"],
        top_to_bottom: false,
        standard: "o",
    },
    Script {
        name: "tibt",
        ot: &[*b"tibt"],
        top_to_bottom: false,
        standard: "o",
    },
    Script {
        name: "hani",
        ot: &[*b"hani"],
        top_to_bottom: false,
        standard: "田 囗",
    },
];

/// The scripts' default styles, in FreeType's order, which is the
/// priority order when two could claim one glyph.
pub(super) static STYLES: [Style; 60] = [
    Style {
        name: "adlm_dflt",
        script: 0,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_ADLAM_CAPITAL_TOP
            Blue {
                chars: "𞤌 𞤅 𞤈 𞤏 𞤔 𞤚",
                props: 1,
            },
            // AF_BLUE_STRING_ADLAM_CAPITAL_BOTTOM
            Blue {
                chars: "𞤂 𞤖",
                props: 0,
            },
            // AF_BLUE_STRING_ADLAM_SMALL_TOP
            Blue {
                chars: "𞤬 𞤮 𞤻 𞤼 𞤾",
                props: 9,
            },
            // AF_BLUE_STRING_ADLAM_SMALL_BOTTOM
            Blue {
                chars: "𞤤 𞤨 𞤩 𞤭 𞤴 𞤸 𞤺 𞥀",
                props: 0,
            },
        ],
        nonbase: &[(0x1D944, 0x1E94A)],
    },
    Style {
        name: "arab_dflt",
        script: 1,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_ARABIC_TOP
            Blue {
                chars: "ا إ ل ك ط ظ",
                props: 1,
            },
            // AF_BLUE_STRING_ARABIC_BOTTOM
            Blue {
                chars: "ت ث ط ظ ك",
                props: 0,
            },
            // AF_BLUE_STRING_ARABIC_JOIN
            Blue {
                chars: "ـ",
                props: 4,
            },
        ],
        nonbase: &[
            (0x0600, 0x0605),
            (0x0610, 0x061A),
            (0x064B, 0x065F),
            (0x0670, 0x0670),
            (0x06D6, 0x06DC),
            (0x06DF, 0x06E4),
            (0x06E7, 0x06E8),
            (0x06EA, 0x06ED),
            (0x08D3, 0x08FF),
            (0x08D4, 0x08E1),
            (0xFBB2, 0xFBC1),
            (0xFE70, 0xFE70),
            (0xFE72, 0xFE72),
            (0xFE74, 0xFE74),
            (0xFE76, 0xFE76),
            (0xFE78, 0xFE78),
            (0xFE7A, 0xFE7A),
            (0xFE7C, 0xFE7C),
            (0xFE7E, 0xFE7E),
        ],
    },
    Style {
        name: "armn_dflt",
        script: 2,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_ARMENIAN_CAPITAL_TOP
            Blue {
                chars: "Ա Մ Ւ Ս Բ Գ Դ Օ",
                props: 1,
            },
            // AF_BLUE_STRING_ARMENIAN_CAPITAL_BOTTOM
            Blue {
                chars: "Ւ Ո Դ Ճ Շ Ս Տ Օ",
                props: 0,
            },
            // AF_BLUE_STRING_ARMENIAN_SMALL_ASCENDER
            Blue {
                chars: "ե է ի մ վ ֆ ճ",
                props: 1,
            },
            // AF_BLUE_STRING_ARMENIAN_SMALL_TOP
            Blue {
                chars: "ա յ ւ ս գ շ ր օ",
                props: 9,
            },
            // AF_BLUE_STRING_ARMENIAN_SMALL_BOTTOM
            Blue {
                chars: "հ ո ճ ա ե ծ ս օ",
                props: 0,
            },
            // AF_BLUE_STRING_ARMENIAN_SMALL_DESCENDER
            Blue {
                chars: "բ ը ի լ ղ պ փ ց",
                props: 0,
            },
        ],
        nonbase: &[(0x0559, 0x055F)],
    },
    Style {
        name: "avst_dflt",
        script: 3,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_AVESTAN_TOP
            Blue {
                chars: "𐬀 𐬁 𐬐 𐬛",
                props: 1,
            },
            // AF_BLUE_STRING_AVESTAN_BOTTOM
            Blue {
                chars: "𐬀 𐬁",
                props: 0,
            },
        ],
        nonbase: &[(0x10B39, 0x10B3F)],
    },
    Style {
        name: "bamu_dflt",
        script: 4,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_BAMUM_TOP
            Blue {
                chars: "ꚧ ꚨ ꛛ ꛉ ꛁ ꛈ ꛫ ꛯ",
                props: 1,
            },
            // AF_BLUE_STRING_BAMUM_BOTTOM
            Blue {
                chars: "ꚭ ꚳ ꚶ ꛬ ꚢ ꚽ ꛯ ꛲",
                props: 0,
            },
        ],
        nonbase: &[(0xA6F0, 0xA6F1)],
    },
    Style {
        name: "beng_dflt",
        script: 5,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_BENGALI_TOP
            Blue {
                chars: "ই ট ঠ ি ী ৈ ৗ",
                props: 1,
            },
            // AF_BLUE_STRING_BENGALI_HEAD
            Blue {
                chars: "ও এ ড ত ন ব ল ক",
                props: 1,
            },
            // AF_BLUE_STRING_BENGALI_BASE
            Blue {
                chars: "অ ড ত ন ব ভ ল ক",
                props: 13,
            },
            // AF_BLUE_STRING_BENGALI_BASE
            Blue {
                chars: "অ ড ত ন ব ভ ল ক",
                props: 0,
            },
        ],
        nonbase: &[
            (0x0981, 0x0981),
            (0x09BC, 0x09BC),
            (0x09C1, 0x09C4),
            (0x09CD, 0x09CD),
            (0x09E2, 0x09E3),
            (0x09FE, 0x09FE),
        ],
    },
    Style {
        name: "buhd_dflt",
        script: 6,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_BUHID_TOP
            Blue {
                chars: "ᝐ ᝈ",
                props: 1,
            },
            // AF_BLUE_STRING_BUHID_LARGE
            Blue {
                chars: "ᝅ ᝊ ᝎ",
                props: 1,
            },
            // AF_BLUE_STRING_BUHID_SMALL
            Blue {
                chars: "ᝂ ᝃ ᝉ ᝌ",
                props: 9,
            },
            // AF_BLUE_STRING_BUHID_BOTTOM
            Blue {
                chars: "ᝀ ᝃ ᝆ ᝉ ᝋ ᝏ ᝑ",
                props: 0,
            },
        ],
        nonbase: &[(0x1752, 0x1753)],
    },
    Style {
        name: "cakm_dflt",
        script: 7,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_CHAKMA_TOP
            Blue {
                chars: "𑄃 𑄅 𑄉 𑄙 𑄗",
                props: 1,
            },
            // AF_BLUE_STRING_CHAKMA_BOTTOM
            Blue {
                chars: "𑄅 𑄛 𑄝 𑄗 𑄓",
                props: 0,
            },
            // AF_BLUE_STRING_CHAKMA_DESCENDER
            Blue {
                chars: "𑄖𑄳𑄢 𑄘𑄳𑄢 𑄙𑄳𑄢 𑄤𑄳𑄢 𑄥𑄳𑄢",
                props: 0,
            },
        ],
        nonbase: &[(0x11100, 0x11102), (0x11127, 0x11134), (0x11146, 0x11146)],
    },
    Style {
        name: "cans_dflt",
        script: 8,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_CANADIAN_SYLLABICS_TOP
            Blue {
                chars: "ᗜ ᖴ ᐁ ᒣ ᑫ ᑎ ᔑ ᗰ",
                props: 1,
            },
            // AF_BLUE_STRING_CANADIAN_SYLLABICS_BOTTOM
            Blue {
                chars: "ᗶ ᖵ ᒧ ᐃ ᑌ ᒍ ᔑ ᗢ",
                props: 0,
            },
            // AF_BLUE_STRING_CANADIAN_SYLLABICS_SMALL_TOP
            Blue {
                chars: "ᓓ ᓕ ᓀ ᓂ ᓄ ᕄ ᕆ ᘣ",
                props: 9,
            },
            // AF_BLUE_STRING_CANADIAN_SYLLABICS_SMALL_BOTTOM
            Blue {
                chars: "ᕃ ᓂ ᓀ ᕂ ᓗ ᓚ ᕆ ᘣ",
                props: 0,
            },
            // AF_BLUE_STRING_CANADIAN_SYLLABICS_SUPS_TOP
            Blue {
                chars: "ᐪ ᙆ ᣘ ᐢ ᒾ ᣗ ᔆ",
                props: 1,
            },
            // AF_BLUE_STRING_CANADIAN_SYLLABICS_SUPS_BOTTOM
            Blue {
                chars: "ᙆ ᗮ ᒻ ᐞ ᔆ ᒡ ᒢ ᓑ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "cari_dflt",
        script: 9,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_CARIAN_TOP
            Blue {
                chars: "𐊧 𐊫 𐊬 𐊭 𐊱 𐊺 𐊼 𐊿",
                props: 1,
            },
            // AF_BLUE_STRING_CARIAN_BOTTOM
            Blue {
                chars: "𐊣 𐊧 𐊷 𐋀 𐊫 𐊸 𐋉",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "cher_dflt",
        script: 10,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_CHEROKEE_CAPITAL
            Blue {
                chars: "Ꮖ Ꮋ Ꭼ Ꮓ Ꭴ Ꮳ Ꭶ Ꮥ",
                props: 1,
            },
            // AF_BLUE_STRING_CHEROKEE_CAPITAL
            Blue {
                chars: "Ꮖ Ꮋ Ꭼ Ꮓ Ꭴ Ꮳ Ꭶ Ꮥ",
                props: 0,
            },
            // AF_BLUE_STRING_CHEROKEE_SMALL_ASCENDER
            Blue {
                chars: "ꮒ ꮤ ꮶ ꭴ ꭾ ꮗ ꮝ ꮿ",
                props: 1,
            },
            // AF_BLUE_STRING_CHEROKEE_SMALL
            Blue {
                chars: "ꮖ ꭼ ꮓ ꮠ ꮳ ꭶ ꮥ ꮻ",
                props: 9,
            },
            // AF_BLUE_STRING_CHEROKEE_SMALL
            Blue {
                chars: "ꮖ ꭼ ꮓ ꮠ ꮳ ꭶ ꮥ ꮻ",
                props: 0,
            },
            // AF_BLUE_STRING_CHEROKEE_SMALL_DESCENDER
            Blue {
                chars: "ᏸ ꮐ ꭹ ꭻ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "copt_dflt",
        script: 11,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_COPTIC_CAPITAL_TOP
            Blue {
                chars: "Ⲍ Ⲏ Ⲡ Ⳟ Ⲟ Ⲑ Ⲥ Ⳋ",
                props: 1,
            },
            // AF_BLUE_STRING_COPTIC_CAPITAL_BOTTOM
            Blue {
                chars: "Ⳑ Ⳙ Ⳟ Ⲏ Ⲟ Ⲑ Ⳝ Ⲱ",
                props: 0,
            },
            // AF_BLUE_STRING_COPTIC_SMALL_TOP
            Blue {
                chars: "ⲍ ⲏ ⲡ ⳟ ⲟ ⲑ ⲥ ⳋ",
                props: 9,
            },
            // AF_BLUE_STRING_COPTIC_SMALL_BOTTOM
            Blue {
                chars: "ⳑ ⳙ ⳟ ⲏ ⲟ ⲑ ⳝ Ⳓ",
                props: 0,
            },
        ],
        nonbase: &[(0x2CEF, 0x2CF1)],
    },
    Style {
        name: "cprt_dflt",
        script: 12,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_CYPRIOT_TOP
            Blue {
                chars: "𐠍 𐠙 𐠳 𐠱 𐠅 𐠓 𐠣 𐠦",
                props: 1,
            },
            // AF_BLUE_STRING_CYPRIOT_BOTTOM
            Blue {
                chars: "𐠃 𐠊 𐠛 𐠣 𐠳 𐠵 𐠐",
                props: 0,
            },
            // AF_BLUE_STRING_CYPRIOT_SMALL
            Blue {
                chars: "𐠈 𐠏 𐠖",
                props: 1,
            },
            // AF_BLUE_STRING_CYPRIOT_SMALL
            Blue {
                chars: "𐠈 𐠏 𐠖",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "cyrl_dflt",
        script: 13,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_CYRILLIC_CAPITAL_TOP
            Blue {
                chars: "Б В Е П З О С Э",
                props: 1,
            },
            // AF_BLUE_STRING_CYRILLIC_CAPITAL_BOTTOM
            Blue {
                chars: "Б В Е Ш З О С Э",
                props: 0,
            },
            // AF_BLUE_STRING_CYRILLIC_SMALL
            Blue {
                chars: "х п н ш е з о с",
                props: 9,
            },
            // AF_BLUE_STRING_CYRILLIC_SMALL
            Blue {
                chars: "х п н ш е з о с",
                props: 0,
            },
            // AF_BLUE_STRING_CYRILLIC_SMALL_DESCENDER
            Blue {
                chars: "р у ф",
                props: 0,
            },
        ],
        nonbase: &[
            (0x0483, 0x0489),
            (0x2DE0, 0x2DFF),
            (0xA66F, 0xA67F),
            (0xA69E, 0xA69F),
        ],
    },
    Style {
        name: "deva_dflt",
        script: 14,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_DEVANAGARI_TOP
            Blue {
                chars: "ई ऐ ओ औ ि ी ो ौ",
                props: 1,
            },
            // AF_BLUE_STRING_DEVANAGARI_HEAD
            Blue {
                chars: "क म अ आ थ ध भ श",
                props: 1,
            },
            // AF_BLUE_STRING_DEVANAGARI_BASE
            Blue {
                chars: "क न म उ छ ट ठ ड",
                props: 13,
            },
            // AF_BLUE_STRING_DEVANAGARI_BASE
            Blue {
                chars: "क न म उ छ ट ठ ड",
                props: 0,
            },
            // AF_BLUE_STRING_DEVANAGARI_BOTTOM
            Blue {
                chars: "ु ृ",
                props: 0,
            },
        ],
        nonbase: &[
            (0x0900, 0x0902),
            (0x093A, 0x093A),
            (0x0941, 0x0948),
            (0x094D, 0x094D),
            (0x0953, 0x0957),
            (0x0962, 0x0963),
            (0xA8E0, 0xA8F1),
            (0xA8FF, 0xA8FF),
        ],
    },
    Style {
        name: "dsrt_dflt",
        script: 15,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_DESERET_CAPITAL_TOP
            Blue {
                chars: "𐐂 𐐄 𐐋 𐐗 𐐑",
                props: 1,
            },
            // AF_BLUE_STRING_DESERET_CAPITAL_BOTTOM
            Blue {
                chars: "𐐀 𐐂 𐐄 𐐗 𐐛",
                props: 0,
            },
            // AF_BLUE_STRING_DESERET_SMALL_TOP
            Blue {
                chars: "𐐪 𐐬 𐐳 𐐿 𐐹",
                props: 9,
            },
            // AF_BLUE_STRING_DESERET_SMALL_BOTTOM
            Blue {
                chars: "𐐨 𐐪 𐐬 𐐿 𐑃",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "ethi_dflt",
        script: 16,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_ETHIOPIC_TOP
            Blue {
                chars: "ሀ ሃ ዘ ፐ ማ በ ዋ ዐ",
                props: 1,
            },
            // AF_BLUE_STRING_ETHIOPIC_BOTTOM
            Blue {
                chars: "ለ ሐ በ ዘ ሀ ሪ ዐ ጨ",
                props: 0,
            },
        ],
        nonbase: &[(0x135D, 0x135F)],
    },
    Style {
        name: "geor_dflt",
        script: 17,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_GEORGIAN_MKHEDRULI_TOP
            Blue {
                chars: "გ დ ე ვ თ ი ო ღ",
                props: 9,
            },
            // AF_BLUE_STRING_GEORGIAN_MKHEDRULI_BOTTOM
            Blue {
                chars: "ა ზ მ ს შ ძ ხ პ",
                props: 0,
            },
            // AF_BLUE_STRING_GEORGIAN_MKHEDRULI_ASCENDER
            Blue {
                chars: "ს ხ ქ ზ მ შ ჩ წ",
                props: 1,
            },
            // AF_BLUE_STRING_GEORGIAN_MKHEDRULI_DESCENDER
            Blue {
                chars: "ე ვ ჟ ტ უ ფ ქ ყ",
                props: 0,
            },
            // AF_BLUE_STRING_GEORGIAN_MTAVRULI_TOP
            Blue {
                chars: "Ნ Ჟ Ჳ Ჸ Გ Ე Ო Ჴ",
                props: 1,
            },
            // AF_BLUE_STRING_GEORGIAN_MTAVRULI_BOTTOM
            Blue {
                chars: "Ი Ჲ Ო Ჩ Მ Შ Ჯ Ჽ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "geok_dflt",
        script: 18,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_GEORGIAN_ASOMTAVRULI_TOP
            Blue {
                chars: "Ⴑ Ⴇ Ⴙ Ⴜ Ⴄ Ⴅ Ⴓ Ⴚ",
                props: 1,
            },
            // AF_BLUE_STRING_GEORGIAN_ASOMTAVRULI_BOTTOM
            Blue {
                chars: "Ⴄ Ⴅ Ⴇ Ⴈ Ⴆ Ⴑ Ⴊ Ⴋ",
                props: 0,
            },
            // AF_BLUE_STRING_GEORGIAN_NUSKHURI_TOP
            Blue {
                chars: "ⴁ ⴗ ⴂ ⴄ ⴅ ⴇ ⴔ ⴖ",
                props: 9,
            },
            // AF_BLUE_STRING_GEORGIAN_NUSKHURI_BOTTOM
            Blue {
                chars: "ⴈ ⴌ ⴖ ⴎ ⴃ ⴆ ⴋ ⴢ",
                props: 0,
            },
            // AF_BLUE_STRING_GEORGIAN_NUSKHURI_ASCENDER
            Blue {
                chars: "ⴐ ⴑ ⴓ ⴕ ⴙ ⴛ ⴡ ⴣ",
                props: 1,
            },
            // AF_BLUE_STRING_GEORGIAN_NUSKHURI_DESCENDER
            Blue {
                chars: "ⴄ ⴅ ⴔ ⴕ ⴁ ⴂ ⴘ ⴝ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "glag_dflt",
        script: 19,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_GLAGOLITIC_CAPITAL_TOP
            Blue {
                chars: "Ⰵ Ⱄ Ⱚ Ⰴ Ⰲ Ⰺ Ⱛ Ⰻ",
                props: 1,
            },
            // AF_BLUE_STRING_GLAGOLITIC_CAPITAL_BOTTOM
            Blue {
                chars: "Ⰵ Ⰴ Ⰲ Ⱚ Ⱎ Ⱑ Ⰺ Ⱄ",
                props: 0,
            },
            // AF_BLUE_STRING_GLAGOLITIC_SMALL_TOP
            Blue {
                chars: "ⰵ ⱄ ⱚ ⰴ ⰲ ⰺ ⱛ ⰻ",
                props: 9,
            },
            // AF_BLUE_STRING_GLAGOLITIC_SMALL_BOTTOM
            Blue {
                chars: "ⰵ ⰴ ⰲ ⱚ ⱎ ⱑ ⰺ ⱄ",
                props: 0,
            },
        ],
        nonbase: &[(0x1E000, 0x1E02F)],
    },
    Style {
        name: "goth_dflt",
        script: 20,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_GOTHIC_TOP
            Blue {
                chars: "𐌲 𐌶 𐍀 𐍄 𐌴 𐍃 𐍈 𐌾",
                props: 1,
            },
            // AF_BLUE_STRING_GOTHIC_BOTTOM
            Blue {
                chars: "𐌶 𐌴 𐍃 𐍈",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "grek_dflt",
        script: 21,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_GREEK_CAPITAL_TOP
            Blue {
                chars: "Γ Β Ε Ζ Θ Ο Ω",
                props: 1,
            },
            // AF_BLUE_STRING_GREEK_CAPITAL_BOTTOM
            Blue {
                chars: "Β Δ Ζ Ξ Θ Ο",
                props: 0,
            },
            // AF_BLUE_STRING_GREEK_SMALL_BETA_TOP
            Blue {
                chars: "β θ δ ζ λ ξ",
                props: 1,
            },
            // AF_BLUE_STRING_GREEK_SMALL
            Blue {
                chars: "α ε ι ο π σ τ ω",
                props: 9,
            },
            // AF_BLUE_STRING_GREEK_SMALL
            Blue {
                chars: "α ε ι ο π σ τ ω",
                props: 0,
            },
            // AF_BLUE_STRING_GREEK_SMALL_DESCENDER
            Blue {
                chars: "β γ η μ ρ φ χ ψ",
                props: 0,
            },
        ],
        nonbase: &[
            (0x037A, 0x037A),
            (0x0384, 0x0385),
            (0x1FBD, 0x1FC1),
            (0x1FCD, 0x1FCF),
            (0x1FDD, 0x1FDF),
            (0x1FED, 0x1FEF),
            (0x1FFD, 0x1FFE),
        ],
    },
    Style {
        name: "gujr_dflt",
        script: 22,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_GUJARATI_TOP
            Blue {
                chars: "ત ન ઋ ઌ છ ટ ર ૦",
                props: 9,
            },
            // AF_BLUE_STRING_GUJARATI_BOTTOM
            Blue {
                chars: "ખ ગ ઘ ઞ ઇ ઈ ઠ જ",
                props: 0,
            },
            // AF_BLUE_STRING_GUJARATI_ASCENDER
            Blue {
                chars: "ઈ ઊ િ ી લી શ્ચિ જિ સી",
                props: 1,
            },
            // AF_BLUE_STRING_GUJARATI_DESCENDER
            Blue {
                chars: "ુ ૃ ૄ ખુ છૃ છૄ",
                props: 0,
            },
            // AF_BLUE_STRING_GUJARATI_DIGIT_TOP
            Blue {
                chars: "૦ ૧ ૨ ૩ ૭",
                props: 1,
            },
        ],
        nonbase: &[
            (0x0A81, 0x0A82),
            (0x0ABC, 0x0ABC),
            (0x0AC1, 0x0AC8),
            (0x0ACD, 0x0ACD),
            (0x0AE2, 0x0AE3),
            (0x0AFA, 0x0AFF),
        ],
    },
    Style {
        name: "guru_dflt",
        script: 23,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_GURMUKHI_TOP
            Blue {
                chars: "ਇ ਈ ਉ ਏ ਓ ੳ ਿ ੀ",
                props: 1,
            },
            // AF_BLUE_STRING_GURMUKHI_HEAD
            Blue {
                chars: "ਕ ਗ ਙ ਚ ਜ ਤ ਧ ਸ",
                props: 1,
            },
            // AF_BLUE_STRING_GURMUKHI_BASE
            Blue {
                chars: "ਕ ਗ ਙ ਚ ਜ ਤ ਧ ਸ",
                props: 13,
            },
            // AF_BLUE_STRING_GURMUKHI_BOTTOM
            Blue {
                chars: "ਅ ਏ ਓ ਗ ਜ ਠ ਰ ਸ",
                props: 0,
            },
            // AF_BLUE_STRING_GURMUKHI_DIGIT_TOP
            Blue {
                chars: "੦ ੧ ੨ ੩ ੭",
                props: 1,
            },
        ],
        nonbase: &[
            (0x0A01, 0x0A02),
            (0x0A3C, 0x0A3C),
            (0x0A41, 0x0A51),
            (0x0A70, 0x0A71),
            (0x0A75, 0x0A75),
        ],
    },
    Style {
        name: "hebr_dflt",
        script: 24,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_HEBREW_TOP
            Blue {
                chars: "ב ד ה ח ך כ ם ס",
                props: 17,
            },
            // AF_BLUE_STRING_HEBREW_BOTTOM
            Blue {
                chars: "ב ט כ ם ס צ",
                props: 0,
            },
            // AF_BLUE_STRING_HEBREW_DESCENDER
            Blue {
                chars: "ק ך ן ף ץ",
                props: 0,
            },
        ],
        nonbase: &[
            (0x0591, 0x05BF),
            (0x05C1, 0x05C2),
            (0x05C4, 0x05C5),
            (0x05C7, 0x05C7),
            (0xFB1E, 0xFB1E),
        ],
    },
    Style {
        name: "kali_dflt",
        script: 25,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_KAYAH_LI_TOP
            Blue {
                chars: "꤅ ꤏ ꤁ ꤋ ꤀ ꤍ",
                props: 9,
            },
            // AF_BLUE_STRING_KAYAH_LI_BOTTOM
            Blue {
                chars: "꤈ ꤘ ꤀ ꤍ ꤢ",
                props: 0,
            },
            // AF_BLUE_STRING_KAYAH_LI_ASCENDER
            Blue {
                chars: "ꤖ ꤡ",
                props: 1,
            },
            // AF_BLUE_STRING_KAYAH_LI_DESCENDER
            Blue {
                chars: "ꤑ ꤜ ꤞ",
                props: 0,
            },
            // AF_BLUE_STRING_KAYAH_LI_LARGE_DESCENDER
            Blue {
                chars: "ꤑ꤬ ꤜ꤭ ꤔ꤬",
                props: 0,
            },
        ],
        nonbase: &[(0xA926, 0xA92D)],
    },
    Style {
        name: "khmr_dflt",
        script: 26,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_KHMER_TOP
            Blue {
                chars: "ខ ទ ន ឧ ឩ ា",
                props: 9,
            },
            // AF_BLUE_STRING_KHMER_SUBSCRIPT_TOP
            Blue {
                chars: "ក្ក ក្ខ ក្គ ក្ថ",
                props: 2,
            },
            // AF_BLUE_STRING_KHMER_BOTTOM
            Blue {
                chars: "ខ ឃ ច ឋ ប ម យ ឲ",
                props: 0,
            },
            // AF_BLUE_STRING_KHMER_DESCENDER
            Blue {
                chars: "ត្រ រៀ ឲ្យ អឿ",
                props: 0,
            },
            // AF_BLUE_STRING_KHMER_LARGE_DESCENDER
            Blue {
                chars: "ន្ត្រៃ ង្ខ្យ ក្បៀ ច្រៀ ន្តឿ ល្បឿ",
                props: 0,
            },
        ],
        nonbase: &[
            (0x17B7, 0x17BD),
            (0x17C6, 0x17C6),
            (0x17C9, 0x17D3),
            (0x17DD, 0x17DD),
        ],
    },
    Style {
        name: "khms_dflt",
        script: 27,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_KHMER_SYMBOLS_WAXING_TOP
            Blue {
                chars: "᧠ ᧡",
                props: 9,
            },
            // AF_BLUE_STRING_KHMER_SYMBOLS_WANING_BOTTOM
            Blue {
                chars: "᧶ ᧹",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "knda_dflt",
        script: 28,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_KANNADA_TOP
            Blue {
                chars: "ಇ ಊ ಐ ಣ ಸಾ ನಾ ದಾ ರಾ",
                props: 1,
            },
            // AF_BLUE_STRING_KANNADA_BOTTOM
            Blue {
                chars: "ಅ ಉ ಎ ಲ ೦ ೨ ೬ ೭",
                props: 0,
            },
        ],
        nonbase: &[
            (0x0C81, 0x0C81),
            (0x0CBC, 0x0CBC),
            (0x0CBF, 0x0CBF),
            (0x0CC6, 0x0CC6),
            (0x0CCC, 0x0CCD),
            (0x0CE2, 0x0CE3),
        ],
    },
    Style {
        name: "lao_dflt",
        script: 29,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_LAO_TOP
            Blue {
                chars: "າ ດ ອ ມ ລ ວ ຣ ງ",
                props: 9,
            },
            // AF_BLUE_STRING_LAO_BOTTOM
            Blue {
                chars: "າ ອ ບ ຍ ຣ ຮ ວ ຢ",
                props: 0,
            },
            // AF_BLUE_STRING_LAO_ASCENDER
            Blue {
                chars: "ປ ຢ ຟ ຝ",
                props: 1,
            },
            // AF_BLUE_STRING_LAO_LARGE_ASCENDER
            Blue {
                chars: "ໂ ໄ ໃ",
                props: 1,
            },
            // AF_BLUE_STRING_LAO_DESCENDER
            Blue {
                chars: "ງ ຊ ຖ ຽ ໆ ຯ",
                props: 0,
            },
        ],
        nonbase: &[(0x0EB1, 0x0EB1), (0x0EB4, 0x0EBC), (0x0EC8, 0x0ECD)],
    },
    Style {
        name: "latn_dflt",
        script: 30,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_LATIN_CAPITAL_TOP
            Blue {
                chars: "T H E Z O C Q S",
                props: 1,
            },
            // AF_BLUE_STRING_LATIN_CAPITAL_BOTTOM
            Blue {
                chars: "H E Z L O C U S",
                props: 0,
            },
            // AF_BLUE_STRING_LATIN_SMALL_F_TOP
            Blue {
                chars: "f i j k d b h",
                props: 1,
            },
            // AF_BLUE_STRING_LATIN_SMALL_TOP
            Blue {
                chars: "u v x z o e s c",
                props: 9,
            },
            // AF_BLUE_STRING_LATIN_SMALL_BOTTOM
            Blue {
                chars: "n r x z o e s c",
                props: 0,
            },
            // AF_BLUE_STRING_LATIN_SMALL_DESCENDER
            Blue {
                chars: "p q g j y",
                props: 0,
            },
        ],
        nonbase: &[
            (0x005E, 0x0060),
            (0x007E, 0x007E),
            (0x00A8, 0x00A9),
            (0x00AE, 0x00B0),
            (0x00B4, 0x00B4),
            (0x00B8, 0x00B8),
            (0x00BC, 0x00BE),
            (0x02B9, 0x02DF),
            (0x02E5, 0x02FF),
            (0x0300, 0x036F),
            (0x1AB0, 0x1ABE),
            (0x1DC0, 0x1DFF),
            (0x2017, 0x2017),
            (0x203E, 0x203E),
            (0xA788, 0xA788),
            (0xA7F8, 0xA7FA),
        ],
    },
    Style {
        name: "latb_dflt",
        script: 31,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_LATIN_SUBS_CAPITAL_TOP
            Blue {
                chars: "₀ ₃ ₅ ₇ ₈",
                props: 1,
            },
            // AF_BLUE_STRING_LATIN_SUBS_CAPITAL_BOTTOM
            Blue {
                chars: "₀ ₁ ₂ ₃ ₈",
                props: 0,
            },
            // AF_BLUE_STRING_LATIN_SUBS_SMALL_F_TOP
            Blue {
                chars: "ᵢ ⱼ ₕ ₖ ₗ",
                props: 1,
            },
            // AF_BLUE_STRING_LATIN_SUBS_SMALL
            Blue {
                chars: "ₐ ₑ ₒ ₓ ₙ ₛ ᵥ ᵤ ᵣ",
                props: 9,
            },
            // AF_BLUE_STRING_LATIN_SUBS_SMALL
            Blue {
                chars: "ₐ ₑ ₒ ₓ ₙ ₛ ᵥ ᵤ ᵣ",
                props: 0,
            },
            // AF_BLUE_STRING_LATIN_SUBS_SMALL_DESCENDER
            Blue {
                chars: "ᵦ ᵧ ᵨ ᵩ ₚ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "latp_dflt",
        script: 32,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_LATIN_SUPS_CAPITAL_TOP
            Blue {
                chars: "⁰ ³ ⁵ ⁷ ᵀ ᴴ ᴱ ᴼ",
                props: 1,
            },
            // AF_BLUE_STRING_LATIN_SUPS_CAPITAL_BOTTOM
            Blue {
                chars: "⁰ ¹ ² ³ ᴱ ᴸ ᴼ ᵁ",
                props: 0,
            },
            // AF_BLUE_STRING_LATIN_SUPS_SMALL_F_TOP
            Blue {
                chars: "ᵇ ᵈ ᵏ ʰ ʲ ᶠ ⁱ",
                props: 1,
            },
            // AF_BLUE_STRING_LATIN_SUPS_SMALL
            Blue {
                chars: "ᵉ ᵒ ʳ ˢ ˣ ᶜ ᶻ",
                props: 9,
            },
            // AF_BLUE_STRING_LATIN_SUPS_SMALL
            Blue {
                chars: "ᵉ ᵒ ʳ ˢ ˣ ᶜ ᶻ",
                props: 0,
            },
            // AF_BLUE_STRING_LATIN_SUPS_SMALL_DESCENDER
            Blue {
                chars: "ᵖ ʸ ᵍ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "lisu_dflt",
        script: 33,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_LISU_TOP
            Blue {
                chars: "ꓡ ꓧ ꓱ ꓶ ꓩ ꓚ ꓵ ꓳ",
                props: 1,
            },
            // AF_BLUE_STRING_LISU_BOTTOM
            Blue {
                chars: "ꓕ ꓜ ꓞ ꓡ ꓛ ꓢ ꓳ ꓴ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "mlym_dflt",
        script: 34,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_MALAYALAM_TOP
            Blue {
                chars: "ഒ ട ഠ റ ച പ ച്ച പ്പ",
                props: 1,
            },
            // AF_BLUE_STRING_MALAYALAM_BOTTOM
            Blue {
                chars: "ട ഠ ധ ശ ഘ ച ഥ ല",
                props: 0,
            },
        ],
        nonbase: &[
            (0x0D00, 0x0D01),
            (0x0D3B, 0x0D3C),
            (0x0D4D, 0x0D4E),
            (0x0D62, 0x0D63),
        ],
    },
    Style {
        name: "medf_dflt",
        script: 35,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_MEDEFAIDRIN_CAPITAL_TOP
            Blue {
                chars: "𖹀 𖹁 𖹂 𖹃 𖹏 𖹚 𖹟",
                props: 1,
            },
            // AF_BLUE_STRING_MEDEFAIDRIN_CAPITAL_BOTTOM
            Blue {
                chars: "𖹀 𖹁 𖹂 𖹃 𖹏 𖹚 𖹒 𖹓",
                props: 0,
            },
            // AF_BLUE_STRING_MEDEFAIDRIN_SMALL_F_TOP
            Blue {
                chars: "𖹤 𖹬 𖹧 𖹴 𖹶 𖹾",
                props: 1,
            },
            // AF_BLUE_STRING_MEDEFAIDRIN_SMALL_TOP
            Blue {
                chars: "𖹠 𖹡 𖹢 𖹹 𖹳 𖹮",
                props: 9,
            },
            // AF_BLUE_STRING_MEDEFAIDRIN_SMALL_BOTTOM
            Blue {
                chars: "𖹠 𖹡 𖹢 𖹳 𖹭 𖹽",
                props: 0,
            },
            // AF_BLUE_STRING_MEDEFAIDRIN_SMALL_DESCENDER
            Blue {
                chars: "𖹥 𖹨 𖹩",
                props: 0,
            },
            // AF_BLUE_STRING_MEDEFAIDRIN_DIGIT_TOP
            Blue {
                chars: "𖺀 𖺅 𖺈 𖺄 𖺍",
                props: 1,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "mong_dflt",
        script: 36,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_MONGOLIAN_TOP_BASE
            Blue {
                chars: "ᠳ ᠴ ᠶ ᠽ ᡂ ᡊ ‍ᡡ‍ ‍ᡳ‍",
                props: 1,
            },
            // AF_BLUE_STRING_MONGOLIAN_BOTTOM_BASE
            Blue {
                chars: "ᡃ",
                props: 0,
            },
        ],
        nonbase: &[(0x1885, 0x1886), (0x18A9, 0x18A9)],
    },
    Style {
        name: "mymr_dflt",
        script: 37,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_MYANMAR_TOP
            Blue {
                chars: "ခ ဂ င ဒ ဝ ၥ ၊ ။",
                props: 9,
            },
            // AF_BLUE_STRING_MYANMAR_BOTTOM
            Blue {
                chars: "င ဎ ဒ ပ ဗ ဝ ၊ ။",
                props: 0,
            },
            // AF_BLUE_STRING_MYANMAR_ASCENDER
            Blue {
                chars: "ဩ ြ ၍ ၏ ၆ ါ ိ",
                props: 1,
            },
            // AF_BLUE_STRING_MYANMAR_DESCENDER
            Blue {
                chars: "ဉ ည ဥ ဩ ဨ ၂ ၅ ၉",
                props: 0,
            },
        ],
        nonbase: &[
            (0x102D, 0x1030),
            (0x1032, 0x1037),
            (0x103A, 0x103A),
            (0x103D, 0x103E),
            (0x1058, 0x1059),
            (0x105E, 0x1060),
            (0x1071, 0x1074),
            (0x1082, 0x1082),
            (0x1085, 0x1086),
            (0x108D, 0x108D),
            (0xA9E5, 0xA9E5),
            (0xAA7C, 0xAA7C),
        ],
    },
    Style {
        name: "nkoo_dflt",
        script: 38,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_NKO_TOP
            Blue {
                chars: "ߐ ߉ ߒ ߟ ߖ ߜ ߠ ߥ",
                props: 1,
            },
            // AF_BLUE_STRING_NKO_BOTTOM
            Blue {
                chars: "߀ ߘ ߡ ߠ ߥ",
                props: 0,
            },
            // AF_BLUE_STRING_NKO_SMALL_TOP
            Blue {
                chars: "ߏ ߛ ߋ",
                props: 9,
            },
            // AF_BLUE_STRING_NKO_SMALL_BOTTOM
            Blue {
                chars: "ߎ ߏ ߛ ߋ",
                props: 0,
            },
        ],
        nonbase: &[(0x07EB, 0x07F5), (0x07FD, 0x07FD)],
    },
    Style {
        name: "none_dflt",
        script: 39,
        system: System::Dummy,
        blues: &[],
        nonbase: &[],
    },
    Style {
        name: "olck_dflt",
        script: 40,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_OL_CHIKI
            Blue {
                chars: "ᱛ ᱜ ᱝ ᱡ ᱢ ᱥ",
                props: 1,
            },
            // AF_BLUE_STRING_OL_CHIKI
            Blue {
                chars: "ᱛ ᱜ ᱝ ᱡ ᱢ ᱥ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "orkh_dflt",
        script: 41,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_OLD_TURKIC_TOP
            Blue {
                chars: "𐰗 𐰘 𐰧",
                props: 1,
            },
            // AF_BLUE_STRING_OLD_TURKIC_BOTTOM
            Blue {
                chars: "𐰉 𐰗 𐰦 𐰧",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "osge_dflt",
        script: 42,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_OSAGE_CAPITAL_TOP
            Blue {
                chars: "𐒾 𐓍 𐓒 𐓓 𐒻 𐓂 𐒵 𐓆",
                props: 1,
            },
            // AF_BLUE_STRING_OSAGE_CAPITAL_BOTTOM
            Blue {
                chars: "𐒰 𐓍 𐓂 𐒿 𐓎 𐒹",
                props: 0,
            },
            // AF_BLUE_STRING_OSAGE_CAPITAL_DESCENDER
            Blue {
                chars: "𐒼 𐒽 𐒾",
                props: 0,
            },
            // AF_BLUE_STRING_OSAGE_SMALL_TOP
            Blue {
                chars: "𐓵 𐓶 𐓺 𐓻 𐓝 𐓣 𐓪 𐓮",
                props: 9,
            },
            // AF_BLUE_STRING_OSAGE_SMALL_BOTTOM
            Blue {
                chars: "𐓘 𐓚 𐓣 𐓵 𐓡 𐓧 𐓪 𐓶",
                props: 0,
            },
            // AF_BLUE_STRING_OSAGE_SMALL_ASCENDER
            Blue {
                chars: "𐓤 𐓦 𐓸 𐓹 𐓛",
                props: 1,
            },
            // AF_BLUE_STRING_OSAGE_SMALL_DESCENDER
            Blue {
                chars: "𐓤 𐓥 𐓦",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "osma_dflt",
        script: 43,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_OSMANYA_TOP
            Blue {
                chars: "𐒆 𐒉 𐒐 𐒒 𐒘 𐒛 𐒠 𐒣",
                props: 1,
            },
            // AF_BLUE_STRING_OSMANYA_BOTTOM
            Blue {
                chars: "𐒀 𐒂 𐒆 𐒈 𐒊 𐒒 𐒠 𐒩",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "rohg_dflt",
        script: 44,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_ROHINGYA_TOP
            Blue {
                chars: "𐴃 𐴀 𐴆 𐴖 𐴕",
                props: 1,
            },
            // AF_BLUE_STRING_ROHINGYA_BOTTOM
            Blue {
                chars: "𐴔 𐴖 𐴕 𐴑 𐴐",
                props: 0,
            },
            // AF_BLUE_STRING_ROHINGYA_JOIN
            Blue {
                chars: "ـ",
                props: 4,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "saur_dflt",
        script: 45,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_SAURASHTRA_TOP
            Blue {
                chars: "ꢜ ꢞ ꢳ ꢂ ꢖ ꢒ ꢝ ꢛ",
                props: 1,
            },
            // AF_BLUE_STRING_SAURASHTRA_BOTTOM
            Blue {
                chars: "ꢂ ꢨ ꢺ ꢤ ꢎ",
                props: 0,
            },
        ],
        nonbase: &[(0xA880, 0xA881), (0xA8B4, 0xA8C5)],
    },
    Style {
        name: "shaw_dflt",
        script: 46,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_SHAVIAN_TOP
            Blue {
                chars: "𐑕 𐑙",
                props: 1,
            },
            // AF_BLUE_STRING_SHAVIAN_BOTTOM
            Blue {
                chars: "𐑔 𐑖 𐑗 𐑹 𐑻",
                props: 0,
            },
            // AF_BLUE_STRING_SHAVIAN_DESCENDER
            Blue {
                chars: "𐑟 𐑣",
                props: 0,
            },
            // AF_BLUE_STRING_SHAVIAN_SMALL_TOP
            Blue {
                chars: "𐑱 𐑲 𐑳 𐑴 𐑸 𐑺 𐑼",
                props: 9,
            },
            // AF_BLUE_STRING_SHAVIAN_SMALL_BOTTOM
            Blue {
                chars: "𐑴 𐑻 𐑹",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "sinh_dflt",
        script: 47,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_SINHALA_TOP
            Blue {
                chars: "ඉ ක ඝ ඳ ප ය ල ෆ",
                props: 1,
            },
            // AF_BLUE_STRING_SINHALA_BOTTOM
            Blue {
                chars: "එ ඔ ඝ ජ ට ථ ධ ර",
                props: 0,
            },
            // AF_BLUE_STRING_SINHALA_DESCENDER
            Blue {
                chars: "ද ඳ උ ල තූ තු බු දු",
                props: 0,
            },
        ],
        nonbase: &[(0x0DCA, 0x0DCA), (0x0DD2, 0x0DD6)],
    },
    Style {
        name: "sund_dflt",
        script: 48,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_SUNDANESE_TOP
            Blue {
                chars: "ᮋ ᮞ ᮮ ᮽ ᮰ ᮈ",
                props: 1,
            },
            // AF_BLUE_STRING_SUNDANESE_BOTTOM
            Blue {
                chars: "ᮄ ᮔ ᮕ ᮗ ᮰ ᮆ ᮈ ᮉ",
                props: 0,
            },
            // AF_BLUE_STRING_SUNDANESE_DESCENDER
            Blue {
                chars: "ᮼ ᳄",
                props: 0,
            },
        ],
        nonbase: &[(0x1B80, 0x1B82), (0x1BA1, 0x1BAD)],
    },
    Style {
        name: "taml_dflt",
        script: 49,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_TAMIL_TOP
            Blue {
                chars: "உ ஒ ஓ ற ஈ க ங ச",
                props: 1,
            },
            // AF_BLUE_STRING_TAMIL_BOTTOM
            Blue {
                chars: "க ச ல ஶ உ ங ட ப",
                props: 0,
            },
        ],
        nonbase: &[(0x0B82, 0x0B82), (0x0BC0, 0x0BC2), (0x0BCD, 0x0BCD)],
    },
    Style {
        name: "tavt_dflt",
        script: 50,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_TAI_VIET_TOP
            Blue {
                chars: "ꪆ ꪔ ꪒ ꪖ ꪫ",
                props: 1,
            },
            // AF_BLUE_STRING_TAI_VIET_BOTTOM
            Blue {
                chars: "ꪉ ꪫ ꪮ",
                props: 0,
            },
        ],
        nonbase: &[
            (0xAAB0, 0xAAB0),
            (0xAAB2, 0xAAB4),
            (0xAAB7, 0xAAB8),
            (0xAABE, 0xAABF),
            (0xAAC1, 0xAAC1),
        ],
    },
    Style {
        name: "telu_dflt",
        script: 51,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_TELUGU_TOP
            Blue {
                chars: "ఇ ఌ ఙ ఞ ణ ఱ ౯",
                props: 1,
            },
            // AF_BLUE_STRING_TELUGU_BOTTOM
            Blue {
                chars: "అ క చ ర ఽ ౨ ౬",
                props: 0,
            },
        ],
        nonbase: &[
            (0x0C00, 0x0C00),
            (0x0C04, 0x0C04),
            (0x0C3E, 0x0C40),
            (0x0C46, 0x0C56),
            (0x0C62, 0x0C63),
        ],
    },
    Style {
        name: "tfng_dflt",
        script: 52,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_TIFINAGH
            Blue {
                chars: "ⵔ ⵙ ⵛ ⵞ ⴵ ⴼ ⴹ ⵎ",
                props: 1,
            },
            // AF_BLUE_STRING_TIFINAGH
            Blue {
                chars: "ⵔ ⵙ ⵛ ⵞ ⴵ ⴼ ⴹ ⵎ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "thai_dflt",
        script: 53,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_THAI_TOP
            Blue {
                chars: "บ เ แ อ ก า",
                props: 9,
            },
            // AF_BLUE_STRING_THAI_BOTTOM
            Blue {
                chars: "บ ป ษ ฯ อ ย ฮ",
                props: 0,
            },
            // AF_BLUE_STRING_THAI_ASCENDER
            Blue {
                chars: "ป ฝ ฟ",
                props: 1,
            },
            // AF_BLUE_STRING_THAI_LARGE_ASCENDER
            Blue {
                chars: "โ ใ ไ",
                props: 1,
            },
            // AF_BLUE_STRING_THAI_DESCENDER
            Blue {
                chars: "ฎ ฏ ฤ ฦ",
                props: 0,
            },
            // AF_BLUE_STRING_THAI_LARGE_DESCENDER
            Blue {
                chars: "ญ ฐ",
                props: 0,
            },
            // AF_BLUE_STRING_THAI_DIGIT_TOP
            Blue {
                chars: "๐ ๑ ๓",
                props: 0,
            },
        ],
        nonbase: &[(0x0E31, 0x0E31), (0x0E34, 0x0E3A), (0x0E47, 0x0E4E)],
    },
    Style {
        name: "vaii_dflt",
        script: 54,
        system: System::Latin,
        blues: &[
            // AF_BLUE_STRING_VAI_TOP
            Blue {
                chars: "ꗍ ꘖ ꘙ ꘜ ꖜ ꖝ ꔅ ꕢ",
                props: 1,
            },
            // AF_BLUE_STRING_VAI_BOTTOM
            Blue {
                chars: "ꗍ ꘖ ꘙ ꗞ ꔅ ꕢ ꖜ ꔆ",
                props: 0,
            },
        ],
        nonbase: &[],
    },
    Style {
        name: "limb_dflt",
        script: 55,
        system: System::Indic,
        blues: &[],
        nonbase: &[(0x1920, 0x1922), (0x1927, 0x1934), (0x1937, 0x193B)],
    },
    Style {
        name: "orya_dflt",
        script: 56,
        system: System::Indic,
        blues: &[],
        nonbase: &[
            (0x0B01, 0x0B02),
            (0x0B3C, 0x0B3C),
            (0x0B3F, 0x0B3F),
            (0x0B41, 0x0B44),
            (0x0B4D, 0x0B56),
            (0x0B62, 0x0B63),
        ],
    },
    Style {
        name: "sylo_dflt",
        script: 57,
        system: System::Indic,
        blues: &[],
        nonbase: &[
            (0xA802, 0xA802),
            (0xA806, 0xA806),
            (0xA80B, 0xA80B),
            (0xA825, 0xA826),
        ],
    },
    Style {
        name: "tibt_dflt",
        script: 58,
        system: System::Indic,
        blues: &[],
        nonbase: &[
            (0x0F18, 0x0F19),
            (0x0F35, 0x0F35),
            (0x0F37, 0x0F37),
            (0x0F39, 0x0F39),
            (0x0F3E, 0x0F3F),
            (0x0F71, 0x0F7E),
            (0x0F80, 0x0F84),
            (0x0F86, 0x0F87),
            (0x0F8D, 0x0FBC),
        ],
    },
    Style {
        name: "hani_dflt",
        script: 59,
        system: System::Cjk,
        blues: &[
            // AF_BLUE_STRING_CJK_TOP
            Blue {
                chars: "他 们 你 來 們 到 和 地 对 對 就 席 我 时 時 會 来 為 能 舰 說 说 这 這 齊 | 军 同 已 愿 既 星 是 景 民 照 现 現 理 用 置 要 軍 那 配 里 開 雷 露 面 顾",
                props: 1,
            },
            // AF_BLUE_STRING_CJK_BOTTOM
            Blue {
                chars: "个 为 人 他 以 们 你 來 個 們 到 和 大 对 對 就 我 时 時 有 来 為 要 說 说 | 主 些 因 它 想 意 理 生 當 看 着 置 者 自 著 裡 过 还 进 進 過 道 還 里 面",
                props: 0,
            },
        ],
        nonbase: &[(0x302A, 0x302F), (0x3190, 0x319F)],
    },
];

/// Code points to styles: sorted, disjoint `(first, last, style)`
/// ranges, resolved first-come-first-served in style order.
pub(super) static RANGES: [(u32, u32, u8); 138] = [
    (0x0020, 0x007F, 30),   // latn_dflt
    (0x00A0, 0x00A9, 30),   // latn_dflt
    (0x00AA, 0x00AA, 32),   // latp_dflt
    (0x00AB, 0x00B1, 30),   // latn_dflt
    (0x00B2, 0x00B3, 32),   // latp_dflt
    (0x00B4, 0x00B8, 30),   // latn_dflt
    (0x00B9, 0x00BA, 32),   // latp_dflt
    (0x00BB, 0x02AF, 30),   // latn_dflt
    (0x02B0, 0x02B8, 32),   // latp_dflt
    (0x02B9, 0x02DF, 30),   // latn_dflt
    (0x02E0, 0x02E4, 32),   // latp_dflt
    (0x02E5, 0x036F, 30),   // latn_dflt
    (0x0370, 0x03FF, 21),   // grek_dflt
    (0x0400, 0x052F, 13),   // cyrl_dflt
    (0x0530, 0x058F, 2),    // armn_dflt
    (0x0590, 0x05FF, 24),   // hebr_dflt
    (0x0600, 0x06FF, 1),    // arab_dflt
    (0x0750, 0x07FF, 1),    // arab_dflt
    (0x08A0, 0x08FF, 1),    // arab_dflt
    (0x0900, 0x093B, 14),   // deva_dflt
    (0x093D, 0x0950, 14),   // deva_dflt
    (0x0953, 0x0963, 14),   // deva_dflt
    (0x0966, 0x097F, 14),   // deva_dflt
    (0x0980, 0x09FF, 5),    // beng_dflt
    (0x0A00, 0x0A7F, 23),   // guru_dflt
    (0x0A80, 0x0AFF, 22),   // gujr_dflt
    (0x0B00, 0x0B7F, 56),   // orya_dflt
    (0x0B80, 0x0BFF, 49),   // taml_dflt
    (0x0C00, 0x0C7F, 51),   // telu_dflt
    (0x0C80, 0x0CFF, 28),   // knda_dflt
    (0x0D00, 0x0D7F, 34),   // mlym_dflt
    (0x0D80, 0x0DFF, 47),   // sinh_dflt
    (0x0E00, 0x0E7F, 53),   // thai_dflt
    (0x0E80, 0x0EFF, 29),   // lao_dflt
    (0x0F00, 0x0FFF, 58),   // tibt_dflt
    (0x1000, 0x109F, 37),   // mymr_dflt
    (0x10A0, 0x10CD, 18),   // geok_dflt
    (0x10D0, 0x10FF, 17),   // geor_dflt
    (0x1100, 0x11FF, 59),   // hani_dflt
    (0x1200, 0x139F, 16),   // ethi_dflt
    (0x13A0, 0x13FF, 10),   // cher_dflt
    (0x1400, 0x167F, 8),    // cans_dflt
    (0x1740, 0x175F, 6),    // buhd_dflt
    (0x1780, 0x17FF, 26),   // khmr_dflt
    (0x1800, 0x18AF, 36),   // mong_dflt
    (0x18B0, 0x18FF, 8),    // cans_dflt
    (0x1900, 0x194F, 55),   // limb_dflt
    (0x19E0, 0x19FF, 27),   // khms_dflt
    (0x1AB0, 0x1ABE, 30),   // latn_dflt
    (0x1B80, 0x1BBF, 48),   // sund_dflt
    (0x1C50, 0x1C7F, 40),   // olck_dflt
    (0x1C80, 0x1C8F, 13),   // cyrl_dflt
    (0x1C90, 0x1CBF, 17),   // geor_dflt
    (0x1CC0, 0x1CCF, 48),   // sund_dflt
    (0x1D00, 0x1D2B, 30),   // latn_dflt
    (0x1D2C, 0x1D61, 32),   // latp_dflt
    (0x1D62, 0x1D6A, 31),   // latb_dflt
    (0x1D6B, 0x1D77, 30),   // latn_dflt
    (0x1D78, 0x1D78, 32),   // latp_dflt
    (0x1D79, 0x1D9A, 30),   // latn_dflt
    (0x1D9B, 0x1DBF, 32),   // latp_dflt
    (0x1DC0, 0x1EFF, 30),   // latn_dflt
    (0x1F00, 0x1FFF, 21),   // grek_dflt
    (0x2000, 0x206F, 30),   // latn_dflt
    (0x2070, 0x207F, 32),   // latp_dflt
    (0x2080, 0x209C, 31),   // latb_dflt
    (0x20A0, 0x20B8, 30),   // latn_dflt
    (0x20B9, 0x20B9, 14),   // deva_dflt
    (0x20BA, 0x20CF, 30),   // latn_dflt
    (0x2150, 0x218F, 30),   // latn_dflt
    (0x2C00, 0x2C5F, 19),   // glag_dflt
    (0x2C60, 0x2C7B, 30),   // latn_dflt
    (0x2C7C, 0x2C7C, 31),   // latb_dflt
    (0x2C7D, 0x2C7D, 32),   // latp_dflt
    (0x2C7E, 0x2C7F, 30),   // latn_dflt
    (0x2C80, 0x2CFF, 11),   // copt_dflt
    (0x2D00, 0x2D2D, 18),   // geok_dflt
    (0x2D30, 0x2D7F, 52),   // tfng_dflt
    (0x2D80, 0x2DDF, 16),   // ethi_dflt
    (0x2DE0, 0x2DFF, 13),   // cyrl_dflt
    (0x2E00, 0x2E7F, 30),   // latn_dflt
    (0x2E80, 0x2FDF, 59),   // hani_dflt
    (0x2FF0, 0x31FF, 59),   // hani_dflt
    (0x3300, 0x9FFF, 59),   // hani_dflt
    (0xA4D0, 0xA4FF, 33),   // lisu_dflt
    (0xA500, 0xA63F, 54),   // vaii_dflt
    (0xA640, 0xA69F, 13),   // cyrl_dflt
    (0xA6A0, 0xA6FF, 4),    // bamu_dflt
    (0xA720, 0xA76F, 30),   // latn_dflt
    (0xA770, 0xA770, 32),   // latp_dflt
    (0xA771, 0xA7F7, 30),   // latn_dflt
    (0xA7F8, 0xA7F9, 32),   // latp_dflt
    (0xA7FA, 0xA7FF, 30),   // latn_dflt
    (0xA800, 0xA82F, 57),   // sylo_dflt
    (0xA880, 0xA8DF, 45),   // saur_dflt
    (0xA8E0, 0xA8FF, 14),   // deva_dflt
    (0xA900, 0xA92F, 25),   // kali_dflt
    (0xA960, 0xA97F, 59),   // hani_dflt
    (0xA9E0, 0xA9FF, 37),   // mymr_dflt
    (0xAA60, 0xAA7F, 37),   // mymr_dflt
    (0xAA80, 0xAADF, 50),   // tavt_dflt
    (0xAB00, 0xAB2F, 16),   // ethi_dflt
    (0xAB30, 0xAB5B, 30),   // latn_dflt
    (0xAB5C, 0xAB5F, 32),   // latp_dflt
    (0xAB60, 0xAB6F, 30),   // latn_dflt
    (0xAB70, 0xABBF, 10),   // cher_dflt
    (0xAC00, 0xD7FF, 59),   // hani_dflt
    (0xF900, 0xFAFF, 59),   // hani_dflt
    (0xFB00, 0xFB06, 30),   // latn_dflt
    (0xFB13, 0xFB17, 2),    // armn_dflt
    (0xFB1D, 0xFB4F, 24),   // hebr_dflt
    (0xFB50, 0xFDFF, 1),    // arab_dflt
    (0xFE10, 0xFE1F, 59),   // hani_dflt
    (0xFE30, 0xFE4F, 59),   // hani_dflt
    (0xFE70, 0xFEFF, 1),    // arab_dflt
    (0xFF00, 0xFFEF, 59),   // hani_dflt
    (0x102A0, 0x102DF, 9),  // cari_dflt
    (0x10330, 0x1034F, 20), // goth_dflt
    (0x10400, 0x1044F, 15), // dsrt_dflt
    (0x10450, 0x1047F, 46), // shaw_dflt
    (0x10480, 0x104AF, 43), // osma_dflt
    (0x104B0, 0x104FF, 42), // osge_dflt
    (0x10800, 0x1083F, 12), // cprt_dflt
    (0x10B00, 0x10B3F, 3),  // avst_dflt
    (0x10C00, 0x10C4F, 41), // orkh_dflt
    (0x10D00, 0x10D3F, 44), // rohg_dflt
    (0x11100, 0x1114F, 7),  // cakm_dflt
    (0x11660, 0x1167F, 36), // mong_dflt
    (0x16E40, 0x16E9F, 35), // medf_dflt
    (0x1B000, 0x1B12F, 59), // hani_dflt
    (0x1D300, 0x1D35F, 59), // hani_dflt
    (0x1D400, 0x1D7FF, 30), // latn_dflt
    (0x1E000, 0x1E02F, 19), // glag_dflt
    (0x1E900, 0x1E95F, 0),  // adlm_dflt
    (0x1EE00, 0x1EEFF, 1),  // arab_dflt
    (0x20000, 0x2A6DF, 59), // hani_dflt
    (0x2A700, 0x2EBEF, 59), // hani_dflt
    (0x2F800, 0x2FA1F, 59), // hani_dflt
];
