//! Virtual Filesystem (VFS) layer.
//!
//! The VFS provides a uniform interface for filesystem operations,
//! decoupling the kernel and userspace from specific filesystem
//! implementations.  All file I/O goes through VFS traits.
//!
//! ## Architecture
//!
//! ```text
//! kshell / syscalls
//!       ↓
//!   VFS (mount table, path resolution)
//!       ↓
//!   Filesystem trait impl (FAT16, ext4, …)
//!       ↓
//!   BlockDevice trait
//!       ↓
//!   driver (virtio-blk, NVMe, …)
//! ```
//!
//! ## Mount table
//!
//! Multiple filesystems can be mounted at different paths (e.g., `/`
//! for the root FAT volume and `/tmp` for a volatile ramfs).  The VFS
//! uses longest-prefix matching to route operations to the correct
//! filesystem.

pub mod a11y;
pub mod acl;
#[allow(dead_code)]
pub mod ar;
pub mod atime;
pub mod archive;
pub mod audit;
pub mod authbroker;
pub mod appnotify;
pub mod appdefaults;
pub mod applaunch;
pub mod appregistry;
pub mod appcompat;
pub mod apppermissions;
pub mod appstore;
pub mod appsandbox;
pub mod associations;
pub mod audioeq;
pub mod audiodevice;
pub mod audiomux;
pub mod autostart;
pub mod autofix;
pub mod backup;
pub mod battery;
pub mod blktrace;
pub mod bootcfg;
pub mod bookmarks;
pub mod brightness;
pub mod backupsched;
pub mod batch;
pub mod bench;
pub mod bluetooth;
#[allow(dead_code)]
pub mod bzip2;
pub mod cache;
pub mod capsettings;
pub mod cas;
pub mod certmgr;
pub mod cgroupfs;
pub mod cliphistory;
pub mod clipboard;
pub mod clipsync;
pub mod clipaction;
pub mod cloudsync;
pub mod colorblind;
pub mod colorpicker;
pub mod coredump;
pub mod colorscheme;
pub mod colortemp;
pub mod compstat;
pub mod cpufreq;
pub mod cpuidle;
pub mod cputopo;
pub mod changetrack;
pub mod columnview;
pub mod compress;
pub mod contextmenu;
#[allow(dead_code)]
pub mod cpio;
pub mod crashreport;
pub mod credentials;
pub mod cursorsettings;
pub mod datausage;
pub mod dedup;
pub mod defaultapps;
pub mod deskicons;
pub mod detailcols;
pub mod devicemgr;
pub mod devfs;
pub mod devpair;
pub mod dictation;
pub mod directio;
pub mod dmastat;
pub mod dmevent;
pub mod diskencrypt;
pub mod diskclean;
pub mod diskhealth;
pub mod diskio;
pub mod diskquota;
pub mod disksmart;
pub mod display;
pub mod displayarrange;
pub mod displaycolor;
pub mod displaycal;
pub mod dirsync;
pub mod dnssettings;
pub mod dpiscaling;
pub mod dragdrop;
pub mod driverupdate;
pub mod dumpanalyzer;
pub mod dyndns;
pub mod dynlock;
pub mod encrypt;
pub mod entropy;
pub mod envvars;
pub mod epollstat;
pub mod energysaver;
pub mod eventlog;
pub mod eyeprotect;
pub mod ext4;
pub mod faceunlock;
pub mod fat;
pub mod fdtable;
pub mod focusassist;
pub mod focussession;
pub mod fcomment;
pub mod fcompress;
pub mod fontmgr;
pub mod fontpreview;
pub mod fileinfo;
pub mod fileops;
pub mod filepicker;
pub mod filerules;
pub mod fileselect;
pub mod filetransfer;
pub mod fileshare;
pub mod filetype;
pub mod filevault;
pub mod fontsettings;
pub mod fileversion;
pub mod findex;
pub mod freeze;
pub mod fscache;
pub mod fstrim;
pub mod fstune;
pub mod fwsettings;
pub mod futexstat;
pub mod fwupdate;
pub mod gamemode;
pub mod gestures;
pub mod groupmgr;
pub mod fswalk;
pub mod gamepadinput;
pub mod handle;
pub mod haptfeedback;
pub mod hdrdisplay;
pub mod health;
pub mod hwmonitor;
pub mod hotkeys;
pub mod hotcorners;
pub mod history;
pub mod ime;
pub mod immutable;
pub mod index;
pub mod inputa11y;
pub mod inputmethod;
pub mod installer;
pub mod intercept;
pub mod iosched;
pub mod ipclog;
pub mod iotdevice;
pub mod ioprio;
pub mod irqbalance;
pub mod irqstat;
pub mod integrity;
pub mod iso9660;
pub mod journal;
pub mod kmod;
pub mod kbmacro;
pub mod kbsettings;
pub mod kernelbuild;
pub mod kbshortcuts;
pub mod kconsole;
pub mod kernlog;
pub mod kernparam;
pub mod keylayout;
pub mod langpack;
pub mod linkcheck;
pub mod loadavg;
pub mod locale;
pub mod lockwallpaper;
pub mod logrotate;
pub mod location;
pub mod magnifier;
pub mod loginscreen;
#[allow(dead_code)]
pub mod lz4;
pub mod mediakeys;
pub mod memdiag;
pub mod memlayout;
pub mod memcg;
pub mod memfs;
pub mod mime;
pub mod mmtune;
pub mod mobilelink;
pub mod monitors;
pub mod mount_ns;
pub mod multiclip;
pub mod mousegestures;
pub mod mousesettings;
pub mod netdiag;
pub mod netfilter;
pub mod nameservice;
pub mod netmon;
pub mod netindicator;
pub mod netshare;
pub mod netprofile;
pub mod netspeed;
pub mod netproxy;
pub mod netthrottle;
pub mod netusage;
pub mod networkbridge;
pub mod notifbadge;
pub mod notiffilter;
pub mod notifgroup;
pub mod numastat;
pub mod netsettings;
pub mod nightlight;
pub mod notifcenter;
pub mod notifprefs;
pub mod notify;
pub mod oobe;
pub mod oomkiller;
pub mod openwith;
pub mod osreset;
pub mod overlay;
pub mod parental;
pub mod parentaltime;
pub mod partmgr;
pub mod pagestat;
pub mod pathbar;
pub mod peninput;
pub mod perfmon;
pub mod pftrack;
pub mod pinnedapps;
pub mod pipe;
pub mod playmedia;
pub mod pkgmgr;
pub mod prochistory;
pub mod procfs;
pub mod procstat;
pub mod prociso;
pub mod policy;
pub mod policyengine;
pub mod power;
pub mod powerprofile;
pub mod powerwake;
pub mod prefetch;
pub mod preview;
pub mod printmgr;
pub mod printqueue;
pub mod profile;
pub mod progmgr;
pub mod properties;
pub mod queryable;
pub mod quicknote;
pub mod quicksettings;
pub mod quota;
pub mod raidmgr;
pub mod rcustat;
pub mod readdir_plus;
pub mod recent;
pub mod recentsearch;
pub mod recoverypart;
pub mod remoteassist;
pub mod remotedesktop;
pub mod restorepoint;
pub mod reclaim;
pub mod rundialog;
pub mod schedclass;
pub mod schedtune;
pub mod screensaver;
pub mod screenlock;
pub mod screenreader;
pub mod screenshot;
pub mod screenrec;
pub mod screentime;
pub mod scriptlang;
pub mod search;
pub mod sealing;
pub mod secureboot;
pub mod secureerase;
pub mod secpolicy;
pub mod sharesheet;
pub mod shmem;
pub mod slabstat;
pub mod servicemgr;
pub mod sessionmgr;
pub mod sidebar;
pub mod signalq;
pub mod snapshot;
pub mod snaplayout;
pub mod softirq;
pub mod splitview;
pub mod soundevents;
pub mod soundmixer;
pub mod surroundsound;
pub mod spatialaudio;
pub mod sparse;
pub mod speechio;
pub mod spellcheck;
pub mod splice;
pub mod startmenu;
pub mod startupopt;
pub mod startuprepair;
pub mod statusbar;
pub mod storageclean;
pub mod storagesense;
pub mod swapcfg;
pub mod swapmon;
pub mod sysanimations;
pub mod systemsounds;
pub mod systemimage;
#[allow(dead_code)]
pub mod rar;
pub mod rlimit;
pub mod symlink_security;
pub mod sysdiag;
pub mod sysfs;
pub mod syslog;
pub mod sysrq;
pub mod sysctlfs;
pub mod sysprofiler;
pub mod sysresource;
pub mod sysmaint;
pub mod sysinfo;
pub mod sysuptime;
pub mod sysrestore;
pub mod systray;
pub mod tags;
pub mod tar;
pub mod taskbar;
pub mod tasksched;
pub mod taskmon;
pub mod telemetry;
pub mod templates;
pub mod theme;
pub mod thermal;
pub mod timesync;
pub mod timerq;
pub mod tracemon;
pub mod timezone;
pub mod tlbstat;
pub mod toolbar;
pub mod touchpad;
pub mod touchscreen;
pub mod thumbcache;
pub mod tmpwatch;
pub mod transaction;
pub mod trash;
pub mod undelete;
pub mod updatemgr;
pub mod usagetime;
pub mod usbmgr;
pub mod usbpolicy;
pub mod usage;
pub mod useracct;
pub mod userprofile;
pub mod vdesktop;
pub mod vfs;
pub mod viewstate;
pub mod voicecontrol;
pub mod vmmap;
pub mod volumeosd;
pub mod vpn;
pub mod vpnprofile;
pub mod wakesensor;
pub mod wallpaper;
pub mod webcam;
pub mod widgets;
pub mod wifiscan;
pub mod wqstat;
pub mod windowrules;
pub mod wintiling;
pub mod winsnap;
#[allow(dead_code)]
pub mod sevenz;
#[allow(dead_code)]
pub mod xz;
#[allow(dead_code)]
pub mod zip;
#[allow(dead_code)]
pub mod zstd;

pub use vfs::{
    DirEntry, EntryType, FileAttr, FileMeta, FileSystem, FsInfo, LockType, Timestamp, Vfs,
    validate_path,
};
