//! The POSIX `cksum` CRC: upstream's `src/cksum.c`.
//!
//! `cksum`'s default algorithm, and the one POSIX specifies: a CRC-32 over the
//! polynomial 0x04C11DB7 fed **most-significant bit first**, with the file's
//! length appended to the data — least-significant byte first, and only as
//! many bytes as the length needs — and the result complemented. It is not the
//! CRC-32 of gzip and ZIP (the workspace's `crc32` crate), which runs the same
//! polynomial bit-reversed, starts from all ones and appends no length; the
//! two share a polynomial and nothing else, so neither can compute the other.
//!
//! # What is ported
//!
//! * The table. Upstream ships `crctab.c`, generated by the `#ifdef CRCTAB`
//!   program at the top of `cksum.c`; [`CRCTAB`] is that program run at
//!   compile time — `fill_r`, `crc_remainder`, and the loop that derives the
//!   seven slice tables from the first — rather than a copy of its output, so
//!   the 2048 words cannot hold a typo.
//! * `cksum_slice8`'s loop: eight bytes at a time through eight tables, then
//!   the remainder a byte at a time. The grouping does not change the result
//!   — a CRC is a function of the byte sequence alone — so it is kept for speed
//!   and the unit tests check it against the byte-at-a-time form.
//! * `crc_sum_stream`'s finish and `output_crc`'s line, `%u %s` and the name.
//!
//! # What is not
//!
//! Upstream's x86 build can run the CRC with PCLMUL carry-less multiplication
//! (`cksum_pclmul.c`), and `--debug` then says `using pclmul hardware support`
//! or `pclmul support not detected`. The result is the same number. This port
//! has only the table path, so it behaves as upstream built without
//! `USE_PCLMUL_CRC32` does — on aarch64, say — where `--debug` prints nothing
//! for the CRC, since there is no choice to report.

/// `GEN`: the generating polynomial's terms below x^32 (x^26 ... x^0), the
/// `i`th bit set for each x^i. 0x04C11DB7.
const GEN: u32 = (1 << 26)
    | (1 << 23)
    | (1 << 22)
    | (1 << 16)
    | (1 << 12)
    | (1 << 11)
    | (1 << 10)
    | (1 << 8)
    | (1 << 7)
    | (1 << 5)
    | (1 << 4)
    | (1 << 2)
    | (1 << 1)
    | 1;

/// `crctab[8][256]`: `CRCTAB[0]` is the byte table, and `CRCTAB[k][i]` the
/// CRC of byte `i` followed by `k` zero bytes, which is what lets eight bytes
/// be folded in one step.
static CRCTAB: [[u32; 256]; 8] = crc_tables();

/// The `#ifdef CRCTAB` program's `main`, at compile time.
// Every index below is bounded by its loop's own condition (`k < 8`,
// `i < 256`, `bit < 8`), and every shift is of a `u32` by less than 32 with the
// high bits meant to fall off. `get` is not available in a `const fn` here, so
// the lints cannot be satisfied the way the rest of the file satisfies them.
#[allow(clippy::indexing_slicing, clippy::arithmetic_side_effects)]
const fn crc_tables() -> [[u32; 256]; 8] {
    // `fill_r`: r[k] is x^(32 + k) modulo the polynomial.
    let mut r = [0u32; 8];
    r[0] = GEN;
    let mut k = 1;
    while k < 8 {
        let prev = r[k - 1];
        r[k] = (prev << 1) ^ if prev & (1 << 31) != 0 { GEN } else { 0 };
        k += 1;
    }

    // `crc_remainder`: the byte table, from the eight single-bit remainders.
    let mut tab = [[0u32; 256]; 8];
    let mut i = 0;
    while i < 256 {
        let mut rem = 0u32;
        let mut bit = 0;
        while bit < 8 {
            if i & (1 << bit) != 0 {
                rem ^= r[bit];
            }
            bit += 1;
        }
        tab[0][i] = rem;
        i += 1;
    }

    // The seven slice tables: byte `i`, then `offset` zero bytes.
    let mut i = 0;
    while i < 256 {
        let mut crc = tab[0][i];
        let mut offset = 1;
        while offset < 8 {
            crc = (crc << 8) ^ tab[0][(crc >> 24) as usize];
            tab[offset][i] = crc;
            offset += 1;
        }
        i += 1;
    }
    tab
}

/// One table entry by byte. `usize::from(u8)` is below 256 by type, so the
/// `get` cannot miss and compiles to a plain load.
#[inline(always)]
fn t(table: usize, byte: u8) -> u32 {
    CRCTAB
        .get(table)
        .and_then(|row| row.get(usize::from(byte)))
        .copied()
        .unwrap_or(0)
}

/// One byte into the CRC: `crc = (crc << 8) ^ crctab[0][((crc >> 24) ^ b) & 0xFF]`.
#[inline(always)]
fn step(crc: u32, byte: u8) -> u32 {
    let [top, ..] = crc.to_be_bytes();
    (crc << 8) ^ t(0, top ^ byte)
}

/// A CRC in progress, with the byte count its finish needs.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Crc {
    crc: u32,
    length: u64,
}

impl Crc {
    /// Absorb the next bytes: `cksum_slice8`'s loop.
    pub fn update(&mut self, data: &[u8]) {
        // `length += bytes_read`, which upstream checks for `EOVERFLOW`. A
        // 64-bit count cannot overflow on any input that exists (16 EiB), so
        // the check is spent on nothing and the addition saturates instead.
        self.length = self
            .length
            .saturating_add(u64::try_from(data.len()).unwrap_or(u64::MAX));

        let (groups, tail) = data.as_chunks::<8>();
        let mut crc = self.crc;
        for group in groups {
            let [a0, a1, a2, a3, b0, b1, b2, b3] = *group;
            // `crc ^= SWAP (first)`: the first four bytes as a big-endian word.
            let [c0, c1, c2, c3] = (crc ^ u32::from_be_bytes([a0, a1, a2, a3])).to_be_bytes();
            crc = t(7, c0)
                ^ t(6, c1)
                ^ t(5, c2)
                ^ t(4, c3)
                ^ t(3, b0)
                ^ t(2, b1)
                ^ t(1, b2)
                ^ t(0, b3);
        }
        for &byte in tail {
            crc = step(crc, byte);
        }
        self.crc = crc;
    }

    /// Bytes absorbed: the size `output_crc` prints.
    #[must_use]
    pub const fn length(&self) -> u64 {
        self.length
    }

    /// `crc_sum_stream`'s finish: the length's bytes, low first, for as many
    /// bytes as it has, then the complement.
    #[must_use]
    pub fn finish(&self) -> u32 {
        let mut crc = self.crc;
        let mut rest = self.length;
        while rest != 0 {
            let [.., low] = rest.to_be_bytes();
            crc = step(crc, low);
            rest >>= 8;
        }
        !crc
    }
}

/// `output_crc`: `%u %s` — the CRC and the size in bytes — then the name if
/// one was named, then `delim`. The name is data and printed as its bytes.
///
/// `raw` is `cksum --raw`: the CRC alone, as four big-endian bytes, and
/// nothing else.
#[must_use]
pub fn output_crc(crc: u32, length: u64, name: Option<&[u8]>, raw: bool, delim: u8) -> Vec<u8> {
    if raw {
        return crc.to_be_bytes().to_vec();
    }
    let mut out = format!("{crc} {length}").into_bytes();
    if let Some(name) = name {
        out.push(b' ');
        out.extend_from_slice(name);
    }
    out.push(delim);
    out
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]
mod tests {
    use super::*;

    fn cksum(data: &[u8]) -> (u32, u64) {
        let mut c = Crc::default();
        c.update(data);
        (c.finish(), c.length())
    }

    /// The textbook MSB-first table entry, computed the slow way: the byte in
    /// the top eight bits, eight shift-and-reduce steps.
    fn slow_entry(i: u32) -> u32 {
        let mut crc = i << 24;
        for _ in 0..8 {
            crc = if crc & 0x8000_0000 != 0 {
                (crc << 1) ^ 0x04c1_1db7
            } else {
                crc << 1
            };
        }
        crc
    }

    #[test]
    fn the_generated_byte_table_is_the_msb_first_crc_table() {
        for i in 0..256u32 {
            assert_eq!(CRCTAB[0][i as usize], slow_entry(i), "entry {i}");
        }
        // Two spot checks against upstream's shipped `crctab.c`.
        assert_eq!(CRCTAB[0][1], 0x04c1_1db7);
        assert_eq!(CRCTAB[0][255], 0xb1f7_40b4);
    }

    /// Values measured from GNU 9.4's `cksum`.
    #[test]
    fn checksums_match_upstream() {
        assert_eq!(cksum(b""), (4_294_967_295, 0));
        assert_eq!(cksum(b"hello\n"), (3_015_617_425, 6));
        // POSIX's own example value for the nine digits.
        assert_eq!(cksum(b"123456789"), (930_766_865, 9));
    }

    /// Eight at a time is one at a time, at every split.
    #[test]
    fn slicing_by_eight_changes_nothing() {
        let data: Vec<u8> = (0..300u32).map(|i| (i * 7 % 256) as u8).collect();
        let mut bytewise = 0u32;
        for &b in &data {
            bytewise = step(bytewise, b);
        }
        let mut whole = Crc::default();
        whole.update(&data);
        assert_eq!(whole.crc, bytewise);
        for split in 0..=data.len() {
            let mut c = Crc::default();
            c.update(&data[..split]);
            c.update(&data[split..]);
            assert_eq!(c.finish(), whole.finish(), "split at {split}");
        }
    }

    /// The length goes in low byte first and only as far as it has bytes:
    /// 256 bytes append two, 255 append one.
    #[test]
    fn the_length_is_appended_as_its_own_bytes() {
        let a = cksum(&[0u8; 255]);
        let b = cksum(&[0u8; 256]);
        assert_eq!(a.1, 255);
        assert_eq!(b.1, 256);
        // Recompute by hand: zeros through the table, then the length bytes.
        let by_hand = |n: usize, length_bytes: &[u8]| {
            let mut crc = 0u32;
            for _ in 0..n {
                crc = step(crc, 0);
            }
            for &b in length_bytes {
                crc = step(crc, b);
            }
            !crc
        };
        assert_eq!(a.0, by_hand(255, &[0xff]));
        assert_eq!(b.0, by_hand(256, &[0x00, 0x01]));
    }

    #[test]
    fn the_line_is_upstreams() {
        assert_eq!(output_crc(1, 2, None, false, b'\n'), b"1 2\n");
        assert_eq!(output_crc(1, 2, Some(b"a b"), false, 0), b"1 2 a b\0");
        assert_eq!(
            output_crc(0x0102_0304, 9, Some(b"f"), true, b'\n'),
            [1, 2, 3, 4]
        );
    }
}
