"""Mutation test for connect4's suite.

Breaks one piece of production code at a time and checks that the test which
claims to cover it is the one that fails.  A test that passes against a broken
program is not testing the program.

Connect Four is the eighteenth application in this campaign and arrived in the
usual shape: `main` built a `Connect4App`, dropped it and exited, `render` was
never given the window it drew into, and there was no mouse code in the file at
all -- for a game whose entire interface is "put one in that column".

Usage:  python -u apps/connect4/mutate.py [substring ...]
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

from mutation_harness import sweep  # noqa: E402  (path set above)

SRC = Path(__file__).parent / "src" / "main.rs"

# (name, old, new, [tests that must fail])
MUTATIONS = [
    # ── Run geometry ──────────────────────────────────────────────────────
    (
        "a run may leave the right edge",
        "        if r >= ROWS || c >= COLS {",
        "        if r >= ROWS {",
        ["a_run_that_would_leave_the_right_edge_is_refused"],
    ),
    (
        "a run may leave the top",
        "        if r >= ROWS || c >= COLS {",
        "        if c >= COLS {",
        ["a_run_that_would_leave_the_top_is_refused"],
    ),
    (
        "a run may start left of the board and fold back onto it",
        "        let (r, c) = (usize::try_from(r).ok()?, usize::try_from(c).ok()?);",
        "        let (r, c) = (usize::try_from(r).ok()?, usize::try_from(c.abs()).ok()?);",
        ["a_run_that_would_leave_the_left_edge_is_refused"],
    ),
    (
        "the cells of a run do not step",
        "        let step = isize::try_from(i).ok()?;",
        "        let step = 1_isize;",
        ["a_run_that_fits_reports_the_four_cells_it_covers"],
    ),
    (
        "a run steps by rows only",
        "            .checked_add(dc.checked_mul(step)?)?;",
        "            .checked_add(dc)?;",
        ["a_run_that_fits_reports_the_four_cells_it_covers"],
    ),
    (
        "the run directions include a run walked backwards",
        "const DIRECTIONS: [(isize, isize); 4] = [(0, 1), (1, 0), (1, 1), (1, -1)];",
        "const DIRECTIONS: [(isize, isize); 4] = [(0, 1), (1, 0), (1, 1), (0, -1)];",
        ["a_run_and_the_same_run_walked_backwards_are_not_both_listed"],
    ),
    (
        "the diagonals are not scanned at all",
        "const DIRECTIONS: [(isize, isize); 4] = [(0, 1), (1, 0), (1, 1), (1, -1)];",
        "const DIRECTIONS: [(isize, isize); 4] = [(0, 1), (1, 0), (0, 1), (1, 0)];",
        ["no_run_is_yielded_twice"],
    ),
    (
        "the runs are listed for one row only",
        "    (0..ROWS).flat_map(|row| {",
        "    (0..1).flat_map(|row| {",
        ["the_board_holds_sixty_nine_runs_of_four"],
    ),
    # ── The board ─────────────────────────────────────────────────────────
    (
        "a column takes one more piece than it holds",
        "        self.height(col).is_some_and(|filled| filled < ROWS)",
        "        self.height(col).is_some_and(|filled| filled <= ROWS)",
        ["a_full_column_is_not_offered_as_a_move"],
    ),
    (
        "a column that is not on the board takes pieces",
        "        self.height(col).is_some_and(|filled| filled < ROWS)",
        "        self.height(col).is_none_or(|filled| filled < ROWS)",
        ["a_column_that_is_not_on_the_board_takes_nothing"],
    ),
    (
        "a cell off the board reads as a piece",
        "            .unwrap_or(Cell::Empty)",
        "            .unwrap_or(Cell::Red)",
        ["a_cell_off_the_board_reads_as_empty_rather_than_panicking"],
    ),
    (
        "a dropped piece does not raise the column it fell into",
        "        *self.heights.get_mut(col)? = row.saturating_add(1);",
        "        *self.heights.get_mut(col)? = row;",
        ["a_dropped_piece_lands_on_top_of_what_is_already_there"],
    ),
    (
        "a drop is not counted",
        "        self.piece_count = self.piece_count.saturating_add(1);",
        "        self.piece_count = self.piece_count;",
        ["a_board_is_full_only_when_every_cell_is"],
    ),
    (
        "a piece taken back comes off the cell above the one it was in",
        "        let row = self.height(col)?.checked_sub(1)?;",
        "        let row = self.height(col)?;",
        ["taking_a_piece_back_returns_the_piece_that_was_taken"],
    ),
    (
        "taking a piece back leaves the column as high as it was",
        "        *self.heights.get_mut(col)? = row;\n        self.piece_count = self.piece_count.saturating_sub(1);",
        "        self.piece_count = self.piece_count.saturating_sub(1);",
        ["a_drop_and_the_undo_of_it_leave_the_board_exactly_as_it_was"],
    ),
    (
        "taking a piece back does not uncount it",
        "        self.piece_count = self.piece_count.saturating_sub(1);",
        "        self.piece_count = self.piece_count.saturating_add(1);",
        ["a_drop_and_the_undo_of_it_leave_the_board_exactly_as_it_was"],
    ),
    (
        "a refused move is evaluated and taken back anyway",
        "        self.drop_piece(col, piece)?;\n        let out = f(self);",
        "        let _ = self.drop_piece(col, piece);\n        let out = f(self);",
        ["with_move_on_a_full_column_runs_nothing_and_undoes_nothing"],
    ),
    (
        "a move looked at is left on the board",
        "        let undone = self.undo_drop(col);",
        "        let undone = Some(Cell::Empty);",
        ["with_move_leaves_the_board_exactly_as_it_found_it"],
    ),
    (
        "the board is full one piece before it is",
        "        self.piece_count >= CELL_COUNT",
        "        self.piece_count >= CELL_COUNT.saturating_sub(1)",
        ["a_board_is_full_only_when_every_cell_is"],
    ),
    (
        "four empty cells belong to whoever asks",
        "        if first == Cell::Empty {\n            return None;\n        }",
        "",
        ["a_run_of_four_empty_cells_is_not_a_win_for_nobody"],
    ),
    (
        "a run belongs to a player one of whose pieces is in it",
        "        occupants.all(|cell| cell == first).then_some(first)",
        "        occupants.any(|cell| cell == first).then_some(first)",
        ["a_line_broken_by_the_other_colour_is_not_a_win"],
    ),
    (
        "a full board is still being played",
        "            return (GameStatus::Draw, None);",
        "            return (GameStatus::Playing, None);",
        ["a_full_board_with_no_line_on_it_is_a_draw"],
    ),
    (
        "a full board is a draw even with four in a row on it",
        "        if let Some((winner, cells)) =\n            all_lines().find_map(|cells| Some((self.line_owner(cells)?, cells)))\n        {\n            return (GameStatus::Won(winner), Some(WinLine { cells }));\n        }\n        if self.is_full() {",
        "        if self.is_full() {\n            return (GameStatus::Draw, None);\n        }\n        if let Some((winner, cells)) =\n            all_lines().find_map(|cells| Some((self.line_owner(cells)?, cells)))\n        {\n            return (GameStatus::Won(winner), Some(WinLine { cells }));\n        }\n        if self.is_full() {",
        ["a_full_board_with_a_line_on_it_is_a_win_and_not_a_draw"],
    ),
    (
        "nobody wins an empty board",
        "        if player == Cell::Empty {\n            return false;\n        }\n",
        "",
        ["nobody_has_won_an_empty_board_including_nobody"],
    ),
    (
        "one cell of a colour is four in a row",
        "                .all(|(row, col)| self.get(row, col) == player)",
        "                .any(|(row, col)| self.get(row, col) == player)",
        ["the_win_scan_and_the_ai_s_form_of_it_agree"],
    ),
    (
        "the moves are searched from the left edge rather than the centre",
        "        const ORDER: [usize; COLS] = [3, 2, 4, 1, 5, 0, 6];",
        "        const ORDER: [usize; COLS] = [0, 1, 2, 3, 4, 5, 6];",
        ["the_playable_columns_are_ordered_from_the_centre_outwards"],
    ),
    (
        "a full column is offered as a move",
        "            .filter(|&c| self.can_drop(c))\n            .collect()",
        "            .collect()",
        ["a_full_column_is_not_offered_as_a_move"],
    ),
    # ── The search ────────────────────────────────────────────────────────
    (
        "three in a row is scored as a win",
        "    if player_count == 4 {",
        "    if player_count >= 3 {",
        ["three_with_a_gap_is_worth_more_than_two_with_two"],
    ),
    (
        "three with nowhere to finish is scored as a threat",
        "    } else if player_count == 3 && empty_count == 1 {",
        "    } else if player_count == 3 {",
        ["three_with_no_gap_to_complete_them_is_worth_nothing"],
    ),
    (
        "two with the other colour beside them is scored as a chance",
        "    } else if player_count == 2 && empty_count == 2 {",
        "    } else if player_count == 2 {",
        ["a_window_both_colours_are_in_is_worth_nothing_to_either"],
    ),
    (
        "the opponent's threat is scored as your own",
        "    } else if opp_count == 3 && empty_count == 1 {\n        SCORE_OPP_THREE",
        "    } else if opp_count == 3 && empty_count == 1 {\n        SCORE_THREE",
        ["the_opponents_three_with_a_gap_scores_against_you"],
    ),
    (
        "the opponent is the player themselves",
        "    let opp = player.opponent();",
        "    let opp = player;",
        ["the_opponents_three_with_a_gap_scores_against_you"],
    ),
    (
        "the holes in a window are counted as pieces",
        "    let empty_count = window.iter().filter(|&&c| c == Cell::Empty).count();",
        "    let empty_count = window.iter().filter(|&&c| c != Cell::Empty).count();",
        ["three_with_a_gap_is_worth_more_than_two_with_two"],
    ),
    (
        "the centre bonus is paid for the other player's pieces",
        "        .filter(|&row| board.get(row, CENTER_COL) == player)",
        "        .filter(|&row| board.get(row, CENTER_COL) == player.opponent())",
        ["the_centre_bonus_is_paid_to_the_player_it_is_evaluated_for"],
    ),
    (
        "the centre column is worth nothing",
        "        .saturating_mul(SCORE_CENTER);",
        "        .saturating_mul(0);",
        ["a_piece_in_the_centre_column_is_worth_more_than_one_at_the_edge"],
    ),
    (
        "a position is scored by its centre column alone",
        "        score = score.saturating_add(evaluate_window(&window, player));",
        "        score = score.saturating_add(0);",
        ["a_position_is_scored_by_the_runs_on_it_and_not_only_by_the_centre_column"],
    ),
    (
        "a full board is not over",
        "    board.has_won(Cell::Red) || board.has_won(Cell::Yellow) || board.is_full()",
        "    board.has_won(Cell::Red) || board.has_won(Cell::Yellow)",
        ["a_position_is_over_when_the_board_is_full"],
    ),
    (
        "only one colour's win ends the position",
        "    board.has_won(Cell::Red) || board.has_won(Cell::Yellow) || board.is_full()",
        "    board.has_won(Cell::Red) || board.is_full()",
        ["a_position_is_over_when_someone_has_won"],
    ),
    (
        "a won position is searched on past the win",
        "    if depth == 0 || is_terminal(board) {",
        "    if depth == 0 {",
        ["a_win_found_sooner_is_worth_more_than_the_same_win_found_later"],
    ),
    (
        "a win is worth the same however far off it is",
        "            return (SCORE_WIN.saturating_add(depth), None);",
        "            return (SCORE_WIN, None);",
        ["a_win_found_sooner_is_worth_more_than_the_same_win_found_later"],
    ),
    (
        "the opponent's win is scored as the searcher's own",
        "            return (SCORE_WIN.saturating_add(depth).saturating_neg(), None);",
        "            return (SCORE_WIN.saturating_add(depth), None);",
        ["a_position_the_opponent_has_already_won_scores_against_the_searcher"],
    ),
    (
        "a drawn position is scored as a win",
        "        if board.is_full() {\n            return (0, None);\n        }",
        "        if board.is_full() {\n            return (SCORE_WIN, None);\n        }",
        ["a_full_position_scores_level"],
    ),
    (
        "a leaf names a column nothing looked at",
        "        return (evaluate_board(board, ai_player), None);",
        "        return (evaluate_board(board, ai_player), Some(CENTER_COL));",
        ["a_search_that_reaches_its_depth_reports_a_score_and_no_column"],
    ),
    (
        "the search never gets any shallower",
        "    let deeper = depth.saturating_sub(1);",
        "    let deeper = depth;",
        ["a_search_that_can_see_the_win_scores_it_as_a_win"],
    ),
    (
        "both sides of the search play the AI's pieces",
        "    let mover = if maximizing {\n        ai_player\n    } else {\n        ai_player.opponent()\n    };",
        "    let mover = ai_player;",
        ["a_threat_the_search_cannot_block_is_scored_as_a_loss"],
    ),
    (
        "the opponent maximises too",
        "    let mut best_score = if maximizing { i32::MIN } else { i32::MAX };",
        "    let mut best_score = i32::MIN;",
        ["the_side_that_is_not_the_ai_picks_the_move_that_hurts_it_most"],
    ),
    (
        "the column the search reports is the first it tried",
        "    (best_score, best_col)",
        "    (best_score, moves.first().copied())",
        ["a_search_that_can_see_the_win_scores_it_as_a_win"],
    ),
    (
        "the search reports a column the other side chose",
        "            if score < best_score {\n                best_score = score;\n                best_col = Some(col);\n            }",
        "            if score < best_score {\n                best_score = score;\n            }\n            best_col = Some(col);",
        ["the_side_that_is_not_the_ai_picks_the_move_that_hurts_it_most"],
    ),
    (
        "the AI does not look for the move that wins now",
        "    for player in [ai_player, ai_player.opponent()] {",
        "    for player in [ai_player.opponent()] {",
        ["the_ai_plays_the_move_that_wins_now"],
    ),
    (
        "the AI does not look for the move that stops a loss",
        "    for player in [ai_player, ai_player.opponent()] {",
        "    for player in [ai_player] {",
        ["the_ai_blocks_the_move_that_would_lose_now"],
    ),
    (
        "the AI would rather block their win than take its own",
        "    for player in [ai_player, ai_player.opponent()] {",
        "    for player in [ai_player.opponent(), ai_player] {",
        ["the_ai_takes_its_own_win_rather_than_blocking_theirs"],
    ),
    (
        "the winning move is looked for with the wrong piece in hand",
        "            if board.with_move(col, player, |after| after.has_won(player)) == Some(true) {",
        "            if board.with_move(col, player, |after| after.has_won(player.opponent()))\n                == Some(true)\n            {",
        ["the_ai_plays_the_move_that_wins_now"],
    ),
    # ── The layout ────────────────────────────────────────────────────────
    (
        "a window of no size produces a layout of no size",
        "        let w = width.max(1.0);\n        let h = height.max(1.0);",
        "        let w = width;\n        let h = height;",
        ["a_window_of_no_size_still_produces_a_layout_of_some_size"],
    ),
    (
        "the type size has no floor",
        "        let font = (h / 40.0).clamp(8.0, 18.0);",
        "        let font = h / 40.0;",
        ["the_type_size_is_bounded_at_both_ends"],
    ),
    (
        "the small type has no floor",
        "        let small = (font - 3.0).max(7.0);",
        "        let small = font - 3.0;",
        ["the_type_size_is_bounded_at_both_ends"],
    ),
    (
        "the padding may eat the window it is padding",
        "        let pad = (w.min(h) * 0.02).clamp(2.0, 12.0).min(w.min(h) / 4.0);",
        "        let pad = (w.min(h) * 0.02).clamp(2.0, 12.0);",
        ["the_padding_never_eats_more_than_a_quarter_of_the_smaller_side"],
    ),
    (
        "the bands are dropped in the order they are drawn in",
        "const BAND_DROP_ORDER: [usize; 4] = [2, 1, 0, 3];",
        "const BAND_DROP_ORDER: [usize; 4] = [0, 1, 2, 3];",
        ["a_window_too_short_for_the_chrome_drops_the_chute_first_and_the_footer_last"],
    ),
    (
        "the footer is dropped before the header",
        "const BAND_DROP_ORDER: [usize; 4] = [2, 1, 0, 3];",
        "const BAND_DROP_ORDER: [usize; 4] = [2, 1, 3, 0];",
        ["a_window_too_short_for_the_chrome_drops_the_chute_first_and_the_footer_last"],
    ),
    (
        "the board is promised none of the window",
        "        let budget = (h - h * BOARD_SHARE - pad * 2.0).max(0.0);",
        "        let budget = h;",
        ["the_board_keeps_nearly_half_the_window_when_everything_fits"],
    ),
    (
        "a band that did not fit is a flat strip rather than nothing",
        "        let header = if hdr_h > 0.0 {\n            Rect::new(0.0, 0.0, w, hdr_h)\n        } else {\n            Rect::EMPTY\n        };",
        "        let header = Rect::new(0.0, 0.0, w, hdr_h);",
        ["a_band_that_did_not_fit_is_nothing_rather_than_a_flat_strip"],
    ),
    (
        "the status line is drawn over the header",
        "        let info = if inf_h > 0.0 {\n            Rect::new(0.0, hdr_h, w, inf_h)",
        "        let info = if inf_h > 0.0 {\n            Rect::new(0.0, 0.0, w, inf_h)",
        ["the_bands_are_stacked_in_the_order_they_are_read_in"],
    ),
    (
        "the footer is measured down from the top of the window",
        "            Rect::new(0.0, h - foot_h, w, foot_h)",
        "            Rect::new(0.0, foot_h, w, foot_h)",
        ["the_bands_are_stacked_in_the_order_they_are_read_in"],
    ),
    (
        "the board may run under the footer",
        "        let bottom = h - foot_h;",
        "        let bottom = h;",
        ["the_board_never_runs_into_the_footer_or_the_bands_above_it"],
    ),
    (
        "the board may run up into the bands above it",
        "        let top = hdr_h + inf_h + chute_h;",
        "        let top = 0.0;",
        ["the_board_never_runs_into_the_footer_or_the_bands_above_it"],
    ),
    (
        "the cells are as wide as the window allows and as tall as it does",
        "        let step = (avail_w / COLS as f32).min(avail_h / ROWS as f32).max(0.0);",
        "        let step = (avail_w / COLS as f32).max(0.0);",
        ["the_board_never_runs_into_the_footer_or_the_bands_above_it"],
    ),
    (
        "the board is pinned to the left edge",
        "        let board = Rect::new((w - bw) / 2.0, top + pad + (avail_h - bh) / 2.0, bw, bh);",
        "        let board = Rect::new(0.0, top + pad + (avail_h - bh) / 2.0, bw, bh);",
        ["the_board_is_centred_across_the_window"],
    ),
    (
        "the chute sits where its band was reserved rather than on the board",
        "            Rect::new(board.x, (board.y - chute_h).max(0.0), bw, chute_h)",
        "            Rect::new(board.x, hdr_h + inf_h, bw, chute_h)",
        ["the_chute_sits_directly_on_top_of_the_board_and_over_the_same_columns"],
    ),
    (
        "the chute is as wide as the window rather than as the board",
        "            Rect::new(board.x, (board.y - chute_h).max(0.0), bw, chute_h)",
        "            Rect::new(board.x, (board.y - chute_h).max(0.0), w, chute_h)",
        ["the_chute_sits_directly_on_top_of_the_board_and_over_the_same_columns"],
    ),
    (
        "a band with no width still counts as showing",
        "        band.w > 0.0 && band.h > 0.0",
        "        band.h > 0.0",
        ["shows_answers_no_for_a_band_with_no_area"],
    ),
    (
        "there is a fourth button in a row of three",
        "        if index >= count {\n            return Rect::EMPTY;\n        }",
        "        if index >= count.saturating_add(1) {\n            return Rect::EMPTY;\n        }",
        ["there_is_no_fourth_footer_button"],
    ),
    (
        "every footer button is drawn in the first button's place",
        "            row.x + gap + index as f32 * (bw + gap),",
        "            row.x + gap,",
        ["the_three_footer_buttons_are_side_by_side_inside_the_footer"],
    ),
    (
        "the footer buttons are as tall as the footer and start above it",
        "            row.y + (row.h - bh) / 2.0,",
        "            row.y - bh,",
        ["the_three_footer_buttons_are_side_by_side_inside_the_footer"],
    ),
    (
        "the footer buttons are wider than the footer",
        "        let bw = ((row.w - gap * (n + 1.0)) / n).max(0.0);",
        "        let bw = row.w;",
        ["the_three_footer_buttons_are_side_by_side_inside_the_footer"],
    ),
    (
        "the header's readouts survive a header that did not fit",
        "        if !self.shows(self.header) || index >= 3 {",
        "        if index >= 3 {",
        ["a_header_that_did_not_fit_has_no_readouts"],
    ),
    (
        "there is a fourth readout",
        "        if !self.shows(self.header) || index >= 3 {",
        "        if !self.shows(self.header) {",
        ["there_is_no_fourth_readout"],
    ),
    (
        "the readouts are laid out from the left edge outwards",
        "        let x = right - (bw + gap) * (index as f32 + 1.0) + gap;",
        "        let x = self.header.x + (bw + gap) * index as f32;",
        ["the_score_readouts_are_laid_out_from_the_right_edge_inwards"],
    ),
    (
        "a readout that runs off the left edge is drawn there anyway",
        "        if x < self.header.x {\n            return Rect::EMPTY;\n        }",
        "",
        ["a_readout_that_would_run_off_the_left_edge_is_dropped"],
    ),
    (
        "a readout is taller than the header it sits in",
        "        Rect::new(x, self.header.y + (self.header.h - bh) / 2.0, bw, bh)",
        "        Rect::new(x, self.header.y, bw, self.header.h * 1.5)",
        ["the_score_readouts_sit_inside_the_header"],
    ),
    (
        "a column that is not on the board has a strip anyway",
        "        if col >= COLS || self.board.is_empty() {",
        "        if self.board.is_empty() {",
        ["a_column_that_is_not_on_the_board_has_no_strip"],
    ),
    (
        "every column strip is the first column's",
        "            self.board.x + col as f32 * self.step,",
        "            self.board.x,",
        ["the_column_strips_tile_the_board_without_overlapping"],
    ),
    (
        "the column strips stop at the top of the board",
        "        let top = if self.shows(self.chute) {\n            self.chute.y\n        } else {\n            self.board.y\n        };",
        "        let top = self.board.y;",
        ["a_column_strip_covers_the_column_it_names_and_the_chute_above_it"],
    ),
    (
        "the column strips stop short of the bottom of the board",
        "            (self.board.bottom() - top).max(0.0),",
        "            (self.board.bottom() - top).max(0.0) / 2.0,",
        ["a_column_strip_covers_the_column_it_names_and_the_chute_above_it"],
    ),
    (
        "there are chute slots when there is no chute",
        "        if col >= COLS || !self.shows(self.chute) {",
        "        if col >= COLS {",
        ["there_are_no_chute_slots_when_the_chute_did_not_fit"],
    ),
    (
        "every chute slot is the first column's",
        "            self.chute.x + col as f32 * self.step,",
        "            self.chute.x,",
        ["a_chute_slot_sits_over_the_column_it_names"],
    ),
    (
        "a chute slot for a column that is not there is the last one's",
        "        if col >= COLS || !self.shows(self.chute) {",
        "        if !self.shows(self.chute) {",
        ["a_chute_slot_for_a_column_that_is_not_there_is_nothing"],
    ),
    (
        "row zero is drawn at the top of the board",
        "        let visual_row = ROWS.saturating_sub(1).saturating_sub(row);",
        "        let visual_row = row;",
        ["row_zero_is_drawn_at_the_bottom_of_the_board"],
    ),
    (
        "the gap between holes is added to the step rather than taken out",
        "            (self.step - gap).max(0.0),\n            (self.step - gap).max(0.0),",
        "            self.step,\n            self.step,",
        ["the_gap_between_holes_comes_out_of_them_and_not_off_the_boards_edge"],
    ),
    (
        "the holes are as wide as the step and as tall as what is left",
        "            (self.step - gap).max(0.0),\n            (self.step - gap).max(0.0),",
        "            self.step,\n            (self.step - gap).max(0.0),",
        ["the_holes_are_round_because_they_are_square"],
    ),
    (
        "the holes are laid out with no offset for the gap",
        "            self.board.x + col as f32 * self.step + gap / 2.0,\n            self.board.y + visual_row as f32 * self.step + gap / 2.0,",
        "            self.board.x + col as f32 * self.step,\n            self.board.y + visual_row as f32 * self.step,",
        ["the_gap_between_holes_comes_out_of_them_and_not_off_the_boards_edge"],
    ),
    (
        "a cell off the board still has a box",
        "        if self.board.is_empty() || row >= ROWS || col >= COLS {",
        "        if self.board.is_empty() {",
        ["a_cell_that_is_not_on_the_board_has_no_box"],
    ),
    (
        "the help sheet is pinned to the top left corner",
        "        let help = Rect::new((w - help_w) / 2.0, (h - help_h) / 2.0, help_w, help_h);",
        "        let help = Rect::new(0.0, 0.0, help_w, help_h);",
        ["the_help_sheet_is_centred_in_the_window"],
    ),
    (
        "the help sheet is wider than the window",
        "        let help_w = (w * 0.92).min(440.0);",
        "        let help_w = w * 1.2;",
        ["every_band_stays_inside_the_window"],
    ),
    # ── The game ──────────────────────────────────────────────────────────
    (
        "the game opens with the cursor against the left wall",
        "            cursor_col: CENTER_COL,\n            current_player: Cell::Red,\n            status: GameStatus::Playing,\n            win_line: None,\n            human_player: Cell::Red,",
        "            cursor_col: 0,\n            current_player: Cell::Red,\n            status: GameStatus::Playing,\n            win_line: None,\n            human_player: Cell::Red,",
        ["a_new_game_starts_empty_with_the_player_to_move_and_the_cursor_in_the_middle"],
    ),
    (
        "the search moves first",
        "            current_player: Cell::Red,\n            status: GameStatus::Playing,\n            win_line: None,",
        "            current_player: Cell::Yellow,\n            status: GameStatus::Playing,\n            win_line: None,",
        ["a_new_game_starts_empty_with_the_player_to_move_and_the_cursor_in_the_middle"],
    ),
    (
        "a new game leaves the cursor where the last one ended",
        "        self.board = Board::new();\n        self.cursor_col = CENTER_COL;",
        "        self.board = Board::new();",
        ["a_new_game_puts_the_cursor_back_in_the_middle"],
    ),
    (
        "a new game keeps the board it was asked to clear",
        "        self.board = Board::new();\n        self.cursor_col = CENTER_COL;",
        "        self.cursor_col = CENTER_COL;",
        ["a_new_game_clears_the_board_and_keeps_the_tally"],
    ),
    (
        "a new game keeps the last game's result",
        "        self.status = GameStatus::Playing;\n        self.win_line = None;\n        self.move_history.clear();",
        "        self.move_history.clear();",
        ["a_new_game_clears_a_finished_games_result"],
    ),
    (
        "a new game leaves the moves of the old one on the list",
        "        self.move_history.clear();\n        self.history.clear();",
        "        self.history.clear();",
        ["a_new_game_clears_the_board_and_keeps_the_tally"],
    ),
    (
        "a new game throws the tally away with the board",
        "        self.move_history.clear();\n        self.history.clear();",
        "        self.move_history.clear();\n        self.history.clear();\n        self.human_wins = 0;\n        self.ai_wins = 0;\n        self.draws = 0;",
        ["a_new_game_clears_the_board_and_keeps_the_tally"],
    ),
    (
        "the search owes a move on a game that is over",
        "        self.status == GameStatus::Playing && self.current_player == self.ai_player",
        "        self.current_player == self.ai_player",
        ["the_search_owes_a_move_only_when_it_is_its_turn_on_a_live_game"],
    ),
    (
        "the search owes a move on the player's turn",
        "        self.status == GameStatus::Playing && self.current_player == self.ai_player",
        "        self.status == GameStatus::Playing",
        ["the_search_owes_a_move_only_when_it_is_its_turn_on_a_live_game"],
    ),
    (
        "a drop on a finished game is played anyway",
        "        if self.status != GameStatus::Playing {\n            return false;\n        }",
        "",
        ["a_drop_on_a_finished_game_is_refused"],
    ),
    (
        "a refused drop still leaves something to take back",
        "        if self.board.drop_piece(col, player).is_none() {\n            return false;\n        }\n        self.history.push(before);",
        "        let played = self.board.drop_piece(col, player).is_some();\n        self.history.push(before);\n        if !played {\n            return false;\n        }",
        ["a_refused_drop_leaves_nothing_to_take_back"],
    ),
    (
        "a drop is not remembered as a move",
        "        self.move_history.push((col, player));",
        "        self.move_history.push((col, player.opponent()));",
        ["a_drop_puts_the_moving_players_piece_on_the_board"],
    ),
    (
        "the turn does not change hands",
        "            GameStatus::Playing => self.current_player = player.opponent(),",
        "            GameStatus::Playing => self.current_player = player,",
        ["a_drop_hands_the_turn_to_the_other_player"],
    ),
    (
        "the result of the drop is not read back off the board",
        "        let (status, line) = self.board.outcome();\n        self.status = status;\n        self.win_line = line;",
        "        let (status, line) = (GameStatus::Playing, None);\n        self.status = status;\n        self.win_line = line;",
        ["a_drop_that_wins_ends_the_game_and_leaves_the_winner_to_move"],
    ),
    (
        "a win does not say which four cells made it",
        "        self.win_line = line;",
        "        self.win_line = None;",
        ["a_drop_that_wins_shows_which_four_cells_did_it"],
    ),
    (
        "a draw is not counted",
        "            GameStatus::Draw => self.draws = self.draws.saturating_add(1),",
        "            GameStatus::Draw => {}",
        ["a_drop_that_fills_the_last_hole_without_a_line_is_a_draw"],
    ),
    (
        "the search plays out of turn",
        "        if !self.ai_to_play() {\n            return None;\n        }",
        "",
        ["the_search_declines_a_turn_that_is_not_its_own"],
    ),
    (
        "the search plays a column of its own choosing",
        "        let col = ai_best_move(&mut self.board, self.ai_player, self.ai_depth)?;\n        if !self.drop_at(col) {",
        "        let col = ai_best_move(&mut self.board, self.ai_player, self.ai_depth)?;\n        let col = col.saturating_add(1) % COLS;\n        if !self.drop_at(col) {",
        ["the_search_plays_the_move_it_owes_and_nothing_else"],
    ),
    (
        "there is something to take back before the first move",
        "        if self.history.is_empty() {\n            return false;\n        }",
        "",
        ["there_is_nothing_to_take_back_before_the_first_move"],
    ),
    (
        "taking back stops after one drop rather than at the player's turn",
        "        while let Some(s) = self.history.pop() {\n            self.restore(s);\n            if self.status == GameStatus::Playing && self.current_player == self.human_player {\n                break;\n            }\n        }",
        "        if let Some(s) = self.history.pop() {\n            self.restore(s);\n        }",
        ["taking_back_takes_the_whole_round_and_not_half_of_it"],
    ),
    (
        "taking back unwinds the whole game",
        "            if self.status == GameStatus::Playing && self.current_player == self.human_player {\n                break;\n            }",
        "",
        ["taking_back_stops_at_the_players_turn_rather_than_unwinding_the_game"],
    ),
    (
        "taking back the winning move leaves the game won",
        "        self.current_player = s.current_player;\n        self.status = GameStatus::Playing;\n        self.win_line = None;",
        "        self.current_player = s.current_player;\n        self.win_line = None;",
        ["taking_back_the_winning_move_puts_the_game_back_in_play"],
    ),
    (
        "taking back the winning move leaves the winning four ringed",
        "        self.current_player = s.current_player;\n        self.status = GameStatus::Playing;\n        self.win_line = None;",
        "        self.current_player = s.current_player;\n        self.status = GameStatus::Playing;",
        ["taking_back_the_winning_move_puts_the_game_back_in_play"],
    ),
    (
        "taking back the winning move keeps the point it scored",
        "        self.human_wins = s.human_wins;\n        self.ai_wins = s.ai_wins;\n        self.draws = s.draws;",
        "",
        ["taking_back_the_winning_move_takes_back_the_point_it_scored"],
    ),
    (
        "the move list is not trimmed to the move it was taken back to",
        "        self.move_history.truncate(s.moves);",
        "",
        ["the_history_is_trimmed_to_the_move_it_is_taken_back_to"],
    ),
    (
        "taking back does not put the position back",
        "        self.board = s.board;\n        self.current_player = s.current_player;",
        "        self.current_player = s.current_player;",
        ["taking_back_restores_the_position_exactly"],
    ),
    (
        "the player may move on the search's turn",
        "        if self.current_player != self.human_player {\n            return EventResult::Ignored;\n        }",
        "",
        ["a_click_by_the_player_out_of_turn_is_ignored"],
    ),
    (
        "the cursor does not follow the column that was played",
        "                if col < COLS {\n                    self.cursor_col = col;\n                }",
        "",
        ["dropping_into_a_named_column_moves_the_cursor_there"],
    ),
    (
        "a drop into a column that is not there moves the cursor off the board",
        "                if col < COLS {\n                    self.cursor_col = col;\n                }",
        "                self.cursor_col = col;",
        ["a_drop_into_a_column_that_is_not_on_the_board_leaves_the_cursor_alone"],
    ),
    (
        "dropping at the cursor drops in the middle instead",
        "            Intent::DropAtCursor => self.drop_for_human(self.cursor_col),",
        "            Intent::DropAtCursor => self.drop_for_human(CENTER_COL),",
        ["dropping_at_the_cursor_drops_where_the_cursor_is"],
    ),
    (
        "left and right are the same way",
        "            Intent::CursorLeft => self.move_cursor(-1),",
        "            Intent::CursorLeft => self.move_cursor(1),",
        ["the_cursor_moves_one_column_at_a_time"],
    ),
    (
        "an undo that took nothing back reports that something happened",
        "            Intent::Undo => {\n                if self.undo() {\n                    EventResult::Consumed\n                } else {\n                    EventResult::Ignored\n                }\n            }",
        "            Intent::Undo => {\n                self.undo();\n                EventResult::Consumed\n            }",
        ["an_undo_with_nothing_to_take_back_reports_that_nothing_happened"],
    ),
    (
        "the cursor runs off the right wall",
        "            .filter(|&c| c < COLS)",
        "            .filter(|&c| c < COLS.saturating_add(1))",
        ["the_cursor_stops_at_the_right_wall_and_says_nothing_happened"],
    ),
    (
        "a cursor against the wall reports that it moved",
        "        else {\n            return EventResult::Ignored;\n        };\n        self.cursor_col = next;",
        "        else {\n            return EventResult::Consumed;\n        };\n        self.cursor_col = next;",
        ["the_cursor_stops_at_the_left_wall_and_says_nothing_happened"],
    ),
    (
        "the sheet is not modal and the game is played behind it",
        "        if self.show_help {\n            self.show_help = false;\n            return EventResult::Consumed;\n        }",
        "",
        ["an_open_sheet_swallows_the_move_a_key_would_have_made"],
    ),
    (
        "an open sheet is left open by whatever was pressed over it",
        "        if self.show_help {\n            self.show_help = false;\n            return EventResult::Consumed;\n        }",
        "        if self.show_help {\n            return EventResult::Consumed;\n        }",
        ["the_two_help_controls_close_a_sheet_they_opened"],
    ),
    (
        "the help key hides the sheet it is supposed to show",
        "            Intent::ToggleHelp => {\n                self.show_help = true;",
        "            Intent::ToggleHelp => {\n                self.show_help = false;",
        ["help_opens_and_shuts_on_the_same_intent"],
    ),
    (
        "a key the sheet swallowed is passed on as well",
        "            self.show_help = false;\n            return EventResult::Consumed;",
        "            self.show_help = false;",
        ["an_open_sheet_swallows_the_move_a_key_would_have_made"],
    ),
    (
        "closing a sheet that is already shut reports that something happened",
        "            Intent::CloseHelp => EventResult::Ignored,",
        "            Intent::CloseHelp => EventResult::Consumed,",
        ["closing_a_sheet_that_is_already_shut_does_nothing"],
    ),
    # ── Keys, clicks and events ───────────────────────────────────────────
    (
        "ctrl+z is not an undo",
        "    if ev.key == Key::Z && ev.modifiers.ctrl {\n        return Some(Intent::Undo);\n    }",
        "",
        ["ctrl_z_takes_a_move_back"],
    ),
    (
        "a bare Z is an undo too",
        "    if ev.key == Key::Z && ev.modifiers.ctrl {",
        "    if ev.key == Key::Z {",
        ["a_bare_z_asks_for_nothing"],
    ),
    (
        "ctrl and alt chords are read as bare keys",
        "    if ev.modifiers.ctrl || ev.modifiers.alt {\n        return None;\n    }",
        "",
        ["ctrl_and_alt_chords_belong_to_the_window_and_not_to_the_board"],
    ),
    (
        "shift stops a key meaning what it means",
        "    if ev.modifiers.ctrl || ev.modifiers.alt {",
        "    if ev.modifiers.ctrl || ev.modifiers.alt || ev.modifiers.shift {",
        ["shift_does_not_stop_a_key_meaning_what_it_means"],
    ),
    (
        "the arrow keys both go the same way",
        "        Key::Left | Key::A => Some(Intent::CursorLeft),",
        "        Key::Left | Key::A => Some(Intent::CursorRight),",
        ["the_arrow_keys_move_the_cursor"],
    ),
    (
        "A and D do not move the cursor",
        "        Key::Left | Key::A => Some(Intent::CursorLeft),\n        Key::Right | Key::D => Some(Intent::CursorRight),",
        "        Key::Left => Some(Intent::CursorLeft),\n        Key::Right => Some(Intent::CursorRight),",
        ["a_and_d_move_the_cursor_the_same_way_the_arrows_do"],
    ),
    (
        "space does not drop a piece",
        "        Key::Enter | Key::Space => Some(Intent::DropAtCursor),",
        "        Key::Enter => Some(Intent::DropAtCursor),",
        ["enter_and_space_both_drop_at_the_cursor"],
    ),
    (
        "the digit keys are off by one",
        "        Key::Num1 => Some(Intent::Drop(0)),",
        "        Key::Num1 => Some(Intent::Drop(1)),",
        ["each_digit_key_names_its_own_column_counting_from_one"],
    ),
    (
        "the last digit key names no column of its own",
        "        Key::Num7 => Some(Intent::Drop(6)),",
        "        Key::Num7 => Some(Intent::Drop(5)),",
        ["each_digit_key_names_its_own_column_counting_from_one"],
    ),
    (
        "N and U are swapped",
        "        Key::N => Some(Intent::NewGame),\n        Key::U => Some(Intent::Undo),",
        "        Key::N => Some(Intent::Undo),\n        Key::U => Some(Intent::NewGame),",
        ["n_starts_a_new_game_and_u_takes_a_move_back_and_h_shows_the_sheet"],
    ),
    (
        "H does not show the sheet",
        "        Key::H => Some(Intent::ToggleHelp),",
        "        Key::H => None,",
        ["n_starts_a_new_game_and_u_takes_a_move_back_and_h_shows_the_sheet"],
    ),
    (
        "escape does not shut the sheet",
        "        Key::Escape => Some(Intent::CloseHelp),",
        "        Key::Escape => None,",
        ["escape_shuts_the_help_sheet"],
    ),
    (
        "a key the window has no use for asks for a move",
        "        _ => None,\n    }\n}\n\n/// What clicking a control asks for.",
        "        _ => Some(Intent::DropAtCursor),\n    }\n}\n\n/// What clicking a control asks for.",
        ["a_key_this_window_has_no_use_for_is_left_for_something_else"],
    ),
    (
        "a column drops into its neighbour",
        "        Target::Column(col) => Intent::Drop(col),",
        "        Target::Column(col) => Intent::Drop(col.saturating_add(1)),",
        ["a_column_asks_for_a_drop_into_itself_and_not_into_its_neighbour"],
    ),
    (
        "the new game button takes a move back",
        "        Target::NewGame => Intent::NewGame,\n        Target::Undo => Intent::Undo,",
        "        Target::NewGame => Intent::Undo,\n        Target::Undo => Intent::NewGame,",
        ["every_control_asks_for_exactly_one_thing"],
    ),
    (
        "clicking the sheet opens it rather than shutting it",
        "        Target::HelpSheet => Intent::CloseHelp,",
        "        Target::HelpSheet => Intent::ToggleHelp,",
        ["every_control_asks_for_exactly_one_thing"],
    ),
    (
        "any mouse button plays a move",
        "        if !matches!(ev.kind, MouseEventKind::Press(MouseButton::Left)) {\n            return EventResult::Ignored;\n        }",
        "",
        ["only_the_left_button_plays_a_move"],
    ),
    (
        "a click that lands on nothing drops a piece anyway",
        "        match frame.hit_test(ev.x, ev.y) {\n            Some(target) => self.apply(target_intent(target)),\n            None => EventResult::Ignored,\n        }",
        "        match frame.hit_test(ev.x, ev.y) {\n            Some(target) => self.apply(target_intent(target)),\n            None => self.apply(Intent::DropAtCursor),\n        }",
        ["a_click_that_lands_on_nothing_does_nothing"],
    ),
    (
        "a click is read against a window of the size the program opened at",
        "        let frame = self.frame(self.width, self.height);",
        "        let frame = self.frame(WINDOW_WIDTH, WINDOW_HEIGHT);",
        ["a_click_is_read_against_the_window_the_last_frame_was_drawn_at"],
    ),
    (
        "a resize is not remembered",
        "        self.width = width;\n        self.height = height;",
        "",
        ["a_resize_is_taken_and_remembered"],
    ),
    (
        "a resize event is not passed on to the layout",
        "        Event::Resize { width, height } => {\n            app.resize(*width as f32, *height as f32);",
        "        Event::Resize { width, height } => {\n            let _ = (width, height);",
        ["a_resize_is_taken_and_remembered"],
    ),
    (
        "the tick does not play the move the search owes",
        "        Event::Tick { .. } => {\n            if app.ai_turn().is_some() {",
        "        Event::Tick { .. } => {\n            if false {",
        ["a_tick_plays_the_move_the_search_owes"],
    ),
    (
        "a tick that played nothing asks for a repaint",
        "            if app.ai_turn().is_some() {\n                EventResult::Consumed\n            } else {\n                EventResult::Ignored\n            }",
        "            app.ai_turn();\n            EventResult::Consumed",
        ["a_tick_on_the_players_turn_does_nothing"],
    ),
    (
        "the clock runs whether or not the search owes a move",
        "        self.ai_to_play().then_some(AI_TICK)",
        "        Some(AI_TICK)",
        ["the_clock_runs_only_while_the_search_owes_a_move"],
    ),
    (
        "the clock never runs",
        "        self.ai_to_play().then_some(AI_TICK)",
        "        None",
        ["the_clock_runs_only_while_the_search_owes_a_move"],
    ),
    (
        "a close request does not close the window",
        "        if matches!(event, Event::CloseRequested) {\n            return Response::Exit;\n        }",
        "",
        ["a_close_request_ends_the_program"],
    ),
    (
        "every event asks for a repaint",
        "        match handle_event(self, event) {\n            EventResult::Consumed => Response::Redraw,\n            EventResult::Ignored => Response::Idle,\n        }",
        "        handle_event(self, event);\n        Response::Redraw",
        ["an_event_that_changed_something_asks_for_a_repaint_and_one_that_did_not_does_not"],
    ),
    (
        "rendering does not remember the size it rendered at",
        "        self.resize(width, height);\n        self.frame(width, height).into_tree()",
        "        self.frame(width, height).into_tree()",
        ["rendering_remembers_the_size_it_rendered_at"],
    ),
    (
        "the window opens too small for the board",
        "        (WINDOW_WIDTH as u32, WINDOW_HEIGHT as u32)",
        "        (80, 60)",
        ["the_window_names_itself_and_opens_at_a_size_the_board_fits_in"],
    ),
    (
        "the window calls itself something else",
        '        "Connect Four".to_string()\n    }\n\n    fn app_id',
        '        "connect4".to_string()\n    }\n\n    fn app_id',
        ["the_window_names_itself_and_opens_at_a_size_the_board_fits_in"],
    ),
    # ── The drawing pass ──────────────────────────────────────────────────
    (
        "a box with no area is painted anyway",
        "fn fill(f: &mut Frame, r: Rect, color: Color, radius: f32) {\n    if r.is_empty() {\n        return;\n    }",
        "fn fill(f: &mut Frame, r: Rect, color: Color, radius: f32) {",
        ["a_box_with_no_area_is_not_painted"],
    ),
    (
        "an empty string is pushed as a line of text",
        "    if body.is_empty() || size < MIN_DRAWN_FONT || max_width.is_some_and(|w| w <= 0.0) {",
        "    if size < MIN_DRAWN_FONT || max_width.is_some_and(|w| w <= 0.0) {",
        ["an_empty_string_is_never_pushed_as_a_line_of_text"],
    ),
    (
        "a line is asked for at a size the renderer would round up",
        "    if body.is_empty() || size < MIN_DRAWN_FONT || max_width.is_some_and(|w| w <= 0.0) {",
        "    if body.is_empty() || max_width.is_some_and(|w| w <= 0.0) {",
        ["no_line_is_ever_asked_for_at_a_size_the_renderer_would_round_up"],
    ),
    (
        "a label with no width to fit in is drawn",
        "    if body.is_empty() || size < MIN_DRAWN_FONT || max_width.is_some_and(|w| w <= 0.0) {",
        "    if body.is_empty() || size < MIN_DRAWN_FONT {",
        ["a_label_with_no_width_to_fit_in_is_not_drawn"],
    ),
    (
        "a line too big for its box begins before it",
        "        r.x + (r.w - tw).max(0.0) / 2.0,\n        r.y + (r.h - th).max(0.0) / 2.0,",
        "        r.x + (r.w - tw) / 2.0,\n        r.y + (r.h - th) / 2.0,",
        ["a_line_too_big_for_its_box_starts_at_the_boxs_corner_rather_than_before_it"],
    ),
    (
        "a centred line is put at the corner of its box",
        "        r.x + (r.w - tw).max(0.0) / 2.0,\n        r.y + (r.h - th).max(0.0) / 2.0,",
        "        r.x,\n        r.y,",
        ["a_line_is_centred_in_its_box_both_ways"],
    ),
    (
        "a button's hit box is not the button",
        "    f.hit(target, r);\n    centred(f, r, body, size, ink, FontWeightHint::Bold);",
        "    f.hit(target, Rect::new(r.x, r.y, r.w * 2.0, r.h));\n    centred(f, r, body, size, ink, FontWeightHint::Bold);",
        ["the_three_footer_buttons_are_controls_and_are_labelled"],
    ),
    (
        "the readouts are drawn left to right and so read right to left",
        "            let r = l.score_box(boxes.len().saturating_sub(1).saturating_sub(i));",
        "            let r = l.score_box(i);",
        ["the_readouts_read_left_to_right_as_you_then_ai_then_draw"],
    ),
    (
        "a readout shows a neighbour's tally",
        '            ("You", self.human_wins, COL_RED),\n            ("AI", self.ai_wins, COL_YELLOW),\n            ("Draw", self.draws, COL_OVERLAY0),',
        '            ("You", self.ai_wins, COL_RED),\n            ("AI", self.draws, COL_YELLOW),\n            ("Draw", self.human_wins, COL_OVERLAY0),',
        ["a_readout_shows_the_tally_it_names_and_not_a_neighbours"],
    ),
    (
        "a readout is not labelled",
        "            centred(\n                f,\n                Rect::new(r.x, r.y, r.w, r.h * 0.5),\n                name,",
        '            centred(\n                f,\n                Rect::new(r.x, r.y, r.w, r.h * 0.5),\n                "",',
        ["the_three_readouts_are_labelled_and_show_their_counts"],
    ),
    (
        "a readout does not show its count",
        "                &count.to_string(),",
        '                "",',
        ["the_three_readouts_are_labelled_and_show_their_counts"],
    ),
    (
        "the title is drawn across the readouts",
        "        let title_w = leftmost - l.header.x - l.pad * 2.0;",
        "        let title_w = l.header.w;",
        ["the_title_is_never_drawn_over_the_readouts"],
    ),
    (
        "the window does not say what game it is",
        '            "Connect Four",\n            l.font,\n            COL_LAVENDER,',
        '            "",\n            l.font,\n            COL_LAVENDER,',
        ["the_window_says_what_game_it_is"],
    ),
    (
        "the status line is not drawn",
        "        centred(\n            f,\n            l.info,\n            &self.status_line(),",
        '        centred(\n            f,\n            l.info,\n            "",',
        ["the_status_line_says_it_is_your_turn_when_it_is"],
    ),
    (
        "the status line is always the same colour",
        "            self.status_colour(),",
        "            COL_BLUE,",
        ["the_status_line_reaches_the_frame_in_the_colour_it_chose"],
    ),
    (
        "a game being thought about looks like a game waiting on you",
        '                if self.ai_to_play() {\n                    "Yellow is thinking...".to_string()',
        '                if self.ai_to_play() {\n                    format!("Your turn ({})", self.human_player.name())',
        ["the_status_line_says_the_search_is_thinking_while_it_owes_a_move"],
    ),
    (
        "a loss is announced as a win",
        '            GameStatus::Won(winner) if winner == self.human_player => "You win!".to_string(),\n            GameStatus::Won(_) => "Yellow wins!".to_string(),',
        '            GameStatus::Won(_) => "You win!".to_string(),\n            GameStatus::Won(_) => "Yellow wins!".to_string(),',
        ["the_status_line_announces_a_win_a_loss_and_a_draw_differently"],
    ),
    (
        "a draw is coloured like a win",
        "            GameStatus::Draw => COL_PEACH,",
        "            GameStatus::Draw => COL_GREEN,",
        ["the_status_line_is_coloured_by_what_it_says"],
    ),
    (
        "a loss is coloured like a win",
        "            GameStatus::Won(winner) if winner == self.human_player => COL_GREEN,\n            GameStatus::Won(_) => COL_RED,",
        "            GameStatus::Won(_) => COL_GREEN,\n            GameStatus::Won(_) => COL_RED,",
        ["the_status_line_is_coloured_by_what_it_says"],
    ),
    (
        "the columns are numbered from zero",
        "                &col.saturating_add(1).to_string(),",
        "                &col.to_string(),",
        ["every_column_is_numbered_above_it"],
    ),
    (
        "every column's number is written over the first column",
        "            let slot = l.chute_slot(col);\n            if slot.is_empty() {\n                continue;\n            }",
        "            let slot = l.chute_slot(0);\n            if slot.is_empty() {\n                continue;\n            }",
        ["each_number_is_drawn_over_the_column_it_names"],
    ),
    (
        "the piece about to fall waits over every column",
        "            let waiting = col == self.cursor_col\n                && self.status == GameStatus::Playing",
        "            let waiting = self.status == GameStatus::Playing",
        ["the_piece_about_to_fall_is_shown_over_the_cursors_column"],
    ),
    (
        "a piece waits over a column that cannot take one",
        "                && self.board.can_drop(col);",
        "                && true;",
        ["nothing_waits_over_a_column_that_cannot_take_a_piece"],
    ),
    (
        "a piece waits over the board of a finished game",
        "                && self.status == GameStatus::Playing\n                && self.current_player == self.human_player",
        "                && self.current_player == self.human_player",
        ["nothing_waits_over_any_column_once_the_game_is_over"],
    ),
    (
        "the board is not drawn",
        "        for row in 0..ROWS {\n            for col in 0..COLS {\n                disc(f, l.cell(row, col), self.board.get(row, col).face());\n            }\n        }",
        "",
        ["every_hole_of_the_board_is_painted"],
    ),
    (
        "every hole is painted as though it were empty",
        "                disc(f, l.cell(row, col), self.board.get(row, col).face());",
        "                disc(f, l.cell(row, col), Cell::Empty.face());",
        ["a_piece_is_painted_in_the_hole_it_landed_in"],
    ),
    (
        "a piece is painted in the hole across the board from its own",
        "                disc(f, l.cell(row, col), self.board.get(row, col).face());",
        "                disc(f, l.cell(row, col), self.board.get(row, COLS - 1 - col).face());",
        ["a_piece_is_painted_in_the_hole_it_landed_in"],
    ),
    (
        "the winning four are not ringed",
        "                f.push(RenderCommand::StrokeRect {",
        "                let _ = COL_GREEN;\n                let _unused = (RenderCommand::StrokeRect {",
        ["the_winning_four_are_ringed_and_joined"],
    ),
    (
        "the line joining the winning four runs between the wrong two cells",
        "        let [(r0, c0), .., (r3, c3)] = line.cells;",
        "        let [(r0, c0), (r3, c3), ..] = line.cells;",
        ["the_line_joining_the_winning_four_runs_between_the_ends_of_the_run"],
    ),
    (
        "a game still in play has four cells ringed",
        "        if let Some(line) = self.win_line {",
        "        if let Some(line) = self.win_line.or(Some(WinLine {\n            cells: [(0, 0), (0, 1), (0, 2), (0, 3)],\n        })) {",
        ["a_game_still_in_play_has_nothing_ringed"],
    ),
    (
        "a column is not a control",
        "            let strip = l.column(col);\n            if !strip.is_empty() {\n                f.hit(Target::Column(col), strip);\n            }",
        "",
        ["every_column_is_a_control_at_every_size_the_board_is_drawn_at"],
    ),
    (
        "a column's control is not the strip the layout says it is",
        "                f.hit(Target::Column(col), strip);",
        "                f.hit(Target::Column(col), Rect::new(strip.x, strip.y, strip.w / 2.0, strip.h));",
        ["a_columns_control_is_the_strip_the_layout_says_it_is"],
    ),
    (
        "a full column loses the control that would refuse it",
        "            let strip = l.column(col);\n            if !strip.is_empty() {",
        "            let strip = l.column(col);\n            if !strip.is_empty() && self.board.can_drop(col) {",
        ["a_full_column_keeps_its_control_and_answers_no"],
    ),
    (
        "two footer buttons share one box",
        "            l.footer_button(1),\n            Target::Undo,",
        "            l.footer_button(0),\n            Target::Undo,",
        ["a_footer_buttons_label_is_inside_the_button"],
    ),
    (
        "a footer button is not labelled",
        '            "New game",',
        '            "",',
        ["the_three_footer_buttons_are_controls_and_are_labelled"],
    ),
    (
        "the undo button is greyed whether or not there is anything to undo",
        "        let (undo_face, undo_ink) = if self.can_undo() {\n            (COL_SURFACE1, COL_TEXT)\n        } else {\n            (COL_SURFACE0, COL_OVERLAY0)\n        };",
        "        let (undo_face, undo_ink) = (COL_SURFACE0, COL_OVERLAY0);",
        ["the_undo_button_is_greyed_when_there_is_nothing_to_take_back"],
    ),
    (
        "the undo button is drawn live with nothing to take back",
        "        let (undo_face, undo_ink) = if self.can_undo() {\n            (COL_SURFACE1, COL_TEXT)\n        } else {\n            (COL_SURFACE0, COL_OVERLAY0)\n        };",
        "        let (undo_face, undo_ink) = (COL_SURFACE1, COL_TEXT);",
        ["the_undo_button_is_greyed_when_there_is_nothing_to_take_back"],
    ),
    (
        "the sheet is drawn over a game nobody asked it about",
        "        if self.show_help {\n            self.draw_help(&mut f, &l);\n        }",
        "        self.draw_help(&mut f, &l);",
        ["the_sheet_is_not_drawn_until_it_is_asked_for"],
    ),
    (
        "the sheet takes only its own rectangle",
        "        f.hit(Target::HelpSheet, l.window);",
        "        f.hit(Target::HelpSheet, h);",
        ["the_sheet_takes_the_whole_window_and_takes_it_last"],
    ),
    (
        "the sheet's hit box is recorded before the controls it covers",
        "        fill(f, h, COL_SURFACE0, (h.h * 0.04).min(10.0));",
        "        f.hit(Target::HelpSheet, l.window);\n        fill(f, h, COL_SURFACE0, (h.h * 0.04).min(10.0));",
        ["the_sheet_takes_the_whole_window_and_takes_it_last"],
    ),
    (
        "the sheet has no band for its heading",
        "        let head_h = (h.h * 0.16).max(0.0);",
        "        let head_h = 0.0;",
        ["the_sheet_lists_every_control_and_what_it_does"],
    ),
    (
        "the sheet's ladder has no band for the line that shuts it",
        "        let step = body_h / (rows + 1.0);",
        "        let step = body_h / rows;",
        ["the_closing_line_is_written_below_the_last_row_and_not_across_it"],
    ),
    (
        "the sheet's rows are sized to the sheet rather than to their band",
        "        let size = l.small.min(step * 0.7);",
        "        let size = l.small;",
        ["the_sheets_rows_do_not_overwrite_one_another"],
    ),
    (
        "the sheet's rows are all written on one line",
        "            let y = h.y + head_h + l.pad + i as f32 * step;",
        "            let y = h.y + head_h + l.pad;",
        ["the_sheets_rows_do_not_overwrite_one_another"],
    ),
    (
        "the key column takes the whole width of the sheet",
        "        let key_w = (h.w * 0.42).max(0.0);",
        "        let key_w = h.w;",
        ["a_rows_meaning_is_written_to_the_right_of_the_key_it_explains"],
    ),
    (
        "the meaning is written over the key it explains",
        "                h.x + l.pad + key_w,\n                y,\n                meaning,",
        "                h.x + l.pad,\n                y,\n                meaning,",
        ["a_rows_meaning_is_written_to_the_right_of_the_key_it_explains"],
    ),
    (
        "the line that shuts the sheet is written across the last row",
        "            Rect::new(h.x, h.y + head_h + l.pad + rows * step, h.w, step),",
        "            Rect::new(h.x, h.y + head_h + l.pad, h.w, step),",
        ["the_closing_line_is_written_below_the_last_row_and_not_across_it"],
    ),
    (
        "the sheet does not say how to shut it",
        '            "Click anywhere to close",',
        '            "",',
        ["the_sheet_lists_every_control_and_what_it_does"],
    ),
    (
        "a row of the sheet is not listed",
        "        for (i, &(key, meaning)) in HELP_ROWS.iter().enumerate() {",
        "        for (i, &(key, meaning)) in HELP_ROWS\n            .iter()\n            .take(HELP_ROWS.len() - 1)\n            .enumerate()\n        {",
        ["the_sheet_lists_every_control_and_what_it_does"],
    ),
]

if __name__ == "__main__":
    sys.exit(sweep(SRC, MUTATIONS, "connect4", timeout=240))
