#!/usr/bin/env python3
"""Generate posix/src/iconv_translit.rs from glibc's C-locale transliteration
table, locale/C-translit.h.in.

    python posix/tools/gen_iconv_translit.py [path/to/C-translit.h.in]

The default input is D:/refsrc/glibc-2.39/locale/C-translit.h.in.  The output
is written next to this script's crate, posix/src/iconv_translit.rs, and says
in its header which glibc it came from.

Why a generated table: `iconv`'s `//TRANSLIT` is glibc's, and what glibc
substitutes for a character the target cannot encode, in the C locale -- the
only locale this libc has -- is exactly this table ("EUR" for the euro sign,
"(C)" for the copyright sign, "<<" for a guillemet), and "?" for anything the
table does not list.  1659 entries, transcribed by hand, would be a
transcription error waiting to happen; parsed, they are the table.

The input format: one entry a line, `"<key>"<TAB>"<replacement>"<TAB># comment`,
each string a C literal whose `\\x` escapes run until a non-hex character (as
glibc's own gen-translit.py reads them).  Every key is one code point.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "iconv_translit.rs"
DEFAULT_IN = Path("D:/refsrc/glibc-2.39/locale/C-translit.h.in")


def decode_literal(s):
    """The code points of a C-translit.h.in string literal (quotes removed)."""
    out, i = [], 0
    while i < len(s):
        ch = s[i]
        if ch != "\\":
            out.append(ord(ch))
            i += 1
            continue
        i += 1
        if i >= len(s):
            raise ValueError(f"trailing backslash in {s!r}")
        if s[i] in '\\"':
            out.append(ord(s[i]))
            i += 1
            continue
        if s[i] != "x":
            raise ValueError(f"unknown escape in {s!r}")
        i += 1
        j = i
        while j < len(s) and s[j] in "0123456789abcdefABCDEF":
            j += 1
        if j == i:
            raise ValueError(f"empty \\x escape in {s!r}")
        out.append(int(s[i:j], 16))
        i = j
    return out


def parse(text):
    entries = []
    for n, line in enumerate(text.splitlines(), 1):
        if not line.startswith('"'):
            continue
        fields = line.split("\t")
        if len(fields) < 2:
            raise ValueError(f"line {n}: expected key and replacement: {line!r}")
        key_lit, rep_lit = fields[0], fields[1]
        if not (key_lit.startswith('"') and key_lit.endswith('"')
                and rep_lit.startswith('"') and rep_lit.endswith('"')):
            raise ValueError(f"line {n}: unquoted field: {line!r}")
        key = decode_literal(key_lit[1:-1])
        rep = decode_literal(rep_lit[1:-1])
        if len(key) != 1:
            raise ValueError(f"line {n}: key is {len(key)} code points")
        entries.append((key[0], rep))
    keys = [k for k, _ in entries]
    if keys != sorted(keys) or len(set(keys)) != len(keys):
        raise ValueError("keys are not strictly increasing")
    return entries


def rust_str(cps):
    parts = []
    for cp in cps:
        c = chr(cp)
        if c == "\\":
            parts.append("\\\\")
        elif c == '"':
            parts.append('\\"')
        elif 0x20 <= cp < 0x7F:
            parts.append(c)
        else:
            parts.append(f"\\u{{{cp:x}}}")
    return '"' + "".join(parts) + '"'


def main(argv):
    src = Path(argv[1]) if len(argv) > 1 else DEFAULT_IN
    text = src.read_text(encoding="utf-8")
    entries = parse(text)
    lines = [
        "// @generated by posix/tools/gen_iconv_translit.py from glibc 2.39's",
        "// locale/C-translit.h.in -- do not edit; regenerate.",
        "",
        "//! glibc's transliteration table for the C locale, which `iconv`'s",
        "//! `//TRANSLIT` consults for a character the target cannot encode.",
        "//!",
        f"//! {len(entries)} entries, sorted by code point for a binary search.  A",
        "//! character the table does not list becomes `?`, as in glibc.",
        "",
        "/// `(code point, replacement)`, strictly increasing by code point.",
        "pub(crate) static C_TRANSLIT: &[(u32, &str)] = &[",
    ]
    for key, rep in entries:
        lines.append(f"    (0x{key:04x}, {rust_str(rep)}),")
    lines.append("];")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}: {len(entries)} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
