"""Generate posix/pwhash/src/streebog_tables.rs: GOST R 34.11-2012
(Streebog)'s tables, from libxcrypt 4.4.36's own.

    python posix/tools/gen_streebog_tables.py [path/to/libxcrypt-4.4.36]

The default tree is D:/refsrc/libxcrypt-4.4.36.  The output goes to
posix/pwhash/src/streebog_tables.rs and says in its header where it came
from.

Why carried and not computed: the hash's round function is three steps --
an S-box (pi), a byte transposition and a linear map over GF(2)^64 -- which
libxcrypt, like every fast Streebog, runs as eight tables of 256 words,
each one the three applied to one byte of one word.  libxcrypt ships only
those tables (alg-gost3411-2012-precalc.h), not pi and the map's matrix
they were made from, and the tables do not determine them (any basis of
each table's span would do).  So the tables are libxcrypt's, read out of its
header -- the little-endian ones, under `#ifndef __GOST3411_BIG_ENDIAN__` --
with the twelve round constants of alg-gost3411-2012-const.h; RFC 6986's
examples, in streebog.rs's tests, hold the result to the standard.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "pwhash" / "src" / "streebog_tables.rs"
DEFAULT_TREE = Path("D:/refsrc/libxcrypt-4.4.36")


def little_endian_block(text: str, decl: str) -> str:
    """The body of the first `decl = { ... };` after the first
    `#ifndef __GOST3411_BIG_ENDIAN__` that precedes it: the little-endian
    variant, which each header gives first."""
    start = text.index("#ifndef __GOST3411_BIG_ENDIAN__")
    i = text.index(decl, start)
    alternative = text.find("#else", start)
    if alternative != -1 and alternative < i:
        sys.exit(f"{decl}: not under the little-endian branch")
    j = text.index("{", i)
    k = text.index("};", j)
    return text[j + 1:k]


def words(body: str) -> list[int]:
    return [int(w, 16) for w in re.findall(r"0x([0-9a-fA-F]+)ULL", body)]


def main() -> None:
    tree = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_TREE
    lib = tree / "lib"
    precalc = (lib / "alg-gost3411-2012-precalc.h").read_text(encoding="utf-8")
    const = (lib / "alg-gost3411-2012-const.h").read_text(encoding="utf-8")
    ax = words(little_endian_block(precalc, "static const unsigned long long Ax[8][256] ="))
    if len(ax) != 8 * 256:
        sys.exit(f"Ax: {len(ax)} words, not 2048")
    # The constants' header has two little-endian blocks, buffer512's and
    # C's; C's is the second `#ifndef`.
    c_start = const.index("static const uint512_u C[12]")
    c_branch = const.rindex("#ifndef __GOST3411_BIG_ENDIAN__", 0, c_start)
    c = words(little_endian_block(const[c_branch:], "static const uint512_u C[12] ="))
    if len(c) != 12 * 8:
        sys.exit(f"C: {len(c)} words, not 96")

    lines = [
        "// Generated by posix/tools/gen_streebog_tables.py from libxcrypt 4.4.36's",
        "// lib/alg-gost3411-2012-precalc.h and lib/alg-gost3411-2012-const.h",
        f"// ({tree.as_posix()}), their little-endian branches.  Do not edit: rerun",
        "// the generator.  Alexey Degtyarev's, under the 2-clause BSD licence:",
        "// the notice is streebog.rs's, which reads these.",
        "",
        "//! GOST R 34.11-2012's tables (see `crate::streebog`).",
        "",
        "// The numbers as libxcrypt's headers write them, so that a search for one",
        "// finds it there.",
        "#![allow(clippy::unreadable_literal)]",
        "",
        "/// The round function's S-box, transposition and linear map at once:",
        "/// `AX[i][b]` is the three applied to byte `b` as byte `i` of a word.",
        "#[rustfmt::skip]",
        "pub(crate) static AX: [[u64; 256]; 8] = [",
    ]
    for row in range(8):
        lines.append("    [")
        chunk = ax[row * 256:(row + 1) * 256]
        for k in range(0, 256, 4):
            lines.append("        " + " ".join(f"0x{w:016x}," for w in chunk[k:k + 4]))
        lines.append("    ],")
    lines.append("];")
    lines.append("")
    lines.append("/// The twelve round constants, each as its eight words, least significant")
    lines.append("/// first.")
    lines.append("#[rustfmt::skip]")
    lines.append("pub(crate) static C: [[u64; 8]; 12] = [")
    for row in range(12):
        chunk = c[row * 8:(row + 1) * 8]
        lines.append("    [")
        for k in range(0, 8, 4):
            lines.append("        " + " ".join(f"0x{w:016x}," for w in chunk[k:k + 4]))
        lines.append("    ],")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{OUT}: {len(ax)} + {len(c)} words")


if __name__ == "__main__":
    main()
