"""Compile the Khmer syllable grammar to a DFA and write `khmer_machine.rs`.

Same job as `gen_indic_machine.py`, same machinery — this script imports its
Thompson construction, subset construction and Moore minimisation rather than
repeating them — over a different and much shorter grammar: three scanner
rules instead of seven, transcribed below from HarfBuzz's
`hb-ot-shaper-khmer-machine.rl`.

The grammar's own comment says it "was experimentally extracted from what
Uniscribe allows", which is worth knowing before trying to reason about why
any particular sequence is or is not a syllable. It is not derived from the
Khmer spec; it is a description of a shipped implementation's behaviour, and
the only reason to have it is to match that behaviour.

# The categories are Indic's

HarfBuzz stores the Indic and Khmer categories in the *same* buffer slot,
one enum laid over another, and generates both from one table. So this
scanner's columns are `gen_indic_tables.CATEGORIES` in full, and a category
no Khmer rule names — `Matra`, `Nukta`, `Repha`, every Myanmar-ish thing —
is reachable only through `other = any`, which is exactly what upstream
does.

# What the Khmer grammar does *not* have

No position axis. The Indic grammar leans on `Category::Matra` plus a
separate `Position` to know where a vowel goes; the Khmer one has four
distinct vowel categories instead (`VAbv`, `VBlw`, `VPre`, `VPst`) and
never consults a position. That is why `gen_indic_tables.py` folds a Khmer
matra's position into its category — see `position_to_category` there.
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from gen_indic_machine import a, c, compile_rules, minimise, opt, s, star  # noqa: E402
from gen_indic_tables import CATEGORIES, RUST_CATEGORY  # noqa: E402

from rustfmt_out import rustfmt

# ---------------------------------------------------------------------------
# The grammar, transcribed from `hb-ot-shaper-khmer-machine.rl`. One Python
# assignment per ragel line, in the same order.
# ---------------------------------------------------------------------------

# c = (C | Ra | V)
CONSONANT = a(c("C"), c("Ra"), c("V"))
# joiner = (ZWJ | ZWNJ)
JOINER = a(c("ZWJ"), c("ZWNJ"))
# cn = c.((ZWJ|ZWNJ)?.Robatic)?
CN = s(CONSONANT, opt(s(opt(JOINER), c("Robatic"))))
# xgroup = (joiner*.Xgroup)*
XGROUP = star(s(star(JOINER), c("Xgroup")))
# ygroup = Ygroup*
YGROUP = star(c("Ygroup"))

# matra_group = VPre? xgroup VBlw? xgroup (joiner?.VAbv)? xgroup VPst?
MATRA_GROUP = s(
    opt(c("VPre")),
    XGROUP,
    opt(c("VBlw")),
    XGROUP,
    opt(s(opt(JOINER), c("VAbv"))),
    XGROUP,
    opt(c("VPst")),
)
# syllable_tail = xgroup matra_group xgroup (H.c)? ygroup
SYLLABLE_TAIL = s(XGROUP, MATRA_GROUP, XGROUP, opt(s(c("H"), CONSONANT)), YGROUP)

# broken_cluster = Robatic? (H.cn)* (H | syllable_tail)
BROKEN_CLUSTER = s(
    opt(c("Robatic")),
    star(s(c("H"), CN)),
    a(c("H"), SYLLABLE_TAIL),
)

# The three scanner rules, in the order ragel lists them — which is the order
# ties are broken in, so it is part of the answer, not presentation.
RULES = (
    # consonant_syllable = (cn|PLACEHOLDER|DOTTEDCIRCLE) broken_cluster
    (
        s(a(CN, c("PLACEHOLDER"), c("DOTTEDCIRCLE")), BROKEN_CLUSTER),
        "Consonant",
    ),
    # broken_cluster
    (BROKEN_CLUSTER, "Broken"),
    # other = any
    (a(*(c(name) for name in CATEGORIES)), "NonKhmer"),
)

# The Rust enum the rules name. Order is the order of the variants there,
# which is also HarfBuzz's `khmer_syllable_type_t` numbering.
SYLLABLE_TYPES = ("Consonant", "Broken", "NonKhmer")


def main():
    transitions, accepts = compile_rules(RULES)
    before = len(transitions)
    transitions, accepts = minimise(transitions, accepts)
    if len(transitions) > 250:
        raise SystemExit(f"{len(transitions)} states will not fit in a u8")

    out = pathlib.Path(__file__).parent / ".." / "src" / "khmer_machine.rs"
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        w = f.write
        w(
            "//! The Khmer syllable machine, as a DFA.\n"
            "//!\n"
            "//! Generated by `gui/font/tools/gen_khmer_machine.py` from the\n"
            "//! same three regular expressions HarfBuzz's ragel scanner uses.\n"
            "//! Do not edit: run the script instead, where the grammar is\n"
            "//! written out and explained.\n"
            "\n"
            "use crate::khmer::Syllable;\n"
            "\n"
            "/// State 0 is dead — nothing leaves it — and state 1 is the\n"
            "/// start. A row is indexed by [`Category`](crate::indic::Category)\n"
            "/// cast to `usize`: Khmer and Indic share one category enum, so\n"
            "/// this table has a column for every Indic category too, reachable\n"
            "/// only through the grammar's `other = any`.\n"
            f"pub(crate) static TRANSITIONS: [[u8; {len(CATEGORIES)}]; "
            f"{len(transitions)}] = [\n"
        )
        for row in transitions:
            w("    [" + ", ".join(str(x) for x in row) + "],\n")
        w("];\n\n")
        w(
            "/// Which rule a state accepts, if any. Where more than one\n"
            "/// rule could accept, this is the first one the grammar lists,\n"
            "/// which is how the scanner breaks a tie.\n"
            f"pub(crate) static ACCEPTS: [Option<Syllable>; {len(accepts)}] = [\n"
        )
        for rule in accepts:
            if rule is None:
                w("    None,\n")
            else:
                w(f"    Some(Syllable::{RULES[rule][1]}),\n")
        w("];\n")
    # Match what `cargo fmt -p osfont` would do to this file, so that
    # regenerating it and formatting it are each a no-op after the other.
    # Without this the two rewrite each other's output forever, and every
    # unrelated diff carries a thousand lines of table churn. See
    # rustfmt_out.py for the whole reason.
    rustfmt(out)

    print(f"wrote {out}")
    print(
        f"  {len(transitions)} states over {len(CATEGORIES)} categories"
        f" ({before} before minimisation)"
    )
    named = sorted({RULES[r][1] for r in accepts if r is not None})
    print(f"  accepting: {', '.join(named)}")
    unused = [t for t in SYLLABLE_TYPES if t not in named]
    if unused:
        raise SystemExit(f"no state accepts {unused} — the grammar lost a rule")
    if set(RUST_CATEGORY) != set(CATEGORIES):
        raise SystemExit("the category table and the machine disagree")


if __name__ == "__main__":
    main()
