"""Generate `gui/font/src/script_tables.rs` from the Unicode Script property.

Run from anywhere:

    python gui/font/tools/gen_script_tables.py

Needs `fonttools`, which carries both the Unicode `Script` property and the
OpenType script-tag registry, so the two halves of the mapping come from one
source and cannot drift apart.

What the tables are for
-----------------------

`SCRIPT_RANGES`
    The Unicode `Script` property as sorted, disjoint ranges, each naming a
    row of `SCRIPT_TAGS`. Only characters with a *real* script are listed:
    `Common` (digits, punctuation, spaces), `Inherited` (combining marks) and
    `Unknown` are left out, because none of them selects a script — they take
    the script of the text around them, and the range table's job is to answer
    "what script is this, if it is one".

`SCRIPT_TAGS`
    For each script, the OpenType script tag(s) a font may register its
    features under, most-preferred first. Two tags rather than one because
    OpenType revised the Indic script tags: a font may register Devanagari
    features under `dev2` (the 2004 rules) or `deva` (the original), and a
    shaper must try the newer first and fall back. Scripts with only one tag
    repeat it, so the lookup never has to branch on how many there are.

`Common` and `Inherited` deliberately have no row. A shaper resolves them to
the surrounding script, and a table that mapped them to `DFLT` would make it
too easy to write a run splitter that starts a new run at every space.
"""

import os

from fontTools import unicodedata as fu

# Scripts that never select a script of their own. `Zyyy` is Common, `Zinh`
# is Inherited, `Zzzz` is Unknown.
NEUTRAL = ("Zyyy", "Zinh", "Zzzz")


def script_ranges():
    """The Script property as (first, last, script) runs, neutrals dropped."""
    runs = []
    for cp in range(0x110000):
        script = fu.script(chr(cp))
        if script in NEUTRAL:
            continue
        if runs and runs[-1][2] == script and runs[-1][1] + 1 == cp:
            runs[-1] = (runs[-1][0], cp, script)
        else:
            runs.append((cp, cp, script))
    return runs


def main():
    runs = script_ranges()

    # One row per script, in the order the ranges first mention them, so that
    # the common scripts cluster at the front of the table.
    tags = {}
    for _, _, script in runs:
        if script in tags:
            continue
        ot = fu.ot_tags_from_script(script)
        if not ot:
            raise SystemExit(f"{script} has no OpenType tag")
        # Most-preferred first, padded to two so the lookup is branchless.
        first = ot[0]
        second = ot[1] if len(ot) > 1 else ot[0]
        for tag in (first, second):
            if len(tag) != 4 or not all(0x20 <= ord(c) <= 0x7E for c in tag):
                raise SystemExit(f"{script}: {tag!r} is not a four-byte tag")
        tags[script] = (len(tags), first, second)

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "src", "script_tables.rs")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        w = f.write
        w("//! The Unicode `Script` property, and the OpenType tags it maps to.\n")
        w("//!\n")
        w("//! Generated by `gui/font/tools/gen_script_tables.py` from Unicode\n")
        w(f"//! {fu.unidata_version} and fontTools' OpenType tag registry. Do not\n")
        w("//! edit: run the script instead.\n")
        w("//!\n")
        w("//! See that script for what each table is for, and for why `Common`\n")
        w("//! and `Inherited` are deliberately absent.\n")
        w("\n")

        w("/// The `Script` property as sorted, disjoint ranges of code points:\n")
        w("/// `(first, last, tag_index)`. A character in no range has no script\n")
        w("/// of its own and takes the script of the text around it.\n")
        w(f"pub(crate) static SCRIPT_RANGES: [(u32, u32, u16); {len(runs)}] = [\n")
        for lo, hi, script in runs:
            i = tags[script][0]
            w(f"    (0x{lo:04X}, 0x{hi:04X}, {i}), // {script}\n")
        w("];\n\n")

        w("/// The OpenType script tags for each script, preferred first.\n")
        w("///\n")
        w("/// A font registers its features under one of these; the pair exists\n")
        w("/// because OpenType revised the Indic tags and a font may use either\n")
        w("/// spelling. Scripts with a single tag repeat it, so a caller can\n")
        w("/// always try both without asking how many there are.\n")
        w(f"pub(crate) static SCRIPT_TAGS: [([u8; 4], [u8; 4]); {len(tags)}] = [\n")
        for script, (_, first, second) in sorted(tags.items(), key=lambda kv: kv[1][0]):
            # `*b"latn"` rather than `[b'l', b'a', b't', b'n']`: the same array,
            # but the byte-string spelling is the one clippy's `byte_char_slices`
            # asks for, and this crate denies `clippy::all`.
            w(f'    (*b"{first}", *b"{second}"), // {script}\n')
        w("];\n")

    print(f"wrote {out}")
    print(f"  Unicode {fu.unidata_version}")
    print(f"  {len(runs)} script ranges over {len(tags)} scripts")
    dual = sum(1 for _, first, second in tags.values() if first != second)
    print(f"  {dual} scripts carry a second, older OpenType tag")


if __name__ == "__main__":
    main()
