"""Generate `gui/font/src/emoji_tables.rs` from the Unicode emoji data.

Run from anywhere:

    python gui/font/tools/gen_emoji_tables.py

Fetches `emoji/emoji-data.txt` from unicode.org for the *same* Unicode version
`unicodedata.unidata_version` reports, for the reason the joining generator
gives: every table in this crate must describe one Unicode, or a character can
be known to one pass and unknown to the next.

What the tables are for
-----------------------

`EMOJI_PRESENTATION`
    The characters drawn as emoji by default (`Emoji_Presentation=Yes`): a
    grinning face, a heart with U+FE0F, a flag. When a text face and the
    emoji face both have a glyph for one of these, face fallback
    (`itemize.rs`) takes the emoji face -- the face a reader expects the
    character to be drawn from -- unless U+FE0E asks for the text form.

`EXTENDED_PICTOGRAPHIC`
    UAX #29's `Extended_Pictographic`: what may follow a ZERO WIDTH JOINER and
    stay in the same grapheme cluster (rule GB11). A family, a profession, a
    heart on fire are each one cluster made of several emoji joined by ZWJs,
    and must be drawn from one face or the sequence falls apart into its
    parts.

Both as sorted, disjoint `(first, last)` ranges.
"""

import os
import unicodedata
import urllib.request

from rustfmt_out import rustfmt


def fetch(version):
    """`emoji-data.txt` for exactly `version`, as text."""
    url = f"https://www.unicode.org/Public/{version}/ucd/emoji/emoji-data.txt"
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8", errors="replace")


def parse(text, prop):
    """Every code point with `prop`, as a set."""
    out = set()
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        field, value = (f.strip() for f in line.split(";"))
        if value != prop:
            continue
        if ".." in field:
            lo, hi = (int(p, 16) for p in field.split(".."))
        else:
            lo = hi = int(field, 16)
        out.update(range(lo, hi + 1))
    return out


def ranges(cps):
    """The set collapsed into sorted, disjoint `(first, last)` runs."""
    runs = []
    for cp in sorted(cps):
        if runs and runs[-1][1] + 1 == cp:
            runs[-1] = (runs[-1][0], cp)
        else:
            runs.append((cp, cp))
    return runs


def table(w, name, doc, runs):
    for line in doc:
        w(f"/// {line}\n" if line else "///\n")
    w(f"pub(crate) static {name}: [(u32, u32); {len(runs)}] = [\n")
    for lo, hi in runs:
        w(f"    (0x{lo:04X}, 0x{hi:04X}),\n")
    w("];\n\n")


def main():
    version = unicodedata.unidata_version
    text = fetch(version)
    presentation = ranges(parse(text, "Emoji_Presentation"))
    pictographic = ranges(parse(text, "Extended_Pictographic"))

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "src", "emoji_tables.rs")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        w = f.write
        w("//! The Unicode emoji properties face fallback needs.\n")
        w("//!\n")
        w("//! Generated by `gui/font/tools/gen_emoji_tables.py` from Unicode\n")
        w(f"//! {version}'s `emoji-data.txt`. Do not edit: run the script\n")
        w("//! instead, which says what each table is for.\n\n")
        table(
            w,
            "EMOJI_PRESENTATION",
            [
                "`Emoji_Presentation=Yes`: drawn as emoji unless U+FE0E asks",
                "otherwise. Sorted, disjoint `(first, last)` ranges.",
            ],
            presentation,
        )
        table(
            w,
            "EXTENDED_PICTOGRAPHIC",
            [
                "`Extended_Pictographic`: what may follow a ZERO WIDTH JOINER in",
                "one grapheme cluster (UAX #29, GB11). Sorted, disjoint ranges.",
            ],
            pictographic,
        )
    rustfmt(out)
    print(f"{out}: {len(presentation)} + {len(pictographic)} ranges (Unicode {version})")


if __name__ == "__main__":
    main()
