"""Generate `gui/font/src/joining_tables.rs` from the Unicode joining data.

Run from anywhere:

    python gui/font/tools/gen_joining_tables.py

Why this one downloads
----------------------

The other two generators read the Unicode Character Database that Python and
`fontTools` already carry. `Joining_Type` is not in either of them, so this
script fetches `extracted/DerivedJoiningType.txt` from unicode.org for the
*same* Unicode version `unicodedata.unidata_version` reports. Pinning it to
that version is the point: the joining table and the normalization table must
describe the same Unicode or a character can be composed by one and unknown to
the other.

`DerivedJoiningType.txt` rather than `ArabicShaping.txt` because the former is
complete — it lists every code point, including the ones whose type follows
from their general category (`Transparent` for every non-spacing mark,
`Non_Joining` for everything else) rather than from an explicit line. Deriving
those two defaults here would mean reimplementing a rule Unicode has already
applied, and getting it subtly wrong for the next Unicode version.

What the table is for
---------------------

`JOINING_RANGES`
    `Joining_Type` as sorted, disjoint ranges. `Non_Joining` — the default,
    and the answer for the overwhelming majority of code points — is left
    out: a character in no range is `Non_Joining`. That is what keeps the
    table to a few hundred rows instead of a few thousand.

The types themselves, and what a shaper does with them:

`D` dual-joining
    Joins on both sides. Most Arabic letters. Takes `init`, `medi`, `fina` or
    `isol` depending on its neighbours.
`R` right-joining
    Joins only to the preceding letter — `alef`, `dal`, `waw` and friends.
    Never `init` or `medi`, because nothing may join to its left.
`L` left-joining
    The mirror image. No Arabic letter is `L`; it exists for a handful of
    other scripts.
`C` join-causing
    ZERO WIDTH JOINER. Joins on both sides but has no form of its own, so it
    forces its neighbours to take joined forms without taking one itself.
`T` transparent
    Combining marks and format characters. Skipped entirely when asking what
    is next to what: an `alef` with a `hamza` above it still joins to the
    letter before the `hamza`.
`U` non-joining
    Everything else, including space, which is what breaks a word.
"""

import os
import unicodedata
import urllib.request

from rustfmt_out import rustfmt

# The order here is the discriminant order in the generated Rust enum, so it
# must match `joining.rs`. `U` is absent on purpose: it is the default and is
# never written to the table.
TYPES = ("D", "R", "L", "C", "T")

LONG = {
    "Dual_Joining": "D",
    "Right_Joining": "R",
    "Left_Joining": "L",
    "Join_Causing": "C",
    "Transparent": "T",
    "Non_Joining": "U",
}


def fetch(version):
    """`DerivedJoiningType.txt` for exactly `version`, as text."""
    url = (
        f"https://www.unicode.org/Public/{version}/ucd/extracted/"
        "DerivedJoiningType.txt"
    )
    with urllib.request.urlopen(url, timeout=60) as r:
        # The file is ASCII apart from the copyright line, which is Latin-1.
        return r.read().decode("utf-8", errors="replace")


def parse(text):
    """`{codepoint: type}` for every code point that is not `Non_Joining`."""
    out = {}
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        field, value = (f.strip() for f in line.split(";"))
        short = LONG.get(value, value)
        if short == "U":
            continue
        if short not in TYPES:
            raise SystemExit(f"unknown Joining_Type {value!r}")
        if ".." in field:
            lo, hi = (int(p, 16) for p in field.split(".."))
        else:
            lo = hi = int(field, 16)
        for cp in range(lo, hi + 1):
            out[cp] = short
    return out


def ranges(by_cp):
    """The map collapsed into sorted, disjoint `(first, last, type)` runs."""
    runs = []
    for cp in sorted(by_cp):
        kind = by_cp[cp]
        if runs and runs[-1][2] == kind and runs[-1][1] + 1 == cp:
            runs[-1] = (runs[-1][0], cp, kind)
        else:
            runs.append((cp, cp, kind))
    return runs


def main():
    version = unicodedata.unidata_version
    runs = ranges(parse(fetch(version)))

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "src", "joining_tables.rs")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        w = f.write
        w("//! The Unicode `Joining_Type` property, for cursive scripts.\n")
        w("//!\n")
        w("//! Generated by `gui/font/tools/gen_joining_tables.py` from Unicode\n")
        w(f"//! {version}'s `DerivedJoiningType.txt`. Do not edit: run the\n")
        w("//! script instead.\n")
        w("//!\n")
        w("//! See that script for what each joining type means and why\n")
        w("//! `Non_Joining` is deliberately absent.\n")
        w("\n")
        w("use crate::joining::JoiningType;\n\n")

        w("/// `Joining_Type` as sorted, disjoint ranges of code points.\n")
        w("///\n")
        w("/// A character in no range is [`JoiningType::NonJoining`], which is\n")
        w("/// the property's default and the answer for nearly every code\n")
        w("/// point — hence its absence here.\n")
        w(
            "pub(crate) static JOINING_RANGES: [(u32, u32, JoiningType); "
            f"{len(runs)}] = [\n"
        )
        names = {
            "D": "DualJoining",
            "R": "RightJoining",
            "L": "LeftJoining",
            "C": "JoinCausing",
            "T": "Transparent",
        }
        for lo, hi, kind in runs:
            w(f"    (0x{lo:04X}, 0x{hi:04X}, JoiningType::{names[kind]}),\n")
        w("];\n")
    # Match what `cargo fmt -p osfont` would do to this file, so that
    # regenerating it and formatting it are each a no-op after the other.
    # Without this the two rewrite each other's output forever, and every
    # unrelated diff carries a thousand lines of table churn. See
    # rustfmt_out.py for the whole reason.
    rustfmt(out)

    print(f"wrote {out}")
    print(f"  Unicode {version}")
    print(f"  {len(runs)} ranges")
    for kind in TYPES:
        n = sum(hi - lo + 1 for lo, hi, k in runs if k == kind)
        print(f"  {names[kind]:13} {n} code points")


if __name__ == "__main__":
    main()
