"""Read HarfBuzz's *packed* USE category table back into a plain dict.

This is a verification aid for `gen_use_table.py`, not part of the build. It
exists because the USE category of a code point is derived by ~30 interacting
predicates over five Unicode properties, and a derivation that is wrong for one
code point in a million produces a shaping difference nobody will ever trace
back to a table. Re-deriving it and *diffing against HarfBuzz's own answer for
every code point* is the only check that actually covers the predicates.

`.hbref/hb-ot-shaper-use-table.hh` is generated by HarfBuzz's `gen-use-table.py`
through `packTab`, which emits a few `uint8_t`/`uint16_t` arrays plus a
single-expression accessor that indexes them in a fixed pattern. Nothing about
that expression is specific to *this* table — it is a chain of shifts and array
reads — so it can be transliterated into Python and evaluated for all 0x110000
code points in a second or two.

The leaf array holds the category *macro names* (`O`, `B`, `VAbv`, …) rather
than numbers, so what comes back out is symbolic and needs no enum mapping.

Usage:

    from hb_use_oracle import load_oracle
    cats = load_oracle(".hbref/hb-ot-shaper-use-table.hh")   # {codepoint: "VAbv"}

`.hbref/` is gitignored — it is a scratch checkout of the HarfBuzz sources at
the exact version the sweep's oracle wraps. When it is absent this module's
callers skip the check rather than failing.
"""

import re

# The accessor emitted for this table. Reproduced here rather than parsed
# because a change to its *shape* (a different number of packTab levels) must
# be a loud failure, not a silently wrong table — `parse_accessor` below checks
# the file still matches this shape and dies if it does not.
_ACCESSOR = re.compile(
    r"hb_use_get_category\s*\(unsigned u\)\s*\{"
    r"\s*/\* packtab: \[(?P<shape>[^\]]*)\] \*/"
    r"\s*return u<(?P<limit>\d+)u \? \(uint8_t\)\((?P<expr>.*?)\) : O;",
    re.S,
)

_ARRAY = re.compile(
    r"static const uint(?:8|16)_t (?P<name>hb_use_u(?:8|16))\[(?P<len>\d+)\]\s*=\s*\{(?P<body>[^}]*)\}",
    re.S,
)


def _parse_arrays(text, categories):
    """`{array_name: [int, ...]}` from the C source.

    Entries are either integers or category macro names; the names are mapped
    through `categories` so the leaf array comes back as numbers and every
    array has one element type.
    """
    out = {}
    for m in _ARRAY.finditer(text):
        vals = []
        for tok in m.group("body").replace("\n", " ").split(","):
            tok = tok.strip()
            if not tok:
                continue
            vals.append(int(tok) if tok.isdigit() else categories[tok])
        if len(vals) != int(m.group("len")):
            raise SystemExit(
                f"{m.group('name')}: declared {m.group('len')} entries, found {len(vals)}"
            )
        out[m.group("name")] = vals
    return out


def _to_python(expr):
    """The C indexing expression as a Python one.

    The transformation is textual and total: `a[i]` is the same in both
    languages, `u` is the same name, `>>`/`&`/`+`/`<<` are the same operators,
    and the only C-ism is the `hb_use_b4` nibble read, which becomes a call to
    the Python function of the same name. `u` suffixes on literals go.
    """
    expr = re.sub(r"(\d)u\b", r"\1", expr)
    return expr.strip()


def _b4(a, i):
    """packTab's 4-bit accessor: nibble `i` of a byte array, low nibble first."""
    return (a[i >> 1] >> ((i & 1) << 2)) & 15


def load_oracle(path, categories):
    """`{codepoint: category_name}` for every code point HarfBuzz gives one.

    Code points whose category is the default `O` are omitted, matching what
    `gen_use_table.py` writes.
    """
    text = open(path, encoding="utf-8").read()
    # Two copies of the table are emitted, a fast one and a `HB_OPTIMIZE_SIZE`
    # one. They must agree by construction; read the first.
    text = text.split("#else")[0]

    arrays = _parse_arrays(text, categories)
    m = _ACCESSOR.search(text)
    if not m:
        raise SystemExit(f"{path}: no hb_use_get_category of the expected shape")

    limit = int(m.group("limit"))
    body = _to_python(m.group("expr"))
    code = compile(body, "<hb_use_get_category>", "eval")

    env = dict(arrays)
    env["hb_use_b4"] = _b4

    names = {v: k for k, v in categories.items()}
    out = {}
    for u in range(limit):
        env["u"] = u
        cat = eval(code, {"__builtins__": {}}, env)  # noqa: S307 - our own text
        if cat:
            out[u] = names[cat]
    return out, limit
