"""Writes src/tables.rs from Tremor's lookup tables, verbatim.

    python tools/convert_tables.py <tremor source directory>

The tables are Tremor's own (generated once, long ago, from floating
point); a decoder held to Tremor bit for bit must use exactly these values,
so they are copied rather than recomputed. Tremor's `X(n)` is `n` when
`_LOW_ACCURACY_` is not defined, which is the build this crate follows.
"""

import pathlib
import re
import sys

src = pathlib.Path(sys.argv[1])

ARRAY = re.compile(
    r"static\s+const\s+(?:LOOKUP_T|ogg_int32_t|long|int|unsigned\s+char)\s+(\w+)\s*\[[^\]]*\]\s*=\s*\{(.*?)\};",
    re.S,
)
VALUE = re.compile(r"-?(?:0x[0-9a-fA-F]+|\d+)")


def arrays(path):
    text = path.read_text(encoding="utf-8")
    # Comments out, then X(n) and XdB(n) to n.
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"\bX(?:dB)?\(([^)]*)\)", r"\1", text)
    found = {}
    for m in ARRAY.finditer(text):
        found[m.group(1)] = [int(v, 0) for v in VALUE.findall(m.group(2))]
    return found


tables = {}
for name in ["mdct_lookup.h", "window_lookup.h", "lsp_lookup.h", "floor1.c", "floor0.c"]:
    tables.update(arrays(src / name))

WANT = [
    ("sincos_lookup0", "SINCOS_LOOKUP0", "i32", 1026, "`{sin(2 pi i / 4096), cos(2 pi i / 4096)}` for i from 0 to 512, in Q31."),
    ("sincos_lookup1", "SINCOS_LOOKUP1", "i32", 1024, "As [`SINCOS_LOOKUP0`] at the midpoints, i + 1/2 for i from 0 to 511."),
    ("vwin64", "VWIN64", "i32", 32, "Vorbis's window, rising half, for blocks of 64."),
    ("vwin128", "VWIN128", "i32", 64, "For blocks of 128."),
    ("vwin256", "VWIN256", "i32", 128, "For blocks of 256."),
    ("vwin512", "VWIN512", "i32", 256, "For blocks of 512."),
    ("vwin1024", "VWIN1024", "i32", 512, "For blocks of 1024."),
    ("vwin2048", "VWIN2048", "i32", 1024, "For blocks of 2048."),
    ("vwin4096", "VWIN4096", "i32", 2048, "For blocks of 4096."),
    ("vwin8192", "VWIN8192", "i32", 4096, "For blocks of 8192."),
    ("FLOOR_fromdB_LOOKUP", "FLOOR_FROM_DB", "i32", 256, "Floor 1's dB steps as linear gains."),
    ("FROMdB_LOOKUP", "FROM_DB", "i32", 35, "Floor 0's coarse dB-to-linear steps."),
    ("FROMdB2_LOOKUP", "FROM_DB2", "i32", 32, "Floor 0's fine dB-to-linear steps."),
    ("INVSQ_LOOKUP_I", "INVSQ_LOOKUP_I", "i64", 65, "1 / sqrt(x) for x from 1/2 to 1, in 16.16."),
    ("INVSQ_LOOKUP_IDel", "INVSQ_LOOKUP_IDEL", "i64", 64, "The differences of [`INVSQ_LOOKUP_I`]."),
    ("COS_LOOKUP_I", "COS_LOOKUP_I", "i32", 129, "cos(x) for x from 0 to pi, in .14."),
    ("barklook", "BARKLOOK", "i32", 28, "The Bark scale's band edges, in Hz."),
    ("MLOOP_1", "MLOOP_1", "u8", 64, "Floor 0's normalisation shifts, by bits 25 to 30."),
    ("MLOOP_2", "MLOOP_2", "u8", 64, "By bits 19 to 24."),
    ("MLOOP_3", "MLOOP_3", "u8", 8, "By bits 16 to 18."),
]

out = [
    "//! Tremor's lookup tables, verbatim: the MDCT's sines and cosines, the",
    "//! windows, and the floors' dB and cosine tables.",
    "//!",
    "//! Generated by `tools/convert_tables.py` from Tremor's `mdct_lookup.h`,",
    "//! `window_lookup.h`, `lsp_lookup.h`, `floor0.c` and `floor1.c`, copyright",
    "//! Xiph.Org, used under its BSD licence (`licenses/tremor-COPYING`). Do",
    "//! not edit by hand.",
    "",
    "#![allow(clippy::unreadable_literal, reason = \"Tremor's values, as Tremor writes them\")]",
    "",
]
for c_name, rust_name, ty, size, doc in WANT:
    values = tables[c_name]
    if len(values) != size:
        sys.exit(f"{c_name}: {len(values)} values, expected {size}")
    out.append(f"/// {doc}")
    out.append(f"pub(crate) static {rust_name}: [{ty}; {size}] = [")
    per = 8 if ty != "u8" else 16
    for i in range(0, size, per):
        row = values[i : i + per]
        if ty == "u8":
            cells = [str(v) for v in row]
        elif ty == "i64" or c_name in ("COS_LOOKUP_I", "barklook"):
            cells = [str(v) for v in row]
        else:
            cells = [f"0x{v:08x}" if v >= 0 else f"-0x{-v:08x}" for v in row]
        out.append("    " + ", ".join(cells) + ",")
    out.append("];")
    out.append("")

pathlib.Path("src/tables.rs").write_text("\n".join(out), encoding="utf-8", newline="\n")
print("wrote src/tables.rs:", ", ".join(w[1] for w in WANT))
