.TH RM 1 "2026-05-18" "OurOS" "User Commands"
.SH NAME
rm \- remove files or directories
.SH SYNOPSIS
.B rm
[\fIOPTIONS\fR] \fIFILE\fR...
.SH DESCRIPTION
Remove (unlink) the FILE(s).  By default, rm does not remove directories.
Use \fB\-r\fR to remove directories and their contents recursively.
.PP
OurOS moves deleted files to the Recycle Bin by default.  Use \fB\-\-permanent\fR
to bypass the Recycle Bin and delete immediately.
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-R\fR, \fB\-\-recursive\fR
Remove directories and their contents recursively.
.TP
\fB\-f\fR, \fB\-\-force\fR
Ignore nonexistent files and arguments, never prompt.
.TP
\fB\-i\fR
Prompt before every removal.
.TP
\fB\-I\fR
Prompt once before removing more than three files or recursing.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is being done.
.TP
\fB\-d\fR, \fB\-\-dir\fR
Remove empty directories.
.TP
\fB\-\-permanent\fR
Bypass the Recycle Bin and delete immediately (OurOS extension).
.SH EXAMPLES
.nf
rm file.txt              Remove a file (to Recycle Bin)
rm -rf /tmp/build/       Recursively force-remove a directory
rm -i *.o                Interactively remove object files
rm --permanent secret    Permanently delete a file
.fi
.SH SEE ALSO
.BR rmdir (1),
.BR unlink (2)
.SH BUGS
Use \fBrm\fR with caution.  There is no easy undo for \fB\-\-permanent\fR.
.SH AUTHOR
OurOS Contributors.
