//! `<linux/netfilter.h>` — Netfilter verdict and hook constants.
//!
//! Netfilter is the Linux packet filtering framework.  These
//! constants define the hook points, verdict codes, and
//! protocol families used by iptables/nftables.

// ---------------------------------------------------------------------------
// Netfilter verdicts (NF_*)
// ---------------------------------------------------------------------------

/// Drop the packet.
pub const NF_DROP: u32 = 0;
/// Accept the packet.
pub const NF_ACCEPT: u32 = 1;
/// Stolen (packet consumed by hook, don't free).
pub const NF_STOLEN: u32 = 2;
/// Queue to userspace.
pub const NF_QUEUE: u32 = 3;
/// Repeat the hook.
pub const NF_REPEAT: u32 = 4;
/// Stop processing (verdict determined elsewhere).
pub const NF_STOP: u32 = 5;

// ---------------------------------------------------------------------------
// Netfilter hook numbers (IPv4)
// ---------------------------------------------------------------------------

/// Pre-routing hook (before routing decision).
pub const NF_INET_PRE_ROUTING: u32 = 0;
/// Local input hook (destined for this host).
pub const NF_INET_LOCAL_IN: u32 = 1;
/// Forward hook (being routed through).
pub const NF_INET_FORWARD: u32 = 2;
/// Local output hook (generated by this host).
pub const NF_INET_LOCAL_OUT: u32 = 3;
/// Post-routing hook (after routing decision).
pub const NF_INET_POST_ROUTING: u32 = 4;
/// Number of IPv4/IPv6 netfilter hooks.
pub const NF_INET_NUMHOOKS: u32 = 5;

// ---------------------------------------------------------------------------
// Netfilter protocol families (NFPROTO_*)
// ---------------------------------------------------------------------------

/// Unspecified.
pub const NFPROTO_UNSPEC: u32 = 0;
/// IPv4.
pub const NFPROTO_IPV4: u32 = 2;
/// ARP.
pub const NFPROTO_ARP: u32 = 3;
/// Netdev (ingress/egress).
pub const NFPROTO_NETDEV: u32 = 5;
/// Bridge.
pub const NFPROTO_BRIDGE: u32 = 7;
/// IPv6.
pub const NFPROTO_IPV6: u32 = 10;
/// DECnet.
pub const NFPROTO_DECNET: u32 = 12;
/// Number of protocol families.
pub const NFPROTO_NUMPROTO: u32 = 13;

// ---------------------------------------------------------------------------
// Netfilter verdict encoding
// ---------------------------------------------------------------------------

/// Verdict mask (low 16 bits).
pub const NF_VERDICT_MASK: u32 = 0x000000FF;
/// Queue number shift (for NF_QUEUE verdict).
pub const NF_VERDICT_QMASK: u32 = 0xFFFF0000;
/// Queue number bit shift.
pub const NF_VERDICT_QBITS: u32 = 16;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_verdicts_distinct() {
        let verdicts = [NF_DROP, NF_ACCEPT, NF_STOLEN, NF_QUEUE, NF_REPEAT, NF_STOP];
        for i in 0..verdicts.len() {
            for j in (i + 1)..verdicts.len() {
                assert_ne!(verdicts[i], verdicts[j]);
            }
        }
    }

    #[test]
    fn test_drop_is_zero() {
        assert_eq!(NF_DROP, 0);
    }

    #[test]
    fn test_accept_is_one() {
        assert_eq!(NF_ACCEPT, 1);
    }

    #[test]
    fn test_hooks_distinct() {
        let hooks = [
            NF_INET_PRE_ROUTING,
            NF_INET_LOCAL_IN,
            NF_INET_FORWARD,
            NF_INET_LOCAL_OUT,
            NF_INET_POST_ROUTING,
        ];
        for i in 0..hooks.len() {
            for j in (i + 1)..hooks.len() {
                assert_ne!(hooks[i], hooks[j]);
            }
        }
    }

    #[test]
    fn test_numhooks() {
        assert_eq!(NF_INET_NUMHOOKS, 5);
    }

    #[test]
    fn test_protos_distinct() {
        let protos = [
            NFPROTO_UNSPEC,
            NFPROTO_IPV4,
            NFPROTO_ARP,
            NFPROTO_NETDEV,
            NFPROTO_BRIDGE,
            NFPROTO_IPV6,
            NFPROTO_DECNET,
        ];
        for i in 0..protos.len() {
            for j in (i + 1)..protos.len() {
                assert_ne!(protos[i], protos[j]);
            }
        }
    }

    #[test]
    fn test_verdict_encoding() {
        assert_eq!(NF_VERDICT_QBITS, 16);
    }
}
