//! `<linux/perf_event.h>` — Software performance event constants.
//!
//! Software events are generated by the kernel itself rather than
//! hardware counters. They track kernel-level metrics like context
//! switches, page faults, and CPU migrations.

// ---------------------------------------------------------------------------
// Software event IDs (PERF_COUNT_SW_*)
// ---------------------------------------------------------------------------

/// CPU clock (nanoseconds of CPU time).
pub const PERF_COUNT_SW_CPU_CLOCK: u64 = 0;
/// Task clock (nanoseconds of task CPU time).
pub const PERF_COUNT_SW_TASK_CLOCK: u64 = 1;
/// Page faults (minor + major).
pub const PERF_COUNT_SW_PAGE_FAULTS: u64 = 2;
/// Context switches.
pub const PERF_COUNT_SW_CONTEXT_SWITCHES: u64 = 3;
/// CPU migrations (task moved to different CPU).
pub const PERF_COUNT_SW_CPU_MIGRATIONS: u64 = 4;
/// Minor page faults (no I/O needed).
pub const PERF_COUNT_SW_PAGE_FAULTS_MIN: u64 = 5;
/// Major page faults (I/O needed).
pub const PERF_COUNT_SW_PAGE_FAULTS_MAJ: u64 = 6;
/// Alignment faults.
pub const PERF_COUNT_SW_ALIGNMENT_FAULTS: u64 = 7;
/// Emulation faults.
pub const PERF_COUNT_SW_EMULATION_FAULTS: u64 = 8;
/// Dummy event (for counting only).
pub const PERF_COUNT_SW_DUMMY: u64 = 9;
/// BPF output event.
pub const PERF_COUNT_SW_BPF_OUTPUT: u64 = 10;
/// cgroup switches.
pub const PERF_COUNT_SW_CGROUP_SWITCHES: u64 = 11;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sw_events_distinct() {
        let events = [
            PERF_COUNT_SW_CPU_CLOCK,
            PERF_COUNT_SW_TASK_CLOCK,
            PERF_COUNT_SW_PAGE_FAULTS,
            PERF_COUNT_SW_CONTEXT_SWITCHES,
            PERF_COUNT_SW_CPU_MIGRATIONS,
            PERF_COUNT_SW_PAGE_FAULTS_MIN,
            PERF_COUNT_SW_PAGE_FAULTS_MAJ,
            PERF_COUNT_SW_ALIGNMENT_FAULTS,
            PERF_COUNT_SW_EMULATION_FAULTS,
            PERF_COUNT_SW_DUMMY,
            PERF_COUNT_SW_BPF_OUTPUT,
            PERF_COUNT_SW_CGROUP_SWITCHES,
        ];
        for i in 0..events.len() {
            for j in (i + 1)..events.len() {
                assert_ne!(events[i], events[j]);
            }
        }
    }

    #[test]
    fn test_cpu_clock_is_zero() {
        assert_eq!(PERF_COUNT_SW_CPU_CLOCK, 0);
    }

    #[test]
    fn test_page_faults_ordering() {
        assert!(PERF_COUNT_SW_PAGE_FAULTS < PERF_COUNT_SW_PAGE_FAULTS_MIN);
        assert!(PERF_COUNT_SW_PAGE_FAULTS_MIN < PERF_COUNT_SW_PAGE_FAULTS_MAJ);
    }

    #[test]
    fn test_sequential_values() {
        assert_eq!(PERF_COUNT_SW_CPU_CLOCK, 0);
        assert_eq!(PERF_COUNT_SW_TASK_CLOCK, 1);
        assert_eq!(PERF_COUNT_SW_PAGE_FAULTS, 2);
        assert_eq!(PERF_COUNT_SW_CONTEXT_SWITCHES, 3);
    }
}
