//! `<linux/wmi.h>` — WMI character-device userspace ABI.
//!
//! Modern Linux exposes ACPI/Windows-Management-Instrumentation
//! method providers at `/dev/wmi/<guid>`. Vendor utilities (Dell
//! libsmbios, Lenovo ThinkPad fan-control, HP Sure Start) open the
//! character device and issue WMI method calls via the ioctl below.

// ---------------------------------------------------------------------------
// ioctl group letter
// ---------------------------------------------------------------------------

/// Magic letter for /dev/wmi/* ioctls.
pub const WMI_IOC: u8 = b'W';

// ---------------------------------------------------------------------------
// ioctl numbers
// ---------------------------------------------------------------------------

/// `WMI_IOWR(method, struct wmi_buffer)` — invoke a WMI method (input + output).
pub const WMI_IOWR_METHOD: u32 = 0xC020_5700;
/// `WMI_IOR(query, struct wmi_buffer)` — query a WMI data block.
pub const WMI_IOR_QUERY: u32 = 0x8020_5701;
/// `WMI_IOW(set, struct wmi_buffer)` — set a WMI data block.
pub const WMI_IOW_SET: u32 = 0x4020_5702;
/// `WMI_IOR(event, struct wmi_buffer)` — fetch a queued WMI event.
pub const WMI_IOR_EVENT: u32 = 0x8020_5703;

// ---------------------------------------------------------------------------
// Limits
// ---------------------------------------------------------------------------

/// Length of a WMI GUID string ("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\0").
pub const WMI_GUID_STR_LEN: u32 = 37;
/// Length of the binary GUID buffer in bytes.
pub const WMI_GUID_LEN: u32 = 16;
/// Maximum size of a wmi_buffer payload in bytes.
pub const WMI_MAX_BUFFER_SIZE: u32 = 4096;

// ---------------------------------------------------------------------------
// WMI method instance encoding (struct wmi_buffer.instance & .method)
// ---------------------------------------------------------------------------

/// Wildcard instance — invoke the default instance.
pub const WMI_INSTANCE_ANY: u8 = 0xff;

// ---------------------------------------------------------------------------
// WMI event flags (struct wmi_event_data.flags)
// ---------------------------------------------------------------------------

/// Event was generated by an ACPI _WED method.
pub const WMI_EVENT_FLAG_FROM_WED: u32 = 1 << 0;
/// Event payload is a Unicode string.
pub const WMI_EVENT_FLAG_STRING: u32 = 1 << 1;
/// Event has been ACK'd by another consumer.
pub const WMI_EVENT_FLAG_ACKED: u32 = 1 << 2;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ioctl_letter_w() {
        assert_eq!(WMI_IOC, b'W');
    }

    #[test]
    fn test_ioctls_distinct_and_use_letter_w() {
        let ops = [WMI_IOWR_METHOD, WMI_IOR_QUERY, WMI_IOW_SET, WMI_IOR_EVENT];
        for i in 0..ops.len() {
            for j in (i + 1)..ops.len() {
                assert_ne!(ops[i], ops[j]);
            }
            // Type byte 'W' (0x57) in bits 8..15.
            assert_eq!((ops[i] >> 8) & 0xff, b'W' as u32);
        }
    }

    #[test]
    fn test_guid_lengths_match() {
        // 16-byte binary GUID is RFC 4122; 37-byte string form is the
        // 36-char canonical representation + NUL.
        assert_eq!(WMI_GUID_LEN, 16);
        assert_eq!(WMI_GUID_STR_LEN, 37);
        assert!(WMI_MAX_BUFFER_SIZE.is_power_of_two());
        assert_eq!(WMI_MAX_BUFFER_SIZE, 4096);
    }

    #[test]
    fn test_instance_wildcard() {
        // 0xff is the standard "any-instance" sentinel.
        assert_eq!(WMI_INSTANCE_ANY, 0xff);
    }

    #[test]
    fn test_event_flag_bits_distinct_pow2() {
        let f = [
            WMI_EVENT_FLAG_FROM_WED,
            WMI_EVENT_FLAG_STRING,
            WMI_EVENT_FLAG_ACKED,
        ];
        for &b in &f {
            assert!(b.is_power_of_two());
        }
        for i in 0..f.len() {
            for j in (i + 1)..f.len() {
                assert_ne!(f[i], f[j]);
            }
        }
    }
}
