//! `<linux/netfilter.h>` (hook subset) — netfilter hook point constants.
//!
//! Netfilter hooks are well-defined points in the network stack where
//! packet inspection and manipulation modules can register callbacks.
//! Each protocol family (IPv4, IPv6, ARP, bridge) has its own set
//! of hooks, though the hook numbers are the same across families.

// ---------------------------------------------------------------------------
// Hook numbers (NF_INET_*)
// ---------------------------------------------------------------------------

/// Pre-routing: packet just arrived, before routing decision.
pub const NF_INET_PRE_ROUTING: u32 = 0;
/// Local in: packet is destined for this host.
pub const NF_INET_LOCAL_IN: u32 = 1;
/// Forward: packet is being forwarded to another host.
pub const NF_INET_FORWARD: u32 = 2;
/// Local out: packet was generated by this host.
pub const NF_INET_LOCAL_OUT: u32 = 3;
/// Post-routing: packet is about to leave, after routing.
pub const NF_INET_POST_ROUTING: u32 = 4;
/// Number of hooks.
pub const NF_INET_NUMHOOKS: u32 = 5;

// ---------------------------------------------------------------------------
// Hook priority values (lower = higher priority)
// ---------------------------------------------------------------------------

/// First (highest priority).
pub const NF_IP_PRI_FIRST: i32 = i32::MIN;
/// Raw table priority (before conntrack).
pub const NF_IP_PRI_RAW: i32 = -300;
/// SELinux first hook.
pub const NF_IP_PRI_SELINUX_FIRST: i32 = -225;
/// Connection tracking.
pub const NF_IP_PRI_CONNTRACK: i32 = -200;
/// Mangle table.
pub const NF_IP_PRI_MANGLE: i32 = -150;
/// NAT destination (DNAT).
pub const NF_IP_PRI_NAT_DST: i32 = -100;
/// Filter table (default iptables).
pub const NF_IP_PRI_FILTER: i32 = 0;
/// Security table.
pub const NF_IP_PRI_SECURITY: i32 = 50;
/// NAT source (SNAT/MASQUERADE).
pub const NF_IP_PRI_NAT_SRC: i32 = 100;
/// SELinux last hook.
pub const NF_IP_PRI_SELINUX_LAST: i32 = 225;
/// Connection tracking confirm.
pub const NF_IP_PRI_CONNTRACK_CONFIRM: i32 = i32::MAX;
/// Last (lowest priority).
pub const NF_IP_PRI_LAST: i32 = i32::MAX;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hooks_distinct() {
        let hooks = [
            NF_INET_PRE_ROUTING, NF_INET_LOCAL_IN,
            NF_INET_FORWARD, NF_INET_LOCAL_OUT,
            NF_INET_POST_ROUTING,
        ];
        for i in 0..hooks.len() {
            for j in (i + 1)..hooks.len() {
                assert_ne!(hooks[i], hooks[j]);
            }
        }
    }

    #[test]
    fn test_hooks_sequential() {
        assert_eq!(NF_INET_PRE_ROUTING, 0);
        assert_eq!(NF_INET_LOCAL_IN, 1);
        assert_eq!(NF_INET_FORWARD, 2);
        assert_eq!(NF_INET_LOCAL_OUT, 3);
        assert_eq!(NF_INET_POST_ROUTING, 4);
    }

    #[test]
    fn test_numhooks() {
        assert_eq!(NF_INET_NUMHOOKS, NF_INET_POST_ROUTING + 1);
    }

    #[test]
    fn test_priority_ordering() {
        // Traffic flow order: raw → conntrack → mangle → nat_dst → filter → security → nat_src → confirm
        assert!(NF_IP_PRI_RAW < NF_IP_PRI_CONNTRACK);
        assert!(NF_IP_PRI_CONNTRACK < NF_IP_PRI_MANGLE);
        assert!(NF_IP_PRI_MANGLE < NF_IP_PRI_NAT_DST);
        assert!(NF_IP_PRI_NAT_DST < NF_IP_PRI_FILTER);
        assert!(NF_IP_PRI_FILTER < NF_IP_PRI_SECURITY);
        assert!(NF_IP_PRI_SECURITY < NF_IP_PRI_NAT_SRC);
    }

    #[test]
    fn test_first_and_last() {
        assert_eq!(NF_IP_PRI_FIRST, i32::MIN);
        assert_eq!(NF_IP_PRI_LAST, i32::MAX);
    }
}
