//! POSIX system identification.
//!
//! Implements `uname()` and `struct utsname` for system identification.
//! Programs use this to determine the OS name, version, and machine type.
//!
//! # Where the values come from
//!
//! This module used to answer out of five compiled-in string literals of its
//! own. It no longer holds an independent opinion about what this system is
//! called: every field is read from the kernel's own `/proc/sys/kernel/*`
//! files, which are generated by the same code that answers `uname(2)`
//! (`kernel/src/fs/procfs.rs` → `gen_sys`, whose comment reads "the uname(2)
//! surface — must stay byte-consistent with sys_uname").
//!
//! | Field | Source | Fallback |
//! |---|---|---|
//! | `sysname` | `/proc/sys/kernel/ostype` | `Linux` |
//! | `nodename` | `/proc/sys/kernel/hostname`, then `/etc/hostname` | the process-local name `gethostname()` reports |
//! | `release` | `/proc/sys/kernel/osrelease` | `6.6.0-slateos` |
//! | `version` | `/proc/sys/kernel/version` | `#1 SMP` |
//! | `machine` | compiled in — the kernel hardcodes it too | `x86_64` |
//! | `domainname` | `/proc/sys/kernel/domainname` | the process-local name `getdomainname()` reports |
//!
//! The fallbacks are byte-identical to the kernel's answers, so a build where
//! procfs is not mounted degrades to the same values rather than inventing a
//! second set.
//!
//! # Why `sysname` is `Linux` and not a name of our own
//!
//! This is settled policy, not a choice made here — see `roadmap-detailed.md`
//! §72 "Version-surface policy (user-directed, 2026-06-10)" and the comment on
//! `sys_uname` in `kernel/src/syscall/linux.rs`, which states it directly:
//! sysname and release are Linux-ABI-only surfaces, native code uses native
//! APIs, so the only callers of `uname()` are Linux binaries that expect Linux
//! values. Reporting `Linux` / `6.6.x` tells such a program which Linux
//! personality it is talking to.
//!
//! The release string in particular **must** satisfy glibc's startup version
//! gate: `__libc_start_main` parses the leading integer triple and aborts the
//! process with "FATAL: kernel too old" if it is below glibc's build-time
//! minimum. The `0.1.0` this module used to report is below every such minimum
//! ever shipped, so any glibc-linked program that reached this code would have
//! died before `main`.

/// Length of each utsname field (including null terminator).
///
/// POSIX requires at least 9 bytes.  We use 65 to match Linux.
const UTSNAME_LEN: usize = 65;

/// Number of fields in `struct utsname`, and hence the byte size the kernel
/// writes.  Named because the size is an ABI contract, not an implementation
/// detail: see the `Utsname::domainname` documentation.
const UTSNAME_FIELDS: usize = 6;

// The kernel's own answers, duplicated here only as the fallback for a build
// where `/proc` is not mounted.  Keep byte-identical to `gen_sys` in
// `kernel/src/fs/procfs.rs` and to `sys_uname` in `kernel/src/syscall/linux.rs`.
const FALLBACK_SYSNAME: &[u8] = b"Linux";
const FALLBACK_RELEASE: &[u8] = b"6.6.0-slateos";
const FALLBACK_VERSION: &[u8] = b"#1 SMP";

/// The machine type.  The kernel hardcodes this too — we are 64-bit x86 only,
/// so there is no file to read and nothing to disagree about.
const MACHINE: &[u8] = b"x86_64";

const PROC_OSTYPE: &[u8] = b"/proc/sys/kernel/ostype";
const PROC_OSRELEASE: &[u8] = b"/proc/sys/kernel/osrelease";
const PROC_VERSION: &[u8] = b"/proc/sys/kernel/version";
const PROC_HOSTNAME: &[u8] = b"/proc/sys/kernel/hostname";
const PROC_DOMAINNAME: &[u8] = b"/proc/sys/kernel/domainname";

/// The persistent host name, read when procfs has no answer.  Same two-step
/// order — live kernel value first, on-disk value second — that `hostname(1)`,
/// `getty`, `logger` and `sysctl` use, so all of them report one name.
const ETC_HOSTNAME: &[u8] = b"/etc/hostname";

/// System identification structure.
///
/// Returned by `uname()`.  Each field is a null-terminated C string.
#[repr(C)]
pub struct Utsname {
    /// Operating system name.
    pub sysname: [u8; UTSNAME_LEN],
    /// Network node hostname.
    pub nodename: [u8; UTSNAME_LEN],
    /// Operating system release.
    pub release: [u8; UTSNAME_LEN],
    /// Operating system version.
    pub version: [u8; UTSNAME_LEN],
    /// Hardware type.
    pub machine: [u8; UTSNAME_LEN],
    /// NIS domain name.
    ///
    /// This field is **not optional padding** — it is part of the ABI, and
    /// omitting it was a buffer overflow waiting to happen. Both glibc's
    /// `struct utsname` (`_UTSNAME_DOMAIN_LENGTH` is 65 on Linux, so the field
    /// is present whether or not `_GNU_SOURCE` is defined; without it the
    /// member is merely renamed `__domainname`) and our own kernel's
    /// `sys_uname` — which does `let mut buf = [0u8; 6 * 65]` and copies all
    /// 390 bytes out to the caller — treat it as the sixth field. While this
    /// struct was 5 × 65 = 325 bytes, a caller that declared it here and
    /// invoked `uname(2)` handed the kernel a buffer 65 bytes shorter than the
    /// kernel writes.
    pub domainname: [u8; UTSNAME_LEN],
}

/// The struct is exactly the block the kernel copies out — checked at compile
/// time, on every target, rather than only in a host test.
///
/// A unit test would not have caught the missing sixth field on the target we
/// actually ship: `cargo test` runs on the Windows build host, and the size of
/// this struct is an ABI contract with a kernel that host never runs.
const _: () = assert!(core::mem::size_of::<Utsname>() == UTSNAME_FIELDS * UTSNAME_LEN);

/// Copy a byte string into a fixed-size utsname field, null-terminated.
fn fill_field(field: &mut [u8; UTSNAME_LEN], src: &[u8]) {
    let mut i: usize = 0;
    let limit = if src.len() < UTSNAME_LEN.wrapping_sub(1) {
        src.len()
    } else {
        UTSNAME_LEN.wrapping_sub(1)
    };

    while i < limit {
        if let (Some(dst), Some(&b)) = (field.get_mut(i), src.get(i)) {
            *dst = b;
        }
        i = i.wrapping_add(1);
    }

    // Null-terminate.
    if let Some(slot) = field.get_mut(i) {
        *slot = 0;
    }
}

/// Strip surrounding ASCII whitespace.
///
/// Every `/proc/sys/kernel/*` value ends in a newline, which is part of the
/// file's format and not part of the name.  A `nodename` with a trailing `\n`
/// in it corrupts anything that pastes it into a longer string.
fn trim(bytes: &[u8]) -> &[u8] {
    let mut start = 0;
    let mut end = bytes.len();
    while start < end {
        match bytes.get(start) {
            Some(b) if b.is_ascii_whitespace() => start = start.wrapping_add(1),
            _ => break,
        }
    }
    while end > start {
        match bytes.get(end.wrapping_sub(1)) {
            Some(b) if b.is_ascii_whitespace() => end = end.wrapping_sub(1),
            _ => break,
        }
    }
    bytes.get(start..end).unwrap_or(&[])
}

/// The kernel's answer if it gave one, otherwise the compiled-in constant.
///
/// A file that exists but is empty counts as no answer: an empty `sysname`
/// would make every program that prints it report nothing at all, which is a
/// worse failure than reporting the value we would have reported anyway.
fn choose<'a>(read: &'a [u8], fallback: &'a [u8]) -> &'a [u8] {
    let trimmed = trim(read);
    if trimmed.is_empty() {
        fallback
    } else {
        trimmed
    }
}

/// Read a whole small kernel file into `buf`, returning the byte count.
///
/// Returns 0 for every failure — a missing `/proc` is the normal case on a
/// system booted without it, not an error worth reporting up through a
/// `uname()` that POSIX says returns a non-negative value on success.
#[cfg(target_os = "none")]
fn read_kernel_file(path: &[u8], buf: &mut [u8]) -> usize {
    let ret = crate::syscall::syscall4(
        crate::syscall::SYS_FS_READ_FILE,
        path.as_ptr() as u64,
        path.len() as u64,
        buf.as_mut_ptr() as u64,
        buf.len() as u64,
    );
    if ret <= 0 {
        return 0;
    }
    #[allow(clippy::cast_sign_loss)]
    let n = ret as usize;
    core::cmp::min(n, buf.len())
}

/// Host builds have no kernel to ask, so every field takes its fallback.
///
/// This is why the fallbacks are the kernel's real values rather than
/// placeholders: the unit tests below run on the host, and they must be
/// exercising the values the target will actually report.
#[cfg(not(target_os = "none"))]
fn read_kernel_file(_path: &[u8], _buf: &mut [u8]) -> usize {
    0
}

/// Fill one field from a kernel file, falling back to a constant.
fn fill_from_file(field: &mut [u8; UTSNAME_LEN], path: &[u8], fallback: &[u8]) {
    let mut buf = [0u8; UTSNAME_LEN - 1];
    let n = read_kernel_file(path, &mut buf);
    let read = buf.get(..n).unwrap_or(&[]);
    fill_field(field, choose(read, fallback));
}

/// Fill one field from the first of several files that answers, else from a
/// process-local value.
///
/// `nodename` and `domainname` differ from the other fields in having a
/// last-resort source that is not a constant: the name this process set with
/// `sethostname()` / `setdomainname()`.  Those setters currently write a
/// process-local variable rather than reaching the kernel (see
/// `known-issues.md` → `B-POSIX-HOSTNAME-IS-PROCESS-LOCAL`), so consulting
/// them last is what keeps `uname().nodename` and `gethostname()` agreeing
/// with each other on a host build and on a `/proc`-less target.
fn fill_from_files_or_local(
    field: &mut [u8; UTSNAME_LEN],
    paths: &[&[u8]],
    local: fn(&mut [u8]) -> usize,
) {
    let mut buf = [0u8; UTSNAME_LEN - 1];
    for path in paths {
        let n = read_kernel_file(path, &mut buf);
        let read = buf.get(..n).unwrap_or(&[]);
        let trimmed = trim(read);
        if !trimmed.is_empty() {
            fill_field(field, trimmed);
            return;
        }
    }
    let n = local(&mut buf);
    fill_field(field, buf.get(..n).unwrap_or(&[]));
}

/// Get system identification.
///
/// Fills the `utsname` structure pointed to by `buf` with information
/// about the operating system and hardware.
///
/// Returns 0 on success, -1 on error.
#[cfg_attr(target_os = "none", unsafe(no_mangle))]
pub extern "C" fn uname(buf: *mut Utsname) -> i32 {
    if buf.is_null() {
        crate::errno::set_errno(crate::errno::EFAULT);
        return -1;
    }

    // SAFETY: Caller guarantees `buf` is valid for writing a Utsname.
    let uts = unsafe { &mut *buf };

    // Zero the entire struct first.
    uts.sysname = [0u8; UTSNAME_LEN];
    uts.nodename = [0u8; UTSNAME_LEN];
    uts.release = [0u8; UTSNAME_LEN];
    uts.version = [0u8; UTSNAME_LEN];
    uts.machine = [0u8; UTSNAME_LEN];
    uts.domainname = [0u8; UTSNAME_LEN];

    fill_from_file(&mut uts.sysname, PROC_OSTYPE, FALLBACK_SYSNAME);
    fill_from_files_or_local(
        &mut uts.nodename,
        &[PROC_HOSTNAME, ETC_HOSTNAME],
        crate::unistd::copy_hostname,
    );
    fill_from_file(&mut uts.release, PROC_OSRELEASE, FALLBACK_RELEASE);
    fill_from_file(&mut uts.version, PROC_VERSION, FALLBACK_VERSION);
    fill_field(&mut uts.machine, MACHINE);
    fill_from_files_or_local(
        &mut uts.domainname,
        &[PROC_DOMAINNAME],
        crate::unistd::copy_domainname,
    );

    0
}

#[cfg(test)]
mod tests {
    use super::*;
    use core::mem;

    // -----------------------------------------------------------------------
    // Struct layout
    // -----------------------------------------------------------------------

    #[test]
    fn utsname_len_is_65() {
        assert_eq!(UTSNAME_LEN, 65);
    }

    #[test]
    fn utsname_struct_size() {
        // 6 fields * 65 bytes each = 390 bytes, matching glibc's struct
        // utsname and the 6 * 65 buffer the kernel's sys_uname copies out.
        // A smaller struct here is a buffer overflow at the syscall boundary,
        // not a cosmetic difference.
        assert_eq!(mem::size_of::<Utsname>(), UTSNAME_FIELDS * UTSNAME_LEN);
        assert_eq!(mem::size_of::<Utsname>(), 390);
    }

    #[test]
    fn the_struct_matches_the_layout_constants_the_tree_already_declared() {
        // `linux_utsname_types` has described a 6-field, 390-byte struct with
        // domainname at offset 325 since it was written; the struct itself was
        // 325 bytes with five fields. The constants were right and the type was
        // wrong, and nothing tied them together, so neither side could notice.
        // This test is that tie.
        use crate::linux_utsname_types as layout;

        assert_eq!(
            mem::size_of::<Utsname>(),
            layout::UTSNAME_SIZE as usize,
            "struct utsname must be the size the layout constants declare"
        );
        assert_eq!(UTSNAME_LEN, layout::UTSNAME_FIELD_LEN as usize);
        assert_eq!(UTSNAME_FIELDS, layout::UTSNAME_FIELD_COUNT as usize);

        // And each field really begins where the constants say it does, so a
        // caller that reaches into the struct by offset — which is what a
        // ported C program doing pointer arithmetic on `uname(2)` output
        // does — lands on the field it meant.
        let uts = unsafe { mem::zeroed::<Utsname>() };
        let base = &uts as *const Utsname as usize;
        for (name, addr, expected) in [
            (
                "sysname",
                &uts.sysname as *const _ as usize,
                layout::UTSNAME_OFF_SYSNAME,
            ),
            (
                "nodename",
                &uts.nodename as *const _ as usize,
                layout::UTSNAME_OFF_NODENAME,
            ),
            (
                "release",
                &uts.release as *const _ as usize,
                layout::UTSNAME_OFF_RELEASE,
            ),
            (
                "version",
                &uts.version as *const _ as usize,
                layout::UTSNAME_OFF_VERSION,
            ),
            (
                "machine",
                &uts.machine as *const _ as usize,
                layout::UTSNAME_OFF_MACHINE,
            ),
            (
                "domainname",
                &uts.domainname as *const _ as usize,
                layout::UTSNAME_OFF_DOMAINNAME,
            ),
        ] {
            assert_eq!(
                addr.wrapping_sub(base),
                expected as usize,
                "{name} is not at its declared offset"
            );
        }
    }

    // -----------------------------------------------------------------------
    // uname — success case
    // -----------------------------------------------------------------------

    #[test]
    fn uname_returns_zero_on_success() {
        let mut uts = unsafe { mem::zeroed::<Utsname>() };
        let ret = uname(&mut uts as *mut Utsname);
        assert_eq!(ret, 0);
    }

    /// The bytes of a field up to its null terminator.
    fn field(bytes: &[u8; UTSNAME_LEN]) -> &[u8] {
        let end = bytes.iter().position(|&b| b == 0).unwrap_or(UTSNAME_LEN);
        bytes.get(..end).unwrap_or(&[])
    }

    fn sample() -> Utsname {
        let mut uts = unsafe { mem::zeroed::<Utsname>() };
        uname(&mut uts as *mut Utsname);
        uts
    }

    #[test]
    fn uname_fills_sysname() {
        // "Linux", not a name of our own: the only callers of uname() are
        // Linux binaries, and this tells them which personality they have.
        assert_eq!(field(&sample().sysname), b"Linux");
    }

    #[test]
    fn uname_fills_nodename() {
        assert_eq!(field(&sample().nodename), b"localhost");
    }

    #[test]
    fn uname_fills_release() {
        assert_eq!(field(&sample().release), b"6.6.0-slateos");
    }

    #[test]
    fn uname_fills_version() {
        assert_eq!(field(&sample().version), b"#1 SMP");
    }

    #[test]
    fn uname_fills_machine() {
        assert_eq!(field(&sample().machine), b"x86_64");
    }

    #[test]
    fn uname_fills_domainname() {
        // The sixth field is filled, not left as the zeroes a caller could
        // have got from `memset` — it is a real value, so a program that
        // prints `u.domainname` prints something.
        assert!(!field(&sample().domainname).is_empty());
    }

    #[test]
    fn the_release_satisfies_glibcs_version_gate() {
        // glibc's __libc_start_main parses the leading MAJOR.MINOR.PATCH and
        // aborts with "FATAL: kernel too old" below its build-time minimum.
        // The old value here was "0.1.0", which fails every such minimum ever
        // shipped — a glibc program reaching this code died before main.
        let release = sample().release;
        let text = field(&release);
        let leading: &[u8] = text.split(|&b| b == b'-').next().unwrap_or(&[]);
        let mut parts = leading.split(|&b| b == b'.');
        let major = parts.next().unwrap_or(&[]);
        assert_eq!(major, b"6");
        let minor = parts.next().unwrap_or(&[]);
        assert_eq!(minor, b"6");
        // And the full string still names our build, for anything that prints
        // it rather than parsing it.
        assert!(text.ends_with(b"-slateos"));
    }

    #[test]
    fn no_field_but_version_contains_a_space() {
        // `uname -a` output is routinely split on whitespace. One field that
        // is two words shifts every field after it. `version` is the sole
        // exception, on Linux as here: "#1 SMP".
        let uts = sample();
        for (name, bytes) in [
            ("sysname", &uts.sysname),
            ("nodename", &uts.nodename),
            ("release", &uts.release),
            ("machine", &uts.machine),
            ("domainname", &uts.domainname),
        ] {
            assert!(
                !field(bytes).contains(&b' '),
                "{name} must be a single token"
            );
        }
    }

    #[test]
    fn no_field_keeps_the_newline_that_ends_a_proc_file() {
        // Every /proc/sys/kernel/* value ends in a newline that belongs to the
        // file format, not to the name. Carrying it into the struct would put
        // a line break in the middle of anything that prints the field as part
        // of a longer string.
        let uts = sample();
        for (name, bytes) in [
            ("sysname", &uts.sysname),
            ("nodename", &uts.nodename),
            ("release", &uts.release),
            ("version", &uts.version),
            ("machine", &uts.machine),
            ("domainname", &uts.domainname),
        ] {
            let value = field(bytes);
            for &bad in b"\n\r\t" {
                assert!(!value.contains(&bad), "{name} must not contain {bad:#04x}");
            }
        }
    }

    // -----------------------------------------------------------------------
    // The values agree with the kernel's
    // -----------------------------------------------------------------------

    #[test]
    fn the_fallbacks_are_the_kernels_own_values() {
        // gen_sys in kernel/src/fs/procfs.rs answers these three paths with
        // exactly these bytes, and sys_uname fills the same. If a future
        // change to the kernel moves them, this module must move with it —
        // it must never become a fifth independent opinion about the name of
        // the system, which is how "CustomOS" / "MintOS" / "Slate OS" / "Linux"
        // came to coexist in one tree.
        assert_eq!(FALLBACK_SYSNAME, b"Linux");
        assert_eq!(FALLBACK_RELEASE, b"6.6.0-slateos");
        assert_eq!(FALLBACK_VERSION, b"#1 SMP");
        assert_eq!(MACHINE, b"x86_64");
    }

    #[test]
    fn the_proc_paths_are_the_ones_the_kernel_generates() {
        // These five must stay spelled as gen_sys spells them; a typo would
        // silently take every field down its fallback path, which looks
        // identical until the kernel's answer changes.
        assert_eq!(PROC_OSTYPE, b"/proc/sys/kernel/ostype");
        assert_eq!(PROC_OSRELEASE, b"/proc/sys/kernel/osrelease");
        assert_eq!(PROC_VERSION, b"/proc/sys/kernel/version");
        assert_eq!(PROC_HOSTNAME, b"/proc/sys/kernel/hostname");
        assert_eq!(PROC_DOMAINNAME, b"/proc/sys/kernel/domainname");
    }

    // -----------------------------------------------------------------------
    // trim / choose — the parsing the target relies on, tested on the host
    // -----------------------------------------------------------------------

    #[test]
    fn trim_strips_the_trailing_newline_of_a_proc_file() {
        assert_eq!(trim(b"Linux\n"), b"Linux");
        assert_eq!(trim(b"  6.6.0-slateos \r\n"), b"6.6.0-slateos");
        assert_eq!(trim(b""), b"");
        assert_eq!(trim(b"\n\n"), b"");
    }

    #[test]
    fn trim_keeps_an_interior_space() {
        // "#1 SMP" is one value, not two.
        assert_eq!(trim(b"#1 SMP\n"), b"#1 SMP");
    }

    #[test]
    fn an_empty_file_falls_back_rather_than_reporting_nothing() {
        assert_eq!(choose(b"", FALLBACK_SYSNAME), b"Linux");
        assert_eq!(choose(b"\n", FALLBACK_SYSNAME), b"Linux");
        assert_eq!(choose(b"   \n", FALLBACK_SYSNAME), b"Linux");
    }

    #[test]
    fn a_file_with_content_wins_over_the_fallback() {
        assert_eq!(choose(b"Linux\n", FALLBACK_SYSNAME), b"Linux");
        assert_eq!(choose(b"6.7.1\n", FALLBACK_RELEASE), b"6.7.1");
    }

    // -----------------------------------------------------------------------
    // uname — null pointer
    // -----------------------------------------------------------------------

    #[test]
    fn uname_null_returns_negative_one() {
        let ret = uname(core::ptr::null_mut());
        assert_eq!(ret, -1);
    }

    // -----------------------------------------------------------------------
    // fill_field — null termination
    // -----------------------------------------------------------------------

    #[test]
    fn fill_field_null_terminates_short_string() {
        let mut field = [0xFFu8; UTSNAME_LEN];
        fill_field(&mut field, b"abc");
        assert_eq!(&field[..3], b"abc");
        assert_eq!(field[3], 0); // null terminator
    }

    #[test]
    fn fill_field_null_terminates_empty_string() {
        let mut field = [0xFFu8; UTSNAME_LEN];
        fill_field(&mut field, b"");
        assert_eq!(field[0], 0); // immediately null-terminated
    }

    #[test]
    fn fill_field_truncates_long_string() {
        // String longer than UTSNAME_LEN - 1 (64 chars max).
        let long = [b'X'; 128];
        let mut field = [0u8; UTSNAME_LEN];
        fill_field(&mut field, &long);
        // First 64 bytes should be 'X'.
        for byte in &field[..64] {
            assert_eq!(*byte, b'X');
        }
        // Byte 64 (index UTSNAME_LEN - 1) must be null terminator.
        assert_eq!(field[64], 0);
    }

    #[test]
    fn fill_field_exact_max_length() {
        // Exactly 64 bytes — fills completely and null-terminates at [64].
        let exact = [b'A'; 64];
        let mut field = [0u8; UTSNAME_LEN];
        fill_field(&mut field, &exact);
        for byte in &field[..64] {
            assert_eq!(*byte, b'A');
        }
        assert_eq!(field[64], 0);
    }

    #[test]
    fn fill_field_preserves_content() {
        let mut field = [0u8; UTSNAME_LEN];
        fill_field(&mut field, b"hello");
        assert_eq!(&field[..5], b"hello");
        assert_eq!(field[5], 0);
    }

    // -----------------------------------------------------------------------
    // uname — fields remain independent (no overlap)
    // -----------------------------------------------------------------------

    #[test]
    fn uname_fields_do_not_overlap() {
        let uts = sample();

        // Each field should start with the correct string and not
        // bleed into adjacent fields.
        assert_eq!(uts.sysname[0], b'L'); // "Linux"
        assert_eq!(uts.nodename[0], b'l'); // "localhost"
        assert_eq!(uts.release[0], b'6'); // "6.6.0-slateos"
        assert_eq!(uts.version[0], b'#'); // "#1 SMP"
        assert_eq!(uts.machine[0], b'x'); // "x86_64"
        assert_eq!(uts.domainname[0], b'('); // "(none)"
    }

    // -----------------------------------------------------------------------
    // uname — nodename reflects the hostname set via sethostname()
    // -----------------------------------------------------------------------

    #[test]
    fn uname_nodename_tracks_sethostname() {
        // Save default state via gethostname so we can restore it.
        let mut saved = [0u8; 256];
        let _ = crate::unistd::gethostname(saved.as_mut_ptr(), saved.len());

        // Change the hostname.
        let new_name = b"uname-test-host";
        let rc = crate::unistd::sethostname(new_name.as_ptr(), new_name.len());
        assert_eq!(rc, 0);

        // uname must now report the new hostname.
        assert_eq!(field(&sample().nodename), new_name);

        // Restore the default hostname for other tests.
        let restore = b"localhost";
        let _ = crate::unistd::sethostname(restore.as_ptr(), restore.len());
    }

    #[test]
    fn uname_domainname_tracks_setdomainname() {
        let new_name = b"uname-test-domain";
        let rc = crate::unistd::setdomainname(new_name.as_ptr(), new_name.len());
        assert_eq!(rc, 0);

        assert_eq!(field(&sample().domainname), new_name);

        let restore = b"(none)";
        let _ = crate::unistd::setdomainname(restore.as_ptr(), restore.len());
    }

    // -----------------------------------------------------------------------
    // uname — zeroes padding after null terminator
    // -----------------------------------------------------------------------

    #[test]
    fn uname_zeroes_entire_struct_first() {
        // Pre-fill with garbage, then call uname.
        let mut uts: Utsname = unsafe { mem::zeroed() };
        // Fill with 0xFF.
        let ptr = &mut uts as *mut Utsname as *mut u8;
        unsafe {
            core::ptr::write_bytes(ptr, 0xFF, mem::size_of::<Utsname>());
        }

        uname(&mut uts as *mut Utsname);

        // After "Linux" (5 bytes) + null at [5], bytes [6..65] should
        // be zero because uname zeroes the struct before filling.
        for &byte in &uts.sysname[6..] {
            assert_eq!(
                byte, 0,
                "sysname should be zeroed after the null terminator"
            );
        }
        // The sixth field is zeroed too — it used not to exist, so a caller
        // that reads it must not get the 0xFF it wrote.
        assert_ne!(uts.domainname[0], 0xFF);
    }
}
