#!/usr/bin/env python3
"""Reproducible build recipe for the `ctest-scanf` SlateOS fixture.

Produces `ctest-scanf.elf`, a native SlateOS (`x86_64-slateos`) binary compiled
from `main.c` by `zig cc` (clang + musl headers) and linked against the posix
`libc.a` sysroot with rust-lld.  `scripts/create-ext4-rootfs.sh` stages it at
`/tests/ctest-scanf.elf`, and the kernel runs it as a ring-3 self-test
(`self_test_cscanf`, `kernel/src/proc/spawn.rs`) that asserts the exit code
(42 == all checks passed).

It covers the `sscanf`/`fscanf` assembly trampolines (`va_trampoline!` in
`posix/src/scanf.rs`), which exist only on the bare-metal target: `cargo test`
can drive `vsscanf`/`vfscanf` directly but can never prove that a real C caller
gets a correct `va_list` out of the trampoline.

That matters more here than for printf.  Every scanf argument is a
*destination pointer*, so an argument taken from the wrong slot is a wrong
address written through, not a wrong number printed — which is what made
BUG-POSIX-SCANF-ARG-ARRAY-OOB an arbitrary stack write rather than an
information leak.  The checks therefore concentrate past the sixth pointer,
where the arguments stop coming from the register save area and start coming
from the caller's overflow area, and bracket the destinations with canaries so
an off-by-one store shows up as corruption of a neighbour.

`scanf` itself (gp_offset 8, `va_list*` in `%rsi`) is not exercised here: it
reads stdin, which a non-interactive self-test cannot supply without blocking.
Its trampoline is generated by the same macro from the same three constants,
and the engine behind it is the one `sscanf`/`fscanf` share.

Sibling fixtures in the sysroot vararg/float-ABI family:

    ctest-libc-float   double *returns* and *varargs* doubles
    ctest-libm         *named* float arguments (%xmm0-7 by SSE class)
    ctest-longdouble   `long double`: X87/X87UP -> MEMORY, returned in %st(0)
    ctest-fortify      the same rules again, through the `__*_chk` ABI
    ctest-scanf        the scanf trampolines, whose varargs are all pointers

`-fno-builtin` keeps clang from folding `sscanf`-shaped calls with literal
arguments, which would make the fixture pass without entering the sysroot;
`main.c` additionally launders every input string through a volatile global.

Otherwise the compile flags mirror `toolchain/x86_64-slateos.json` (static
relocation, large code model).

Run with fastpy on PYTHONPATH so `compiler` is importable, from the root of
the worktree you are actually working in. There are four checkouts of this
repo, and naming one of them in a command is how a lane ends up building
another lane's artifact -- see `scripts/lib/worktree.sh`:

    PYTHONPATH="D:/visual studio projects/fastpy" \
        python services/ctest-scanf/build.py

The posix sysroot (`libc.a`) must already be built and must be *current* with
`posix/src/` and with `toolchain/build-sysroot.ps1`'s RUSTFLAGS.
"""

import subprocess
import sys
from pathlib import Path

from compiler import toolchain

HERE = Path(__file__).resolve().parent
OS_ROOT = HERE.parent.parent
SYSROOT_LIB = OS_ROOT / "toolchain" / "sysroot" / "lib"


def main() -> None:
    zig = toolchain._find_zig_cc()
    if zig is None:
        sys.exit(
            "Cannot find `zig` for the SlateOS C cross-compile. Install zig "
            "(it bundles clang + musl), put it on PATH, or set FASTPY_ZIG."
        )
    if not (SYSROOT_LIB / "libc.a").exists():
        sys.exit(f"Missing sysroot libc.a in {SYSROOT_LIB}; run toolchain/build-sysroot.ps1")

    obj = HERE / "main.o"
    cmd = [
        str(zig), "cc",
        f"--target={toolchain._SLATEOS_ZIG_TARGET}",
        "-c", "-O2",
        "-fno-builtin",           # call the sysroot, don't inline/fold
        "-mcmodel=large",         # match codegen code-model=large
        "-fno-pic", "-fno-pie",   # match relocation-model=static
        "-Wall", "-Wextra", "-Werror",
        str(HERE / "main.c"),
        "-o", str(obj),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if result.returncode != 0 or not obj.exists():
        sys.exit(f"C cross-compile failed:\n{result.stdout}\n{result.stderr}")

    exe = toolchain._link_slateos(
        [obj],
        HERE / "ctest-scanf.elf",
        entry="_start",
        sysroot_lib_dir=SYSROOT_LIB,
        libs=["c"],
    )
    print("OBJ:", obj, obj.stat().st_size)
    print("EXE:", exe, exe.stat().st_size)


if __name__ == "__main__":
    main()
