//! The Unicode `Script` property, and the OpenType tags it maps to.
//!
//! Generated by `gui/font/tools/gen_script_tables.py` from Unicode
//! 16.0.0 and fontTools' OpenType tag registry. Do not
//! edit: run the script instead.
//!
//! See that script for what each table is for, and for why `Common`
//! and `Inherited` are deliberately absent.

/// The `Script` property as sorted, disjoint ranges of code points:
/// `(first, last, tag_index)`. A character in no range has no script
/// of its own and takes the script of the text around it.
pub(crate) static SCRIPT_RANGES: [(u32, u32, u16); 778] = [
    (0x0041, 0x005A, 0), // Latn
    (0x0061, 0x007A, 0), // Latn
    (0x00AA, 0x00AA, 0), // Latn
    (0x00BA, 0x00BA, 0), // Latn
    (0x00C0, 0x00D6, 0), // Latn
    (0x00D8, 0x00F6, 0), // Latn
    (0x00F8, 0x02B8, 0), // Latn
    (0x02E0, 0x02E4, 0), // Latn
    (0x02EA, 0x02EB, 1), // Bopo
    (0x0370, 0x0373, 2), // Grek
    (0x0375, 0x0377, 2), // Grek
    (0x037A, 0x037D, 2), // Grek
    (0x037F, 0x037F, 2), // Grek
    (0x0384, 0x0384, 2), // Grek
    (0x0386, 0x0386, 2), // Grek
    (0x0388, 0x038A, 2), // Grek
    (0x038C, 0x038C, 2), // Grek
    (0x038E, 0x03A1, 2), // Grek
    (0x03A3, 0x03E1, 2), // Grek
    (0x03E2, 0x03EF, 3), // Copt
    (0x03F0, 0x03FF, 2), // Grek
    (0x0400, 0x0484, 4), // Cyrl
    (0x0487, 0x052F, 4), // Cyrl
    (0x0531, 0x0556, 5), // Armn
    (0x0559, 0x058A, 5), // Armn
    (0x058D, 0x058F, 5), // Armn
    (0x0591, 0x05C7, 6), // Hebr
    (0x05D0, 0x05EA, 6), // Hebr
    (0x05EF, 0x05F4, 6), // Hebr
    (0x0600, 0x0604, 7), // Arab
    (0x0606, 0x060B, 7), // Arab
    (0x060D, 0x061A, 7), // Arab
    (0x061C, 0x061E, 7), // Arab
    (0x0620, 0x063F, 7), // Arab
    (0x0641, 0x064A, 7), // Arab
    (0x0656, 0x066F, 7), // Arab
    (0x0671, 0x06DC, 7), // Arab
    (0x06DE, 0x06FF, 7), // Arab
    (0x0700, 0x070D, 8), // Syrc
    (0x070F, 0x074A, 8), // Syrc
    (0x074D, 0x074F, 8), // Syrc
    (0x0750, 0x077F, 7), // Arab
    (0x0780, 0x07B1, 9), // Thaa
    (0x07C0, 0x07FA, 10), // Nkoo
    (0x07FD, 0x07FF, 10), // Nkoo
    (0x0800, 0x082D, 11), // Samr
    (0x0830, 0x083E, 11), // Samr
    (0x0840, 0x085B, 12), // Mand
    (0x085E, 0x085E, 12), // Mand
    (0x0860, 0x086A, 8), // Syrc
    (0x0870, 0x0891, 7), // Arab
    (0x0897, 0x08E1, 7), // Arab
    (0x08E3, 0x08FF, 7), // Arab
    (0x0900, 0x0950, 13), // Deva
    (0x0955, 0x0963, 13), // Deva
    (0x0966, 0x097F, 13), // Deva
    (0x0980, 0x0983, 14), // Beng
    (0x0985, 0x098C, 14), // Beng
    (0x098F, 0x0990, 14), // Beng
    (0x0993, 0x09A8, 14), // Beng
    (0x09AA, 0x09B0, 14), // Beng
    (0x09B2, 0x09B2, 14), // Beng
    (0x09B6, 0x09B9, 14), // Beng
    (0x09BC, 0x09C4, 14), // Beng
    (0x09C7, 0x09C8, 14), // Beng
    (0x09CB, 0x09CE, 14), // Beng
    (0x09D7, 0x09D7, 14), // Beng
    (0x09DC, 0x09DD, 14), // Beng
    (0x09DF, 0x09E3, 14), // Beng
    (0x09E6, 0x09FE, 14), // Beng
    (0x0A01, 0x0A03, 15), // Guru
    (0x0A05, 0x0A0A, 15), // Guru
    (0x0A0F, 0x0A10, 15), // Guru
    (0x0A13, 0x0A28, 15), // Guru
    (0x0A2A, 0x0A30, 15), // Guru
    (0x0A32, 0x0A33, 15), // Guru
    (0x0A35, 0x0A36, 15), // Guru
    (0x0A38, 0x0A39, 15), // Guru
    (0x0A3C, 0x0A3C, 15), // Guru
    (0x0A3E, 0x0A42, 15), // Guru
    (0x0A47, 0x0A48, 15), // Guru
    (0x0A4B, 0x0A4D, 15), // Guru
    (0x0A51, 0x0A51, 15), // Guru
    (0x0A59, 0x0A5C, 15), // Guru
    (0x0A5E, 0x0A5E, 15), // Guru
    (0x0A66, 0x0A76, 15), // Guru
    (0x0A81, 0x0A83, 16), // Gujr
    (0x0A85, 0x0A8D, 16), // Gujr
    (0x0A8F, 0x0A91, 16), // Gujr
    (0x0A93, 0x0AA8, 16), // Gujr
    (0x0AAA, 0x0AB0, 16), // Gujr
    (0x0AB2, 0x0AB3, 16), // Gujr
    (0x0AB5, 0x0AB9, 16), // Gujr
    (0x0ABC, 0x0AC5, 16), // Gujr
    (0x0AC7, 0x0AC9, 16), // Gujr
    (0x0ACB, 0x0ACD, 16), // Gujr
    (0x0AD0, 0x0AD0, 16), // Gujr
    (0x0AE0, 0x0AE3, 16), // Gujr
    (0x0AE6, 0x0AF1, 16), // Gujr
    (0x0AF9, 0x0AFF, 16), // Gujr
    (0x0B01, 0x0B03, 17), // Orya
    (0x0B05, 0x0B0C, 17), // Orya
    (0x0B0F, 0x0B10, 17), // Orya
    (0x0B13, 0x0B28, 17), // Orya
    (0x0B2A, 0x0B30, 17), // Orya
    (0x0B32, 0x0B33, 17), // Orya
    (0x0B35, 0x0B39, 17), // Orya
    (0x0B3C, 0x0B44, 17), // Orya
    (0x0B47, 0x0B48, 17), // Orya
    (0x0B4B, 0x0B4D, 17), // Orya
    (0x0B55, 0x0B57, 17), // Orya
    (0x0B5C, 0x0B5D, 17), // Orya
    (0x0B5F, 0x0B63, 17), // Orya
    (0x0B66, 0x0B77, 17), // Orya
    (0x0B82, 0x0B83, 18), // Taml
    (0x0B85, 0x0B8A, 18), // Taml
    (0x0B8E, 0x0B90, 18), // Taml
    (0x0B92, 0x0B95, 18), // Taml
    (0x0B99, 0x0B9A, 18), // Taml
    (0x0B9C, 0x0B9C, 18), // Taml
    (0x0B9E, 0x0B9F, 18), // Taml
    (0x0BA3, 0x0BA4, 18), // Taml
    (0x0BA8, 0x0BAA, 18), // Taml
    (0x0BAE, 0x0BB9, 18), // Taml
    (0x0BBE, 0x0BC2, 18), // Taml
    (0x0BC6, 0x0BC8, 18), // Taml
    (0x0BCA, 0x0BCD, 18), // Taml
    (0x0BD0, 0x0BD0, 18), // Taml
    (0x0BD7, 0x0BD7, 18), // Taml
    (0x0BE6, 0x0BFA, 18), // Taml
    (0x0C00, 0x0C0C, 19), // Telu
    (0x0C0E, 0x0C10, 19), // Telu
    (0x0C12, 0x0C28, 19), // Telu
    (0x0C2A, 0x0C39, 19), // Telu
    (0x0C3C, 0x0C44, 19), // Telu
    (0x0C46, 0x0C48, 19), // Telu
    (0x0C4A, 0x0C4D, 19), // Telu
    (0x0C55, 0x0C56, 19), // Telu
    (0x0C58, 0x0C5A, 19), // Telu
    (0x0C5C, 0x0C5D, 19), // Telu
    (0x0C60, 0x0C63, 19), // Telu
    (0x0C66, 0x0C6F, 19), // Telu
    (0x0C77, 0x0C7F, 19), // Telu
    (0x0C80, 0x0C8C, 20), // Knda
    (0x0C8E, 0x0C90, 20), // Knda
    (0x0C92, 0x0CA8, 20), // Knda
    (0x0CAA, 0x0CB3, 20), // Knda
    (0x0CB5, 0x0CB9, 20), // Knda
    (0x0CBC, 0x0CC4, 20), // Knda
    (0x0CC6, 0x0CC8, 20), // Knda
    (0x0CCA, 0x0CCD, 20), // Knda
    (0x0CD5, 0x0CD6, 20), // Knda
    (0x0CDC, 0x0CDE, 20), // Knda
    (0x0CE0, 0x0CE3, 20), // Knda
    (0x0CE6, 0x0CEF, 20), // Knda
    (0x0CF1, 0x0CF3, 20), // Knda
    (0x0D00, 0x0D0C, 21), // Mlym
    (0x0D0E, 0x0D10, 21), // Mlym
    (0x0D12, 0x0D44, 21), // Mlym
    (0x0D46, 0x0D48, 21), // Mlym
    (0x0D4A, 0x0D4F, 21), // Mlym
    (0x0D54, 0x0D63, 21), // Mlym
    (0x0D66, 0x0D7F, 21), // Mlym
    (0x0D81, 0x0D83, 22), // Sinh
    (0x0D85, 0x0D96, 22), // Sinh
    (0x0D9A, 0x0DB1, 22), // Sinh
    (0x0DB3, 0x0DBB, 22), // Sinh
    (0x0DBD, 0x0DBD, 22), // Sinh
    (0x0DC0, 0x0DC6, 22), // Sinh
    (0x0DCA, 0x0DCA, 22), // Sinh
    (0x0DCF, 0x0DD4, 22), // Sinh
    (0x0DD6, 0x0DD6, 22), // Sinh
    (0x0DD8, 0x0DDF, 22), // Sinh
    (0x0DE6, 0x0DEF, 22), // Sinh
    (0x0DF2, 0x0DF4, 22), // Sinh
    (0x0E01, 0x0E3A, 23), // Thai
    (0x0E40, 0x0E5B, 23), // Thai
    (0x0E81, 0x0E82, 24), // Laoo
    (0x0E84, 0x0E84, 24), // Laoo
    (0x0E86, 0x0E8A, 24), // Laoo
    (0x0E8C, 0x0EA3, 24), // Laoo
    (0x0EA5, 0x0EA5, 24), // Laoo
    (0x0EA7, 0x0EBD, 24), // Laoo
    (0x0EC0, 0x0EC4, 24), // Laoo
    (0x0EC6, 0x0EC6, 24), // Laoo
    (0x0EC8, 0x0ECE, 24), // Laoo
    (0x0ED0, 0x0ED9, 24), // Laoo
    (0x0EDC, 0x0EDF, 24), // Laoo
    (0x0F00, 0x0F47, 25), // Tibt
    (0x0F49, 0x0F6C, 25), // Tibt
    (0x0F71, 0x0F97, 25), // Tibt
    (0x0F99, 0x0FBC, 25), // Tibt
    (0x0FBE, 0x0FCC, 25), // Tibt
    (0x0FCE, 0x0FD4, 25), // Tibt
    (0x0FD9, 0x0FDA, 25), // Tibt
    (0x1000, 0x109F, 26), // Mymr
    (0x10A0, 0x10C5, 27), // Geor
    (0x10C7, 0x10C7, 27), // Geor
    (0x10CD, 0x10CD, 27), // Geor
    (0x10D0, 0x10FA, 27), // Geor
    (0x10FC, 0x10FF, 27), // Geor
    (0x1100, 0x11FF, 28), // Hang
    (0x1200, 0x1248, 29), // Ethi
    (0x124A, 0x124D, 29), // Ethi
    (0x1250, 0x1256, 29), // Ethi
    (0x1258, 0x1258, 29), // Ethi
    (0x125A, 0x125D, 29), // Ethi
    (0x1260, 0x1288, 29), // Ethi
    (0x128A, 0x128D, 29), // Ethi
    (0x1290, 0x12B0, 29), // Ethi
    (0x12B2, 0x12B5, 29), // Ethi
    (0x12B8, 0x12BE, 29), // Ethi
    (0x12C0, 0x12C0, 29), // Ethi
    (0x12C2, 0x12C5, 29), // Ethi
    (0x12C8, 0x12D6, 29), // Ethi
    (0x12D8, 0x1310, 29), // Ethi
    (0x1312, 0x1315, 29), // Ethi
    (0x1318, 0x135A, 29), // Ethi
    (0x135D, 0x137C, 29), // Ethi
    (0x1380, 0x1399, 29), // Ethi
    (0x13A0, 0x13F5, 30), // Cher
    (0x13F8, 0x13FD, 30), // Cher
    (0x1400, 0x167F, 31), // Cans
    (0x1680, 0x169C, 32), // Ogam
    (0x16A0, 0x16EA, 33), // Runr
    (0x16EE, 0x16F8, 33), // Runr
    (0x1700, 0x1715, 34), // Tglg
    (0x171F, 0x171F, 34), // Tglg
    (0x1720, 0x1734, 35), // Hano
    (0x1740, 0x1753, 36), // Buhd
    (0x1760, 0x176C, 37), // Tagb
    (0x176E, 0x1770, 37), // Tagb
    (0x1772, 0x1773, 37), // Tagb
    (0x1780, 0x17DD, 38), // Khmr
    (0x17E0, 0x17E9, 38), // Khmr
    (0x17F0, 0x17F9, 38), // Khmr
    (0x1800, 0x1801, 39), // Mong
    (0x1804, 0x1804, 39), // Mong
    (0x1806, 0x1819, 39), // Mong
    (0x1820, 0x1878, 39), // Mong
    (0x1880, 0x18AA, 39), // Mong
    (0x18B0, 0x18F5, 31), // Cans
    (0x1900, 0x191E, 40), // Limb
    (0x1920, 0x192B, 40), // Limb
    (0x1930, 0x193B, 40), // Limb
    (0x1940, 0x1940, 40), // Limb
    (0x1944, 0x194F, 40), // Limb
    (0x1950, 0x196D, 41), // Tale
    (0x1970, 0x1974, 41), // Tale
    (0x1980, 0x19AB, 42), // Talu
    (0x19B0, 0x19C9, 42), // Talu
    (0x19D0, 0x19DA, 42), // Talu
    (0x19DE, 0x19DF, 42), // Talu
    (0x19E0, 0x19FF, 38), // Khmr
    (0x1A00, 0x1A1B, 43), // Bugi
    (0x1A1E, 0x1A1F, 43), // Bugi
    (0x1A20, 0x1A5E, 44), // Lana
    (0x1A60, 0x1A7C, 44), // Lana
    (0x1A7F, 0x1A89, 44), // Lana
    (0x1A90, 0x1A99, 44), // Lana
    (0x1AA0, 0x1AAD, 44), // Lana
    (0x1B00, 0x1B4C, 45), // Bali
    (0x1B4E, 0x1B7F, 45), // Bali
    (0x1B80, 0x1BBF, 46), // Sund
    (0x1BC0, 0x1BF3, 47), // Batk
    (0x1BFC, 0x1BFF, 47), // Batk
    (0x1C00, 0x1C37, 48), // Lepc
    (0x1C3B, 0x1C49, 48), // Lepc
    (0x1C4D, 0x1C4F, 48), // Lepc
    (0x1C50, 0x1C7F, 49), // Olck
    (0x1C80, 0x1C8A, 4), // Cyrl
    (0x1C90, 0x1CBA, 27), // Geor
    (0x1CBD, 0x1CBF, 27), // Geor
    (0x1CC0, 0x1CC7, 46), // Sund
    (0x1D00, 0x1D25, 0), // Latn
    (0x1D26, 0x1D2A, 2), // Grek
    (0x1D2B, 0x1D2B, 4), // Cyrl
    (0x1D2C, 0x1D5C, 0), // Latn
    (0x1D5D, 0x1D61, 2), // Grek
    (0x1D62, 0x1D65, 0), // Latn
    (0x1D66, 0x1D6A, 2), // Grek
    (0x1D6B, 0x1D77, 0), // Latn
    (0x1D78, 0x1D78, 4), // Cyrl
    (0x1D79, 0x1DBE, 0), // Latn
    (0x1DBF, 0x1DBF, 2), // Grek
    (0x1E00, 0x1EFF, 0), // Latn
    (0x1F00, 0x1F15, 2), // Grek
    (0x1F18, 0x1F1D, 2), // Grek
    (0x1F20, 0x1F45, 2), // Grek
    (0x1F48, 0x1F4D, 2), // Grek
    (0x1F50, 0x1F57, 2), // Grek
    (0x1F59, 0x1F59, 2), // Grek
    (0x1F5B, 0x1F5B, 2), // Grek
    (0x1F5D, 0x1F5D, 2), // Grek
    (0x1F5F, 0x1F7D, 2), // Grek
    (0x1F80, 0x1FB4, 2), // Grek
    (0x1FB6, 0x1FC4, 2), // Grek
    (0x1FC6, 0x1FD3, 2), // Grek
    (0x1FD6, 0x1FDB, 2), // Grek
    (0x1FDD, 0x1FEF, 2), // Grek
    (0x1FF2, 0x1FF4, 2), // Grek
    (0x1FF6, 0x1FFE, 2), // Grek
    (0x2071, 0x2071, 0), // Latn
    (0x207F, 0x207F, 0), // Latn
    (0x2090, 0x209C, 0), // Latn
    (0x2126, 0x2126, 2), // Grek
    (0x212A, 0x212B, 0), // Latn
    (0x2132, 0x2132, 0), // Latn
    (0x214E, 0x214E, 0), // Latn
    (0x2160, 0x2188, 0), // Latn
    (0x2800, 0x28FF, 50), // Brai
    (0x2C00, 0x2C5F, 51), // Glag
    (0x2C60, 0x2C7F, 0), // Latn
    (0x2C80, 0x2CF3, 3), // Copt
    (0x2CF9, 0x2CFF, 3), // Copt
    (0x2D00, 0x2D25, 27), // Geor
    (0x2D27, 0x2D27, 27), // Geor
    (0x2D2D, 0x2D2D, 27), // Geor
    (0x2D30, 0x2D67, 52), // Tfng
    (0x2D6F, 0x2D70, 52), // Tfng
    (0x2D7F, 0x2D7F, 52), // Tfng
    (0x2D80, 0x2D96, 29), // Ethi
    (0x2DA0, 0x2DA6, 29), // Ethi
    (0x2DA8, 0x2DAE, 29), // Ethi
    (0x2DB0, 0x2DB6, 29), // Ethi
    (0x2DB8, 0x2DBE, 29), // Ethi
    (0x2DC0, 0x2DC6, 29), // Ethi
    (0x2DC8, 0x2DCE, 29), // Ethi
    (0x2DD0, 0x2DD6, 29), // Ethi
    (0x2DD8, 0x2DDE, 29), // Ethi
    (0x2DE0, 0x2DFF, 4), // Cyrl
    (0x2E80, 0x2E99, 53), // Hani
    (0x2E9B, 0x2EF3, 53), // Hani
    (0x2F00, 0x2FD5, 53), // Hani
    (0x3005, 0x3005, 53), // Hani
    (0x3007, 0x3007, 53), // Hani
    (0x3021, 0x3029, 53), // Hani
    (0x302E, 0x302F, 28), // Hang
    (0x3038, 0x303B, 53), // Hani
    (0x3041, 0x3096, 54), // Hira
    (0x309D, 0x309F, 54), // Hira
    (0x30A1, 0x30FA, 55), // Kana
    (0x30FD, 0x30FF, 55), // Kana
    (0x3105, 0x312F, 1), // Bopo
    (0x3131, 0x318E, 28), // Hang
    (0x31A0, 0x31BF, 1), // Bopo
    (0x31F0, 0x31FF, 55), // Kana
    (0x3200, 0x321E, 28), // Hang
    (0x3260, 0x327E, 28), // Hang
    (0x32D0, 0x32FE, 55), // Kana
    (0x3300, 0x3357, 55), // Kana
    (0x3400, 0x4DBF, 53), // Hani
    (0x4E00, 0x9FFF, 53), // Hani
    (0xA000, 0xA48C, 56), // Yiii
    (0xA490, 0xA4C6, 56), // Yiii
    (0xA4D0, 0xA4FF, 57), // Lisu
    (0xA500, 0xA62B, 58), // Vaii
    (0xA640, 0xA69F, 4), // Cyrl
    (0xA6A0, 0xA6F7, 59), // Bamu
    (0xA722, 0xA787, 0), // Latn
    (0xA78B, 0xA7DC, 0), // Latn
    (0xA7F1, 0xA7FF, 0), // Latn
    (0xA800, 0xA82C, 60), // Sylo
    (0xA840, 0xA877, 61), // Phag
    (0xA880, 0xA8C5, 62), // Saur
    (0xA8CE, 0xA8D9, 62), // Saur
    (0xA8E0, 0xA8FF, 13), // Deva
    (0xA900, 0xA92D, 63), // Kali
    (0xA92F, 0xA92F, 63), // Kali
    (0xA930, 0xA953, 64), // Rjng
    (0xA95F, 0xA95F, 64), // Rjng
    (0xA960, 0xA97C, 28), // Hang
    (0xA980, 0xA9CD, 65), // Java
    (0xA9D0, 0xA9D9, 65), // Java
    (0xA9DE, 0xA9DF, 65), // Java
    (0xA9E0, 0xA9FE, 26), // Mymr
    (0xAA00, 0xAA36, 66), // Cham
    (0xAA40, 0xAA4D, 66), // Cham
    (0xAA50, 0xAA59, 66), // Cham
    (0xAA5C, 0xAA5F, 66), // Cham
    (0xAA60, 0xAA7F, 26), // Mymr
    (0xAA80, 0xAAC2, 67), // Tavt
    (0xAADB, 0xAADF, 67), // Tavt
    (0xAAE0, 0xAAF6, 68), // Mtei
    (0xAB01, 0xAB06, 29), // Ethi
    (0xAB09, 0xAB0E, 29), // Ethi
    (0xAB11, 0xAB16, 29), // Ethi
    (0xAB20, 0xAB26, 29), // Ethi
    (0xAB28, 0xAB2E, 29), // Ethi
    (0xAB30, 0xAB5A, 0), // Latn
    (0xAB5C, 0xAB64, 0), // Latn
    (0xAB65, 0xAB65, 2), // Grek
    (0xAB66, 0xAB69, 0), // Latn
    (0xAB70, 0xABBF, 30), // Cher
    (0xABC0, 0xABED, 68), // Mtei
    (0xABF0, 0xABF9, 68), // Mtei
    (0xAC00, 0xD7A3, 28), // Hang
    (0xD7B0, 0xD7C6, 28), // Hang
    (0xD7CB, 0xD7FB, 28), // Hang
    (0xF900, 0xFA6D, 53), // Hani
    (0xFA70, 0xFAD9, 53), // Hani
    (0xFB00, 0xFB06, 0), // Latn
    (0xFB13, 0xFB17, 5), // Armn
    (0xFB1D, 0xFB36, 6), // Hebr
    (0xFB38, 0xFB3C, 6), // Hebr
    (0xFB3E, 0xFB3E, 6), // Hebr
    (0xFB40, 0xFB41, 6), // Hebr
    (0xFB43, 0xFB44, 6), // Hebr
    (0xFB46, 0xFB4F, 6), // Hebr
    (0xFB50, 0xFD3D, 7), // Arab
    (0xFD40, 0xFDCF, 7), // Arab
    (0xFDF0, 0xFDFF, 7), // Arab
    (0xFE2E, 0xFE2F, 4), // Cyrl
    (0xFE70, 0xFE74, 7), // Arab
    (0xFE76, 0xFEFC, 7), // Arab
    (0xFF21, 0xFF3A, 0), // Latn
    (0xFF41, 0xFF5A, 0), // Latn
    (0xFF66, 0xFF6F, 55), // Kana
    (0xFF71, 0xFF9D, 55), // Kana
    (0xFFA0, 0xFFBE, 28), // Hang
    (0xFFC2, 0xFFC7, 28), // Hang
    (0xFFCA, 0xFFCF, 28), // Hang
    (0xFFD2, 0xFFD7, 28), // Hang
    (0xFFDA, 0xFFDC, 28), // Hang
    (0x10000, 0x1000B, 69), // Linb
    (0x1000D, 0x10026, 69), // Linb
    (0x10028, 0x1003A, 69), // Linb
    (0x1003C, 0x1003D, 69), // Linb
    (0x1003F, 0x1004D, 69), // Linb
    (0x10050, 0x1005D, 69), // Linb
    (0x10080, 0x100FA, 69), // Linb
    (0x10140, 0x1018E, 2), // Grek
    (0x101A0, 0x101A0, 2), // Grek
    (0x10280, 0x1029C, 70), // Lyci
    (0x102A0, 0x102D0, 71), // Cari
    (0x10300, 0x10323, 72), // Ital
    (0x1032D, 0x1032F, 72), // Ital
    (0x10330, 0x1034A, 73), // Goth
    (0x10350, 0x1037A, 74), // Perm
    (0x10380, 0x1039D, 75), // Ugar
    (0x1039F, 0x1039F, 75), // Ugar
    (0x103A0, 0x103C3, 76), // Xpeo
    (0x103C8, 0x103D5, 76), // Xpeo
    (0x10400, 0x1044F, 77), // Dsrt
    (0x10450, 0x1047F, 78), // Shaw
    (0x10480, 0x1049D, 79), // Osma
    (0x104A0, 0x104A9, 79), // Osma
    (0x104B0, 0x104D3, 80), // Osge
    (0x104D8, 0x104FB, 80), // Osge
    (0x10500, 0x10527, 81), // Elba
    (0x10530, 0x10563, 82), // Aghb
    (0x1056F, 0x1056F, 82), // Aghb
    (0x10570, 0x1057A, 83), // Vith
    (0x1057C, 0x1058A, 83), // Vith
    (0x1058C, 0x10592, 83), // Vith
    (0x10594, 0x10595, 83), // Vith
    (0x10597, 0x105A1, 83), // Vith
    (0x105A3, 0x105B1, 83), // Vith
    (0x105B3, 0x105B9, 83), // Vith
    (0x105BB, 0x105BC, 83), // Vith
    (0x105C0, 0x105F3, 84), // Todr
    (0x10600, 0x10736, 85), // Lina
    (0x10740, 0x10755, 85), // Lina
    (0x10760, 0x10767, 85), // Lina
    (0x10780, 0x10785, 0), // Latn
    (0x10787, 0x107B0, 0), // Latn
    (0x107B2, 0x107BA, 0), // Latn
    (0x10800, 0x10805, 86), // Cprt
    (0x10808, 0x10808, 86), // Cprt
    (0x1080A, 0x10835, 86), // Cprt
    (0x10837, 0x10838, 86), // Cprt
    (0x1083C, 0x1083C, 86), // Cprt
    (0x1083F, 0x1083F, 86), // Cprt
    (0x10840, 0x10855, 87), // Armi
    (0x10857, 0x1085F, 87), // Armi
    (0x10860, 0x1087F, 88), // Palm
    (0x10880, 0x1089E, 89), // Nbat
    (0x108A7, 0x108AF, 89), // Nbat
    (0x108E0, 0x108F2, 90), // Hatr
    (0x108F4, 0x108F5, 90), // Hatr
    (0x108FB, 0x108FF, 90), // Hatr
    (0x10900, 0x1091B, 91), // Phnx
    (0x1091F, 0x1091F, 91), // Phnx
    (0x10920, 0x10939, 92), // Lydi
    (0x1093F, 0x1093F, 92), // Lydi
    (0x10940, 0x10959, 93), // Sidt
    (0x10980, 0x1099F, 94), // Mero
    (0x109A0, 0x109B7, 95), // Merc
    (0x109BC, 0x109CF, 95), // Merc
    (0x109D2, 0x109FF, 95), // Merc
    (0x10A00, 0x10A03, 96), // Khar
    (0x10A05, 0x10A06, 96), // Khar
    (0x10A0C, 0x10A13, 96), // Khar
    (0x10A15, 0x10A17, 96), // Khar
    (0x10A19, 0x10A35, 96), // Khar
    (0x10A38, 0x10A3A, 96), // Khar
    (0x10A3F, 0x10A48, 96), // Khar
    (0x10A50, 0x10A58, 96), // Khar
    (0x10A60, 0x10A7F, 97), // Sarb
    (0x10A80, 0x10A9F, 98), // Narb
    (0x10AC0, 0x10AE6, 99), // Mani
    (0x10AEB, 0x10AF6, 99), // Mani
    (0x10B00, 0x10B35, 100), // Avst
    (0x10B39, 0x10B3F, 100), // Avst
    (0x10B40, 0x10B55, 101), // Prti
    (0x10B58, 0x10B5F, 101), // Prti
    (0x10B60, 0x10B72, 102), // Phli
    (0x10B78, 0x10B7F, 102), // Phli
    (0x10B80, 0x10B91, 103), // Phlp
    (0x10B99, 0x10B9C, 103), // Phlp
    (0x10BA9, 0x10BAF, 103), // Phlp
    (0x10C00, 0x10C48, 104), // Orkh
    (0x10C80, 0x10CB2, 105), // Hung
    (0x10CC0, 0x10CF2, 105), // Hung
    (0x10CFA, 0x10CFF, 105), // Hung
    (0x10D00, 0x10D27, 106), // Rohg
    (0x10D30, 0x10D39, 106), // Rohg
    (0x10D40, 0x10D65, 107), // Gara
    (0x10D69, 0x10D85, 107), // Gara
    (0x10D8E, 0x10D8F, 107), // Gara
    (0x10E60, 0x10E7E, 7), // Arab
    (0x10E80, 0x10EA9, 108), // Yezi
    (0x10EAB, 0x10EAD, 108), // Yezi
    (0x10EB0, 0x10EB1, 108), // Yezi
    (0x10EC2, 0x10EC7, 7), // Arab
    (0x10ED0, 0x10ED8, 7), // Arab
    (0x10EFA, 0x10EFF, 7), // Arab
    (0x10F00, 0x10F27, 109), // Sogo
    (0x10F30, 0x10F59, 110), // Sogd
    (0x10F70, 0x10F89, 111), // Ougr
    (0x10FB0, 0x10FCB, 112), // Chrs
    (0x10FE0, 0x10FF6, 113), // Elym
    (0x11000, 0x1104D, 114), // Brah
    (0x11052, 0x11075, 114), // Brah
    (0x1107F, 0x1107F, 114), // Brah
    (0x11080, 0x110C2, 115), // Kthi
    (0x110CD, 0x110CD, 115), // Kthi
    (0x110D0, 0x110E8, 116), // Sora
    (0x110F0, 0x110F9, 116), // Sora
    (0x11100, 0x11134, 117), // Cakm
    (0x11136, 0x11147, 117), // Cakm
    (0x11150, 0x11176, 118), // Mahj
    (0x11180, 0x111DF, 119), // Shrd
    (0x111E1, 0x111F4, 22), // Sinh
    (0x11200, 0x11211, 120), // Khoj
    (0x11213, 0x11241, 120), // Khoj
    (0x11280, 0x11286, 121), // Mult
    (0x11288, 0x11288, 121), // Mult
    (0x1128A, 0x1128D, 121), // Mult
    (0x1128F, 0x1129D, 121), // Mult
    (0x1129F, 0x112A9, 121), // Mult
    (0x112B0, 0x112EA, 122), // Sind
    (0x112F0, 0x112F9, 122), // Sind
    (0x11300, 0x11303, 123), // Gran
    (0x11305, 0x1130C, 123), // Gran
    (0x1130F, 0x11310, 123), // Gran
    (0x11313, 0x11328, 123), // Gran
    (0x1132A, 0x11330, 123), // Gran
    (0x11332, 0x11333, 123), // Gran
    (0x11335, 0x11339, 123), // Gran
    (0x1133C, 0x11344, 123), // Gran
    (0x11347, 0x11348, 123), // Gran
    (0x1134B, 0x1134D, 123), // Gran
    (0x11350, 0x11350, 123), // Gran
    (0x11357, 0x11357, 123), // Gran
    (0x1135D, 0x11363, 123), // Gran
    (0x11366, 0x1136C, 123), // Gran
    (0x11370, 0x11374, 123), // Gran
    (0x11380, 0x11389, 124), // Tutg
    (0x1138B, 0x1138B, 124), // Tutg
    (0x1138E, 0x1138E, 124), // Tutg
    (0x11390, 0x113B5, 124), // Tutg
    (0x113B7, 0x113C0, 124), // Tutg
    (0x113C2, 0x113C2, 124), // Tutg
    (0x113C5, 0x113C5, 124), // Tutg
    (0x113C7, 0x113CA, 124), // Tutg
    (0x113CC, 0x113D5, 124), // Tutg
    (0x113D7, 0x113D8, 124), // Tutg
    (0x113E1, 0x113E2, 124), // Tutg
    (0x11400, 0x1145B, 125), // Newa
    (0x1145D, 0x11461, 125), // Newa
    (0x11480, 0x114C7, 126), // Tirh
    (0x114D0, 0x114D9, 126), // Tirh
    (0x11580, 0x115B5, 127), // Sidd
    (0x115B8, 0x115DD, 127), // Sidd
    (0x11600, 0x11644, 128), // Modi
    (0x11650, 0x11659, 128), // Modi
    (0x11660, 0x1166C, 39), // Mong
    (0x11680, 0x116B9, 129), // Takr
    (0x116C0, 0x116C9, 129), // Takr
    (0x116D0, 0x116E3, 26), // Mymr
    (0x11700, 0x1171A, 130), // Ahom
    (0x1171D, 0x1172B, 130), // Ahom
    (0x11730, 0x11746, 130), // Ahom
    (0x11800, 0x1183B, 131), // Dogr
    (0x118A0, 0x118F2, 132), // Wara
    (0x118FF, 0x118FF, 132), // Wara
    (0x11900, 0x11906, 133), // Diak
    (0x11909, 0x11909, 133), // Diak
    (0x1190C, 0x11913, 133), // Diak
    (0x11915, 0x11916, 133), // Diak
    (0x11918, 0x11935, 133), // Diak
    (0x11937, 0x11938, 133), // Diak
    (0x1193B, 0x11946, 133), // Diak
    (0x11950, 0x11959, 133), // Diak
    (0x119A0, 0x119A7, 134), // Nand
    (0x119AA, 0x119D7, 134), // Nand
    (0x119DA, 0x119E4, 134), // Nand
    (0x11A00, 0x11A47, 135), // Zanb
    (0x11A50, 0x11AA2, 136), // Soyo
    (0x11AB0, 0x11ABF, 31), // Cans
    (0x11AC0, 0x11AF8, 137), // Pauc
    (0x11B00, 0x11B09, 13), // Deva
    (0x11B60, 0x11B67, 119), // Shrd
    (0x11BC0, 0x11BE1, 138), // Sunu
    (0x11BF0, 0x11BF9, 138), // Sunu
    (0x11C00, 0x11C08, 139), // Bhks
    (0x11C0A, 0x11C36, 139), // Bhks
    (0x11C38, 0x11C45, 139), // Bhks
    (0x11C50, 0x11C6C, 139), // Bhks
    (0x11C70, 0x11C8F, 140), // Marc
    (0x11C92, 0x11CA7, 140), // Marc
    (0x11CA9, 0x11CB6, 140), // Marc
    (0x11D00, 0x11D06, 141), // Gonm
    (0x11D08, 0x11D09, 141), // Gonm
    (0x11D0B, 0x11D36, 141), // Gonm
    (0x11D3A, 0x11D3A, 141), // Gonm
    (0x11D3C, 0x11D3D, 141), // Gonm
    (0x11D3F, 0x11D47, 141), // Gonm
    (0x11D50, 0x11D59, 141), // Gonm
    (0x11D60, 0x11D65, 142), // Gong
    (0x11D67, 0x11D68, 142), // Gong
    (0x11D6A, 0x11D8E, 142), // Gong
    (0x11D90, 0x11D91, 142), // Gong
    (0x11D93, 0x11D98, 142), // Gong
    (0x11DA0, 0x11DA9, 142), // Gong
    (0x11DB0, 0x11DDB, 143), // Tols
    (0x11DE0, 0x11DE9, 143), // Tols
    (0x11EE0, 0x11EF8, 144), // Maka
    (0x11F00, 0x11F10, 145), // Kawi
    (0x11F12, 0x11F3A, 145), // Kawi
    (0x11F3E, 0x11F5A, 145), // Kawi
    (0x11FB0, 0x11FB0, 57), // Lisu
    (0x11FC0, 0x11FF1, 18), // Taml
    (0x11FFF, 0x11FFF, 18), // Taml
    (0x12000, 0x12399, 146), // Xsux
    (0x12400, 0x1246E, 146), // Xsux
    (0x12470, 0x12474, 146), // Xsux
    (0x12480, 0x12543, 146), // Xsux
    (0x12F90, 0x12FF2, 147), // Cpmn
    (0x13000, 0x13455, 148), // Egyp
    (0x13460, 0x143FA, 148), // Egyp
    (0x14400, 0x14646, 149), // Hluw
    (0x16100, 0x16139, 150), // Gukh
    (0x16800, 0x16A38, 59), // Bamu
    (0x16A40, 0x16A5E, 151), // Mroo
    (0x16A60, 0x16A69, 151), // Mroo
    (0x16A6E, 0x16A6F, 151), // Mroo
    (0x16A70, 0x16ABE, 152), // Tnsa
    (0x16AC0, 0x16AC9, 152), // Tnsa
    (0x16AD0, 0x16AED, 153), // Bass
    (0x16AF0, 0x16AF5, 153), // Bass
    (0x16B00, 0x16B45, 154), // Hmng
    (0x16B50, 0x16B59, 154), // Hmng
    (0x16B5B, 0x16B61, 154), // Hmng
    (0x16B63, 0x16B77, 154), // Hmng
    (0x16B7D, 0x16B8F, 154), // Hmng
    (0x16D40, 0x16D79, 155), // Krai
    (0x16E40, 0x16E9A, 156), // Medf
    (0x16EA0, 0x16EB8, 157), // Berf
    (0x16EBB, 0x16ED3, 157), // Berf
    (0x16F00, 0x16F4A, 158), // Plrd
    (0x16F4F, 0x16F87, 158), // Plrd
    (0x16F8F, 0x16F9F, 158), // Plrd
    (0x16FE0, 0x16FE0, 159), // Tang
    (0x16FE1, 0x16FE1, 160), // Nshu
    (0x16FE2, 0x16FE3, 53), // Hani
    (0x16FE4, 0x16FE4, 161), // Kits
    (0x16FF0, 0x16FF6, 53), // Hani
    (0x17000, 0x18AFF, 159), // Tang
    (0x18B00, 0x18CD5, 161), // Kits
    (0x18CFF, 0x18CFF, 161), // Kits
    (0x18D00, 0x18D1E, 159), // Tang
    (0x18D80, 0x18DF2, 159), // Tang
    (0x1AFF0, 0x1AFF3, 55), // Kana
    (0x1AFF5, 0x1AFFB, 55), // Kana
    (0x1AFFD, 0x1AFFE, 55), // Kana
    (0x1B000, 0x1B000, 55), // Kana
    (0x1B001, 0x1B11F, 54), // Hira
    (0x1B120, 0x1B122, 55), // Kana
    (0x1B132, 0x1B132, 54), // Hira
    (0x1B150, 0x1B152, 54), // Hira
    (0x1B155, 0x1B155, 55), // Kana
    (0x1B164, 0x1B167, 55), // Kana
    (0x1B170, 0x1B2FB, 160), // Nshu
    (0x1BC00, 0x1BC6A, 162), // Dupl
    (0x1BC70, 0x1BC7C, 162), // Dupl
    (0x1BC80, 0x1BC88, 162), // Dupl
    (0x1BC90, 0x1BC99, 162), // Dupl
    (0x1BC9C, 0x1BC9F, 162), // Dupl
    (0x1D200, 0x1D245, 2), // Grek
    (0x1D800, 0x1DA8B, 163), // Sgnw
    (0x1DA9B, 0x1DA9F, 163), // Sgnw
    (0x1DAA1, 0x1DAAF, 163), // Sgnw
    (0x1DF00, 0x1DF1E, 0), // Latn
    (0x1DF25, 0x1DF2A, 0), // Latn
    (0x1E000, 0x1E006, 51), // Glag
    (0x1E008, 0x1E018, 51), // Glag
    (0x1E01B, 0x1E021, 51), // Glag
    (0x1E023, 0x1E024, 51), // Glag
    (0x1E026, 0x1E02A, 51), // Glag
    (0x1E030, 0x1E06D, 4), // Cyrl
    (0x1E08F, 0x1E08F, 4), // Cyrl
    (0x1E100, 0x1E12C, 164), // Hmnp
    (0x1E130, 0x1E13D, 164), // Hmnp
    (0x1E140, 0x1E149, 164), // Hmnp
    (0x1E14E, 0x1E14F, 164), // Hmnp
    (0x1E290, 0x1E2AE, 165), // Toto
    (0x1E2C0, 0x1E2F9, 166), // Wcho
    (0x1E2FF, 0x1E2FF, 166), // Wcho
    (0x1E4D0, 0x1E4F9, 167), // Nagm
    (0x1E5D0, 0x1E5FA, 168), // Onao
    (0x1E5FF, 0x1E5FF, 168), // Onao
    (0x1E6C0, 0x1E6DE, 169), // Tayo
    (0x1E6E0, 0x1E6F5, 169), // Tayo
    (0x1E6FE, 0x1E6FF, 169), // Tayo
    (0x1E7E0, 0x1E7E6, 29), // Ethi
    (0x1E7E8, 0x1E7EB, 29), // Ethi
    (0x1E7ED, 0x1E7EE, 29), // Ethi
    (0x1E7F0, 0x1E7FE, 29), // Ethi
    (0x1E800, 0x1E8C4, 170), // Mend
    (0x1E8C7, 0x1E8D6, 170), // Mend
    (0x1E900, 0x1E94B, 171), // Adlm
    (0x1E950, 0x1E959, 171), // Adlm
    (0x1E95E, 0x1E95F, 171), // Adlm
    (0x1EE00, 0x1EE03, 7), // Arab
    (0x1EE05, 0x1EE1F, 7), // Arab
    (0x1EE21, 0x1EE22, 7), // Arab
    (0x1EE24, 0x1EE24, 7), // Arab
    (0x1EE27, 0x1EE27, 7), // Arab
    (0x1EE29, 0x1EE32, 7), // Arab
    (0x1EE34, 0x1EE37, 7), // Arab
    (0x1EE39, 0x1EE39, 7), // Arab
    (0x1EE3B, 0x1EE3B, 7), // Arab
    (0x1EE42, 0x1EE42, 7), // Arab
    (0x1EE47, 0x1EE47, 7), // Arab
    (0x1EE49, 0x1EE49, 7), // Arab
    (0x1EE4B, 0x1EE4B, 7), // Arab
    (0x1EE4D, 0x1EE4F, 7), // Arab
    (0x1EE51, 0x1EE52, 7), // Arab
    (0x1EE54, 0x1EE54, 7), // Arab
    (0x1EE57, 0x1EE57, 7), // Arab
    (0x1EE59, 0x1EE59, 7), // Arab
    (0x1EE5B, 0x1EE5B, 7), // Arab
    (0x1EE5D, 0x1EE5D, 7), // Arab
    (0x1EE5F, 0x1EE5F, 7), // Arab
    (0x1EE61, 0x1EE62, 7), // Arab
    (0x1EE64, 0x1EE64, 7), // Arab
    (0x1EE67, 0x1EE6A, 7), // Arab
    (0x1EE6C, 0x1EE72, 7), // Arab
    (0x1EE74, 0x1EE77, 7), // Arab
    (0x1EE79, 0x1EE7C, 7), // Arab
    (0x1EE7E, 0x1EE7E, 7), // Arab
    (0x1EE80, 0x1EE89, 7), // Arab
    (0x1EE8B, 0x1EE9B, 7), // Arab
    (0x1EEA1, 0x1EEA3, 7), // Arab
    (0x1EEA5, 0x1EEA9, 7), // Arab
    (0x1EEAB, 0x1EEBB, 7), // Arab
    (0x1EEF0, 0x1EEF1, 7), // Arab
    (0x1F200, 0x1F200, 54), // Hira
    (0x20000, 0x2A6DF, 53), // Hani
    (0x2A700, 0x2B81D, 53), // Hani
    (0x2B820, 0x2CEAD, 53), // Hani
    (0x2CEB0, 0x2EBE0, 53), // Hani
    (0x2EBF0, 0x2EE5D, 53), // Hani
    (0x2F800, 0x2FA1D, 53), // Hani
    (0x30000, 0x3134A, 53), // Hani
    (0x31350, 0x33479, 53), // Hani
];

/// The OpenType script tags for each script, preferred first.
///
/// A font registers its features under one of these; the pair exists
/// because OpenType revised the Indic tags and a font may use either
/// spelling. Scripts with a single tag repeat it, so a caller can
/// always try both without asking how many there are.
pub(crate) static SCRIPT_TAGS: [([u8; 4], [u8; 4]); 172] = [
    ([b'l', b'a', b't', b'n'], [b'l', b'a', b't', b'n']), // Latn
    ([b'b', b'o', b'p', b'o'], [b'b', b'o', b'p', b'o']), // Bopo
    ([b'g', b'r', b'e', b'k'], [b'g', b'r', b'e', b'k']), // Grek
    ([b'c', b'o', b'p', b't'], [b'c', b'o', b'p', b't']), // Copt
    ([b'c', b'y', b'r', b'l'], [b'c', b'y', b'r', b'l']), // Cyrl
    ([b'a', b'r', b'm', b'n'], [b'a', b'r', b'm', b'n']), // Armn
    ([b'h', b'e', b'b', b'r'], [b'h', b'e', b'b', b'r']), // Hebr
    ([b'a', b'r', b'a', b'b'], [b'a', b'r', b'a', b'b']), // Arab
    ([b's', b'y', b'r', b'c'], [b's', b'y', b'r', b'c']), // Syrc
    ([b't', b'h', b'a', b'a'], [b't', b'h', b'a', b'a']), // Thaa
    ([b'n', b'k', b'o', b' '], [b'n', b'k', b'o', b' ']), // Nkoo
    ([b's', b'a', b'm', b'r'], [b's', b'a', b'm', b'r']), // Samr
    ([b'm', b'a', b'n', b'd'], [b'm', b'a', b'n', b'd']), // Mand
    ([b'd', b'e', b'v', b'2'], [b'd', b'e', b'v', b'a']), // Deva
    ([b'b', b'n', b'g', b'2'], [b'b', b'e', b'n', b'g']), // Beng
    ([b'g', b'u', b'r', b'2'], [b'g', b'u', b'r', b'u']), // Guru
    ([b'g', b'j', b'r', b'2'], [b'g', b'u', b'j', b'r']), // Gujr
    ([b'o', b'r', b'y', b'2'], [b'o', b'r', b'y', b'a']), // Orya
    ([b't', b'm', b'l', b'2'], [b't', b'a', b'm', b'l']), // Taml
    ([b't', b'e', b'l', b'2'], [b't', b'e', b'l', b'u']), // Telu
    ([b'k', b'n', b'd', b'2'], [b'k', b'n', b'd', b'a']), // Knda
    ([b'm', b'l', b'm', b'2'], [b'm', b'l', b'y', b'm']), // Mlym
    ([b's', b'i', b'n', b'h'], [b's', b'i', b'n', b'h']), // Sinh
    ([b't', b'h', b'a', b'i'], [b't', b'h', b'a', b'i']), // Thai
    ([b'l', b'a', b'o', b' '], [b'l', b'a', b'o', b' ']), // Laoo
    ([b't', b'i', b'b', b't'], [b't', b'i', b'b', b't']), // Tibt
    ([b'm', b'y', b'm', b'2'], [b'm', b'y', b'm', b'r']), // Mymr
    ([b'g', b'e', b'o', b'r'], [b'g', b'e', b'o', b'r']), // Geor
    ([b'h', b'a', b'n', b'g'], [b'h', b'a', b'n', b'g']), // Hang
    ([b'e', b't', b'h', b'i'], [b'e', b't', b'h', b'i']), // Ethi
    ([b'c', b'h', b'e', b'r'], [b'c', b'h', b'e', b'r']), // Cher
    ([b'c', b'a', b'n', b's'], [b'c', b'a', b'n', b's']), // Cans
    ([b'o', b'g', b'a', b'm'], [b'o', b'g', b'a', b'm']), // Ogam
    ([b'r', b'u', b'n', b'r'], [b'r', b'u', b'n', b'r']), // Runr
    ([b't', b'g', b'l', b'g'], [b't', b'g', b'l', b'g']), // Tglg
    ([b'h', b'a', b'n', b'o'], [b'h', b'a', b'n', b'o']), // Hano
    ([b'b', b'u', b'h', b'd'], [b'b', b'u', b'h', b'd']), // Buhd
    ([b't', b'a', b'g', b'b'], [b't', b'a', b'g', b'b']), // Tagb
    ([b'k', b'h', b'm', b'r'], [b'k', b'h', b'm', b'r']), // Khmr
    ([b'm', b'o', b'n', b'g'], [b'm', b'o', b'n', b'g']), // Mong
    ([b'l', b'i', b'm', b'b'], [b'l', b'i', b'm', b'b']), // Limb
    ([b't', b'a', b'l', b'e'], [b't', b'a', b'l', b'e']), // Tale
    ([b't', b'a', b'l', b'u'], [b't', b'a', b'l', b'u']), // Talu
    ([b'b', b'u', b'g', b'i'], [b'b', b'u', b'g', b'i']), // Bugi
    ([b'l', b'a', b'n', b'a'], [b'l', b'a', b'n', b'a']), // Lana
    ([b'b', b'a', b'l', b'i'], [b'b', b'a', b'l', b'i']), // Bali
    ([b's', b'u', b'n', b'd'], [b's', b'u', b'n', b'd']), // Sund
    ([b'b', b'a', b't', b'k'], [b'b', b'a', b't', b'k']), // Batk
    ([b'l', b'e', b'p', b'c'], [b'l', b'e', b'p', b'c']), // Lepc
    ([b'o', b'l', b'c', b'k'], [b'o', b'l', b'c', b'k']), // Olck
    ([b'b', b'r', b'a', b'i'], [b'b', b'r', b'a', b'i']), // Brai
    ([b'g', b'l', b'a', b'g'], [b'g', b'l', b'a', b'g']), // Glag
    ([b't', b'f', b'n', b'g'], [b't', b'f', b'n', b'g']), // Tfng
    ([b'h', b'a', b'n', b'i'], [b'h', b'a', b'n', b'i']), // Hani
    ([b'k', b'a', b'n', b'a'], [b'k', b'a', b'n', b'a']), // Hira
    ([b'k', b'a', b'n', b'a'], [b'k', b'a', b'n', b'a']), // Kana
    ([b'y', b'i', b' ', b' '], [b'y', b'i', b' ', b' ']), // Yiii
    ([b'l', b'i', b's', b'u'], [b'l', b'i', b's', b'u']), // Lisu
    ([b'v', b'a', b'i', b' '], [b'v', b'a', b'i', b' ']), // Vaii
    ([b'b', b'a', b'm', b'u'], [b'b', b'a', b'm', b'u']), // Bamu
    ([b's', b'y', b'l', b'o'], [b's', b'y', b'l', b'o']), // Sylo
    ([b'p', b'h', b'a', b'g'], [b'p', b'h', b'a', b'g']), // Phag
    ([b's', b'a', b'u', b'r'], [b's', b'a', b'u', b'r']), // Saur
    ([b'k', b'a', b'l', b'i'], [b'k', b'a', b'l', b'i']), // Kali
    ([b'r', b'j', b'n', b'g'], [b'r', b'j', b'n', b'g']), // Rjng
    ([b'j', b'a', b'v', b'a'], [b'j', b'a', b'v', b'a']), // Java
    ([b'c', b'h', b'a', b'm'], [b'c', b'h', b'a', b'm']), // Cham
    ([b't', b'a', b'v', b't'], [b't', b'a', b'v', b't']), // Tavt
    ([b'm', b't', b'e', b'i'], [b'm', b't', b'e', b'i']), // Mtei
    ([b'l', b'i', b'n', b'b'], [b'l', b'i', b'n', b'b']), // Linb
    ([b'l', b'y', b'c', b'i'], [b'l', b'y', b'c', b'i']), // Lyci
    ([b'c', b'a', b'r', b'i'], [b'c', b'a', b'r', b'i']), // Cari
    ([b'i', b't', b'a', b'l'], [b'i', b't', b'a', b'l']), // Ital
    ([b'g', b'o', b't', b'h'], [b'g', b'o', b't', b'h']), // Goth
    ([b'p', b'e', b'r', b'm'], [b'p', b'e', b'r', b'm']), // Perm
    ([b'u', b'g', b'a', b'r'], [b'u', b'g', b'a', b'r']), // Ugar
    ([b'x', b'p', b'e', b'o'], [b'x', b'p', b'e', b'o']), // Xpeo
    ([b'd', b's', b'r', b't'], [b'd', b's', b'r', b't']), // Dsrt
    ([b's', b'h', b'a', b'w'], [b's', b'h', b'a', b'w']), // Shaw
    ([b'o', b's', b'm', b'a'], [b'o', b's', b'm', b'a']), // Osma
    ([b'o', b's', b'g', b'e'], [b'o', b's', b'g', b'e']), // Osge
    ([b'e', b'l', b'b', b'a'], [b'e', b'l', b'b', b'a']), // Elba
    ([b'a', b'g', b'h', b'b'], [b'a', b'g', b'h', b'b']), // Aghb
    ([b'v', b'i', b't', b'h'], [b'v', b'i', b't', b'h']), // Vith
    ([b't', b'o', b'd', b'r'], [b't', b'o', b'd', b'r']), // Todr
    ([b'l', b'i', b'n', b'a'], [b'l', b'i', b'n', b'a']), // Lina
    ([b'c', b'p', b'r', b't'], [b'c', b'p', b'r', b't']), // Cprt
    ([b'a', b'r', b'm', b'i'], [b'a', b'r', b'm', b'i']), // Armi
    ([b'p', b'a', b'l', b'm'], [b'p', b'a', b'l', b'm']), // Palm
    ([b'n', b'b', b'a', b't'], [b'n', b'b', b'a', b't']), // Nbat
    ([b'h', b'a', b't', b'r'], [b'h', b'a', b't', b'r']), // Hatr
    ([b'p', b'h', b'n', b'x'], [b'p', b'h', b'n', b'x']), // Phnx
    ([b'l', b'y', b'd', b'i'], [b'l', b'y', b'd', b'i']), // Lydi
    ([b's', b'i', b'd', b't'], [b's', b'i', b'd', b't']), // Sidt
    ([b'm', b'e', b'r', b'o'], [b'm', b'e', b'r', b'o']), // Mero
    ([b'm', b'e', b'r', b'c'], [b'm', b'e', b'r', b'c']), // Merc
    ([b'k', b'h', b'a', b'r'], [b'k', b'h', b'a', b'r']), // Khar
    ([b's', b'a', b'r', b'b'], [b's', b'a', b'r', b'b']), // Sarb
    ([b'n', b'a', b'r', b'b'], [b'n', b'a', b'r', b'b']), // Narb
    ([b'm', b'a', b'n', b'i'], [b'm', b'a', b'n', b'i']), // Mani
    ([b'a', b'v', b's', b't'], [b'a', b'v', b's', b't']), // Avst
    ([b'p', b'r', b't', b'i'], [b'p', b'r', b't', b'i']), // Prti
    ([b'p', b'h', b'l', b'i'], [b'p', b'h', b'l', b'i']), // Phli
    ([b'p', b'h', b'l', b'p'], [b'p', b'h', b'l', b'p']), // Phlp
    ([b'o', b'r', b'k', b'h'], [b'o', b'r', b'k', b'h']), // Orkh
    ([b'h', b'u', b'n', b'g'], [b'h', b'u', b'n', b'g']), // Hung
    ([b'r', b'o', b'h', b'g'], [b'r', b'o', b'h', b'g']), // Rohg
    ([b'g', b'a', b'r', b'a'], [b'g', b'a', b'r', b'a']), // Gara
    ([b'y', b'e', b'z', b'i'], [b'y', b'e', b'z', b'i']), // Yezi
    ([b's', b'o', b'g', b'o'], [b's', b'o', b'g', b'o']), // Sogo
    ([b's', b'o', b'g', b'd'], [b's', b'o', b'g', b'd']), // Sogd
    ([b'o', b'u', b'g', b'r'], [b'o', b'u', b'g', b'r']), // Ougr
    ([b'c', b'h', b'r', b's'], [b'c', b'h', b'r', b's']), // Chrs
    ([b'e', b'l', b'y', b'm'], [b'e', b'l', b'y', b'm']), // Elym
    ([b'b', b'r', b'a', b'h'], [b'b', b'r', b'a', b'h']), // Brah
    ([b'k', b't', b'h', b'i'], [b'k', b't', b'h', b'i']), // Kthi
    ([b's', b'o', b'r', b'a'], [b's', b'o', b'r', b'a']), // Sora
    ([b'c', b'a', b'k', b'm'], [b'c', b'a', b'k', b'm']), // Cakm
    ([b'm', b'a', b'h', b'j'], [b'm', b'a', b'h', b'j']), // Mahj
    ([b's', b'h', b'r', b'd'], [b's', b'h', b'r', b'd']), // Shrd
    ([b'k', b'h', b'o', b'j'], [b'k', b'h', b'o', b'j']), // Khoj
    ([b'm', b'u', b'l', b't'], [b'm', b'u', b'l', b't']), // Mult
    ([b's', b'i', b'n', b'd'], [b's', b'i', b'n', b'd']), // Sind
    ([b'g', b'r', b'a', b'n'], [b'g', b'r', b'a', b'n']), // Gran
    ([b't', b'u', b't', b'g'], [b't', b'u', b't', b'g']), // Tutg
    ([b'n', b'e', b'w', b'a'], [b'n', b'e', b'w', b'a']), // Newa
    ([b't', b'i', b'r', b'h'], [b't', b'i', b'r', b'h']), // Tirh
    ([b's', b'i', b'd', b'd'], [b's', b'i', b'd', b'd']), // Sidd
    ([b'm', b'o', b'd', b'i'], [b'm', b'o', b'd', b'i']), // Modi
    ([b't', b'a', b'k', b'r'], [b't', b'a', b'k', b'r']), // Takr
    ([b'a', b'h', b'o', b'm'], [b'a', b'h', b'o', b'm']), // Ahom
    ([b'd', b'o', b'g', b'r'], [b'd', b'o', b'g', b'r']), // Dogr
    ([b'w', b'a', b'r', b'a'], [b'w', b'a', b'r', b'a']), // Wara
    ([b'd', b'i', b'a', b'k'], [b'd', b'i', b'a', b'k']), // Diak
    ([b'n', b'a', b'n', b'd'], [b'n', b'a', b'n', b'd']), // Nand
    ([b'z', b'a', b'n', b'b'], [b'z', b'a', b'n', b'b']), // Zanb
    ([b's', b'o', b'y', b'o'], [b's', b'o', b'y', b'o']), // Soyo
    ([b'p', b'a', b'u', b'c'], [b'p', b'a', b'u', b'c']), // Pauc
    ([b's', b'u', b'n', b'u'], [b's', b'u', b'n', b'u']), // Sunu
    ([b'b', b'h', b'k', b's'], [b'b', b'h', b'k', b's']), // Bhks
    ([b'm', b'a', b'r', b'c'], [b'm', b'a', b'r', b'c']), // Marc
    ([b'g', b'o', b'n', b'm'], [b'g', b'o', b'n', b'm']), // Gonm
    ([b'g', b'o', b'n', b'g'], [b'g', b'o', b'n', b'g']), // Gong
    ([b't', b'o', b'l', b's'], [b't', b'o', b'l', b's']), // Tols
    ([b'm', b'a', b'k', b'a'], [b'm', b'a', b'k', b'a']), // Maka
    ([b'k', b'a', b'w', b'i'], [b'k', b'a', b'w', b'i']), // Kawi
    ([b'x', b's', b'u', b'x'], [b'x', b's', b'u', b'x']), // Xsux
    ([b'c', b'p', b'm', b'n'], [b'c', b'p', b'm', b'n']), // Cpmn
    ([b'e', b'g', b'y', b'p'], [b'e', b'g', b'y', b'p']), // Egyp
    ([b'h', b'l', b'u', b'w'], [b'h', b'l', b'u', b'w']), // Hluw
    ([b'g', b'u', b'k', b'h'], [b'g', b'u', b'k', b'h']), // Gukh
    ([b'm', b'r', b'o', b'o'], [b'm', b'r', b'o', b'o']), // Mroo
    ([b't', b'n', b's', b'a'], [b't', b'n', b's', b'a']), // Tnsa
    ([b'b', b'a', b's', b's'], [b'b', b'a', b's', b's']), // Bass
    ([b'h', b'm', b'n', b'g'], [b'h', b'm', b'n', b'g']), // Hmng
    ([b'k', b'r', b'a', b'i'], [b'k', b'r', b'a', b'i']), // Krai
    ([b'm', b'e', b'd', b'f'], [b'm', b'e', b'd', b'f']), // Medf
    ([b'b', b'e', b'r', b'f'], [b'b', b'e', b'r', b'f']), // Berf
    ([b'p', b'l', b'r', b'd'], [b'p', b'l', b'r', b'd']), // Plrd
    ([b't', b'a', b'n', b'g'], [b't', b'a', b'n', b'g']), // Tang
    ([b'n', b's', b'h', b'u'], [b'n', b's', b'h', b'u']), // Nshu
    ([b'k', b'i', b't', b's'], [b'k', b'i', b't', b's']), // Kits
    ([b'd', b'u', b'p', b'l'], [b'd', b'u', b'p', b'l']), // Dupl
    ([b's', b'g', b'n', b'w'], [b's', b'g', b'n', b'w']), // Sgnw
    ([b'h', b'm', b'n', b'p'], [b'h', b'm', b'n', b'p']), // Hmnp
    ([b't', b'o', b't', b'o'], [b't', b'o', b't', b'o']), // Toto
    ([b'w', b'c', b'h', b'o'], [b'w', b'c', b'h', b'o']), // Wcho
    ([b'n', b'a', b'g', b'm'], [b'n', b'a', b'g', b'm']), // Nagm
    ([b'o', b'n', b'a', b'o'], [b'o', b'n', b'a', b'o']), // Onao
    ([b't', b'a', b'y', b'o'], [b't', b'a', b'y', b'o']), // Tayo
    ([b'm', b'e', b'n', b'd'], [b'm', b'e', b'n', b'd']), // Mend
    ([b'a', b'd', b'l', b'm'], [b'a', b'd', b'l', b'm']), // Adlm
];
