//! The Universal Shaping Engine.
//!
//! One shaper for eighty-eight scripts — everything from Balinese to Egyptian
//! hieroglyphs — and the last of the five this crate has. Where
//! [`indic_shape`](crate::indic_shape), [`khmer`](crate::khmer) and
//! [`myanmar`](crate::myanmar) each encode one writing system's rules, USE
//! encodes the *shape* those rules share and leaves the particulars to the
//! font: a cluster is a base with modifiers hung on it, the font's features
//! decide what each modifier turns into, and the engine's own contribution is
//! to say where a cluster ends, which glyphs a repha and a pre-base vowel move
//! past, and which of the four positional forms a cluster takes.
//!
//! Microsoft's specification is at
//! <https://learn.microsoft.com/en-us/typography/script-development/use>; this
//! follows HarfBuzz's `hb-ot-shaper-use.cc` and `hb-ot-shaper-use-machine.rl`,
//! which is the implementation everything is measured against.
//!
//! # The three things that make it unlike the other three shapers
//!
//! * **The cluster machine reads a filtered view of the run.** Indic, Khmer and
//!   Myanmar hand their machines every glyph. USE hides two kinds first — the
//!   `CGJ` category, which is the combining grapheme joiner, ZWJ and the
//!   variation selectors, and a ZWNJ whose next visible glyph is a combining
//!   mark — so that neither can cut a cluster in half. The hidden glyphs are
//!   not *removed*: they stay in the run and belong to whichever cluster the
//!   machine was in when it stepped over them. See [`clusters`], which is
//!   where the two consequences of that are written out.
//! * **The font decides what a repha is.** Indic recognises a reph by spelling
//!   (`Ra` + virama) and Myanmar a kinzi likewise. USE runs the font's `rphf`
//!   feature *alone*, as a stage of its own, and then asks which glyph the font
//!   rewrote — see [`record_rphf`]. `pref` is treated the same way, and a glyph
//!   it rewrote becomes a pre-base vowel. Neither question can be answered
//!   without having run the lookup, which is why [`SubGlyph::substituted`]
//!   exists.
//! * **The positional forms are per *cluster*, not per letter.** For most USE
//!   scripts `isol`/`init`/`medi`/`fina` do not mean cursive joining at all:
//!   [`setup_topographical_masks`] hands them out by looking at whether the
//!   *previous cluster* joined, which is a much coarser question than the
//!   Unicode `Joining_Type` that [`joining`](crate::joining) answers. The
//!   eleven USE scripts that really do join cursively are the exception and
//!   take the ordinary path — see [`has_arabic_joining`].
//!
//! # What is not here
//!
//! * **Vowel constraints.** HarfBuzz's `preprocess_text_use` is
//!   `_hb_preprocess_text_vowel_constraints`, which inserts a dotted circle
//!   between a consonant and an independent vowel that Unicode says may not
//!   follow it. That is a table of its own and a separate pass; this crate has
//!   neither, for USE or for Indic.
//! * **`compose_use` as a hook of this shaper's own.** HarfBuzz refuses to
//!   recompose a split matra during normalization by declining any composition
//!   whose first character is a mark, and hangs that refusal off each shaper's
//!   vtable. The rule *is* implemented, but not here: it lives in
//!   [`norm`](crate::norm) as `SplitVowels::LeaveApart`, one switch the drawing
//!   path always sets and the text path never does, rather than a copy per
//!   shaper. It is safe as a global because the 47 characters it can affect all
//!   belong to Indic or USE scripts — `norm`'s
//!   `only_indic_and_use_compose_from_a_mark` is what fails if a table
//!   regeneration changes that. See `design-decisions.md` §439. Khmer's
//!   [`split_matras`](crate::khmer::split_matras) is the same rule for the
//!   decompositions Unicode does *not* record.
//!
//! # The categories and the machine
//!
//! [`Category`] and the ranges it is read from are generated by
//! `tools/gen_universal_table.py` from Unicode and the `ms-use` override files
//! HarfBuzz vendors, and checked against HarfBuzz's own packed table code point
//! by code point. [`Cluster`] and the DFA that produces it are generated by
//! `tools/gen_universal_machine.py` from the ten regular expressions of the
//! ragel grammar. Neither is transcribed by hand, and neither should be edited.

use alloc::vec::Vec;

use crate::gsub::{ALL_FEATURES, Staging, SubGlyph, Substitutions, feature_bit, feature_bits};
use crate::lang::Lang;
use crate::norm;
use crate::script::ScriptTags;
use crate::syllabic;
use crate::universal_machine::{ACCEPTS, TRANSITIONS};
use crate::universal_tables::USE_RANGES;

/// What the Universal Shaping Engine makes of one character.
///
/// The dense order of the variants is the column order of
/// [`TRANSITIONS`](crate::universal_machine::TRANSITIONS): a row is indexed by
/// `category as usize`, so reordering this enum silently mis-scans every run
/// until the machine is regenerated. `tools/gen_universal_machine.py` takes the
/// order from the same dict `tools/gen_universal_table.py` writes the ranges
/// from, so regenerating both together is enough to keep them in step —
/// `the_machine_has_a_column_for_every_category` is what fails if they drift.
///
/// The number in each doc comment is HarfBuzz's, from
/// `hb-ot-shaper-use-machine.rl`. They are *not* the discriminants: HarfBuzz's
/// run to 56 with thirteen gaps, which would cost thirteen dead columns in
/// every row of the table. They are recorded so that a category read out of a
/// HarfBuzz trace can be found here.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub(crate) enum Category {
    /// `O`, 0. Anything the engine has no rule about — most of Unicode.
    /// Heads a symbol cluster, so it is not simply ignored.
    #[default]
    Other = 0,
    /// `B`, 1. A base: the consonant or independent vowel a cluster is built
    /// on.
    Base = 1,
    /// `N`, 4. A digit, which heads a numeral cluster.
    BaseNum = 2,
    /// `GB`, 5. A generic base — a space, a hyphen, a dotted circle: not a
    /// letter, but something a mark may legitimately be hung on.
    BaseOther = 3,
    /// `CGJ`, 6. A combining grapheme joiner, a ZWJ or a variation selector:
    /// hidden from the cluster machine entirely. See [`clusters`].
    Cgj = 4,
    /// `SUB`, 11. A subjoined consonant written as one character, rather than
    /// as a virama followed by a consonant.
    ConsSub = 5,
    /// `H`, 12. A visible virama, which kills the inherent vowel.
    Halant = 6,
    /// `HN`, 13. A number joiner, which binds two digits into one numeral.
    HalantNum = 7,
    /// `ZWNJ`, 14. Zero-width non-joiner. Hidden from the cluster machine when
    /// what follows it is a combining mark. See [`clusters`].
    NonJoiner = 8,
    /// `WJ`, 16. Word joiner.
    WordJoiner = 9,
    /// `R`, 18. A repha: written first and drawn late. Either the character
    /// said so or the font's `rphf` did — see [`record_rphf`].
    Repha = 10,
    /// `VPre`, 22. A dependent vowel drawn to the left of the cluster, and so
    /// moved to the front of it. See [`reorder_cluster`].
    VowelPre = 11,
    /// `VMPre`, 23. A vowel modifier drawn to the left, moved with the vowels.
    VowelModPre = 12,
    /// `FAbv`, 24. A final consonant drawn above.
    ConsFinalAbove = 13,
    /// `FBlw`, 25. A final consonant drawn below.
    ConsFinalBelow = 14,
    /// `FPst`, 26. A final consonant drawn after.
    ConsFinalPost = 15,
    /// `MAbv`, 27. A medial consonant drawn above.
    ConsMedAbove = 16,
    /// `MBlw`, 28. A medial consonant drawn below.
    ConsMedBelow = 17,
    /// `MPst`, 29. A medial consonant drawn after.
    ConsMedPost = 18,
    /// `MPre`, 30. A medial consonant drawn before.
    ConsMedPre = 19,
    /// `CMAbv`, 31. A consonant modifier drawn above — a nukta and its kin.
    ConsModAbove = 20,
    /// `CMBlw`, 32. A consonant modifier drawn below.
    ConsModBelow = 21,
    /// `VAbv`, 33. A dependent vowel drawn above.
    VowelAbove = 22,
    /// `VBlw`, 34. A dependent vowel drawn below.
    VowelBelow = 23,
    /// `VPst`, 35. A dependent vowel drawn after.
    VowelPost = 24,
    /// `VMAbv`, 37. A vowel modifier drawn above.
    VowelModAbove = 25,
    /// `VMBlw`, 38. A vowel modifier drawn below.
    VowelModBelow = 26,
    /// `VMPst`, 39. A vowel modifier drawn after.
    VowelModPost = 27,
    /// `SMAbv`, 41. A symbol modifier drawn above, which makes a symbol
    /// cluster.
    SymModAbove = 28,
    /// `SMBlw`, 42. A symbol modifier drawn below.
    ///
    /// No character carries it. Upstream's table `#define`s `SMBlw` and then
    /// `#undef`s it without ever having used it, so nothing in `USE_RANGES`
    /// names this variant either. It has to exist regardless: the machine's
    /// columns are these discriminants, and dropping it would shift every
    /// category after it one column left.
    #[allow(dead_code)]
    SymModBelow = 29,
    /// `CS`, 43. A consonant with a stacker built in, which may head a cluster
    /// the way a repha does.
    ConsWithStacker = 30,
    /// `IS`, 44. An invisible stacker: a virama that stacks without being
    /// drawn. Terminates a cluster.
    InvisibleStacker = 31,
    /// `FMAbv`, 45. A final-consonant modifier drawn above.
    ConsFinalModAbove = 32,
    /// `FMBlw`, 46. A final-consonant modifier drawn below.
    ConsFinalModBelow = 33,
    /// `FMPst`, 47. A final-consonant modifier with nowhere in particular to
    /// go. Alone it is a cluster of its own, and one that earns no dotted
    /// circle — the grammar lists it between the well-formed rules and the
    /// broken one for exactly that reason.
    ConsFinalModPost = 34,
    /// `Sk`, 48. A sakot, which joins two Tai Tham syllables and terminates a
    /// cluster.
    Sakot = 35,
    /// `G`, 49. An Egyptian hieroglyph.
    Hieroglyph = 36,
    /// `J`, 50. A hieroglyph joiner.
    HieroglyphJoiner = 37,
    /// `SB`, 51. The start of a hieroglyph segment — a bracket.
    HieroglyphSegBegin = 38,
    /// `SE`, 52. The end of one.
    HieroglyphSegEnd = 39,
    /// `HVM`, 53. A character that is a halant in some contexts and a vowel
    /// modifier in others, which is why the grammar admits it in both places.
    HalantOrVowelModifier = 40,
    /// `HM`, 54. A hieroglyph modifier.
    HieroglyphMod = 41,
    /// `HR`, 55. A hieroglyph mirror control.
    HieroglyphMirror = 42,
    /// `RK`, 56. A reordering killer, which terminates a cluster the way an
    /// invisible stacker does.
    ReorderingKiller = 43,
}

impl Category {
    /// How many there are, which is how wide a row of the machine is.
    pub(crate) const COUNT: usize = 44;

    /// The category of `ch`, or [`Other`](Self::Other) if the table has no
    /// range covering it — which is the answer for all but about fifteen
    /// thousand code points.
    #[must_use]
    pub(crate) fn of(ch: char) -> Self {
        let cp = ch as u32;
        // The ranges are disjoint and sorted, so the last one starting at or
        // before `cp` is the only one that can contain it.
        let Some(i) = USE_RANGES
            .partition_point(|&(lo, _, _)| lo <= cp)
            .checked_sub(1)
        else {
            return Self::Other;
        };
        match USE_RANGES.get(i) {
            Some(&(_, hi, category)) if cp <= hi => category,
            _ => Self::Other,
        }
    }
}

/// Everything the engine needs to know about one character, on the glyph it
/// became.
///
/// Two facts and not one, because the cluster machine asks two questions and
/// only the first has a [`Category`] for an answer. The second — "is the next
/// visible thing a combining mark?" — is the Unicode general category `Mn`,
/// `Mc` or `Me`, and it is *not* recoverable from the USE category: five
/// categories contain both marks and non-marks, `Other` most of all. So the
/// bit rides along. See [`clusters`].
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(crate) struct Char {
    /// What it is.
    pub(crate) category: Category,
    /// Whether the character was a combining mark of any kind:
    /// `HB_UNICODE_GENERAL_CATEGORY_IS_MARK`, which is
    /// [`norm::is_any_mark`](crate::norm::is_any_mark) and *not*
    /// [`SubGlyph::mark`], whose question is about advance widths and whose
    /// answer is conditional on the face.
    pub(crate) mark: bool,
}

impl Char {
    /// Not USE: what every glyph of every run this shaper does not touch
    /// carries.
    pub(crate) const DEFAULT: Self = Self {
        category: Category::Other,
        mark: false,
    };

    /// What `ch` contributes.
    #[must_use]
    pub(crate) fn of(ch: char) -> Self {
        Self {
            category: Category::of(ch),
            mark: norm::is_any_mark(ch),
        }
    }
}

/// Which of the grammar's ten rules matched a cluster.
///
/// Nine kinds for ten rules: `other` and the lone `FMPst` rule both produce
/// [`NonCluster`](Self::NonCluster), which is HarfBuzz's arrangement and the
/// point of it is that a stray final-consonant modifier gets no dotted circle.
// `NonCluster` repeats the type's name, which the lint dislikes. It is
// upstream's `use_non_cluster` and it is the *negation* of the type, not a
// variant of it — the alternatives ("Lone", "None") both read as "no cluster
// matched" when what happened is that a cluster of exactly this kind did.
#[allow(clippy::enum_variant_names)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Cluster {
    /// Ended by an invisible stacker or a reordering killer.
    ViramaTerminated,
    /// Ended by a sakot, which joins it to the syllable that follows.
    SakotTerminated,
    /// The ordinary case: a base with modifiers, vowels and finals on it.
    Standard,
    /// Digits bound by number joiners, ending in a joiner.
    NumberJoinerTerminated,
    /// Digits bound by number joiners, ending in a digit.
    Numeral,
    /// Something that is not a letter carrying a symbol modifier.
    Symbol,
    /// Egyptian hieroglyphs, which have a grammar of their own and never join.
    Hieroglyph,
    /// Not a well-formed cluster: marks with no base to hang on. The only kind
    /// that earns a dotted circle.
    Broken,
    /// One character of anything else, and the lone `FMPst` rule. Never
    /// reordered, never given a circle, and never joined to.
    NonCluster,
}

impl Cluster {
    /// This kind as the low nibble of a [`SubGlyph::syllable`] byte.
    ///
    /// The numbering is HarfBuzz's `use_syllable_type_t`, so a value read out
    /// of one of its traces means the same thing here — and so that the leading
    /// unstamped glyphs [`clusters`] has to account for read back as the kind
    /// HarfBuzz's zero gives them.
    #[must_use]
    pub(crate) fn code(self) -> u8 {
        match self {
            Self::ViramaTerminated => 0,
            Self::SakotTerminated => 1,
            Self::Standard => 2,
            Self::NumberJoinerTerminated => 3,
            Self::Numeral => 4,
            Self::Symbol => 5,
            Self::Hieroglyph => 6,
            Self::Broken => 7,
            Self::NonCluster => 8,
        }
    }

    /// The kind [`code`](Self::code) writes as `code`'s low nibble.
    ///
    /// The seven nibbles no kind uses read back as
    /// [`NonCluster`](Self::NonCluster), the kind that does nothing.
    #[must_use]
    pub(crate) fn from_code(code: u8) -> Self {
        match code & 0x0F {
            0 => Self::ViramaTerminated,
            1 => Self::SakotTerminated,
            2 => Self::Standard,
            3 => Self::NumberJoinerTerminated,
            4 => Self::Numeral,
            5 => Self::Symbol,
            6 => Self::Hieroglyph,
            7 => Self::Broken,
            _ => Self::NonCluster,
        }
    }
}

/// The OpenType script tags the Universal Shaping Engine shapes, sorted.
///
/// [`fallback::COMPLEX_SCRIPTS`](crate::fallback::COMPLEX_SCRIPTS) minus the
/// thirteen tags that reach one of the other four complex shapers or the Thai
/// one: the nine Indic `*2` tags, `khmr`, `mym2`, `thai` and `lao `. That is
/// the whole derivation, and
/// `the_engine_takes_every_complex_script_no_other_shaper_claims` is the test
/// that keeps it true as scripts are added.
///
/// Two entries are worth pointing at. **`sinh`** is here and not with the Indic
/// nine: HarfBuzz's `hb_ot_shaper_categorize` sends Sinhala to USE outright,
/// with no `*3`-tag condition, which is why Sinhala text is shaped by a
/// different engine from its neighbours. **`egyp`** is here because the
/// hieroglyph grammar lives in this machine — quadrat layout is USE's job.
///
/// One divergence from HarfBuzz, and it cannot arise: HarfBuzz also sends a
/// *Devanagari* (or Bengali, or …) run to USE when the tag its `GSUB` was taken
/// from ends in `'3'`. No `*3` tag is in this crate's fallback chain, so no
/// face can be chosen under one. The same note is on
/// [`fallback::shaped_as_default`](crate::fallback::shaped_as_default).
static USE_SCRIPTS: [[u8; 4]; 88] = [
    *b"adlm", *b"ahom", *b"bali", *b"batk", *b"berf", *b"bhks", *b"brah", *b"bugi", *b"buhd",
    *b"cakm", *b"cham", *b"chrs", *b"cpmn", *b"diak", *b"dogr", *b"dupl", *b"egyp", *b"elym",
    *b"gara", *b"gong", *b"gonm", *b"gran", *b"gukh", *b"hano", *b"hmng", *b"hmnp", *b"java",
    *b"kali", *b"kawi", *b"khar", *b"khoj", *b"kits", *b"krai", *b"kthi", *b"lana", *b"lepc",
    *b"limb", *b"mahj", *b"maka", *b"mand", *b"mani", *b"marc", *b"medf", *b"modi", *b"mong",
    *b"mtei", *b"mult", *b"nagm", *b"nand", *b"newa", *b"nko ", *b"onao", *b"ougr", *b"phag",
    *b"phlp", *b"plrd", *b"rjng", *b"rohg", *b"saur", *b"shrd", *b"sidd", *b"sidt", *b"sind",
    *b"sinh", *b"sogd", *b"sogo", *b"soyo", *b"sund", *b"sunu", *b"sylo", *b"tagb", *b"takr",
    *b"tale", *b"tavt", *b"tayo", *b"tfng", *b"tglg", *b"tibt", *b"tirh", *b"tnsa", *b"todr",
    *b"tols", *b"toto", *b"tutg", *b"vith", *b"wcho", *b"yezi", *b"zanb",
];

/// The USE scripts whose letters really do join cursively, sorted.
///
/// HarfBuzz's `has_arabic_joining` list minus Arabic and Syriac, which reach
/// the Arabic shaper rather than this one. For these eleven the engine builds
/// an *Arabic* shaping plan and lets it hand out `isol`/`init`/`medi`/`fina`
/// per letter from the Unicode `Joining_Type`, then skips
/// [`setup_topographical_masks`] entirely.
///
/// This crate has no separate plan to build: [`joining::forms`](crate::joining)
/// already runs over every piece of every run, script-independently, because a
/// letter's joining type is a property of the character and not of the writing
/// system around it. So the four form masks are on the glyphs before this
/// shaper is called, and all that is left to do is not overwrite them.
#[must_use]
pub(crate) fn has_arabic_joining(tags: Option<ScriptTags>) -> bool {
    static JOINING: [[u8; 4]; 11] = [
        *b"adlm", *b"chrs", *b"mand", *b"mani", *b"mong", *b"nko ", *b"ougr", *b"phag", *b"phlp",
        *b"rohg", *b"sogd",
    ];
    tags.is_some_and(|tags| JOINING.binary_search(&tags.preferred).is_ok())
}

/// Whether a run of `tags` is shaped by the Universal Shaping Engine.
///
/// The script's half of the question only. The face may still call the shaper
/// off by filing its features under `DFLT` or `latn`, which is
/// [`fallback::shaped_as_default`](crate::fallback::shaped_as_default) and is
/// checked at the dispatch point, exactly as it is for Myanmar and Indic.
#[must_use]
pub(crate) fn shapes(tags: Option<ScriptTags>) -> bool {
    tags.is_some_and(|tags| USE_SCRIPTS.binary_search(&tags.preferred).is_ok())
}

/// Cut `glyphs` into clusters, appending `(start, end, kind)` to `out`.
///
/// The same longest-match scan the other three shapers use, over the same kind
/// of generated DFA — but run against a *filtered* view of the run, which is
/// USE's alone and is the reason this cannot simply take a slice of categories.
/// Two kinds of glyph are hidden from the machine:
///
/// 1. **`CGJ`** — the combining grapheme joiner, ZWJ, and the variation
///    selectors. A ZWJ between a consonant and a virama asks the font for a
///    conjunct; letting it reach the machine would end the cluster at it.
/// 2. **A `ZWNJ` whose next visible glyph is a combining mark.** A ZWNJ is
///    normally a cluster *terminator* — every rule of the grammar ends with an
///    optional one. Before a mark it is not asking for a break, it is asking
///    the font not to form a ligature, and breaking there would strand the mark
///    in a cluster of its own. "Combining mark" is the Unicode general
///    category, all three of `Mn`, `Mc` and `Me`, which is why [`Char`] carries
///    a bit for it.
///
/// Hidden is not removed. The glyphs stay in the run and the ranges are in run
/// coordinates, which has two consequences, both HarfBuzz's:
///
/// * **A hidden glyph joins the cluster before it.** A range ends where the
///   next *visible* glyph starts, so anything filtered out in between is swept
///   up by the cluster it follows.
/// * **Hidden glyphs at the very start of the run belong to no cluster at
///   all.** HarfBuzz never stamps them, leaving their syllable byte at zero,
///   whose low nibble is [`Cluster::ViramaTerminated`] and whose serial is a
///   value [`syllabic::stamp`] never issues — so they form a cluster of their
///   own, distinct from the first real one. That is reproduced here as an
///   explicit leading range, because everything downstream requires the ranges
///   to tile the run exactly. It is inert either way: such a range is given the
///   `rphf` mask and a positional form exactly as HarfBuzz's is, and
///   [`reorder_cluster`] finds neither a repha nor a pre-base vowel in it.
pub(crate) fn clusters(glyphs: &[SubGlyph], out: &mut Vec<(usize, usize, Cluster)>) {
    out.clear();
    if glyphs.is_empty() {
        return;
    }
    // Run indices of the glyphs the machine may see, in order.
    let mut view: Vec<usize> = Vec::with_capacity(glyphs.len());
    for (i, g) in glyphs.iter().enumerate() {
        let hidden = match g.universal.category {
            Category::Cgj => true,
            // A ZWNJ is hidden only when what follows it — looking past any
            // hidden glyph in between — is a combining mark. Before anything
            // else it is a real symbol the grammar can match on.
            Category::NonJoiner => glyphs
                .iter()
                .skip(i.saturating_add(1))
                .find(|next| next.universal.category != Category::Cgj)
                .is_some_and(|next| next.universal.mark),
            _ => false,
        };
        if !hidden {
            view.push(i);
        }
    }
    let Some(&first) = view.first() else {
        // Every glyph filtered out: HarfBuzz stamps none of them, so the whole
        // run is the one leading range.
        out.push((0, glyphs.len(), Cluster::ViramaTerminated));
        return;
    };
    if first > 0 {
        out.push((0, first, Cluster::ViramaTerminated));
    }
    let cats: Vec<Category> = view
        .iter()
        .map(|&i| {
            glyphs
                .get(i)
                .map_or(Category::Other, |g| g.universal.category)
        })
        .collect();
    let mut at = 0usize;
    while at < cats.len() {
        // State 1 is the start; state 0 is dead. See `universal_machine`.
        let mut state = 1usize;
        let mut best: Option<(usize, Cluster)> = None;
        for (j, &cat) in cats.iter().enumerate().skip(at) {
            let next = match TRANSITIONS.get(state).and_then(|row| row.get(cat as usize)) {
                Some(&next) if next != 0 => usize::from(next),
                // Dead, or a table that does not cover this state — either way
                // nothing longer can match from here.
                _ => break,
            };
            state = next;
            if let Some(&Some(kind)) = ACCEPTS.get(state) {
                best = Some((j.saturating_add(1), kind));
            }
        }
        // `other = any` accepts one symbol of anything, so `best` is only ever
        // `None` if the table is corrupt; advancing by one is then both the
        // right answer and the one that guarantees termination.
        let (end, kind) = best.unwrap_or((at.saturating_add(1), Cluster::NonCluster));
        let start_at = view.get(at).copied().unwrap_or(glyphs.len());
        // Past the last visible glyph the cluster runs to the end of the run,
        // sweeping up whatever was filtered out behind it.
        let end_at = view.get(end).copied().unwrap_or(glyphs.len());
        out.push((start_at, end_at, kind));
        at = end;
    }
}

/// The four features that run before the reordering and before `rphf`, each
/// constrained to a cluster.
///
/// `nukt` and `akhn` join `locl` and `ccmp` here — HarfBuzz calls the four
/// together the "default glyph pre-processing group" — and only `akhn` is
/// marked `F_MANUAL_ZWJ`, which is why [`manual_zwj`] names it and not the
/// other three.
const PRE: [&[u8; 4]; 4] = [b"locl", b"ccmp", b"nukt", b"akhn"];

/// The repha feature, which gets a stage of its own so that
/// [`record_rphf`] can see what it did.
const RPHF: &[u8; 4] = b"rphf";

/// The pre-base form feature, which gets a stage of its own for the same
/// reason [`RPHF`] does. See [`record_pref`].
const PREF: &[u8; 4] = b"pref";

/// The seven features applied together, after `pref` and before the
/// reordering, each constrained to a cluster.
///
/// HarfBuzz's `use_basic_features`, and *together* is the point — this is
/// Khmer's arrangement rather than Myanmar's or Indic's, which run their basic
/// features one at a time. USE has no reason to separate them because it never
/// asks what any of them produced; the two features it does ask about, `rphf`
/// and `pref`, are the two that were pulled out in front.
const BASIC: [&[u8; 4]; 7] = [b"rkrf", b"abvf", b"blwf", b"half", b"pstf", b"vatu", b"cjct"];

/// The four positional features, in the order `joining_form_t` numbers them.
///
/// Handed out per cluster by [`setup_topographical_masks`], or per letter by
/// the ordinary cursive pass for the eleven scripts of
/// [`has_arabic_joining`]. Not global either way, which is why they are
/// `add_feature` in HarfBuzz and absent from [`global`] here.
const TOPO: [&[u8; 4]; 4] = [b"isol", b"init", b"medi", b"fina"];

/// The five features applied last, once the cluster boundaries are forgotten.
///
/// HarfBuzz's `use_other_features`, and the "standard typographic presentation"
/// group: global, manual-ZWJ, and — unlike everything above — **not**
/// per-cluster, so a rule in one of them may match across a cluster boundary.
/// <https://github.com/harfbuzz/harfbuzz/issues/3531>
const OTHER: [&[u8; 4]; 5] = [b"abvs", b"blws", b"haln", b"pres", b"psts"];

/// Every feature every glyph in the run is eligible for.
///
/// HarfBuzz's `enable_feature` implies `F_GLOBAL`, and the engine enables
/// everything except `rphf` and the four of [`TOPO`] — those two sets are
/// `add_feature`, which hands the mask out per glyph. `locl` and `ccmp` are
/// already in `gsub::ALWAYS`; naming them again costs nothing and keeps this
/// readable against the C.
fn global() -> u64 {
    feature_bits(&PRE) | feature_bit(PREF) | feature_bits(&BASIC) | feature_bits(&OTHER)
}

/// The features whose lookups must match a ZWJ rather than step over it.
///
/// `F_MANUAL_ZWJ` on everything the engine names except `locl`, `ccmp`, `nukt`
/// and the four positional features. The matching manual-ZWNJ set is **empty**,
/// exactly as Myanmar's is: HarfBuzz marks these `F_MANUAL_ZWJ` and not
/// `F_MANUAL_JOINERS`, so a lookup here still steps over a ZWNJ as though it
/// were not there. Observable in one place — a context rule whose input names a
/// ZWNJ — and wrong in that place if the two are conflated.
fn manual_zwj() -> u64 {
    feature_bit(b"akhn")
        | feature_bit(RPHF)
        | feature_bit(PREF)
        | feature_bits(&BASIC)
        | feature_bits(&OTHER)
}

/// The features whose lookups see one cluster at a time.
///
/// `F_PER_SYLLABLE` on the pre-processing four, `rphf`, `pref` and the basic
/// seven — everything up to the reordering. The four positional features and
/// the five presentation ones are deliberately outside it: the first run after
/// `hb_syllabic_clear_var` has thrown the boundaries away, and confining them
/// would be the bug that issue 3531 is about.
fn per_syllable() -> u64 {
    feature_bits(&PRE) | feature_bit(RPHF) | feature_bit(PREF) | feature_bits(&BASIC)
}

/// The six passes the lookups are applied in, as sets of feature bits.
///
/// The pre-processing four, then `rphf` alone, then `pref` alone, then the
/// basic seven, then the positional four, then everything else. HarfBuzz's
/// eleven pauses compile to exactly this: a pause both closes the stage it
/// follows and opens the next, and two adjacent pauses make an empty stage that
/// runs no lookups, so they are merged into one callback here.
///
/// "Everything else" is every feature this crate knows rather than just the
/// five of [`OTHER`], because the ordinary features — `liga`, `rlig`, `calt`
/// and the rest — belong to that last stage too: HarfBuzz appends them after
/// the shaper's own and they land in whatever stage is open, which is this one.
/// USE has no `override_features`, so nothing is switched off.
///
/// The five earlier sets are masked *out* of the last, and have to be: **a
/// feature belongs to exactly one stage.** HarfBuzz gets that from its map
/// builder, which merges the two entries a tag can pick up — `locl` and `ccmp`
/// are named both here and by the common features every run gets — and keeps
/// the *lower* stage. Leave one in two stages and every lookup it reaches runs
/// twice.
fn stages() -> [u64; 6] {
    let pre = feature_bits(&PRE);
    let rphf = feature_bit(RPHF);
    let pref = feature_bit(PREF);
    let basic = feature_bits(&BASIC);
    let topo = feature_bits(&TOPO);
    let early = pre | rphf | pref | basic | topo;
    [pre, rphf, pref, basic, topo, ALL_FEATURES & !early]
}

/// Hand out the `rphf` mask: HarfBuzz's `setup_rphf_mask`.
///
/// Only the head of a cluster may become a repha, and "the head" is at most
/// three glyphs — or exactly one, when the first glyph is already a repha by
/// category. Three rather than one because a repha is spelled with two or three
/// characters in several of these scripts, and the font's `rphf` lookup is
/// written against the whole spelling.
///
/// Nothing happens when the face has no `rphf` at all, which is what a zero
/// `mask` means. That is the same zero [`record_rphf`] tests, so the two agree
/// without having to ask twice.
fn setup_rphf_mask(glyphs: &mut [SubGlyph], ranges: &[(usize, usize, Cluster)], mask: u64) {
    if mask == 0 {
        return;
    }
    for &(start, end, _) in ranges {
        let head = glyphs
            .get(start)
            .map_or(Category::Other, |g| g.universal.category);
        let limit = if head == Category::Repha {
            1
        } else {
            end.saturating_sub(start).min(3)
        };
        for g in glyphs
            .get_mut(start..start.saturating_add(limit))
            .unwrap_or_default()
        {
            g.mask |= mask;
        }
    }
}

/// `masks[ISOL]`: the form a cluster takes when nothing joins to it.
const ISOL: usize = 0;
/// `masks[INIT]`: the form a cluster takes when the one after it joins back.
const INIT: usize = 1;
/// `masks[MEDI]`: joined on both sides.
const MEDI: usize = 2;
/// `masks[FINA]`: the form a cluster takes when it joins to the one before it.
const FINA: usize = 3;

/// Hand out the four positional forms, one per cluster: HarfBuzz's
/// `setup_topographical_masks`.
///
/// Not cursive joining, though it borrows its four feature tags. In most USE
/// scripts these features mean "this cluster is at the start / middle / end of
/// a *word*", and the rule for what counts as a word is a single pass: every
/// cluster joins to the one before it, except the two kinds that never join —
/// hieroglyph clusters and non-clusters — which reset the chain.
///
/// The pass is one cluster behind itself, which is what `last_start` is for. A
/// cluster is given [`ISOL`] on the assumption that nothing will follow it;
/// when something does, the *previous* cluster's mask is rewritten from
/// [`ISOL`] to [`INIT`] or from [`FINA`] to [`MEDI`] before this one is given
/// [`FINA`]. Note that `last_start` is updated on **every** iteration including
/// the non-joining kinds, so the fixup can never reach back past one of them.
///
/// `masks` is indexed by [`ISOL`], [`INIT`], [`MEDI`], [`FINA`] — the order of
/// [`TOPO`], which is the order HarfBuzz's `joining_form_t` numbers them in.
/// Each entry is `0` where the face has no such feature, and the whole pass is
/// skipped when all four are, which is the common case: a font for a
/// non-joining script registers none of them.
///
/// The mask is *replaced*, not or-ed: a cluster takes exactly one of the four,
/// and a cluster the pass reaches twice — the fixup, then nothing — must not
/// end up with two.
fn setup_topographical_masks(
    glyphs: &mut [SubGlyph],
    ranges: &[(usize, usize, Cluster)],
    masks: [u64; 4],
) {
    let all = masks.iter().fold(0u64, |all, &m| all | m);
    if all == 0 {
        return;
    }
    let other = !all;
    let at = |form: usize| masks.get(form).copied().unwrap_or(0);
    let mut last_start = 0usize;
    let mut last_form: Option<usize> = None;
    for &(start, end, kind) in ranges {
        if matches!(kind, Cluster::Hieroglyph | Cluster::NonCluster) {
            // These do not join, and break the chain for whatever follows.
            last_form = None;
            last_start = start;
            continue;
        }
        let join = matches!(last_form, Some(ISOL | FINA));
        if join {
            let fixed = if last_form == Some(FINA) { MEDI } else { INIT };
            for g in glyphs.get_mut(last_start..start).unwrap_or_default() {
                g.mask = (g.mask & other) | at(fixed);
            }
        }
        let form = if join { FINA } else { ISOL };
        for g in glyphs.get_mut(start..end).unwrap_or_default() {
            g.mask = (g.mask & other) | at(form);
        }
        last_form = Some(form);
        last_start = start;
    }
}

/// Forget which glyphs the last stage rewrote: HarfBuzz's
/// `_hb_clear_substitution_flags`.
///
/// Run before `rphf` and again after it, so that "was this glyph substituted?"
/// means "by the stage that just ran" and not "by anything, ever".
fn clear_substituted(glyphs: &mut [SubGlyph]) {
    for g in glyphs.iter_mut() {
        g.substituted = false;
    }
}

/// Note which glyph the font turned into a repha: HarfBuzz's `record_rphf_use`.
///
/// The first substituted glyph in each cluster becomes [`Category::Repha`], and
/// the search stops at the first glyph the `rphf` mask was not handed to — so
/// it looks at the same one-to-three glyphs [`setup_rphf_mask`] offered the
/// feature, and no further.
///
/// This is where USE differs most sharply from the other three shapers. A reph
/// is not a spelling here; it is whatever this font's `rphf` lookup chose to
/// make one, which is a question only the font can answer and only by having
/// been run. That is the entire reason `rphf` gets a stage to itself.
fn record_rphf(glyphs: &mut [SubGlyph], mask: u64) {
    if mask == 0 {
        return;
    }
    syllabic::for_each(glyphs, |_, _, cluster| {
        for g in cluster.iter_mut() {
            if g.mask & mask == 0 {
                break;
            }
            if g.substituted {
                g.universal.category = Category::Repha;
                break;
            }
        }
    });
}

/// Note which glyph the font turned into a pre-base form: HarfBuzz's
/// `record_pref_use`.
///
/// The twin of [`record_rphf`] with one deliberate difference: there is **no
/// mask guard**. `pref` is a global feature, so every glyph was offered it and
/// the search runs to the end of the cluster.
///
/// The glyph becomes [`Category::VowelPre`] rather than a category of its own,
/// because from here on it behaves as one: [`reorder_cluster`] moves it to the
/// front of the cluster exactly as it moves a left-drawn vowel, which is what a
/// pre-base form is.
fn record_pref(glyphs: &mut [SubGlyph]) {
    syllabic::for_each(glyphs, |_, _, cluster| {
        for g in cluster.iter_mut() {
            if g.substituted {
                g.universal.category = Category::VowelPre;
                break;
            }
        }
    });
}

/// Whether this glyph ends a cluster's consonant stack: HarfBuzz's
/// `is_halant_use`.
///
/// Three categories, and the ligation test that goes with all of them: a glyph
/// the font joined is no longer the character it was categorised from, so
/// treating it as a virama would put a pre-base vowel inside a conjunct.
fn is_halant(g: &SubGlyph) -> bool {
    matches!(
        g.universal.category,
        Category::Halant | Category::HalantOrVowelModifier | Category::InvisibleStacker
    ) && !g.lig.ligated()
}

/// Whether a repha must stop in front of this glyph: HarfBuzz's
/// `POST_BASE_FLAGS64`, plus [`is_halant`].
///
/// Everything drawn relative to the base rather than as part of it — the
/// finals, the medials, the vowels and their modifiers. A repha is drawn above
/// the base, so it belongs after the base and before the first of these.
fn is_post_base(g: &SubGlyph) -> bool {
    matches!(
        g.universal.category,
        Category::ConsFinalAbove
            | Category::ConsFinalBelow
            | Category::ConsFinalPost
            | Category::ConsFinalModAbove
            | Category::ConsFinalModBelow
            | Category::ConsFinalModPost
            | Category::ConsMedAbove
            | Category::ConsMedBelow
            | Category::ConsMedPost
            | Category::ConsMedPre
            | Category::VowelAbove
            | Category::VowelBelow
            | Category::VowelPost
            | Category::VowelPre
            | Category::VowelModAbove
            | Category::VowelModBelow
            | Category::VowelModPost
            | Category::VowelModPre
    ) || is_halant(g)
}

/// Insert the dotted circles, then lay out each cluster.
///
/// Both halves of HarfBuzz's `reorder_use`, and in its order: the circle has to
/// be in place before a broken cluster is reordered, because the reordering
/// treats a broken cluster as an ordinary one and the circle is the base it is
/// built on.
///
/// The circle is a [`Category::Base`] and it goes *after* a repha, which is
/// HarfBuzz's `USE(B), USE(R)` pair: a repha is drawn above the letter that
/// follows it, so it must keep a letter after it to be drawn above.
fn reorder(glyphs: &mut Vec<SubGlyph>, dotted: Option<u16>) {
    syllabic::insert_dotted_circles(
        glyphs,
        dotted,
        |g| {
            g.universal = Char {
                category: Category::Base,
                // U+25CC is `So`, and in any case this runs long after the only
                // pass that reads the bit.
                mark: false,
            };
        },
        |stamp| Cluster::from_code(stamp) == Cluster::Broken,
        |g| g.universal.category == Category::Repha,
    );
    syllabic::for_each(glyphs, |stamp, _, cluster| {
        reorder_cluster(Cluster::from_code(stamp), cluster);
    });
}

/// Lay out one cluster: HarfBuzz's `reorder_syllable_use`.
///
/// `glyphs` is exactly the cluster, and comes out the same length — this only
/// permutes. Two passes, in this order, and they are the whole of USE's
/// reordering:
///
/// 1. **A repha moves forward**, to just before the first post-base glyph, or
///    to the end of the cluster if there is none. It is written first and drawn
///    above the base, so it belongs after the base — and before anything that
///    hangs off the base, which is what [`is_post_base`] enumerates.
/// 2. **A pre-base vowel moves back**, to the front of the cluster or to just
///    after the last virama, whichever is nearer. Drawn to the left of the
///    consonant it was typed after; stopping at a virama is what keeps it
///    outside a conjunct rather than wedged into the middle of one.
///
/// Only five of the nine kinds are reordered at all. A numeral, a
/// number-joiner-terminated cluster, a hieroglyph cluster and a non-cluster
/// contain nothing either pass could move, and HarfBuzz returns early rather
/// than let the passes find that out.
///
/// The second pass skips a pre-base vowel that is not the first component of a
/// multiple substitution: a font that split one character into two pieces put
/// the pieces in drawn order already, and moving the second piece would undo
/// that.
fn reorder_cluster(kind: Cluster, glyphs: &mut [SubGlyph]) {
    if !matches!(
        kind,
        Cluster::ViramaTerminated
            | Cluster::SakotTerminated
            | Cluster::Standard
            | Cluster::Symbol
            | Cluster::Broken
    ) {
        return;
    }
    let end = glyphs.len();

    // Move things forward.
    if end > 1
        && glyphs
            .first()
            .is_some_and(|g| g.universal.category == Category::Repha)
    {
        for i in 1..end {
            let post = glyphs.get(i).is_some_and(is_post_base);
            if !post && i.saturating_add(1) != end {
                continue;
            }
            // Before the post-base glyph, or onto the last glyph when there is
            // none. Everything in between shifts back one, which is what a
            // rotate is.
            let to = if post { i.saturating_sub(1) } else { i };
            if let Some(run) = glyphs.get_mut(..=to) {
                syllabic::merge_clusters(run);
                run.rotate_left(1);
            }
            break;
        }
    }

    // Move things back.
    let mut j = 0usize;
    for i in 0..end {
        if glyphs.get(i).is_some_and(is_halant) {
            j = i.saturating_add(1);
            continue;
        }
        let movable = glyphs.get(i).is_some_and(|g| {
            matches!(
                g.universal.category,
                Category::VowelPre | Category::VowelModPre
            ) && g.lig.comp() == 0
        });
        if movable
            && j < i
            && let Some(run) = glyphs.get_mut(j..=i)
        {
            syllabic::merge_clusters(run);
            run.rotate_right(1);
        }
    }
}

/// Shape one run of text with the Universal Shaping Engine, end to end.
///
/// `glyphs` is one script run, one glyph per character, as `cmap` produced it
/// and with [`SubGlyph::universal`] already set from the character. It comes
/// back reordered and substituted, and may be longer: a broken cluster gains a
/// dotted circle.
///
/// `subs` may be `None`. The reordering is not conditional on the font having
/// substitutions — a pre-base vowel is written after its consonant and drawn
/// before it whatever the font does — so a face with no `GSUB` still gets it.
/// What it does *not* get is a repha or a pre-base form, since both are
/// defined by a lookup having run.
///
/// `glyph` maps a character to a glyph: the face's `cmap`. It is asked about
/// exactly one character, the dotted circle.
pub(crate) fn shape(
    data: &[u8],
    subs: Option<&Substitutions>,
    tags: Option<ScriptTags>,
    lang: Option<Lang>,
    glyphs: &mut Vec<SubGlyph>,
    glyph: impl Fn(char) -> Option<u16>,
) {
    if glyphs.is_empty() {
        return;
    }
    let global = global();
    for g in glyphs.iter_mut() {
        g.mask |= global;
    }
    // HarfBuzz's `get_1_mask`: the bit that selects this tag's lookups, or zero
    // when the face reaches none. Both users read it as a yes-or-no first —
    // there is nothing to hand out if the font cannot form a repha.
    let mask = |tag: &[u8; 4]| subs.map_or(0, |subs| subs.feature_mask(tags, lang, tag));
    let rphf = mask(RPHF);

    let mut ranges: Vec<(usize, usize, Cluster)> = Vec::new();
    clusters(glyphs, &mut ranges);
    syllabic::stamp(glyphs, &ranges, Cluster::code);
    setup_rphf_mask(glyphs, &ranges, rphf);
    // Skipped for the eleven scripts that join cursively: their glyphs already
    // carry a form mask, chosen per letter from the Unicode joining type, and
    // this pass would overwrite it with a per-cluster answer.
    if !has_arabic_joining(tags) {
        setup_topographical_masks(glyphs, &ranges, TOPO.map(mask));
    }

    let dotted = glyph('\u{25CC}');
    let Some(subs) = subs else {
        // No lookups to run, so no stages either — but the reordering still has
        // to happen, and with no stages to hang it on it happens here.
        reorder(glyphs, dotted);
        return;
    };
    let stages = stages();
    subs.apply_stages(
        data,
        tags,
        lang,
        &Staging {
            stages: &stages,
            per_syllable: per_syllable(),
            // Empty on purpose: USE's features are `F_MANUAL_ZWJ`, not
            // `F_MANUAL_JOINERS`. See `manual_zwj`.
            manual_zwnj: 0,
            manual_zwj: manual_zwj(),
        },
        glyphs,
        |stage, glyphs| match stage {
            0 => clear_substituted(glyphs),
            1 => {
                record_rphf(glyphs, rphf);
                clear_substituted(glyphs);
            }
            2 => record_pref(glyphs),
            3 => {
                reorder(glyphs, dotted);
                // Past this point the confinement would be wrong: the five
                // presentation features are global and may match across a
                // cluster boundary.
                syllabic::clear(glyphs);
            }
            _ => {}
        },
    );
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]
mod tests {
    use super::*;
    use alloc::vec;

    /// The machine's rows are indexed by a category's discriminant, so a table
    /// generated against a different category list would silently mis-scan.
    #[test]
    fn the_machine_has_a_column_for_every_category() {
        assert!(!TRANSITIONS.is_empty(), "the machine has no states");
        assert_eq!(TRANSITIONS.len(), ACCEPTS.len());
        for row in &TRANSITIONS {
            assert_eq!(row.len(), Category::COUNT);
        }
        // And the last variant really is the last column.
        assert_eq!(Category::ReorderingKiller as usize, Category::COUNT - 1);
    }

    /// The engine takes every complex script no other shaper claims. Written as
    /// a subtraction rather than a second hand-kept list, so that adding a
    /// script to `fallback::COMPLEX_SCRIPTS` and forgetting this one fails here
    /// instead of silently shaping it as plain text.
    #[test]
    fn the_engine_takes_every_complex_script_no_other_shaper_claims() {
        let claimed = [
            *b"bng2", *b"dev2", *b"gjr2", *b"gur2", *b"knd2", *b"mlm2", *b"ory2", *b"tel2",
            *b"tml2", *b"khmr", *b"mym2", *b"thai", *b"lao ",
        ];
        let expected: Vec<[u8; 4]> = crate::fallback::COMPLEX_SCRIPTS
            .iter()
            .copied()
            .filter(|tag| !claimed.contains(tag))
            .collect();
        assert_eq!(USE_SCRIPTS.to_vec(), expected);
    }

    /// Both script lists are binary-searched, so both must be sorted.
    #[test]
    fn the_script_lists_are_sorted() {
        assert!(USE_SCRIPTS.is_sorted());
        for tag in [*b"adlm", *b"chrs", *b"mand", *b"mong", *b"sogd"] {
            assert!(has_arabic_joining(Some(ScriptTags::exactly(tag))));
        }
        // Arabic and Syriac are in HarfBuzz's list but reach the Arabic shaper,
        // not this one — and are not USE scripts at all.
        for tag in [*b"arab", *b"syrc", *b"elym", *b"yezi", *b"java"] {
            assert!(!has_arabic_joining(Some(ScriptTags::exactly(tag))));
        }
        assert!(!has_arabic_joining(None));
    }

    /// Sinhala is a USE script and not an Indic one, which is a real
    /// difference: HarfBuzz sends it here outright.
    #[test]
    fn the_script_set_is_the_one_harfbuzz_sends_here() {
        for tag in [*b"sinh", *b"java", *b"tibt", *b"egyp", *b"adlm", *b"lana"] {
            assert!(shapes(Some(ScriptTags::exactly(tag))), "{tag:?}");
        }
        for tag in [*b"dev2", *b"khmr", *b"mym2", *b"thai", *b"latn", *b"arab"] {
            assert!(!shapes(Some(ScriptTags::exactly(tag))), "{tag:?}");
        }
        assert!(!shapes(None));
    }

    /// No feature may appear in two stages. A lookup a feature reaches is
    /// applied once per stage that names it, so a tag left in an early stage
    /// and in the catch-all one runs its lookups twice.
    #[test]
    fn no_feature_is_applied_in_two_stages() {
        let stages = stages();
        for (i, &a) in stages.iter().enumerate() {
            for &b in stages.iter().skip(i + 1) {
                assert_eq!(a & b, 0);
            }
        }
        assert_eq!(stages.iter().fold(0, |all, &s| all | s), ALL_FEATURES);
    }

    /// `rphf` and `pref` each get a stage of their own, because the engine asks
    /// what each of them did. The basic seven share one, because it asks
    /// nothing about them.
    #[test]
    fn the_two_recorded_features_each_get_a_stage_of_their_own() {
        let stages = stages();
        assert_eq!(stages[0], feature_bits(&PRE));
        assert_eq!(stages[1], feature_bit(RPHF));
        assert_eq!(stages[2], feature_bit(PREF));
        assert_eq!(stages[3], feature_bits(&BASIC));
        assert_eq!(stages[4], feature_bits(&TOPO));
        assert_eq!(stages[5] & feature_bits(&OTHER), feature_bits(&OTHER));
    }

    /// The presentation five run after the cluster stamps are cleared, and the
    /// positional four are not confined to a cluster either.
    #[test]
    fn the_late_features_are_not_confined_to_a_cluster() {
        let per = per_syllable();
        assert_eq!(per & feature_bits(&OTHER), 0);
        assert_eq!(per & feature_bits(&TOPO), 0);
        assert_eq!(per & feature_bits(&PRE), feature_bits(&PRE));
        assert_eq!(per & feature_bit(RPHF), feature_bit(RPHF));
        assert_eq!(per & feature_bits(&BASIC), feature_bits(&BASIC));
    }

    /// `rphf` and the four positional features are handed out per glyph, so
    /// they must not be in the global mask; everything else the engine names
    /// is.
    #[test]
    fn only_the_per_glyph_features_are_left_out_of_the_global_mask() {
        let global = global();
        assert_eq!(global & feature_bit(RPHF), 0);
        assert_eq!(global & feature_bits(&TOPO), 0);
        for set in [&feature_bits(&PRE), &feature_bits(&BASIC), &feature_bits(&OTHER)] {
            assert_eq!(global & set, *set);
        }
        assert_eq!(global & feature_bit(PREF), feature_bit(PREF));
    }

    /// USE has no `override_features`, so `liga` stays on — Khmer's `stages`
    /// switches it off and this one must not copy that.
    #[test]
    fn ligatures_are_not_switched_off() {
        assert_ne!(stages()[5] & feature_bit(b"liga"), 0);
    }

    /// A spot-check that the generated table says what the grammar is written
    /// against. Every rule below is about characters that never arrive if these
    /// are wrong.
    #[test]
    fn the_table_categorises_the_characters_the_grammar_names() {
        let cat = Category::of;
        // Javanese: ꦏ KA is a base, ꦶ vowel sign I is above, ꦺ TALING is
        // pre-base, ꧀ PANGKON is a visible virama.
        assert_eq!(cat('\u{A98F}'), Category::Base);
        assert_eq!(cat('\u{A9B6}'), Category::VowelAbove);
        assert_eq!(cat('\u{A9BA}'), Category::VowelPre);
        assert_eq!(cat('\u{A9C0}'), Category::Halant);
        // Chakma's invisible stacker, and Tai Tham's sakot.
        assert_eq!(cat('\u{11133}'), Category::InvisibleStacker);
        assert_eq!(cat('\u{1A60}'), Category::Sakot);
        // The joiners, which the filter is about.
        assert_eq!(cat('\u{200C}'), Category::NonJoiner);
        assert_eq!(cat('\u{200D}'), Category::Cgj);
        assert_eq!(cat('\u{034F}'), Category::Cgj);
        assert_eq!(cat('\u{FE00}'), Category::Cgj);
        // Egyptian hieroglyphs and their controls.
        assert_eq!(cat('\u{13000}'), Category::Hieroglyph);
        assert_eq!(cat('\u{13430}'), Category::HieroglyphJoiner);
        // Latin is nothing to the engine, which is what lets a mixed run
        // through one shaper.
        assert_eq!(cat('a'), Category::Other);
        assert_eq!(cat('\u{10FFFF}'), Category::Other);
    }

    /// The two facts [`Char`] carries are genuinely independent: a `Base` may
    /// be a combining mark and an `Other` very often is.
    #[test]
    fn the_mark_bit_is_not_recoverable_from_the_category() {
        // U+0BCD TAMIL SIGN VIRAMA is `Mn` and categorised `H`.
        assert!(Char::of('\u{0BCD}').mark);
        // U+0903 DEVANAGARI SIGN VISARGA is `Mc` — a *spacing* mark, which
        // `norm::is_mark` alone would miss.
        assert!(Char::of('\u{0903}').mark);
        assert!(!Char::of('a').mark);
        assert!(!Char::of('\u{25CC}').mark);
    }

    fn run(text: &str) -> Vec<SubGlyph> {
        text.chars()
            .enumerate()
            .map(|(i, ch)| SubGlyph {
                universal: Char::of(ch),
                ..SubGlyph::cursive(u16::try_from(i).unwrap_or(0), i, None)
            })
            .collect()
    }

    fn cut(text: &str) -> Vec<(usize, usize, Cluster)> {
        let glyphs = run(text);
        let mut out = Vec::new();
        clusters(&glyphs, &mut out);
        out
    }

    /// The ranges must tile the run exactly — contiguous, non-empty, and
    /// ending where the run does. Everything downstream assumes it, and the
    /// filtered view is the thing most likely to break it.
    #[test]
    fn the_clusters_tile_every_run_they_are_given() {
        for text in [
            "\u{A98F}\u{A9BA}\u{A9C0}\u{A990}",
            "\u{200D}\u{A98F}\u{200C}\u{A9B6}",
            "\u{FE00}\u{FE00}\u{034F}",
            "a\u{200C}b\u{25CC}\u{0BCD}",
            "\u{13000}\u{13430}\u{13001}",
            "\u{11103}\u{11133}\u{11104}",
            "123\u{A9C0}",
            "\u{1A20}\u{1A60}\u{1A21}",
        ] {
            let cut = cut(text);
            let mut at = 0usize;
            for &(start, end, _) in &cut {
                assert_eq!(start, at, "{text:?} has a hole at {at}");
                assert!(end > start, "{text:?} has an empty cluster at {at}");
                at = end;
            }
            assert_eq!(at, text.chars().count(), "{text:?} was cut short");
        }
        assert!(cut("").is_empty());
    }

    /// A base with its vowels and finals is one cluster; two bases are two.
    #[test]
    fn a_base_and_its_marks_are_one_cluster() {
        assert_eq!(
            cut("\u{A98F}\u{A9B6}"),
            vec![(0, 2, Cluster::Standard)],
            "a Javanese base and its vowel"
        );
        assert_eq!(
            cut("\u{A98F}\u{A990}"),
            vec![(0, 1, Cluster::Standard), (1, 2, Cluster::Standard)]
        );
    }

    /// An invisible stacker ends its cluster, and a sakot ends a different
    /// kind of one. Both are what the reordering keys on.
    #[test]
    fn the_terminators_name_the_cluster_kind() {
        assert_eq!(
            cut("\u{11103}\u{11133}"),
            vec![(0, 2, Cluster::ViramaTerminated)]
        );
        assert_eq!(
            cut("\u{1A20}\u{1A60}"),
            vec![(0, 2, Cluster::SakotTerminated)]
        );
        // A reordering killer ends a cluster the way an invisible stacker does,
        // which is the other half of the same grammar rule. U+1BF2 is BATAK
        // PANGOLAT — the only script with a reordering killer in it — so the
        // letters either side of it are Batak too. `run` is handed one script's
        // worth of text, which is what the itemizer would have produced.
        assert_eq!(
            cut("\u{1BC0}\u{1BF2}\u{1BC0}"),
            vec![
                (0, 2, Cluster::ViramaTerminated),
                (2, 3, Cluster::Standard)
            ]
        );
    }

    /// A vowel sign with no base is broken text, which is what earns a dotted
    /// circle. A lone `FMPst` is not, which is why the grammar lists it
    /// separately.
    #[test]
    fn marks_with_no_base_are_broken() {
        assert_eq!(cut("\u{A9B6}"), vec![(0, 1, Cluster::Broken)]);
        // U+00B2 SUPERSCRIPT TWO is `FMPst`, and alone it is a non-cluster.
        assert_eq!(cut("\u{00B2}"), vec![(0, 1, Cluster::NonCluster)]);
    }

    /// A `CGJ` glyph is hidden from the machine and joins the cluster before
    /// it, rather than cutting it in two.
    #[test]
    fn a_hidden_glyph_joins_the_cluster_before_it() {
        // Base, ZWJ, vowel: one cluster of three, not two of one and two.
        assert_eq!(
            cut("\u{A98F}\u{200D}\u{A9B6}"),
            vec![(0, 3, Cluster::Standard)]
        );
        // And at the end of the run.
        assert_eq!(
            cut("\u{A98F}\u{A9B6}\u{200D}"),
            vec![(0, 3, Cluster::Standard)]
        );
    }

    /// Hidden glyphs at the *start* of the run belong to no cluster HarfBuzz
    /// ever stamps, so they get one of their own.
    #[test]
    fn hidden_glyphs_at_the_start_are_a_cluster_of_their_own() {
        assert_eq!(
            cut("\u{200D}\u{A98F}\u{A9B6}"),
            vec![(0, 1, Cluster::ViramaTerminated), (1, 3, Cluster::Standard)]
        );
        // A run of nothing but hidden glyphs is all one such range.
        assert_eq!(
            cut("\u{200D}\u{034F}"),
            vec![(0, 2, Cluster::ViramaTerminated)]
        );
    }

    /// A ZWNJ normally ends a cluster — and does not when a combining mark
    /// follows it, because there it is asking the font not to ligate rather
    /// than asking for a break.
    #[test]
    fn a_zwnj_before_a_mark_is_hidden() {
        // Base, ZWNJ, base: the ZWNJ ends the first cluster.
        assert_eq!(
            cut("\u{A98F}\u{200C}\u{A990}"),
            vec![(0, 2, Cluster::Standard), (2, 3, Cluster::Standard)]
        );
        // Base, ZWNJ, vowel sign: hidden, so all three are one cluster.
        assert_eq!(
            cut("\u{A98F}\u{200C}\u{A9B6}"),
            vec![(0, 3, Cluster::Standard)]
        );
    }

    /// The stamp's low nibble round-trips under every serial the high nibble
    /// can hold, and a nibble no kind claims reads as the kind that does
    /// nothing.
    #[test]
    fn a_cluster_kind_survives_the_nibble_it_is_stored_in() {
        for serial in 0..16u8 {
            for kind in [
                Cluster::ViramaTerminated,
                Cluster::SakotTerminated,
                Cluster::Standard,
                Cluster::NumberJoinerTerminated,
                Cluster::Numeral,
                Cluster::Symbol,
                Cluster::Hieroglyph,
                Cluster::Broken,
                Cluster::NonCluster,
            ] {
                assert_eq!(Cluster::from_code((serial << 4) | kind.code()), kind);
            }
        }
        assert_eq!(Cluster::from_code(0), Cluster::ViramaTerminated);
        assert_eq!(Cluster::from_code(0x0F), Cluster::NonCluster);
    }

    fn order(glyphs: &[SubGlyph]) -> Vec<u16> {
        glyphs.iter().map(|g| g.gid).collect()
    }

    /// A repha is drawn above the base, so it moves to just after it — and
    /// stops in front of anything hung off the base.
    #[test]
    fn a_repha_moves_to_just_after_the_base() {
        let mut glyphs = run("\u{A98F}\u{A990}\u{A991}");
        glyphs[0].universal.category = Category::Repha;
        reorder_cluster(Cluster::Standard, &mut glyphs);
        // No post-base glyph anywhere, so it goes to the end.
        assert_eq!(order(&glyphs), vec![1, 2, 0]);
        // Everything it jumped over is now one cluster to a caret.
        assert!(glyphs.iter().all(|g| g.cluster == 0));

        // With a vowel sign after the base it stops in front of it.
        let mut glyphs = run("\u{A98F}\u{A990}\u{A9B6}");
        glyphs[0].universal.category = Category::Repha;
        reorder_cluster(Cluster::Standard, &mut glyphs);
        assert_eq!(order(&glyphs), vec![1, 0, 2]);
    }

    /// A repha in a cluster of one has nowhere to go.
    #[test]
    fn a_lone_repha_does_not_move() {
        let mut glyphs = run("\u{A98F}");
        glyphs[0].universal.category = Category::Repha;
        reorder_cluster(Cluster::Standard, &mut glyphs);
        assert_eq!(order(&glyphs), vec![0]);
    }

    /// A pre-base vowel is stored after its consonant and drawn before it.
    #[test]
    fn a_pre_base_vowel_moves_in_front_of_its_base() {
        // ꦏ KA, ꦺ TALING — the vowel is `VPre`.
        let mut glyphs = run("\u{A98F}\u{A9BA}");
        reorder_cluster(Cluster::Standard, &mut glyphs);
        assert_eq!(order(&glyphs), vec![1, 0]);
        assert_eq!(glyphs[0].cluster, 0);
        assert_eq!(glyphs[1].cluster, 0);
    }

    /// It stops at a virama rather than crossing it, which is what keeps it
    /// outside a conjunct instead of wedged into the middle of one.
    #[test]
    fn a_pre_base_vowel_stops_at_a_virama() {
        // KA, PANGKON (virama), KA, TALING: the vowel goes in front of the
        // *second* KA, not the first.
        let mut glyphs = run("\u{A98F}\u{A9C0}\u{A990}\u{A9BA}");
        reorder_cluster(Cluster::Standard, &mut glyphs);
        assert_eq!(order(&glyphs), vec![0, 1, 3, 2]);
    }

    /// A glyph the font ligated is no longer the virama it was categorised
    /// from, so the vowel walks straight past it.
    #[test]
    fn a_ligated_virama_does_not_stop_a_pre_base_vowel() {
        let mut glyphs = run("\u{A98F}\u{A9C0}\u{A990}\u{A9BA}");
        glyphs[1].lig = crate::gsub::Lig::at(1, 2, 0);
        reorder_cluster(Cluster::Standard, &mut glyphs);
        assert_eq!(order(&glyphs), vec![3, 0, 1, 2]);
    }

    /// Only the first piece of a multiple substitution moves: a font that split
    /// one vowel into two put the pieces in drawn order already.
    #[test]
    fn only_the_first_piece_of_a_split_vowel_moves() {
        let mut glyphs = run("\u{A98F}\u{A9BA}");
        // Second piece of a decomposition: no `comps` of its own, so the
        // component index survives `Lig::comp`.
        glyphs[1].lig = crate::gsub::Lig::at(1, 0, 1).split();
        reorder_cluster(Cluster::Standard, &mut glyphs);
        assert_eq!(order(&glyphs), vec![0, 1]);
    }

    /// Four of the nine kinds are never reordered, and a numeral is the
    /// clearest case: it has digits in it that neither pass may touch.
    #[test]
    fn the_kinds_that_are_never_reordered_are_left_alone() {
        for kind in [
            Cluster::NumberJoinerTerminated,
            Cluster::Numeral,
            Cluster::Hieroglyph,
            Cluster::NonCluster,
        ] {
            let mut glyphs = run("\u{A98F}\u{A9BA}");
            reorder_cluster(kind, &mut glyphs);
            assert_eq!(order(&glyphs), vec![0, 1], "{kind:?}");
        }
    }

    /// The repha mask goes to at most the first three glyphs of a cluster — or
    /// to exactly one when the head is already a repha.
    #[test]
    fn the_repha_mask_reaches_only_the_head_of_a_cluster() {
        let mut glyphs = run("\u{A98F}\u{A990}\u{A991}\u{A992}");
        let ranges = vec![(0usize, 4usize, Cluster::Standard)];
        setup_rphf_mask(&mut glyphs, &ranges, 1 << 40);
        let has: Vec<bool> = glyphs.iter().map(|g| g.mask & (1 << 40) != 0).collect();
        assert_eq!(has, vec![true, true, true, false]);

        let mut glyphs = run("\u{A98F}\u{A990}\u{A991}\u{A992}");
        glyphs[0].universal.category = Category::Repha;
        setup_rphf_mask(&mut glyphs, &ranges, 1 << 40);
        let has: Vec<bool> = glyphs.iter().map(|g| g.mask & (1 << 40) != 0).collect();
        assert_eq!(has, vec![true, false, false, false]);
    }

    /// A face with no `rphf` gets no mask handed out at all, which is the same
    /// zero `record_rphf` tests.
    #[test]
    fn a_face_without_rphf_is_not_asked_for_one() {
        let mut glyphs = run("\u{A98F}\u{A990}");
        let before: Vec<u64> = glyphs.iter().map(|g| g.mask).collect();
        setup_rphf_mask(&mut glyphs, &[(0, 2, Cluster::Standard)], 0);
        assert!(glyphs.iter().map(|g| g.mask).eq(before));
        record_rphf(&mut glyphs, 0);
        assert!(glyphs.iter().all(|g| g.universal.category != Category::Repha));
    }

    /// The positional pass is one cluster behind itself: the first cluster is
    /// `isol` until a second one turns it into `init`.
    #[test]
    fn the_positional_forms_are_fixed_up_one_cluster_late() {
        let masks = [1u64 << 40, 1 << 41, 1 << 42, 1 << 43];
        let form = |g: &SubGlyph| masks.iter().position(|&m| g.mask & m != 0);
        let mut glyphs = run("\u{A98F}\u{A990}\u{A991}");
        let ranges = vec![
            (0usize, 1usize, Cluster::Standard),
            (1, 2, Cluster::Standard),
            (2, 3, Cluster::Standard),
        ];
        setup_topographical_masks(&mut glyphs, &ranges, masks);
        let forms: Vec<Option<usize>> = glyphs.iter().map(form).collect();
        assert_eq!(forms, vec![Some(INIT), Some(MEDI), Some(FINA)]);

        // One cluster alone stays isolated.
        let mut glyphs = run("\u{A98F}");
        setup_topographical_masks(&mut glyphs, &[(0, 1, Cluster::Standard)], masks);
        assert_eq!(glyphs.iter().map(form).collect::<Vec<_>>(), vec![Some(ISOL)]);
    }

    /// A non-cluster breaks the chain, so the cluster before it stays `isol`
    /// and the one after it starts a new word.
    #[test]
    fn a_non_cluster_breaks_the_positional_chain() {
        let masks = [1u64 << 40, 1 << 41, 1 << 42, 1 << 43];
        let form = |g: &SubGlyph| masks.iter().position(|&m| g.mask & m != 0);
        let mut glyphs = run("\u{A98F} \u{A990}");
        let ranges = vec![
            (0usize, 1usize, Cluster::Standard),
            (1, 2, Cluster::NonCluster),
            (2, 3, Cluster::Standard),
        ];
        setup_topographical_masks(&mut glyphs, &ranges, masks);
        let forms: Vec<Option<usize>> = glyphs.iter().map(form).collect();
        assert_eq!(forms, vec![Some(ISOL), None, Some(ISOL)]);
    }

    /// A face with none of the four features gets no pass at all — which is
    /// most faces, since a non-joining script's font registers none of them.
    #[test]
    fn a_face_without_the_positional_features_is_left_alone() {
        let mut glyphs = run("\u{A98F}\u{A990}");
        let before: Vec<u64> = glyphs.iter().map(|g| g.mask).collect();
        setup_topographical_masks(
            &mut glyphs,
            &[(0, 1, Cluster::Standard), (1, 2, Cluster::Standard)],
            [0; 4],
        );
        assert!(glyphs.iter().map(|g| g.mask).eq(before));
    }

    /// A broken cluster gains a dotted circle; a well-formed one does not.
    #[test]
    fn a_broken_cluster_gains_a_dotted_circle() {
        let mut glyphs = run("\u{A9B6}");
        let mut ranges = Vec::new();
        clusters(&glyphs, &mut ranges);
        assert_eq!(ranges, vec![(0, 1, Cluster::Broken)]);
        syllabic::stamp(&mut glyphs, &ranges, Cluster::code);
        reorder(&mut glyphs, Some(99));
        assert_eq!(glyphs.len(), 2);
        assert_eq!(order(&glyphs), vec![99, 0]);
        assert_eq!(glyphs[0].universal.category, Category::Base);
        assert_eq!(glyphs[0].cluster, glyphs[1].cluster);

        let mut glyphs = run("\u{A98F}\u{A9B6}");
        let mut ranges = Vec::new();
        clusters(&glyphs, &mut ranges);
        syllabic::stamp(&mut glyphs, &ranges, Cluster::code);
        reorder(&mut glyphs, Some(99));
        assert_eq!(glyphs.len(), 2, "nothing to fix");
    }

    /// The circle goes *after* a repha, which is drawn above the letter that
    /// follows it and so needs a letter to follow.
    ///
    /// Reading that off the output takes a cluster of this shape and no
    /// shorter, because the repha's own forward move runs straight afterwards
    /// and hides the difference in every simpler one: in `repha + circle +
    /// post-base` the repha hops the circle and lands exactly where inserting
    /// the circle in front of it would have put things. Here it hops *three*
    /// glyphs, so the two orders come out different — `[circle, 1, 2, repha,
    /// 3]` if the circle went after the repha, `[circle, repha, 1, 2, 3]` if it
    /// went before.
    #[test]
    fn the_circle_goes_after_a_repha() {
        let mut glyphs = run("\u{A98F}\u{A98F}\u{A98F}\u{A9B6}");
        glyphs[0].universal.category = Category::Repha;
        let ranges = vec![(0usize, 4usize, Cluster::Broken)];
        syllabic::stamp(&mut glyphs, &ranges, Cluster::code);
        reorder(&mut glyphs, Some(99));
        assert_eq!(order(&glyphs), vec![99, 1, 2, 0, 3]);
    }

    /// A face with no U+25CC gets no circle, which is the honest answer: there
    /// is nothing to draw.
    #[test]
    fn a_face_without_a_dotted_circle_gains_no_glyphs() {
        let mut glyphs = run("\u{A9B6}");
        let mut ranges = Vec::new();
        clusters(&glyphs, &mut ranges);
        syllabic::stamp(&mut glyphs, &ranges, Cluster::code);
        reorder(&mut glyphs, None);
        assert_eq!(glyphs.len(), 1);
    }

    /// A run of Latin passes through untouched, which is what lets a mixed run
    /// go through one shaper.
    #[test]
    fn a_latin_run_passes_through_untouched() {
        let mut glyphs = run("ab");
        let before = order(&glyphs);
        let mut ranges = Vec::new();
        clusters(&glyphs, &mut ranges);
        // `O` heads a symbol cluster, one per character.
        assert_eq!(
            ranges,
            vec![(0, 1, Cluster::Symbol), (1, 2, Cluster::Symbol)]
        );
        syllabic::stamp(&mut glyphs, &ranges, Cluster::code);
        reorder(&mut glyphs, Some(99));
        assert_eq!(order(&glyphs), before);
    }
}
