/* Generated by posix/tools/oracle/obstack_harness.py from glibc 2.39's
 * answers; do not edit. services/ctest-obstack/build.py says what it is. */
#define _GNU_SOURCE
#define SLATEOS_FIXTURE

#include <obstack.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

#ifdef SLATEOS_FIXTURE
/* The lines, collected, to be compared with glibc's at the end. */
static char text[1 << 16];
static size_t text_len;

static void OUT(const char *fmt, ...) __attribute__((__format__(__printf__, 1, 2)));
static void OUT(const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    int n = vsnprintf(text + text_len, sizeof text - text_len, fmt, ap);
    va_end(ap);
    if (n > 0 && (size_t) n < sizeof text - text_len)
        text_len += (size_t) n;
}
#else
# define OUT printf
#endif

static void (*obstack_alloc_failed_handler_default)(void);
static const char *const SCEN[] = {"init", "steps", "size1", "size64", "size100", "size128", "size255", "size4095", "size9000", "align1", "align2", "align4", "align8", "align16", "align32", "align256", "mask", "grows", "free", "empty", "emptyfirst", "move", "newchunk", "witharg", "fails"};
static const char *const OPS0[] = {"begin:0:0", "grow:10", "finish", "grow:4000", "finish", "grow:5000", "finish", "alloc:1", "alloc:4064", "alloc:100000"};
static const char *const OPS1[] = {"begin:0:0", "grow:1", "grow:2", "grow:3", "grow:500", "grow:1000", "grow:1500", "grow:2000", "grow:4000", "finish", "1grow:65", "1grow:66", "1grow:67", "1grow:68", "1grow:69", "finish"};
static const char *const OPS2[] = {"begin:1:0", "grow:50", "finish", "grow:200", "finish", "alloc:1000", "copy:30", "copy0:30"};
static const char *const OPS3[] = {"begin:64:0", "grow:50", "finish", "grow:200", "finish", "alloc:1000", "copy:30", "copy0:30"};
static const char *const OPS4[] = {"begin:100:0", "grow:50", "finish", "grow:200", "finish", "alloc:1000", "copy:30", "copy0:30"};
static const char *const OPS5[] = {"begin:128:0", "grow:50", "finish", "grow:200", "finish", "alloc:1000", "copy:30", "copy0:30"};
static const char *const OPS6[] = {"begin:255:0", "grow:50", "finish", "grow:200", "finish", "alloc:1000", "copy:30", "copy0:30"};
static const char *const OPS7[] = {"begin:4095:0", "grow:50", "finish", "grow:200", "finish", "alloc:1000", "copy:30", "copy0:30"};
static const char *const OPS8[] = {"begin:9000:0", "grow:50", "finish", "grow:200", "finish", "alloc:1000", "copy:30", "copy0:30"};
static const char *const OPS9[] = {"begin:0:1", "grow:3", "finish", "alloc:5", "alloc:17", "grow:1", "finish", "copy0:4"};
static const char *const OPS10[] = {"begin:0:2", "grow:3", "finish", "alloc:5", "alloc:17", "grow:1", "finish", "copy0:4"};
static const char *const OPS11[] = {"begin:0:4", "grow:3", "finish", "alloc:5", "alloc:17", "grow:1", "finish", "copy0:4"};
static const char *const OPS12[] = {"begin:0:8", "grow:3", "finish", "alloc:5", "alloc:17", "grow:1", "finish", "copy0:4"};
static const char *const OPS13[] = {"begin:0:16", "grow:3", "finish", "alloc:5", "alloc:17", "grow:1", "finish", "copy0:4"};
static const char *const OPS14[] = {"begin:0:32", "grow:3", "finish", "alloc:5", "alloc:17", "grow:1", "finish", "copy0:4"};
static const char *const OPS15[] = {"begin:0:256", "grow:3", "finish", "alloc:5", "alloc:17", "grow:1", "finish", "copy0:4"};
static const char *const OPS16[] = {"begin:0:0", "mask:0", "alloc:3", "alloc:3", "mask:7", "alloc:3", "mask:255", "alloc:3", "alloc:300"};
static const char *const OPS17[] = {"begin:200:0", "1grow:120", "1grow:0", "ptr:1234", "int:-5", "blank:20", "blank:-3", "grow0:7", "finish", "room:5000", "grow:10", "finish", "blank:0", "finish"};
static const char *const OPS18[] = {"begin:0:0", "alloc:10", "alloc:3000", "alloc:3000", "alloc:3000", "free:#3", "free:#2", "alloc:10", "free:#1", "alloc:5000", "freeall"};
static const char *const OPS19[] = {"begin:0:0", "grow:100", "finish", "finish", "grow:4000", "finish", "grow:4000", "finish", "free:#2", "grow:5", "finish"};
static const char *const OPS20[] = {"begin:0:0", "finish", "grow:5000", "finish"};
static const char *const OPS21[] = {"begin:0:0", "grow:4000", "grow:100", "finish", "alloc:20", "grow:3000", "grow:3000", "finish"};
static const char *const OPS22[] = {"begin:0:0", "newchunk:0", "grow:7", "newchunk:1", "newchunk:100", "grow:900", "newchunk:5000", "finish", "newchunk:-1"};
static const char *const OPS23[] = {"begin1:300:8", "alloc:100", "alloc:250", "grow:600", "finish", "free:#1", "freeall"};
static const char *const OPS24[] = {"begin:0:0", "alloc:10", "fail:1", "alloc:5000", "alloc:10", "grow:9000", "finish"};
static const char *const *const OPS[] = {OPS0, OPS1, OPS2, OPS3, OPS4, OPS5, OPS6, OPS7, OPS8, OPS9, OPS10, OPS11, OPS12, OPS13, OPS14, OPS15, OPS16, OPS17, OPS18, OPS19, OPS20, OPS21, OPS22, OPS23, OPS24};
static const int NOPS[] = {10, 16, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 14, 11, 11, 4, 8, 9, 7, 7};
static const char *const PF[] = {"%d", "%s-%s", "%5000d", "%%", "", "%c%c", "x%sy", "%.3s"};
static const char *const PA[] = {"42", "ab", "7", "0", "0", "88", "long", "abcdef"};
static const char *const EXPECTED[] = {
    "D 4064 15 1 1",
    "S init begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S init grow:10 = 10 4038 16 26 4064 1 4064 0 [] 0",
    "S init finish = 0 4032 32 32 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S init grow:4000 = 4000 32 32 4032 4064 1 4064 0 [] 0",
    "S init finish = 0 32 4032 4032 4064 1 4064 0 [] 0 #2:0:32:ok",
    "S init grow:5000 = 5000 99 16 5016 5115 2 9179 0 [5115] 0",
    "S init finish = 0 91 5024 5024 5115 2 9179 0 [] 0 #3:0:16:ok",
    "S init alloc:1 = 0 75 5040 5040 5115 2 9179 0 [] 0 #4:0:5024:ok",
    "S init alloc:4064 = 0 99 4080 4080 4179 3 13358 0 [4179] 0 #5:0:16:ok",
    "S init alloc:100000 = 0 99 100016 100016 100115 4 113473 0 [100115] 0 #6:0:16:ok",
    "S steps begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S steps grow:1 = 1 4047 16 17 4064 1 4064 0 [] 0",
    "S steps grow:2 = 3 4045 16 19 4064 1 4064 0 [] 0",
    "S steps grow:3 = 6 4042 16 22 4064 1 4064 0 [] 0",
    "S steps grow:500 = 506 3542 16 522 4064 1 4064 0 [] 0",
    "S steps grow:1000 = 1506 2542 16 1522 4064 1 4064 0 [] 0",
    "S steps grow:1500 = 3006 1042 16 3022 4064 1 4064 0 [] 0",
    "S steps grow:2000 = 5006 474 16 5022 5496 1 5496 0 [5496] 1",
    "S steps grow:4000 = 9006 724 16 9022 9746 1 9746 0 [9746] 1",
    "S steps finish = 0 722 9024 9024 9746 1 9746 0 [] 0 #1:0:16:ok",
    "S steps 1grow:65 = 1 721 9024 9025 9746 1 9746 0 [] 0",
    "S steps 1grow:66 = 2 720 9024 9026 9746 1 9746 0 [] 0",
    "S steps 1grow:67 = 3 719 9024 9027 9746 1 9746 0 [] 0",
    "S steps 1grow:68 = 4 718 9024 9028 9746 1 9746 0 [] 0",
    "S steps 1grow:69 = 5 717 9024 9029 9746 1 9746 0 [] 0",
    "S steps finish = 0 706 9040 9040 9746 1 9746 0 [] 0 #2:0:9024:ok",
    "S size1 begin:1:0 = 0 4294967281 16 16 1 1 1 1 [1] 0",
    "S size1 grow:50 = 50 99 16 66 165 1 165 0 [165] 1",
    "S size1 finish = 0 85 80 80 165 1 165 0 [] 0 #1:0:16:ok",
    "S size1 grow:200 = 200 99 16 216 315 2 480 0 [315] 0",
    "S size1 finish = 0 91 224 224 315 2 480 0 [] 0 #2:0:16:ok",
    "S size1 alloc:1000 = 0 91 1024 1024 1115 3 1595 0 [1115] 0 #3:0:16:ok",
    "S size1 copy:30 = 0 59 1056 1056 1115 3 1595 0 [] 0 #4:0:1024:ok",
    "S size1 copy0:30 = 0 27 1088 1088 1115 3 1595 0 [] 0 #5:0:1056:ok",
    "S size64 begin:64:0 = 0 48 16 16 64 1 64 1 [64] 0",
    "S size64 grow:50 = 50 99 16 66 165 1 165 0 [165] 1",
    "S size64 finish = 0 85 80 80 165 1 165 0 [] 0 #1:0:16:ok",
    "S size64 grow:200 = 200 99 16 216 315 2 480 0 [315] 0",
    "S size64 finish = 0 91 224 224 315 2 480 0 [] 0 #2:0:16:ok",
    "S size64 alloc:1000 = 0 91 1024 1024 1115 3 1595 0 [1115] 0 #3:0:16:ok",
    "S size64 copy:30 = 0 59 1056 1056 1115 3 1595 0 [] 0 #4:0:1024:ok",
    "S size64 copy0:30 = 0 27 1088 1088 1115 3 1595 0 [] 0 #5:0:1056:ok",
    "S size100 begin:100:0 = 0 84 16 16 100 1 100 1 [100] 0",
    "S size100 grow:50 = 50 34 16 66 100 1 100 0 [] 0",
    "S size100 finish = 0 20 80 80 100 1 100 0 [] 0 #1:0:16:ok",
    "S size100 grow:200 = 200 99 16 216 315 2 415 0 [315] 0",
    "S size100 finish = 0 91 224 224 315 2 415 0 [] 0 #2:0:16:ok",
    "S size100 alloc:1000 = 0 91 1024 1024 1115 3 1530 0 [1115] 0 #3:0:16:ok",
    "S size100 copy:30 = 0 59 1056 1056 1115 3 1530 0 [] 0 #4:0:1024:ok",
    "S size100 copy0:30 = 0 27 1088 1088 1115 3 1530 0 [] 0 #5:0:1056:ok",
    "S size128 begin:128:0 = 0 112 16 16 128 1 128 1 [128] 0",
    "S size128 grow:50 = 50 62 16 66 128 1 128 0 [] 0",
    "S size128 finish = 0 48 80 80 128 1 128 0 [] 0 #1:0:16:ok",
    "S size128 grow:200 = 200 99 16 216 315 2 443 0 [315] 0",
    "S size128 finish = 0 91 224 224 315 2 443 0 [] 0 #2:0:16:ok",
    "S size128 alloc:1000 = 0 91 1024 1024 1115 3 1558 0 [1115] 0 #3:0:16:ok",
    "S size128 copy:30 = 0 59 1056 1056 1115 3 1558 0 [] 0 #4:0:1024:ok",
    "S size128 copy0:30 = 0 27 1088 1088 1115 3 1558 0 [] 0 #5:0:1056:ok",
    "S size255 begin:255:0 = 0 239 16 16 255 1 255 1 [255] 0",
    "S size255 grow:50 = 50 189 16 66 255 1 255 0 [] 0",
    "S size255 finish = 0 175 80 80 255 1 255 0 [] 0 #1:0:16:ok",
    "S size255 grow:200 = 200 99 16 216 315 2 570 0 [315] 0",
    "S size255 finish = 0 91 224 224 315 2 570 0 [] 0 #2:0:16:ok",
    "S size255 alloc:1000 = 0 91 1024 1024 1115 3 1685 0 [1115] 0 #3:0:16:ok",
    "S size255 copy:30 = 0 59 1056 1056 1115 3 1685 0 [] 0 #4:0:1024:ok",
    "S size255 copy0:30 = 0 27 1088 1088 1115 3 1685 0 [] 0 #5:0:1056:ok",
    "S size4095 begin:4095:0 = 0 4079 16 16 4095 1 4095 1 [4095] 0",
    "S size4095 grow:50 = 50 4029 16 66 4095 1 4095 0 [] 0",
    "S size4095 finish = 0 4015 80 80 4095 1 4095 0 [] 0 #1:0:16:ok",
    "S size4095 grow:200 = 200 3815 80 280 4095 1 4095 0 [] 0",
    "S size4095 finish = 0 3807 288 288 4095 1 4095 0 [] 0 #2:0:80:ok",
    "S size4095 alloc:1000 = 0 2799 1296 1296 4095 1 4095 0 [] 0 #3:0:288:ok",
    "S size4095 copy:30 = 0 2767 1328 1328 4095 1 4095 0 [] 0 #4:0:1296:ok",
    "S size4095 copy0:30 = 0 2735 1360 1360 4095 1 4095 0 [] 0 #5:0:1328:ok",
    "S size9000 begin:9000:0 = 0 8984 16 16 9000 1 9000 1 [9000] 0",
    "S size9000 grow:50 = 50 8934 16 66 9000 1 9000 0 [] 0",
    "S size9000 finish = 0 8920 80 80 9000 1 9000 0 [] 0 #1:0:16:ok",
    "S size9000 grow:200 = 200 8720 80 280 9000 1 9000 0 [] 0",
    "S size9000 finish = 0 8712 288 288 9000 1 9000 0 [] 0 #2:0:80:ok",
    "S size9000 alloc:1000 = 0 7704 1296 1296 9000 1 9000 0 [] 0 #3:0:288:ok",
    "S size9000 copy:30 = 0 7672 1328 1328 9000 1 9000 0 [] 0 #4:0:1296:ok",
    "S size9000 copy0:30 = 0 7640 1360 1360 9000 1 9000 0 [] 0 #5:0:1328:ok",
    "S align1 begin:0:1 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S align1 grow:3 = 3 4045 16 19 4064 1 4064 0 [] 0",
    "S align1 finish = 0 4045 19 19 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S align1 alloc:5 = 0 4040 24 24 4064 1 4064 0 [] 0 #2:0:19:ok",
    "S align1 alloc:17 = 0 4023 41 41 4064 1 4064 0 [] 0 #3:0:24:ok",
    "S align1 grow:1 = 1 4022 41 42 4064 1 4064 0 [] 0",
    "S align1 finish = 0 4022 42 42 4064 1 4064 0 [] 0 #4:0:41:ok",
    "S align1 copy0:4 = 0 4017 47 47 4064 1 4064 0 [] 0 #5:0:42:ok",
    "S align2 begin:0:2 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S align2 grow:3 = 3 4045 16 19 4064 1 4064 0 [] 0",
    "S align2 finish = 0 4044 20 20 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S align2 alloc:5 = 0 4038 26 26 4064 1 4064 0 [] 0 #2:0:20:ok",
    "S align2 alloc:17 = 0 4020 44 44 4064 1 4064 0 [] 0 #3:0:26:ok",
    "S align2 grow:1 = 1 4019 44 45 4064 1 4064 0 [] 0",
    "S align2 finish = 0 4018 46 46 4064 1 4064 0 [] 0 #4:0:44:ok",
    "S align2 copy0:4 = 0 4012 52 52 4064 1 4064 0 [] 0 #5:0:46:ok",
    "S align4 begin:0:4 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S align4 grow:3 = 3 4045 16 19 4064 1 4064 0 [] 0",
    "S align4 finish = 0 4044 20 20 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S align4 alloc:5 = 0 4036 28 28 4064 1 4064 0 [] 0 #2:0:20:ok",
    "S align4 alloc:17 = 0 4016 48 48 4064 1 4064 0 [] 0 #3:0:28:ok",
    "S align4 grow:1 = 1 4015 48 49 4064 1 4064 0 [] 0",
    "S align4 finish = 0 4012 52 52 4064 1 4064 0 [] 0 #4:0:48:ok",
    "S align4 copy0:4 = 0 4004 60 60 4064 1 4064 0 [] 0 #5:0:52:ok",
    "S align8 begin:0:8 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S align8 grow:3 = 3 4045 16 19 4064 1 4064 0 [] 0",
    "S align8 finish = 0 4040 24 24 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S align8 alloc:5 = 0 4032 32 32 4064 1 4064 0 [] 0 #2:0:24:ok",
    "S align8 alloc:17 = 0 4008 56 56 4064 1 4064 0 [] 0 #3:0:32:ok",
    "S align8 grow:1 = 1 4007 56 57 4064 1 4064 0 [] 0",
    "S align8 finish = 0 4000 64 64 4064 1 4064 0 [] 0 #4:0:56:ok",
    "S align8 copy0:4 = 0 3992 72 72 4064 1 4064 0 [] 0 #5:0:64:ok",
    "S align16 begin:0:16 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S align16 grow:3 = 3 4045 16 19 4064 1 4064 0 [] 0",
    "S align16 finish = 0 4032 32 32 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S align16 alloc:5 = 0 4016 48 48 4064 1 4064 0 [] 0 #2:0:32:ok",
    "S align16 alloc:17 = 0 3984 80 80 4064 1 4064 0 [] 0 #3:0:48:ok",
    "S align16 grow:1 = 1 3983 80 81 4064 1 4064 0 [] 0",
    "S align16 finish = 0 3968 96 96 4064 1 4064 0 [] 0 #4:0:80:ok",
    "S align16 copy0:4 = 0 3952 112 112 4064 1 4064 0 [] 0 #5:0:96:ok",
    "S align32 begin:0:32 = 0 4032 32 32 4064 1 4064 1 [4064] 0",
    "S align32 grow:3 = 3 4029 32 35 4064 1 4064 0 [] 0",
    "S align32 finish = 0 4000 64 64 4064 1 4064 0 [] 0 #1:0:32:ok",
    "S align32 alloc:5 = 0 3968 96 96 4064 1 4064 0 [] 0 #2:0:64:ok",
    "S align32 alloc:17 = 0 3936 128 128 4064 1 4064 0 [] 0 #3:0:96:ok",
    "S align32 grow:1 = 1 3935 128 129 4064 1 4064 0 [] 0",
    "S align32 finish = 0 3904 160 160 4064 1 4064 0 [] 0 #4:0:128:ok",
    "S align32 copy0:4 = 0 3872 192 192 4064 1 4064 0 [] 0 #5:0:160:ok",
    "S align256 begin:0:256 = 0 3808 256 256 4064 1 4064 1 [4064] 0",
    "S align256 grow:3 = 3 3805 256 259 4064 1 4064 0 [] 0",
    "S align256 finish = 0 3552 512 512 4064 1 4064 0 [] 0 #1:0:256:ok",
    "S align256 alloc:5 = 0 3296 768 768 4064 1 4064 0 [] 0 #2:0:512:ok",
    "S align256 alloc:17 = 0 3040 1024 1024 4064 1 4064 0 [] 0 #3:0:768:ok",
    "S align256 grow:1 = 1 3039 1024 1025 4064 1 4064 0 [] 0",
    "S align256 finish = 0 2784 1280 1280 4064 1 4064 0 [] 0 #4:0:1024:ok",
    "S align256 copy0:4 = 0 2528 1536 1536 4064 1 4064 0 [] 0 #5:0:1280:ok",
    "S mask begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S mask mask:0 = 0 4048 16 16 4064 1 4064 1 [] 0",
    "S mask alloc:3 = 0 4045 19 19 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S mask alloc:3 = 0 4042 22 22 4064 1 4064 0 [] 0 #2:0:19:ok",
    "S mask mask:7 = 0 4042 22 22 4064 1 4064 0 [] 0",
    "S mask alloc:3 = 0 4032 32 32 4064 1 4064 0 [] 0 #3:0:22:ok",
    "S mask mask:255 = 0 4032 32 32 4064 1 4064 0 [] 0",
    "S mask alloc:3 = 0 3808 256 256 4064 1 4064 1 [] 0 #4:0:32:ok",
    "S mask alloc:300 = 0 3296 768 768 4064 1 4064 0 [] 0 #5:0:256:ok",
    "S grows begin:200:0 = 0 184 16 16 200 1 200 1 [200] 0",
    "S grows 1grow:120 = 1 183 16 17 200 1 200 0 [] 0",
    "S grows 1grow:0 = 2 182 16 18 200 1 200 0 [] 0",
    "S grows ptr:1234 = 10 174 16 26 200 1 200 0 [] 0",
    "S grows int:-5 = 14 170 16 30 200 1 200 0 [] 0",
    "S grows blank:20 = 34 150 16 50 200 1 200 0 [] 0",
    "S grows blank:-3 = 31 153 16 47 200 1 200 0 [] 0",
    "S grows grow0:7 = 39 145 16 55 200 1 200 0 [] 0",
    "S grows finish = 0 136 64 64 200 1 200 0 [] 0 #1:0:16:ok",
    "S grows room:5000 = 0 5099 16 16 5115 2 5315 0 [5115] 0",
    "S grows grow:10 = 10 5089 16 26 5115 2 5315 0 [] 0",
    "S grows finish = 0 5083 32 32 5115 2 5315 0 [] 0 #2:0:16:ok",
    "S grows blank:0 = 0 5083 32 32 5115 2 5315 0 [] 0",
    "S grows finish = 0 5083 32 32 5115 2 5315 0 [] 0 #3:0:32:ok",
    "S free begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S free alloc:10 = 0 4032 32 32 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S free alloc:3000 = 0 1024 3040 3040 4064 1 4064 0 [] 0 #2:0:32:ok",
    "S free alloc:3000 = 0 1040 3024 3024 4064 2 8128 0 [4064] 0 #3:0:16:ok",
    "S free alloc:3000 = 0 1040 3024 3024 4064 3 12192 0 [4064] 0 #4:0:16:ok",
    "S free free:#3 = 0 4048 16 16 4064 2 8128 0 [] 1",
    "S free free:#2 = 0 4032 32 32 4064 1 4064 0 [] 1",
    "S free alloc:10 = 0 4016 48 48 4064 1 4064 0 [] 0 #5:0:32:ok",
    "S free free:#1 = 0 4048 16 16 4064 1 4064 1 [] 0",
    "S free alloc:5000 = 0 91 5024 5024 5115 2 9179 0 [5115] 0 #6:0:16:ok",
    "S free freeall = freed 2",
    "S empty begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S empty grow:100 = 100 3948 16 116 4064 1 4064 0 [] 0",
    "S empty finish = 0 3936 128 128 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S empty finish = 0 3936 128 128 4064 1 4064 0 [] 0 #2:0:128:ok",
    "S empty grow:4000 = 4000 99 16 4016 4115 2 8179 0 [4115] 0",
    "S empty finish = 0 99 4016 4016 4115 2 8179 0 [] 0 #3:0:16:ok",
    "S empty grow:4000 = 4000 99 16 4016 4115 3 12294 0 [4115] 0",
    "S empty finish = 0 99 4016 4016 4115 3 12294 0 [] 0 #4:0:16:ok",
    "S empty free:#2 = 0 3936 128 128 4064 1 4064 0 [] 2",
    "S empty grow:5 = 5 3931 128 133 4064 1 4064 0 [] 0",
    "S empty finish = 0 3920 144 144 4064 1 4064 0 [] 0 #5:0:128:ok",
    "S emptyfirst begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S emptyfirst finish = 0 4048 16 16 4064 1 4064 1 [] 0 #1:0:16:ok",
    "S emptyfirst grow:5000 = 5000 99 16 5016 5115 2 9179 0 [5115] 0",
    "S emptyfirst finish = 0 91 5024 5024 5115 2 9179 0 [] 0 #2:0:16:ok",
    "S move begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S move grow:4000 = 4000 48 16 4016 4064 1 4064 0 [] 0",
    "S move grow:100 = 4100 599 16 4116 4715 1 4715 0 [4715] 1",
    "S move finish = 0 587 4128 4128 4715 1 4715 0 [] 0 #1:0:16:ok",
    "S move alloc:20 = 0 555 4160 4160 4715 1 4715 0 [] 0 #2:0:4128:ok",
    "S move grow:3000 = 3000 1048 16 3016 4064 2 8779 0 [4064] 0",
    "S move grow:3000 = 6000 474 16 6016 6490 2 11205 0 [6490] 1",
    "S move finish = 0 474 6016 6016 6490 2 11205 0 [] 0 #3:0:16:ok",
    "S newchunk begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S newchunk newchunk:0 = 0 4048 16 16 4064 1 4064 1 [4064] 1",
    "S newchunk grow:7 = 7 4041 16 23 4064 1 4064 0 [] 0",
    "S newchunk newchunk:1 = 7 4041 16 23 4064 1 4064 0 [4064] 1",
    "S newchunk newchunk:100 = 7 4041 16 23 4064 1 4064 0 [4064] 1",
    "S newchunk grow:900 = 907 3141 16 923 4064 1 4064 0 [] 0",
    "S newchunk newchunk:5000 = 907 5212 16 923 6135 1 6135 0 [6135] 1",
    "S newchunk finish = 0 5207 928 928 6135 1 6135 0 [] 0 #1:0:16:ok",
    "S newchunk newchunk:-1 = 0 4048 16 16 4064 2 10199 0 [4064] 0",
    "S witharg begin1:300:8 = 0 284 16 16 300 1 300 1 [300] 0",
    "S witharg alloc:100 = 0 180 120 120 300 1 300 0 [] 0 #1:0:16:ok",
    "S witharg alloc:250 = 0 85 272 272 357 2 657 0 [357] 0 #2:0:16:ok",
    "S witharg grow:600 = 600 91 16 616 707 3 1364 0 [707] 0",
    "S witharg finish = 0 91 616 616 707 3 1364 0 [] 0 #3:0:16:ok",
    "S witharg free:#1 = 0 284 16 16 300 1 300 1 [] 2",
    "S witharg freeall = freed 1",
    "S fails begin:0:0 = 0 4048 16 16 4064 1 4064 1 [4064] 0",
    "S fails alloc:10 = 0 4032 32 32 4064 1 4064 0 [] 0 #1:0:16:ok",
    "S fails fail:1 = 0 4032 32 32 4064 1 4064 0 [] 0",
    "S fails alloc:5000 = failed",
    "S fails alloc:10 = 0 4016 48 48 4064 1 4064 0 [] 0 #2:0:32:ok",
    "S fails grow:9000 = 9000 99 16 9016 9115 2 13179 0 [9115] 0",
    "S fails finish = 0 91 9024 9024 9115 2 13179 0 [] 0 #3:0:16:ok",
    "P %d 42 = 2 3 3c3432",
    "P %s-%s ab = 3 4 3c612d62",
    "P %5000d 7 = 5000 5001 3c202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020...24fbac21fcf4d453",
    "P %% 0 = 1 2 3c25",
    "P \\- 0 = 0 1 3c",
    "P %c%c 88 = 2 3 3c3838",
    "P x%sy long = 6 7 3c786c6f6e6779",
    "P %.3s abcdef = 3 4 3c616263",
    "F default = 6d656d6f7279206578686175737465640a 7"
};

static long allocs[64];
static int nalloc, nfree, fail_in;
static jmp_buf jb;

static void *chunk(long size)
{
    if (fail_in > 0 && --fail_in == 0)
        return NULL;
    if (nalloc < 64)
        allocs[nalloc] = size;
    nalloc++;
    return aligned_alloc(4096, (size_t) ((size + 4095) / 4096) * 4096);
}

static void unchunk(void *p)
{
    nfree++;
    free(p);
}

static void *chunk1(void *arg, long size)
{
    if (arg != (void *) 0x5eed)
        abort();
    return chunk(size);
}

static void unchunk1(void *arg, void *p)
{
    if (arg != (void *) 0x5eed)
        abort();
    unchunk(p);
}

static void jump_out(void)
{
    longjmp(jb, 1);
}

static unsigned char pattern[200000];
static char *objs[64];
static int nobj;

static int chunks_in(struct obstack *h)
{
    int n = 0;
    for (struct _obstack_chunk *c = h->chunk; c; c = c->prev)
        n++;
    return n;
}

/* The chunk an address is in, counted back from the current one, and its
 * offset there; -1 for none. */
static void where(struct obstack *h, char *p, int *which, long *off)
{
    int k = 0;
    for (struct _obstack_chunk *c = h->chunk; c; c = c->prev, k++)
        if ((char *) c < p && p <= c->limit) {
            *which = k;
            *off = (long) (p - (char *) c);
            return;
        }
    *which = -1;
    *off = 0;
}

static void state(struct obstack *h, int obj, int good)
{
    char *base = (char *) h->chunk;
    OUT("%u %u %ld %ld %ld %d %d %d [", obstack_object_size(h), obstack_room(h),
        (long) (h->object_base - base), (long) (h->next_free - base),
        (long) (h->chunk_limit - base), chunks_in(h), obstack_memory_used(h),
        obstack_empty_p(h) ? 1 : 0);
    for (int k = 0; k < nalloc && k < 64; k++)
        OUT("%s%ld", k ? "," : "", allocs[k]);
    OUT("] %d", nfree);
    if (obj >= 0) {
        int which;
        long off;
        where(h, objs[obj], &which, &off);
        OUT(" #%d:%d:%ld:%s", obj + 1, which, off, good ? "ok" : "bad");
    }
    OUT("\n");
    nalloc = nfree = 0;
}

static void run_ops(const char *name, const char *const *ops, int n)
{
    /* Static, as what changes between a setjmp and its longjmp must be. */
    static struct obstack ob;
    static int live;
    struct obstack *h = &ob;
    nobj = 0;
    nalloc = nfree = fail_in = live = 0;
    obstack_alloc_failed_handler = jump_out;
    for (int i = 0; i < n; i++) {
        const char *op = ops[i];
        OUT("S %s %s = ", name, op);
        if (setjmp(jb)) {
            OUT("failed\n");
            nalloc = nfree = 0;
            continue;
        }
        long a = 0, b = 0;
        int obj = -1, good = 1;
        if (sscanf(op, "begin:%ld:%ld", &a, &b) == 2) {
            obstack_specify_allocation(h, (int) a, (int) b, chunk, unchunk);
            live = 1;
        } else if (sscanf(op, "begin1:%ld:%ld", &a, &b) == 2) {
            obstack_specify_allocation_with_arg(h, (int) a, (int) b, chunk1, unchunk1,
                                                (void *) 0x5eed);
            live = 1;
        } else if (sscanf(op, "mask:%ld", &a) == 1)
            obstack_alignment_mask(h) = (int) a;
        else if (sscanf(op, "grow0:%ld", &a) == 1)
            obstack_grow0(h, pattern, (int) a);
        else if (sscanf(op, "grow:%ld", &a) == 1)
            obstack_grow(h, pattern, (int) a);
        else if (sscanf(op, "1grow:%ld", &a) == 1)
            obstack_1grow(h, (char) a);
        else if (sscanf(op, "ptr:%ld", &a) == 1)
            obstack_ptr_grow(h, (void *) a);
        else if (sscanf(op, "int:%ld", &a) == 1)
            obstack_int_grow(h, (int) a);
        else if (sscanf(op, "blank:%ld", &a) == 1)
            obstack_blank(h, (int) a);
        else if (sscanf(op, "room:%ld", &a) == 1)
            obstack_make_room(h, (int) a);
        else if (sscanf(op, "newchunk:%ld", &a) == 1)
            _obstack_newchunk(h, (int) a);
        else if (sscanf(op, "fail:%ld", &a) == 1)
            fail_in = (int) a;
        else if (sscanf(op, "free:#%ld", &a) == 1)
            obstack_free(h, objs[a - 1]);
        else if (!strcmp(op, "freeall")) {
            /* Which leaves h->chunk pointing at a chunk given back. */
            obstack_free(h, NULL);
            live = 0;
            OUT("freed %d\n", nfree);
            nalloc = nfree = 0;
            continue;
        } else {
            int size = (int) obstack_object_size(h);
            char *p;
            if (!strcmp(op, "finish"))
                p = obstack_finish(h);
            else if (sscanf(op, "alloc:%ld", &a) == 1) {
                p = obstack_alloc(h, (int) a);
                memset(p, 0x5a, (size_t) a);
                size = (int) a;
            } else if (sscanf(op, "copy0:%ld", &a) == 1) {
                p = obstack_copy0(h, pattern, (int) a);
                size = (int) a;
                good = p[a] == 0;
            } else if (sscanf(op, "copy:%ld", &a) == 1) {
                p = obstack_copy(h, pattern, (int) a);
                size = (int) a;
            } else {
                OUT("bad op\n");
                continue;
            }
            if (op[0] == 'c')
                good = good && memcmp(p, pattern, (size_t) size) == 0;
            objs[nobj] = p;
            obj = nobj++;
        }
        state(h, obj, good);
    }
    if (live)
        obstack_free(h, NULL);
}

static void p_case(const char *fmt, const char *arg)
{
    struct obstack ob;
    obstack_specify_allocation(&ob, 0, 0, chunk, unchunk);
    obstack_grow(&ob, "<", 1);
    int r;
    if (!strcmp(fmt, "%d") || !strcmp(fmt, "%5000d"))
        r = obstack_printf(&ob, fmt, atoi(arg));
    else if (!strcmp(fmt, "%c%c"))
        r = obstack_printf(&ob, fmt, arg[0], arg[1]);
    else if (!strcmp(fmt, "%s-%s"))
        r = obstack_printf(&ob, fmt, "a", "b");
    else
        r = obstack_printf(&ob, fmt, arg);
    int size = (int) obstack_object_size(&ob);
    char *p = obstack_finish(&ob);
    OUT("P %s %s = %d %d ", *fmt ? fmt : "\\-", arg, r, size);
    for (int k = 0; k < size && k < 64; k++)
        OUT("%02x", (unsigned char) p[k]);
    if (size > 64) {
        unsigned long sum = 0;
        for (int k = 0; k < size; k++)
            sum = sum * 31 + (unsigned char) p[k];
        OUT("...%lx", sum);
    }
    OUT("\n");
    obstack_free(&ob, NULL);
}

static void f_case(void)
{
    int fds[2];
    if (pipe(fds))
        return;
    fflush(stdout);
    pid_t pid = fork();
    if (pid == 0) {
        dup2(fds[1], 2);
        struct obstack ob;
        obstack_exit_failure = 7;
        obstack_alloc_failed_handler = obstack_alloc_failed_handler_default;
        fail_in = 1;
        obstack_specify_allocation(&ob, 0, 0, chunk, unchunk);
        _exit(99);
    }
    close(fds[1]);
    char buf[256];
    int n = (int) read(fds[0], buf, sizeof buf - 1);
    buf[n > 0 ? n : 0] = 0;
    int st = 0;
    waitpid(pid, &st, 0);
    OUT("F default = ");
    for (int k = 0; k < n; k++)
        OUT("%02x", (unsigned char) buf[k]);
    OUT(" %d\n", WIFEXITED(st) ? WEXITSTATUS(st) : -WTERMSIG(st));
}

#ifdef SLATEOS_FIXTURE
static void returns_quietly(void)
{
}

/* A failure handler that returns, which it must not: glibc's
 * _obstack_newchunk goes on through the null chunk and faults, this
 * library's aborts before the macro can write past the chunk it has
 * (design-decisions 1162) -- not glibc's answer, so no line of its. 1 if
 * the child ended as abort() ends one: exit status 134 here, SIGABRT where
 * there are signals. */
static int r_case(void)
{
    fflush(stdout);
    pid_t pid = fork();
    if (pid == 0) {
        struct obstack ob;
        obstack_alloc_failed_handler = returns_quietly;
        obstack_specify_allocation(&ob, 0, 0, chunk, unchunk);
        fail_in = 1;
        obstack_grow(&ob, pattern, 5000);
        _exit(99);
    }
    int st = 0;
    if (pid < 0 || waitpid(pid, &st, 0) != pid)
        return 0;
    return (WIFEXITED(st) && WEXITSTATUS(st) == 134) || (WIFSIGNALED(st) && WTERMSIG(st) == SIGABRT);
}
#endif

int main(void)
{
    obstack_alloc_failed_handler_default = obstack_alloc_failed_handler;
    for (unsigned k = 0; k < sizeof pattern; k++)
        pattern[k] = (unsigned char) (k * 7 + 3);
    {
        struct obstack ob;
        obstack_specify_allocation(&ob, 0, 0, chunk, unchunk);
        OUT("D %ld %d %d %d\n", obstack_chunk_size(&ob), obstack_alignment_mask(&ob),
            obstack_exit_failure, obstack_alloc_failed_handler != NULL);
        obstack_free(&ob, NULL);
    }
    for (unsigned s = 0; s < sizeof SCEN / sizeof *SCEN; s++) {
#ifdef SLATEOS_FIXTURE
        run_ops(SCEN[s], OPS[s], NOPS[s]);
#else
        fflush(stdout);
        pid_t pid = fork();
        if (pid == 0) {
            run_ops(SCEN[s], OPS[s], NOPS[s]);
            fflush(stdout);
            _exit(0);
        }
        int st = 0;
        waitpid(pid, &st, 0);
        if (!WIFEXITED(st))
            OUT("S %s crash %d\n", SCEN[s], WTERMSIG(st));
#endif
    }
    obstack_alloc_failed_handler = obstack_alloc_failed_handler_default;
    for (unsigned k = 0; k < sizeof PF / sizeof *PF; k++)
        p_case(PF[k], PA[k]);
    nalloc = nfree = 0;
    f_case();
#ifdef SLATEOS_FIXTURE
    if (!r_case()) {
        printf("ctest-obstack: a failure handler that returned did not end the process "
               "as abort() does\n");
        return 2;
    }
    /* Each line against glibc's. */
    const char *at = text;
    for (unsigned k = 0; k < sizeof EXPECTED / sizeof *EXPECTED; k++) {
        size_t len = strlen(EXPECTED[k]);
        if (strncmp(at, EXPECTED[k], len) != 0 || at[len] != '\n') {
            const char *nl = strchr(at, '\n');
            printf("ctest-obstack: line %u is not glibc's:\n  want %s\n  got  %.*s\n", k + 1,
                   EXPECTED[k], nl ? (int) (nl - at) : (int) strlen(at), at);
            return 1;
        }
        at += len + 1;
    }
    if (*at) {
        printf("ctest-obstack: more lines than glibc's, from: %.60s\n", at);
        return 1;
    }
    printf("ctest-obstack: %u lines, each glibc's\n", (unsigned) (sizeof EXPECTED / sizeof *EXPECTED));
    return 42;
#else
    return 0;
#endif
}
