"""What the oracle harnesses in this directory share.

Every harness here asks glibc -- 2.39, Ubuntu 24.04's, under WSL -- what it
answers, and records the answers for posix's tests to replay: a C program,
generated or hand-written, built with gcc in WSL and run there. See
README.md for which harness feeds which test.

The C file and the binary are build products. They go in a temporary
directory (`workdir`), never next to the harness, so a run changes nothing in
the tree but the output it exists to write.

A harness whose output is a Rust table that a test carries pasted into its
source prints the table (`emit_table`); `--check` instead compares it with
the pasted copy, so that "this table is still what glibc says" is a command
rather than a belief.
"""

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
POSIX_SRC = HERE.parent.parent / "src"
DISTRO = "Ubuntu"


def wsl_path(p) -> str:
    """A Windows path as WSL mounts it: C:\\x\\y -> /mnt/c/x/y."""
    s = str(Path(p).resolve()).replace("\\", "/")
    return "/mnt/" + s[0].lower() + s[2:]


def workdir() -> tempfile.TemporaryDirectory:
    """A fresh directory for one run's build products, removed afterwards."""
    return tempfile.TemporaryDirectory(prefix="posix-oracle-")


def run(script: str) -> subprocess.CompletedProcess:
    """`script` under bash in WSL; stdout and stderr captured as text."""
    return subprocess.run(
        ["wsl", "-d", DISTRO, "--exec", "bash", "-c", script],
        capture_output=True, text=True, encoding="utf-8",
        env={**os.environ, "MSYS_NO_PATHCONV": "1"},
    )


def _squash(text: str) -> str:
    """The text with its whitespace gone and every comma before a closing
    bracket dropped: what `cargo fmt` cannot change about a table. It reflows
    a long tuple over several lines, adding a trailing comma, and the two
    copies must still compare equal."""
    text = re.sub(r"\s+", "", text)
    return re.sub(r",([)\]}])", r"\1", text)


def emit_table(text: str, source: str) -> None:
    """Print `text`, a Rust table pasted into `posix/src/<source>`'s tests; or,
    with `--check` on the command line, say whether the pasted copy is still
    this (ignoring layout, which `cargo fmt` owns) and exit 1 if not.

    To update the pasted copy: run the harness, paste its output over the
    block that begins with the same `// Generated by` line, `cargo fmt`."""
    if "--check" in sys.argv:
        pasted = (POSIX_SRC / source).read_text(encoding="utf-8")
        if _squash(text) in _squash(pasted):
            print(f"posix/src/{source}: the pasted table is still glibc's answers")
            return
        print(f"posix/src/{source}: the pasted table differs from glibc's answers now")
        sys.exit(1)
    sys.stdout.write(text)
