"""Run hosts_oracle.c under WSL, in a sandbox with this module's /etc/hosts and
/etc/host.conf and no network, once per host.conf: the Rust test data
posix/src/hosts.rs's tests carry pasted.

    python posix/tools/oracle/hosts_harness.py           # print the table
    python posix/tools/oracle/hosts_harness.py --check   # compare with hosts.rs's

The sandbox is `unshare -r -n -m`: a user, network and mount namespace, no
root needed, with this module's files bind-mounted over /etc.
"""
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _wsl import emit_table, workdir, wsl_path  # noqa: E402

HERE = Path(__file__).resolve().parent

HOSTS = (
    b"# The test's hosts file\n"
    b"127.0.0.1\tlocalhost\n"
    b"127.0.1.1\tmyhost.example.com\tmyhost\n"
    b"::1\tlocalhost ip6-localhost ip6-loopback\n"
    b"10.0.0.1 multi.example multi\n"
    b"10.0.0.2 multi.example\n"
    b"fe80::1 multi.example multi6\n"
    b"127.0.0.5 Multi.Example local5\n"
    b"::ffff:192.168.9.9 mapped.example mapped\n"
    b"192.168.1.10 Case.Example ALIAS\n"
    b"bad.address badline\n"
    b"1.2.3.4\n"
    b"1.2.3.5 twice\n"
    b"1.2.3.6 twice  # comment\n"
    b"0x7f000002 hexaddr\n"
    b"010.0.0.1 octaddr\n"
    b"fe80::2%eth0 scoped\n"
    b"2001:db8::5 v6only v6alias\n"
    b"10.9.9.9 trim.example.com trimalias.example.com other.example.org\n"
    b"  172.16.0.1   spaced   sp2\t\n"
    b"172.16.0.2 nul\x00hidden\n"
)

CONFS = {
    "plain": b"# nothing\n",
    "multi": b"multi on\nreorder on\ntrim example.com\n",
}

CMDS = """\
byname localhost
byname LOCALHOST
byname myhost
byname myhost.example.com
byname ip6-localhost
byname2 ip6-localhost 10
byname2 localhost 10
byname multi.example
byname multi
byname2 multi.example 10
byname multi6
byname2 multi6 10
byname mapped
byname2 mapped 10
byname case.example
byname alias
byname badline
byname twice
byname hexaddr
byname octaddr
byname scoped
byname2 v6only 10
byname2 v6alias 10
byname v6only
byname spaced
byname sp2
byname nul
byname hidden
byname 1.2.3.4
byname 1.2.3.4.
byname 127.1
byname 0x7f000001
byname2 ::1 10
byname ::1
byname2 1.2.3.4 10
byname2 ::ffff:1.2.3.4 10
byname abc:def
byname2 abc:def 10
byname2 abc:def. 10
byname nothere
byname -
byname2 localhost 99
byaddr 127.0.0.1 2 4
byaddr 10.0.0.2 2 4
byaddr ::1 10 16
byaddr ::ffff:127.0.0.1 10 16
byaddr 10.9.9.9 2 4
byaddr 1.1.1.1 2 4
byaddr :: 10 16
byaddr 127.0.0.1 10 4
byaddr 127.0.0.1 2 16
byaddr 2001:db8::5 10 16
small localhost 20
small localhost 60
small localhost 200
small 1.2.3.4 40
small 1.2.3.4 60
small example.com 10
small zzz 10
small multi.example 60
nr localhost
nr nothere
nr2 localhost 10
nr2 1.2.3.4 10
ent
"""


def run(work: Path, conf_name: str) -> tuple:
    d = work / conf_name
    d.mkdir(exist_ok=True)
    (d / "hosts").write_bytes(HOSTS)
    (d / "host.conf").write_bytes(CONFS[conf_name])
    (d / "resolv.conf").write_bytes(b"nameserver 10.255.255.1\noptions timeout:1 attempts:1\n")
    (d / "nsswitch.conf").write_bytes(b"hosts: files dns\n")
    (work / "cmds").write_text(CMDS, newline="\n")
    w = wsl_path(d)
    o = wsl_path(work)
    files = " ".join(f"{w}/{n}" for n in ("hosts", "host.conf", "resolv.conf", "nsswitch.conf"))
    script = (
        f"cd {o} && gcc -O0 -Wall -o hosts_oracle {wsl_path(HERE)}/hosts_oracle.c && "
        f"unshare -r -n -m sh -c 'ip link set lo up; e=/tmp/etch.$$; mkdir -p $e && mount -t tmpfs none $e && "
        f"(cp -a /etc/. $e/ 2>/dev/null; true) && rm -f $e/hosts $e/host.conf $e/resolv.conf $e/nsswitch.conf && "
        f"cp {files} $e/ && mount --bind $e /etc && "
        f"./hosts_oracle < {wsl_path(work)}/cmds'"
    )
    out = subprocess.run(["wsl", "-d", "Ubuntu", "--exec", "bash", "-c", script],
                         capture_output=True)
    if out.returncode != 0:
        print(out.stderr.decode(errors="replace"))
        raise SystemExit(out.returncode)
    err = out.stderr.decode(errors="replace")
    return out.stdout.decode(), err


def rust_bytes(b: bytes) -> str:
    out = []
    for c in b:
        if c == 0x22:
            out.append('\\"')
        elif c == 0x5C:
            out.append("\\\\")
        elif c == 0x0A:
            out.append("\\n")
        elif c == 0x09:
            out.append("\\t")
        elif 0x20 <= c < 0x7F:
            out.append(chr(c))
        else:
            out.append("\\x%02x" % c)
    return 'b"' + "".join(out) + '"'


def rust_str_block(name: str, text: str) -> list:
    lines = [f"    const {name}: &str = \"\\"]
    for l in text.splitlines():
        assert '"' not in l and "\\" not in l, l
        lines.append(l + "\\n\\")
    lines.append("\";")
    return lines


def main():
    lines = ["    // Generated by posix/tools/oracle/hosts_harness.py: the files, the commands, and",
             "    // what glibc 2.39 printed for them (hosts_oracle.c), with no network."]
    lines.append(f"    const HOSTS_FILE: &[u8] = {rust_bytes(HOSTS)};")
    for name, conf in CONFS.items():
        lines.append(f"    const CONF_{name.upper()}: &[u8] = {rust_bytes(conf)};")
    lines += rust_str_block("COMMANDS", CMDS)
    with workdir() as tmp:
        for name in CONFS:
            out, err = run(Path(tmp), name)
            lines += rust_str_block(f"GLIBC_{name.upper()}", out)
            lines += rust_str_block(f"GLIBC_{name.upper()}_STDERR", err)
    emit_table("\n".join(lines) + "\n", "hosts.rs")


if __name__ == "__main__":
    main()
