"""glibc 2.39's <mcheck.h> -- mcheck, mcheck_pedantic, mcheck_check_all,
mprobe, mtrace and muntrace -- as the oracle for posix/src/mcheck.rs.

    python posix/tools/oracle/mcheck_harness.py   # writes posix/src/mcheck_oracle.txt

Since glibc 2.34 the working versions live in libc_malloc_debug.so, which a
program gets by preloading it; libc has only what answers without it. A
static program -- every program here -- cannot preload anything, so what
it gets is libc's: the probe is linked statically, and run with
MALLOC_TRACE set, to show that the variable asks for nothing either. One
line a probe, `<probe> = <answer> errno=<kept|changed>`, and whether the
trace file was made.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _wsl import POSIX_SRC, run, workdir, wsl_path  # noqa: E402

OUT = POSIX_SRC / "mcheck_oracle.txt"

PROGRAM = r'''
#include <errno.h>
#include <mcheck.h>
#include <stdio.h>
#include <stdlib.h>

static void abortfunc(enum mcheck_status s) { (void)s; }

static const char *kept(void) { return errno == 12345 ? "kept" : "changed"; }

int main(void)
{
    setvbuf(stdout, NULL, _IONBF, 0);
    errno = 12345;
    int rc = mcheck(NULL);
    printf("mcheck(NULL) = %d errno=%s\n", rc, kept());
    errno = 12345;
    rc = mcheck(abortfunc);
    printf("mcheck(abortfunc) = %d errno=%s\n", rc, kept());
    errno = 12345;
    rc = mcheck_pedantic(NULL);
    printf("mcheck_pedantic(NULL) = %d errno=%s\n", rc, kept());
    void *p = malloc(10);
    errno = 12345;
    printf("mprobe(block) = %d errno=%s\n", (int)mprobe(p), kept());
    free(p);
    errno = 12345;
    mcheck_check_all();
    printf("mcheck_check_all() errno=%s\n", kept());
    errno = 12345;
    mtrace();
    printf("mtrace() errno=%s\n", kept());
    p = malloc(20);
    free(p);
    errno = 12345;
    muntrace();
    printf("muntrace() errno=%s\n", kept());
    printf("MCHECK_DISABLED=%d MCHECK_OK=%d MCHECK_FREE=%d MCHECK_HEAD=%d MCHECK_TAIL=%d\n",
           MCHECK_DISABLED, MCHECK_OK, MCHECK_FREE, MCHECK_HEAD, MCHECK_TAIL);
    return 0;
}
'''


def main() -> None:
    with workdir() as t:
        d = Path(t)
        (d / "mc.c").write_text(PROGRAM, encoding="utf-8", newline="\n")
        w = wsl_path(d)
        script = (
            f"set -e; cp {w}/mc.c /tmp/ && cd /tmp && rm -f /tmp/mtrace.out && "
            "gcc -static -O0 -Wall -Werror -o mcprobe mc.c > gcc.log 2>&1 "
            "|| { cat gcc.log >&2; exit 1; }; "
            "MALLOC_TRACE=/tmp/mtrace.out /tmp/mcprobe; "
            "if [ -e /tmp/mtrace.out ]; then echo 'MALLOC_TRACE file made'; "
            "else echo 'MALLOC_TRACE file not made'; fi"
        )
        r = run(script)
        if r.returncode != 0 or "muntrace" not in r.stdout:
            sys.exit(f"the harness failed:\n{r.stderr}\n{r.stdout[-2000:]}")
        body = r.stdout
    head = ("# glibc 2.39's <mcheck.h>, statically linked, for posix/src/mcheck.rs.\n"
            "# Generated by posix/tools/oracle/mcheck_harness.py; do not edit.\n")
    OUT.write_text(head + body, encoding="utf-8", newline="\n")
    print(f"{OUT.name}: {body.count(chr(10))} lines")


if __name__ == "__main__":
    main()
