"""glibc 2.39's ntp_gettime and ntp_gettimex (<sys/timex.h>) as the oracle
for posix/src/sys_timex.rs.

    python posix/tools/oracle/ntp_harness.py   # writes posix/src/ntp_oracle.txt

What the two give is the clock's -- adjtimex's with no modes -- so the probes
record how they give it, not the values: which of struct ntptimeval's nine
words each writes (the struct filled with 0x55 first: `w` written, `-` left),
and whether what it wrote is adjtimex's, read just before and after (the
maximum error grows by the second while the clock is unsynchronised, so it
may lie between the two). `ntp_gettime` is the library's symbol, reached
past the header, which sends the name to ntp_gettimex (`header ntp_gettime`,
compiled against glibc's <sys/timex.h> as a program would be).
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _wsl import POSIX_SRC, run, workdir, wsl_path  # noqa: E402

OUT = POSIX_SRC / "ntp_oracle.txt"

PROGRAM = r'''
#define _GNU_SOURCE
#include <errno.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <sys/timex.h>

/* The library's own ntp_gettime, which the header redirects to
 * ntp_gettimex. */
extern int ntp_gettime_symbol(struct ntptimeval *) __asm__("ntp_gettime");

static void probe(const char *what, int (*fn)(struct ntptimeval *))
{
    struct timex before, after;
    struct ntptimeval v;
    memset(&v, 0x55, sizeof v);
    memset(&before, 0, sizeof before);
    memset(&after, 0, sizeof after);
    int want = adjtimex(&before);
    errno = 12345;
    int rc = fn(&v);
    int err = errno;
    adjtimex(&after);
    const unsigned char *b = (const unsigned char *)&v;
    char written[16];
    size_t words = sizeof v / 8;
    for (size_t i = 0; i < words; i++) {
        int kept = 1;
        for (size_t j = 0; j < 8; j++)
            if (b[i * 8 + j] != 0x55) kept = 0;
        written[i] = kept ? '-' : 'w';
    }
    written[words] = '\0';
    int time_ok = v.time.tv_sec >= before.time.tv_sec && v.time.tv_sec <= after.time.tv_sec;
    int max_ok = v.maxerror >= before.maxerror && v.maxerror <= after.maxerror;
    int est_ok = v.esterror == before.esterror || v.esterror == after.esterror;
    int tai_ok = v.tai == before.tai || v.tai == after.tai;
    printf("%s = %s written=%s errno=%s time=%s maxerror=%s esterror=%s",
           what, rc == want ? "adjtimex's" : "other", written,
           err == 12345 ? "kept" : "changed", time_ok ? "adjtimex's" : "other",
           max_ok ? "adjtimex's" : "other", est_ok ? "adjtimex's" : "other");
    if (written[4] == 'w')
        printf(" tai=%s reserved=%ld,%ld,%ld,%ld", tai_ok ? "adjtimex's" : "other",
               v.__glibc_reserved1, v.__glibc_reserved2, v.__glibc_reserved3,
               v.__glibc_reserved4);
    printf("\n");
}

static int through_header(struct ntptimeval *v) { return ntp_gettime(v); }

int main(void)
{
    printf("sizeof(struct ntptimeval) = %zu\n", sizeof(struct ntptimeval));
    printf("offsetof tai = %zu, __glibc_reserved1 = %zu\n",
           offsetof(struct ntptimeval, tai), offsetof(struct ntptimeval, __glibc_reserved1));
    probe("ntp_gettime", ntp_gettime_symbol);
    probe("ntp_gettimex", ntp_gettimex);
    probe("header ntp_gettime", through_header);
    return 0;
}
'''


def main() -> None:
    with workdir() as t:
        d = Path(t)
        (d / "ntp.c").write_text(PROGRAM, encoding="utf-8", newline="\n")
        w = wsl_path(d)
        script = (f"set -e; cd {w} && gcc -O0 -Wall -Werror -o /tmp/ntpprobe ntp.c "
                  "&& /tmp/ntpprobe")
        r = run(script)
        if r.returncode != 0 or "ntp_gettimex =" not in r.stdout:
            sys.exit(f"the harness failed:\n{r.stderr}\n{r.stdout[-2000:]}")
        body = r.stdout
    head = ("# glibc 2.39's ntp_gettime and ntp_gettimex, for posix/src/sys_timex.rs.\n"
            "# Generated by posix/tools/oracle/ntp_harness.py; do not edit.\n")
    OUT.write_text(head + body, encoding="utf-8", newline="\n")
    print(f"{OUT.name}: {body.count(chr(10))} lines")


if __name__ == "__main__":
    main()
