"""glibc 2.39's <stdbit.h> -- C23's bit utilities -- as the oracle for
posix/src/stdbit.rs: the fourteen functions for each of the five standard
unsigned types.

    python posix/tools/oracle/stdbit_harness.py   # writes posix/src/stdbit_oracle.txt

Two kinds of line:

    <function> <x> = <result>
    digest <function> <hash>

The first for the edges -- 0, 1, the maximum and its neighbours, every
power of two and its neighbours, alternating bits -- and a fixed sample of
others, for every type; values in hex. The second for `unsigned char` and
`unsigned short`, whose every value is called: the 64-bit FNV-1a of the
results in order, each result folded in whole (`h = (h ^ r) * prime`), so
that 65,536 answers take one line.

Each function is called as `(name)(x)`: glibc's header makes most of them
macros over inline code as well, and the parentheses keep the call a call
into glibc.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _wsl import POSIX_SRC, run, workdir, wsl_path  # noqa: E402

OUT = POSIX_SRC / "stdbit_oracle.txt"

FAMILIES = ["leading_zeros", "leading_ones", "trailing_zeros", "trailing_ones",
            "first_leading_zero", "first_leading_one", "first_trailing_zero",
            "first_trailing_one", "count_zeros", "count_ones", "has_single_bit",
            "bit_width", "bit_floor", "bit_ceil"]
TYPES = {"uc": ("unsigned char", 8), "us": ("unsigned short", 16), "ui": ("unsigned int", 32),
         "ul": ("unsigned long", 64), "ull": ("unsigned long long", 64)}
EXHAUSTIVE = ("uc", "us")


def samples(bits: int) -> list[int]:
    mx = (1 << bits) - 1
    out = {0, 1, 2, 3, mx, mx - 1, mx >> 1, (mx >> 1) + 1, 0x5555555555555555 & mx,
           0xAAAAAAAAAAAAAAAA & mx}
    for i in range(bits):
        p = 1 << i
        out |= {p, p - 1, (p + 1) & mx, mx ^ p}
    x = 0x2545F4914F6CDD1D
    for _ in range(48):  # a fixed xorshift sequence
        x ^= (x << 13) & 0xFFFFFFFFFFFFFFFF
        x ^= x >> 7
        x ^= (x << 17) & 0xFFFFFFFFFFFFFFFF
        out.add(x & mx)
    return sorted(out)


def program() -> str:
    lines = ["#include <stdbit.h>", "#include <stdint.h>", "#include <stdio.h>", "",
             "static uint64_t fold(uint64_t h, uint64_t r) { return (h ^ r) * 0x100000001b3ULL; }",
             "", "int main(void) {", "    uint64_t h;"]
    for sfx, (cty, bits) in TYPES.items():
        vals = ", ".join(f"{v:#x}ULL" for v in samples(bits))
        lines.append(f"    {{ static const unsigned long long v_{sfx}[] = {{{vals}}};")
        lines.append(f"      for (unsigned i = 0; i < sizeof v_{sfx} / sizeof v_{sfx}[0]; i++) {{")
        lines.append(f"        {cty} x = ({cty})v_{sfx}[i];")
        for fam in FAMILIES:
            fn = f"stdc_{fam}_{sfx}"
            lines.append(f'        printf("{fn} %llx = %llx\\n", (unsigned long long)x, '
                         f"(unsigned long long)({fn})(x));")
        lines.append("      } }")
        if sfx in EXHAUSTIVE:
            mx = (1 << bits) - 1
            for fam in FAMILIES:
                fn = f"stdc_{fam}_{sfx}"
                lines.append("    h = 0xcbf29ce484222325ULL;")
                lines.append(f"    for (unsigned long x = 0; x <= {mx:#x}UL; x++)")
                lines.append(f"        h = fold(h, (uint64_t)({fn})(({cty})x));")
                lines.append(f'    printf("digest {fn} %llx\\n", (unsigned long long)h);')
    lines += ["    return 0;", "}", ""]
    return "\n".join(lines)


def main() -> None:
    with workdir() as t:
        d = Path(t)
        (d / "stdbit.c").write_text(program(), encoding="utf-8", newline="\n")
        r = run(f"cd {wsl_path(d)} && gcc -std=c2x -O0 -fno-builtin -o stdbit stdbit.c && ./stdbit")
        if r.returncode != 0:
            sys.exit(f"the harness failed:\n{r.stderr}")
        body = r.stdout
    head = ("# glibc 2.39's <stdbit.h>, for posix/src/stdbit.rs: <function> <x> = <result>, in hex;\n"
            "# and, for every unsigned char and unsigned short, digest <function> <FNV-1a of the\n"
            "# results in order>. Generated by posix/tools/oracle/stdbit_harness.py; do not edit.\n")
    OUT.write_text(head + body, encoding="utf-8", newline="\n")
    print(f"{OUT.name}: {body.count(chr(10))} lines")


if __name__ == "__main__":
    main()
