"""glibc 2.39's names and descriptions of error and signal numbers --
strerror, strerrorname_np, strerrordesc_np, strsignal, sigabbrev_np and sigdescr_np --
as the oracle for posix/src/string.rs and signal.rs.

    python posix/tools/oracle/strname_harness.py   # writes posix/src/strname_oracle.txt

One line a call, for every number from -2 to 139 (errors) and -2 to 69
(signals), the answer quoted, or `NULL`:

    <function> <n> = "<text>" | NULL
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _wsl import POSIX_SRC, run, workdir, wsl_path  # noqa: E402

OUT = POSIX_SRC / "strname_oracle.txt"

PROGRAM = r'''
#define _GNU_SOURCE
#include <signal.h>
#include <stdio.h>
#include <string.h>

static void show(const char *fn, int n, const char *s)
{
    if (s)
        printf("%s %d = \"%s\"\n", fn, n, s);
    else
        printf("%s %d = NULL\n", fn, n);
}

int main(void)
{
    for (int e = -2; e < 140; e++) {
        show("strerror", e, strerror(e));
        show("strerrorname_np", e, strerrorname_np(e));
        show("strerrordesc_np", e, strerrordesc_np(e));
    }
    for (int s = -2; s < 70; s++) {
        show("strsignal", s, strsignal(s));
        show("sigabbrev_np", s, sigabbrev_np(s));
        show("sigdescr_np", s, sigdescr_np(s));
    }
    return 0;
}
'''


def main() -> None:
    with workdir() as t:
        d = Path(t)
        (d / "strname.c").write_text(PROGRAM, encoding="utf-8", newline="\n")
        r = run(f"cd {wsl_path(d)} && gcc -O0 -o strname strname.c && ./strname")
        if r.returncode != 0:
            sys.exit(f"the harness failed:\n{r.stderr}")
        body = r.stdout
    head = ("# glibc 2.39's strerror, strerrorname_np, strerrordesc_np, strsignal, sigabbrev_np and sigdescr_np, for\n"
            "# posix/src/string.rs and signal.rs: <function> <n> = \"<text>\" or NULL.\n"
            "# Generated by posix/tools/oracle/strname_harness.py; do not edit.\n")
    OUT.write_text(head + body, encoding="utf-8", newline="\n")
    print(f"{OUT.name}: {body.count(chr(10))} lines")


if __name__ == "__main__":
    main()
