"""glibc 2.39's strtod/strtof/wcstod/wcstof on NaN spellings, as the oracle
for posix/src/stdlib.rs's `GLIBC_NAN`: result bits, characters consumed,
errno.

    python posix/tools/oracle/strtod_nan_harness.py           # print the table
    python posix/tools/oracle/strtod_nan_harness.py --check   # compare with stdlib.rs's
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _wsl import emit_table, run, workdir, wsl_path  # noqa: E402

INPUTS = [
    "nan", "-nan", "+nan", "NAN", "NaN(1234)", "nan(0x12)", "nan(017)", "nan(abc)",
    "nan(1 2)", "nan(", "nan()", "-nan(0x8000000000000)", "nan(99999999999999999999999)",
    "nan(0x7ffffffffffff)", "  +nan(5)x", "nanx", "nan(_)", "nan(1_2)", "-nan(42)",
    "nan(0x)", "nan(08)", "nan(0x1g)", "nan(0X1F)", "nan(0x400000)", "nan(4194303)",
    "nan(4194304)", "nan(-1)",
]


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_c():
    lines = [
        "#include <stdio.h>", "#include <stdlib.h>", "#include <wchar.h>", "#include <errno.h>",
        "#include <string.h>", "#include <stdint.h>",
        "int main(void) {",
        f"  static const char *in[] = {{{', '.join(c_str(s) for s in INPUTS)}}};",
        f"  static const wchar_t *win[] = {{{', '.join('L' + c_str(s) for s in INPUTS)}}};",
        "  for (unsigned i = 0; i < sizeof in / sizeof in[0]; i++) {",
        "    char *end; wchar_t *wend; uint64_t b; uint32_t f;",
        "    errno = 0; double d = strtod(in[i], &end); int e = errno; memcpy(&b, &d, 8);",
        '    printf("strtod %u %016llx %d %d\\n", i, (unsigned long long)b, (int)(end - in[i]), e);',
        "    errno = 0; float g = strtof(in[i], &end); e = errno; memcpy(&f, &g, 4);",
        '    printf("strtof %u %08x %d %d\\n", i, f, (int)(end - in[i]), e);',
        "    errno = 0; d = wcstod(win[i], &wend); e = errno; memcpy(&b, &d, 8);",
        '    printf("wcstod %u %016llx %d %d\\n", i, (unsigned long long)b, (int)(wend - win[i]), e);',
        "    errno = 0; g = wcstof(win[i], &wend); e = errno; memcpy(&f, &g, 4);",
        '    printf("wcstof %u %08x %d %d\\n", i, f, (int)(wend - win[i]), e);',
        "  }",
        "  return 0;",
        "}",
    ]
    return "\n".join(lines) + "\n"


def main():
    with workdir() as tmp:
        (Path(tmp) / "strtod_nan_oracle.c").write_text(gen_c(), encoding="utf-8", newline="\n")
        r = run(f"cd {wsl_path(tmp)} && gcc -O0 -fno-builtin -w -o strtod_nan_oracle "
                "strtod_nan_oracle.c && ./strtod_nan_oracle")
    if r.returncode != 0:
        sys.exit(f"oracle failed:\n{r.stdout}\n{r.stderr}")
    rows = []
    for line in r.stdout.splitlines():
        fn, i, bits, consumed, err = line.split()
        rows.append(f'        ("{fn}", {c_str(INPUTS[int(i)])}, 0x{bits}, {consumed}, {err}),')
    body = ("    // Generated by posix/tools/oracle/strtod_nan_harness.py from glibc 2.39 under WSL:\n"
            "    // (function, input, result bits, characters consumed, errno).\n"
            "    const GLIBC_NAN: &[(&str, &str, u64, usize, i32)] = &[\n"
            + "\n".join(rows) + "\n    ];\n")
    emit_table(body, "stdlib.rs")


if __name__ == "__main__":
    main()
