#!/usr/bin/env python3
"""Vendor file 5.45's magic database into `userspace/file/magic/`.

`file` reads its rules from file 5.45's own magic database, the one upstream
compiles into `magic.mgc`: `magic/Header`, `magic/Localstuff` and every file
of `magic/Magdir`, which upstream's `magic/Makefile.am` copies into one
directory and compiles with `file -C -m magic`. This copies the same files
into `userspace/file/magic/` -- and nothing else, so that the directory is a
magic directory `file -m` can read as it stands -- and writes
`userspace/file/src/magdir.rs`, which
embeds them in the order libmagic's `apprentice_load` reads a directory --
names sorted by `strcmp` -- so the program carries its database rather than
depending on a file the image may not have.

    curl -sSfLO https://astron.com/pub/file/file-5.45.tar.gz
    python scripts/file-magic-vendor.py file-5.45.tar.gz

The tarball is pinned by SHA-256: a different one is refused rather than
silently producing a different database. Run it again only to move to a new
release, and then change the pin and the version in `file`'s `--version` in
the same commit.
"""

import hashlib
import io
import sys
import tarfile
from pathlib import Path

PINNED_SHA256 = "fc97f51029bb0e2c9f4e3bffefdaf678f0e039ee872b9de5c002a6d09c784d82"
TOP = "file-5.45"

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "userspace" / "file" / "magic"
TABLE = ROOT / "userspace" / "file" / "src" / "magdir.rs"


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: file-magic-vendor.py file-5.45.tar.gz", file=sys.stderr)
        return 2
    data = Path(sys.argv[1]).read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != PINNED_SHA256:
        print(f"refusing: {sys.argv[1]} has SHA-256 {digest}, not the pinned {PINNED_SHA256}",
              file=sys.stderr)
        return 1

    fragments = {}
    copying = None
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        for member in tar.getmembers():
            if not member.isfile():
                continue
            name = member.name
            body = tar.extractfile(member).read()
            if name == f"{TOP}/COPYING":
                copying = body
            elif name in (f"{TOP}/magic/Header", f"{TOP}/magic/Localstuff"):
                fragments[name.rsplit("/", 1)[1]] = body
            elif name.startswith(f"{TOP}/magic/Magdir/"):
                fragments[name.rsplit("/", 1)[1]] = body
    if copying is None or "Header" not in fragments or len(fragments) < 300:
        print("refusing: the tarball does not hold the expected magic files", file=sys.stderr)
        return 1

    # Replace what was there: a fragment upstream removed must not linger.
    if DEST.exists():
        for old in DEST.iterdir():
            old.unlink()
    DEST.mkdir(parents=True, exist_ok=True)
    # The licence is `userspace/file/licenses/file-COPYING`, where the image's
    # notices are gathered from, and heads `magdir.rs`.
    for name, body in fragments.items():
        (DEST / name).write_bytes(body)

    # `apprentice_load` sorts the directory's names with `strcmp`: bytes.
    names = sorted(fragments, key=lambda n: n.encode())
    notice = copying.decode("ascii").rstrip("\n")
    lines = ["// " + l if l else "//" for l in notice.split("\n")]
    out = []
    out.extend(lines)
    out.append("")
    out.append("//! file 5.45's magic database, embedded: generated by")
    out.append("//! `scripts/file-magic-vendor.py` from the pinned release tarball. Do not")
    out.append("//! edit; vendor a new release instead.")
    out.append("//!")
    out.append("//! The fragments are in the order libmagic's `apprentice_load` reads them")
    out.append("//! from a directory -- sorted by `strcmp` -- which is the order their")
    out.append("//! entries are numbered in before the strength sort, and so decides the")
    out.append("//! order of entries the sort finds equal.")
    out.append("")
    out.append("/// Each fragment's name and contents, in load order.")
    out.append("pub static FRAGMENTS: &[(&str, &[u8])] = &[")
    for n in names:
        out.append(f'    ("{n}", include_bytes!("../magic/{n}")),')
    out.append("];")
    out.append("")
    TABLE.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"vendored {len(names)} fragments into {DEST}, table {TABLE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
