"""Generate a searchable one-line index of every script, and refuse a stale one.

## Why

Three times on 2026-09-14 two lanes reasoned from first principles about a rule
this tree already enforced, and in each case the knowledge was in `scripts/`,
written by somebody who had already been burned:

* `rustscan.py` -- 418 lines, eleven days old -- documents in its opening
  paragraph the two traps ("a comment that mentions X", "a test that exercises
  X") that both lanes then rediscovered separately across two gates and four
  false positives. Lane C reached for that exact filename with `cat >` and
  destroyed it.
* `check-selftest-skips.py` governs precisely the question two lanes spent
  three messages arguing about -- whether a self-test may skip on an error from
  the code under test. Its first line says so.
* `create-ext4-rootfs.sh` prints "'[rootfs] DONE.' is the only line that means
  the image was rebuilt", which is the contract that stopped a false green.

Nobody lacked discipline. Nobody knew there was something to look **for**. An
index does not fix judgement; it makes "has this already been decided?" a
question you can ask by keyword instead of by remembering a filename.

## What it does and does not cover

**Covers** `scripts/**/*.py` (first line of the module docstring) and
`scripts/**/*.sh` (first `#` comment line after the shebang). Measured before
building: 225 of 225 Python files have a usable first line, and 133 of 134
shell files do.

**Does not cover the third case above, and this was checked rather than
assumed.** `create-ext4-rootfs.sh`'s header is "Build a real ext4
root-filesystem image for the SlateOS Linux-ABI layer" -- accurate, and it says
nothing about not trusting its exit code. A one-line summary answers *what does
this script do*, not *what does this script promise about its own output*. So
this scores **two of three** on its own test corpus, and the third needs
something a machine cannot extract from a docstring. Recorded here so the gap
is a known limit rather than a later disappointment.

## Staleness

Generated, never hand-edited, and `--check` fails when the file on disk differs
from what the sources produce. A hand-maintained index is a document that rots,
which is the failure this whole exercise is about.
"""

from __future__ import annotations

import ast
import io
import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import selftestflag  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "scripts" / "INDEX.md"
NL = chr(10)
HASH = chr(35)


def py_summary(text: str) -> str:
    try:
        doc = ast.get_docstring(ast.parse(text))
    except SyntaxError:
        return ""
    return (doc or "").strip().split(NL)[0].strip()


def sh_summary(text: str) -> str:
    """First `#` comment line after the shebang, shebang itself excluded."""
    for raw in text.split(NL)[1:12]:
        line = raw.strip()
        if line.startswith(HASH + "!"):
            continue
        if line.startswith(HASH):
            body = line.lstrip(HASH).strip()
            if body:
                return body
        elif line:
            break
    return ""


def entries() -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    base = ROOT / "scripts"
    for path in sorted(base.rglob("*")):
        if path.suffix not in (".py", ".sh") or "__pycache__" in path.parts:
            continue
        rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
        text = io.open(path, encoding="utf-8", errors="replace").read()
        s = py_summary(text) if path.suffix == ".py" else sh_summary(text)
        out.append((rel, s))
    return out


def render(rows: list[tuple[str, str]]) -> str:
    lines = [
        "# Script index",
        "",
        "**Generated by `scripts/gen-script-index.py`. Do not edit.**",
        "Run it to regenerate; `--check` refuses a stale copy.",
        "",
        "Search this by the *question you are asking*, not by the filename you",
        "would have guessed. It answers what a script does -- not what it",
        "promises about its own output, which a one-line summary cannot carry.",
        "",
        "| script | what it does |",
        "|---|---|",
    ]
    for rel, s in rows:
        cell = s.replace("|", "-") if s else "_(no summary line)_"
        lines.append("| `" + rel + "` | " + cell + " |")
    lines.append("")
    lines.append("_" + str(len(rows)) + " scripts._")
    lines.append("")
    return NL.join(lines)


def _self_test() -> int:
    cases = [
        ('"""First line here.' + NL + NL + 'More.' + NL + '"""' + NL, "py",
         "First line here.", "a module docstring's first line"),
        ("x = 1" + NL, "py", "", "no docstring gives no summary"),
        (HASH + "!/bin/sh" + NL + HASH + " Does a thing." + NL, "sh",
         "Does a thing.", "the first comment after a shebang"),
        (HASH + "!/bin/sh" + NL + NL + HASH + " After a blank." + NL, "sh",
         "After a blank.", "a blank line before the comment is skipped"),
        (HASH + "!/bin/sh" + NL + "echo hi" + NL + HASH + " too late" + NL, "sh",
         "", "a comment below real code is not a header"),
        (HASH + "!/bin/sh" + NL + HASH + NL + HASH + " Real one." + NL, "sh",
         "Real one.", "an empty comment line is not the summary"),
    ]
    failed = 0
    for text, kind, want, why in cases:
        got = py_summary(text) if kind == "py" else sh_summary(text)
        ok = got == want
        failed += 0 if ok else 1
        print("%s   %s (want %r, got %r)" % ("ok  " if ok else "FAIL", why, want, got))
    print()
    print("%d self-test case(s), %d failed" % (len(cases), failed))
    return 1 if failed else 0


def main(argv: list[str]) -> int:
    if selftestflag.wants_selftest(argv):
        return _self_test()
    check = "--check" in argv
    unknown = selftestflag.unknown_options(argv, known=("--check",))
    if unknown:
        print("gen-script-index: unknown option(s): " + ", ".join(unknown))
        return 2

    rows = entries()
    if not rows:
        print("gen-script-index: no scripts found under " + str(ROOT / "scripts"))
        return 2
    want = render(rows)
    missing = [r for r, s in rows if not s]

    if check:
        have = io.open(INDEX, encoding="utf-8").read() if INDEX.exists() else ""
        if have != want:
            print("gen-script-index: scripts/INDEX.md is stale. Regenerate:")
            print("    python scripts/gen-script-index.py")
            return 1
        print("ok -- scripts/INDEX.md is current (%d scripts, %d without a summary)."
              % (len(rows), len(missing)))
        return 0

    io.open(INDEX, "w", encoding="utf-8", newline="").write(want)
    print("wrote scripts/INDEX.md: %d scripts, %d without a summary line."
          % (len(rows), len(missing)))
    for r in missing:
        print("  no summary: " + r)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
