#!/bin/bash
# Measure GNU chmod's answer for a cross product of mode strings, starting
# modes, umasks and file kinds, and write it to stdout as the fixture
# `userspace/modechange/tests/data/gnu-chmod.txt`.
#
# Run under a GNU userland (here: WSL) as root, so that setuid/setgid/sticky on
# a regular file are not silently dropped by the kernel before we read them
# back. The starting mode is always *read back* rather than assumed, so a bit
# the kernel refuses to store simply produces a different — and still correct —
# row rather than a wrong one.
#
# Output columns, space separated:
#   start_octal  umask_octal  d|f  status  result_octal  spec
# `spec` is last because it is the only field that may contain anything; it
# never contains a space, since a mode string with one is invalid anyway and is
# recorded here with status 1.
set -u

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
cd "$WORK" || exit 1

SPECS=(
  # --- whole-string octal, including the short/long distinction --------------
  0 7 644 755 700 000 777 4755 2755 1777 7777 00755 02755 000755 0644
  8 9 778 10000 77777 '755x' '755,u+w'
  # --- who x op x single letter ---------------------------------------------
  u+r u+w u+x u+X u+s u+t u-r u-w u-x u-X u-s u-t u=r u=w u=x u=X u=s u=t
  g+r g+w g+x g+X g+s g+t g-r g-w g-x g-s g-t g=r g=w g=x g=X g=s g=t
  o+r o+w o+x o+X o+s o+t o-r o-w o-x o-s o-t o=r o=w o=x o=X o=s o=t
  a+r a+w a+x a+X a+s a+t a-r a-w a-x a-s a-t a=r a=w a=x a=X a=s a=t
  +r +w +x +X +s +t -r -w -x -X -s -t =r =w =x =X =s =t
  # --- no permissions at all -------------------------------------------------
  u+ u- u= g= o= a= + - =
  # --- multi-letter groups ---------------------------------------------------
  u+rw u+rx u+wx u+rwx u+rX u+sx u+st a+rwx a+rX a+rwxXst go-w go+rw ug+s
  ugo+r ugo=rx uga+r ao+x
  # --- copy sources ----------------------------------------------------------
  u+g u+o u-g u-o u=g u=o g+u g-u g=u o+u o-u o=u o+g o=g a=u a+u a=g a=o
  +u -u =u +g =g +o =o
  # --- chained operators inside one clause -----------------------------------
  u+r-w u+r-w+x u=r+w-r go+r-w a+rw-x u+x-x u=rwx-w +r-w
  # --- per-clause octal ------------------------------------------------------
  =644 +7 -111 =0 =7777 '=644,+111' '+1,+2,+4' u=644 a+7 '=644x' '=644+1' =10000
  # --- several clauses -------------------------------------------------------
  'u=rwx,g=rx,o=r' 'u+x,g=u' 'a=r,u+w' 'u+s,g+s,o+t' 'a+X,u-w' 'go-rwx,u+rw'
  'a=,u+rw' '755,u+w' 'u+r,' ',u+r' ','
  # --- rejected shapes -------------------------------------------------------
  '' u ug ugo '*' 'u*x' 'u+rZZZ' 'a+x!' 'u+q' 'U+r' 'A=r' 'u++r' 'u+-r'
)

STARTS=(000 644 755 700 600 010 777 2755 4644 1777 7777 0111)
UMASKS=(000 022 077 044 002)

# A floor on the row count, checked here before a single byte reaches stdout.
# The consuming test asserts the same floor at read time. Saying it twice is
# deliberate: a sweep that measured almost nothing — a `chmod` that is not
# GNU's, a `stat` without `-c`, a kernel refusing every mode — produces a short
# file, and a short file looks like success from both sides unless someone
# counts.
MIN_ROWS=20000

for kind in f d; do
  for start in "${STARTS[@]}"; do
    for umask_v in "${UMASKS[@]}"; do
      for spec in "${SPECS[@]}"; do
        rm -rf t
        if [ "$kind" = d ]; then mkdir t; else : > t; fi
        chmod "$start" t 2>/dev/null
        # Read the mode back: what the kernel actually stored is the input our
        # implementation will be given, whatever we asked for.
        actual=$(stat -c %a t)
        ( umask "$umask_v"; chmod -- "$spec" t ) >/dev/null 2>&1
        status=$?
        result=$(stat -c %a t)
        printf '%04o %s %s %d %04o %s\n' "0$actual" "$umask_v" "$kind" \
          "$status" "0$result" "${spec:-<empty>}"
      done
    done
  done
done > rows

rows=$(wc -l < rows)
if [ "$rows" -lt "$MIN_ROWS" ]; then
  printf 'gen-chmod-fixture: only %s rows measured, expected at least %s; \
refusing to install a truncated fixture\n' "$rows" "$MIN_ROWS" >&2
  exit 1
fi
printf '# Generated by scripts/gen-chmod-fixture.sh under %s.\n' \
  "$(chmod --version 2>/dev/null | head -1)"
printf '# start_octal umask_octal d|f status result_octal spec\n'
cat rows
