#!/usr/bin/env python3
"""Generate `userspace/getconf`'s variable table from glibc 2.39's getconf.c.

`getconf` is a table and a switch: each name it knows is a `sysconf`,
`pathconf` or `confstr` request for one constant (`_SC_ARG_MAX`, ...), listed
in `posix/getconf.c` in the order `getconf -a` prints them. The port takes the
table from upstream's source rather than retyping 319 rows, and the constants'
values from the C headers rather than from memory: the generator compiles a
probe that prints every constant the table names, with the C compiler and
glibc headers of the WSL reference system (Ubuntu 24.04, glibc 2.39), and
writes the two together as Rust.

Those values are the Linux x86_64 ABI's, which SlateOS's C library shares
(`posix/src/unistd.rs` numbers `_SC_ARG_MAX` 0, `_SC_PAGESIZE` 30 and so on);
`userspace/getconf`'s tests hold every constant SlateOS's library defines to
the value here, so a disagreement cannot pass silently. A name the library
does not implement is answered `undefined`, as glibc's getconf answers a name
its kernel does not support.

    python scripts/getconf-gen.py GETCONF_C OUTPUT_RS

GETCONF_C is glibc 2.39's posix/getconf.c, pinned by SHA-256 below; the
probe runs through `wsl`. The output is written with LF line ends.
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
import tempfile

#: posix/getconf.c at the glibc-2.39 tag.
GETCONF_SHA256 = "20a2d69e7377a28219c1fa758c5e17e3372288fa84b871f245a1f73cc8f64664"

ENTRY = re.compile(r'\{\s*"([^"]+)"\s*,\s*(_[A-Z0-9_]+)\s*,\s*(SYSCONF|CONFSTR|PATHCONF)\s*\}')
CALL = {"SYSCONF": "Sysconf", "CONFSTR": "Confstr", "PATHCONF": "Pathconf"}


def table(source: str) -> list[tuple[str, str, str]]:
    """`(name, constant, call)` for every row of `vars[]`, in order."""
    start = source.index("static const struct conf vars[] =")
    end = source.index("{ NULL, 0, SYSCONF }", start)
    rows = ENTRY.findall(source[start:end])
    if len(rows) < 300:
        sys.exit(f"getconf-gen: only {len(rows)} rows found in vars[]; the parse is wrong")
    return rows


def probe_source(constants: list[str]) -> str:
    lines = ["#include <unistd.h>", "#include <stdio.h>", "int main(void) {"]
    for c in constants:
        lines.append(f'  printf("%s %ld\\n", "{c}", (long) {c});')
    lines += ["  return 0;", "}", ""]
    return "\n".join(lines)


def measure(constants: list[str]) -> dict[str, int]:
    """Each constant's value, from the reference system's own headers."""
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "probe.c")
        with open(src, "w", encoding="utf-8", newline="\n") as f:
            f.write(probe_source(constants))
        drive, rest = os.path.splitdrive(os.path.abspath(src))
        wsl_src = f"/mnt/{drive[0].lower()}{rest.replace(os.sep, '/')}"
        script = (
            f"set -e; d=$(mktemp -d); cc -o \"$d/probe\" '{wsl_src}'; \"$d/probe\"; rm -rf \"$d\"\n"
        )
        out = subprocess.run(["wsl", "--", "bash", "-s"], input=script, capture_output=True,
                             text=True, encoding="utf-8", check=False)
        if out.returncode != 0:
            sys.exit(f"getconf-gen: the probe failed:\n{out.stderr}")
    values = {}
    for line in out.stdout.splitlines():
        name, value = line.split()
        values[name] = int(value)
    missing = [c for c in constants if c not in values]
    if missing:
        sys.exit(f"getconf-gen: the probe printed no value for {missing}")
    return values


def emit(rows: list[tuple[str, str, str]], values: dict[str, int]) -> str:
    out = [
        "// Generated by scripts/getconf-gen.py from glibc 2.39's posix/getconf.c",
        f"// (sha256 {GETCONF_SHA256[:16]}...) and the values its constants have in",
        "// glibc 2.39's headers on x86_64 Linux, which SlateOS's C library shares.",
        "// Do not edit: regenerate. Copyright (C) 1991-2024 Free Software",
        "// Foundation, Inc.; GPL-2.0-or-later, as the file it is generated from",
        "// (userspace/localtime/licenses/notices.yaml, the glibc entry).",
        "",
        "use crate::{Call, Var};",
        "",
        "/// `vars[]`: every name `getconf` answers to, in the order `-a` prints them.",
        "#[rustfmt::skip]",
        f"pub(crate) static VARS: [Var; {len(rows)}] = [",
    ]
    for name, const, call in rows:
        out.append(
            f'    Var {{ name: "{name}", constant: "{const}", '
            f"call: Call::{CALL[call]}({values[const]}) }},"
        )
    out += ["];", ""]
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    data = open(sys.argv[1], "rb").read()
    got = hashlib.sha256(data).hexdigest()
    if got != GETCONF_SHA256:
        sys.exit(f"getconf-gen: {sys.argv[1]} is not glibc 2.39's getconf.c (sha256 {got})")
    rows = table(data.decode("utf-8"))
    constants = sorted({const for _, const, _ in rows})
    values = measure(constants)
    with open(sys.argv[2], "w", encoding="utf-8", newline="\n") as f:
        f.write(emit(rows, values))
    print(f"getconf-gen: {len(rows)} names, {len(constants)} constants -> {sys.argv[2]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
