#!/usr/bin/env bash
# Differential test: our `patch` against GNU patch.
#
# ## Why this harness exists
#
# `patch` is one of the two duplicate pairs left under §1005 where `coreutils`
# is genuinely the thinner half. After `dup-bins-survey.py` was taught to count
# `coreutils`' shared modules -- the fix that moved seventeen other pairs --
# only `diff` and `patch` did not move at all, because neither of those bins
# reaches a shared module. `patch` is 892 lines against the standalone's 2183,
# and the option lists agree: nine against eighteen, with the standalone alone
# offering `-d`, `-f`, `-N`, `-F`, `-l`, `-o`, `-E` and `--no-backup-if-mismatch`.
#
# `diff` was measured first and became the first pair the standalone won, 43 to
# 21. This is the other candidate, and the same rule applies: an option list is
# a claim, not a measurement. Five verdicts drawn from option counts have been
# wrong in this tree.
#
# ## Why this harness compares the TREE and not just the output
#
# Every other harness here compares stdout, stderr and an exit status, because
# every other subject is a filter. `patch` is not: its output is a **side
# effect**, and a `patch` that printed the right words while writing the wrong
# bytes would pass any of them.
#
# So each case runs in two disposable copies of the same starting tree -- one
# per side -- and what is compared is the whole tree afterwards: every file,
# its mode, and a hash of its bytes, including the `.orig` backups and `.rej`
# reject files `patch` leaves behind. Those two are not incidental; a reject
# file is how `patch` tells you what it could not do, and an implementation
# that silently dropped it would look identical on stdout.
#
# ## Why the patches are generated by GNU diff
#
# The fixtures are produced by `/usr/bin/diff` at setup, not written by hand.
# This harness is about `patch`, so the input must be a patch nobody can argue
# with; a hand-written hunk header with a miscounted line range would test the
# harness author rather than the subject.
#
# ## Why the reference is the installed binary
#
# GNU patch is its own project, so `DIFF_GNU_SOURCE` -- which fetches coreutils
# -- cannot supply it. The reference is `/usr/bin/patch`, GNU patch 2.7.6,
# Ubuntu `2.7.6-7build3`. That `build3` suffix is a plain rebuild with no Debian
# source patches, which makes this the least-diverged reference of any harness
# here; §726's caveat about Ubuntu's heavily patched coreutils does not bite the
# same way. Recorded rather than assumed.
#
# ## The exit status
#
# `patch` answers 0 when everything applied, 1 when some hunks failed, and 2 for
# trouble. That is the whole of what a script calling `patch` can see, and the
# difference between 0 and 1 is the difference between a clean apply and a tree
# full of `.rej` files, so it is compared on every case.
set -u

DIFF_PROG='patch'
# Every invocation below is bounded, both sides. `patch` searching for a hunk
# with fuzz is a scan over the file for each offset, and a malformed patch is
# exactly the input that makes an implementation loop rather than refuse.
DIFF_NEED=timeout
# shellcheck source=diff-wsl.sh
. "$(dirname "$0")/diff-wsl.sh"

pass=0; fail=0; xfail=0; xpass=0

work=$DIFF_TMP/work
mkdir -p "$work"
cd "$work" >/dev/null || exit 1

# --- the starting tree, built once and copied per case ------------------------
proto=$work/proto
mkdir -p "$proto/a/sub"

printf 'alpha\nbravo\ncharlie\ndelta\n'                 > "$proto/a/base.txt"
printf 'alpha\nbravo\ncharlie\ndelta'                   > "$proto/a/nonl.txt"
printf 'nested\ncontent\nhere\n'                        > "$proto/a/sub/deep.txt"
{ for i in $(seq 1 40); do printf 'line %02d\n' "$i"; done; } > "$proto/a/long.txt"
# A file the patches will not touch, so a side that rewrote the whole tree is
# caught rather than merely a side that got one file wrong.
printf 'untouched\n'                                    > "$proto/a/keep.txt"

# --- the patches, produced by GNU diff ----------------------------------------
mk=$work/mk
mkdir -p "$mk"
cp "$proto/a/base.txt" "$mk/base.txt"
printf 'alpha\nbravo\nCHANGED\ndelta\n'                 > "$mk/base.new"
printf 'alpha\nbravo\ncharlie\ndelta\nadded\n'          > "$mk/base.append"
cp "$proto/a/nonl.txt" "$mk/nonl.txt"
printf 'alpha\nbravo\nCHANGED\ndelta'                   > "$mk/nonl.new"
cp "$proto/a/long.txt" "$mk/long.txt"
{ for i in $(seq 1 40); do
    case $i in 5|35) printf 'CHANGED %02d\n' "$i" ;; *) printf 'line %02d\n' "$i" ;; esac
  done; }                                               > "$mk/long.new"
cp "$proto/a/sub/deep.txt" "$mk/deep.txt"
printf 'nested\nCHANGED\nhere\n'                        > "$mk/deep.new"

# `diff` exits 1 when the files differ, which is the normal case here, so its
# status is deliberately not checked -- only that it wrote something.
patches=$work/patches
mkdir -p "$patches"

# Unified, with `a/` and `b/` prefixes so the strip level matters.
( cd "$mk" && /usr/bin/diff -u --label x/a/base.txt --label y/a/base.txt \
    base.txt base.new ) > "$patches/u.patch" || true
( cd "$mk" && /usr/bin/diff -c --label x/a/base.txt --label y/a/base.txt \
    base.txt base.new ) > "$patches/c.patch" || true
( cd "$mk" && /usr/bin/diff base.txt base.new ) > "$patches/n.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/base.txt --label y/a/base.txt \
    base.txt base.append ) > "$patches/append.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/long.txt --label y/a/long.txt \
    long.txt long.new ) > "$patches/long.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/nonl.txt --label y/a/nonl.txt \
    nonl.txt nonl.new ) > "$patches/nonl.patch" || true
# Two deep path components, so -p0, -p1 and -p2 all land somewhere different.
( cd "$mk" && /usr/bin/diff -u --label x/y/a/sub/deep.txt --label y/z/a/sub/deep.txt \
    deep.txt deep.new ) > "$patches/deep.patch" || true
# A patch that creates a file, and one that deletes it.
printf 'brand\nnew\n' > "$mk/created"
( cd "$mk" && /usr/bin/diff -u --label /dev/null --label y/a/created.txt \
    /dev/null created ) > "$patches/create.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/keep.txt --label /dev/null \
    "$proto/a/keep.txt" /dev/null ) > "$patches/delete.patch" || true
# A patch whose context no longer matches: the hunk is for a file that has moved
# on. This is what produces a `.rej`, and with `-F` what fuzz is for.
printf 'alpha\nDIFFERENT\ncharlie\ndelta\n'             > "$mk/drift.txt"
( cd "$mk" && /usr/bin/diff -u --label x/a/base.txt --label y/a/base.txt \
    drift.txt base.new ) > "$patches/drift.patch" || true
# Not a patch at all.
printf 'this is not a patch\nnor is this\n'             > "$patches/garbage.patch"
printf ''                                               > "$patches/empty.patch"
# A truncated hunk: the header promises four lines and two arrive.
printf -- '--- x/a/base.txt\n+++ y/a/base.txt\n@@ -1,4 +1,4 @@\n alpha\n-bravo\n' \
                                                        > "$patches/truncated.patch"

# --- comparing a whole tree ---------------------------------------------------
# Sorted, one line per entry, with type, mode and a content hash. `cksum` rather
# than the bytes so a long file does not drown the report, and the mode because
# `patch` is expected to preserve it and a backup is expected to inherit it.
snap() {
  ( cd "$1" && find . -mindepth 1 \( -type f -o -type d -o -type l \) -print \
      | LC_ALL=C sort \
      | while IFS= read -r e; do
          if [ -d "$e" ]; then
            printf 'd %s %s\n' "$e" "$(stat -c '%a' "$e")"
          elif [ -L "$e" ]; then
            printf 'l %s -> %s\n' "$e" "$(readlink "$e")"
          else
            printf 'f %s %s %s\n' "$e" "$(stat -c '%a' "$e")" "$(cksum < "$e")"
          fi
        done )
}

run_side() {
  local dir=$1 side=$2; shift 2
  ( cd "$dir" && diff_run timeout -k 2 30 \
      env LC_ALL=C.UTF-8 PATH="$bindir/$side" patch "$@" )
}

# `$1` is the patch file (absolute), the rest are `patch`'s arguments. stdin is
# the patch when no `-i` is given, which is how `patch` is normally driven.
compare() {
  local pfile=$1 use_stdin=$2; shift 2
  local o_dir g_dir o_out g_out o_err g_err o_rc g_rc
  o_dir=$(mktemp -d); g_dir=$(mktemp -d)
  cp -a "$proto/." "$o_dir/"; cp -a "$proto/." "$g_dir/"
  o_err=$(mktemp); g_err=$(mktemp)
  local o_bin g_bin; o_bin=$(mktemp); g_bin=$(mktemp)

  if [ "$use_stdin" = yes ]; then
    run_side "$o_dir" ours "$@" <"$pfile" >"$o_bin" 2>"$o_err"; o_rc=$?
    run_side "$g_dir" gnu  "$@" <"$pfile" >"$g_bin" 2>"$g_err"; g_rc=$?
  else
    run_side "$o_dir" ours "$@" </dev/null >"$o_bin" 2>"$o_err"; o_rc=$?
    run_side "$g_dir" gnu  "$@" </dev/null >"$g_bin" 2>"$g_err"; g_rc=$?
  fi

  o_out=$(od -An -c <"$o_bin"); g_out=$(od -An -c <"$g_bin")
  local o_msg g_msg o_tree g_tree
  o_msg=$(cat "$o_err"); g_msg=$(cat "$g_err")
  o_tree=$(snap "$o_dir"); g_tree=$(snap "$g_dir")
  rm -f "$o_bin" "$g_bin" "$o_err" "$g_err"
  rm -rf "$o_dir" "$g_dir"

  if [ "$o_out" = "$g_out" ] && [ "$o_rc" = "$g_rc" ] \
     && [ "$o_msg" = "$g_msg" ] && [ "$o_tree" = "$g_tree" ]; then
    AGREED=yes
  else
    AGREED=no
  fi
  # The tree is the part most likely to hold the answer, so it is printed even
  # when the difference is elsewhere -- a wrong message with a right tree and a
  # right message with a wrong tree are very different findings.
  REPORT=$(printf '  ours (rc=%s): %s {%s}\n    tree: %s\n  gnu  (rc=%s): %s {%s}\n    tree: %s' \
    "$o_rc" "$(printf '%s' "$o_out" | tr -s ' \n' ' ')" "$(printf '%s' "$o_msg" | tr '\n' '|')" \
    "$(printf '%s' "$o_tree" | tr '\n' '|')" \
    "$g_rc" "$(printf '%s' "$g_out" | tr -s ' \n' ' ')" "$(printf '%s' "$g_msg" | tr '\n' '|')" \
    "$(printf '%s' "$g_tree" | tr '\n' '|')")
}

report() {
  local label="$1"
  if [ "$AGREED" = yes ]; then
    pass=$((pass+1))
    [ -n "${VERBOSE:-}" ] && printf 'OK   %s\n' "$label"
  else
    fail=$((fail+1))
    printf 'DIFF %s\n%s\n' "$label" "$REPORT"
  fi
  return 0
}

# The patch arrives via `-i`, and STDIN IS CLOSED. That is not a stylistic
# choice: when GNU patch cannot find the file to patch it asks "File to patch:"
# on stdin, and if stdin is the patch it eats the rest of the patch as answers.
# The harness's first run hit exactly that and reported 65 differences that were
# all the same mistake. `-i` plus `</dev/null` needs no option either side might
# lack, and GNU then reads EOF and skips the hunk deterministically.
run_case() {
  local p=$1; shift
  compare "$patches/$p" no -i "$patches/$p" "$@"
  report "patch -i $p $*"
}
# The other way in: the patch on stdin. Reserved for cases that apply cleanly,
# since those are the ones that cannot reach the prompt.
run_stdin() {
  local p=$1; shift
  compare "$patches/$p" yes "$@"
  report "patch $* < $p"
}
xfail_case() {
  local why=$1 p=$2; shift 2
  compare "$patches/$p" yes "$@"
  if [ "$AGREED" = yes ]; then
    xpass=$((xpass+1))
    printf 'XPASS patch %s < %s -- expected to differ (%s) and did not\n' "$*" "$p" "$why"
  else
    xfail=$((xfail+1))
    [ -n "${VERBOSE:-}" ] && printf 'xfail patch %s < %s (%s)\n' "$*" "$p" "$why"
  fi
  return 0
}

# --- the three patch formats, applied straight --------------------------------
run_case u.patch -p1
run_case c.patch -p1
run_case n.patch a/base.txt
run_case append.patch -p1
run_case long.patch -p1
run_stdin u.patch -p1
run_stdin c.patch -p1

# --- strip levels -------------------------------------------------------------
run_case deep.patch -p0
run_case deep.patch -p1
run_case deep.patch -p2
run_case deep.patch -p3
run_case u.patch -p0
run_case u.patch -p2
run_case u.patch -p99
run_case u.patch
run_case u.patch -p abc

# --- naming the target explicitly ---------------------------------------------
run_case u.patch -p1 a/base.txt
run_case u.patch a/base.txt
run_case n.patch a/nosuch.txt
run_case u.patch -p1 a/keep.txt

# --- reverse, and already-applied ----------------------------------------------
run_case u.patch -p1 -R
run_case u.patch -p1 --reverse
run_case drift.patch -p1
run_case drift.patch -p1 -N
run_case drift.patch -p1 --forward
run_case drift.patch -p1 -F 3
run_case drift.patch -p1 --fuzz=3
run_case drift.patch -p1 -f
run_case drift.patch -p1 --force

# --- dry run, which must leave the tree exactly as it was ----------------------
run_case u.patch -p1 --dry-run
run_case drift.patch -p1 --dry-run
run_case u.patch -p1 --dry-run -R

# --- backups and rejects --------------------------------------------------------
run_case u.patch -p1 -b
run_case u.patch -p1 --backup
run_case drift.patch -p1 -b
run_case drift.patch -p1 -r myrejects
run_case drift.patch -p1 --no-backup-if-mismatch
run_case u.patch -p1 -Z

# --- quiet and verbose ----------------------------------------------------------
run_case u.patch -p1 -s
run_case u.patch -p1 --quiet
run_case u.patch -p1 --silent
run_case drift.patch -p1 -s
run_case u.patch -p1 -v
run_case u.patch -p1 --verbose

# --- output redirection and directory -------------------------------------------
run_case u.patch -p1 -o out.txt
run_case u.patch -p1 --output=out.txt
run_case u.patch -p1 -d a
run_case u.patch -p0 -d a
run_case u.patch -p1 --directory=a

# --- creating and deleting files -------------------------------------------------
run_case create.patch -p1
run_case delete.patch -p1
run_case delete.patch -p1 -E
run_case delete.patch -p1 --remove-empty-files

# --- the no-newline marker, which `diff` gets wrong on both sides -----------------
run_case nonl.patch -p1
run_case nonl.patch -p1 -b

# --- whitespace -------------------------------------------------------------------
run_case u.patch -p1 -l
run_case u.patch -p1 --ignore-whitespace

# --- input that is not a patch -----------------------------------------------------
run_case garbage.patch -p1
run_case empty.patch -p1
run_case truncated.patch -p1
run_case garbage.patch
run_case empty.patch

# --- refusals -----------------------------------------------------------------------
run_case nosuch.patch -p1
run_case u.patch -p1 --nosuchoption
run_case u.patch -p1 -Q

# --- the two whose text is ours ------------------------------------------------------
xfail_case "our help text, not the GNU project's" empty.patch --help
xfail_case "our version string, not the GNU project's" empty.patch --version

printf '\n%d passed, %d differed, %d differ on purpose' "$pass" "$fail" "$xfail"
if [ "$xpass" -gt 0 ]; then
  printf ', %d NO LONGER differ (update the harness)' "$xpass"
fi
printf '\n'
[ -n "${DIFF_SKIPPED:-}" ] && printf 'skipped:%s\n' "$DIFF_SKIPPED"
[ "$fail" = 0 ] && [ "$xpass" = 0 ]
