#!/usr/bin/env bash
# Differential test: our `patch` against GNU patch.
#
# ## Why this harness exists
#
# `patch` is one of the two duplicate pairs left under §1005 where `coreutils`
# is genuinely the thinner half. After `dup-bins-survey.py` was taught to count
# `coreutils`' shared modules -- the fix that moved seventeen other pairs --
# only `diff` and `patch` did not move at all, because neither of those bins
# reaches a shared module. `patch` is 892 lines against the standalone's 2183,
# and the option lists agree: nine against eighteen, with the standalone alone
# offering `-d`, `-f`, `-N`, `-F`, `-l`, `-o`, `-E` and `--no-backup-if-mismatch`.
#
# `diff` was measured first and became the first pair the standalone won, 43 to
# 21. This is the other candidate, and the same rule applies: an option list is
# a claim, not a measurement. Five verdicts drawn from option counts have been
# wrong in this tree.
#
# ## Why this harness compares the TREE and not just the output
#
# Every other harness here compares stdout, stderr and an exit status, because
# every other subject is a filter. `patch` is not: its output is a **side
# effect**, and a `patch` that printed the right words while writing the wrong
# bytes would pass any of them.
#
# So each case runs in two disposable copies of the same starting tree -- one
# per side -- and what is compared is the whole tree afterwards: every file,
# its mode, and a hash of its bytes, including the `.orig` backups and `.rej`
# reject files `patch` leaves behind. Those two are not incidental; a reject
# file is how `patch` tells you what it could not do, and an implementation
# that silently dropped it would look identical on stdout.
#
# ## Why the patches are generated by GNU diff
#
# The fixtures are produced by `/usr/bin/diff` at setup, not written by hand.
# This harness is about `patch`, so the input must be a patch nobody can argue
# with; a hand-written hunk header with a miscounted line range would test the
# harness author rather than the subject.
#
# ## Why the reference is the installed binary
#
# GNU patch is its own project, so `DIFF_GNU_SOURCE` -- which fetches coreutils
# -- cannot supply it. The reference is `/usr/bin/patch`, GNU patch 2.7.6,
# Ubuntu `2.7.6-7build3`. That `build3` suffix is a plain rebuild with no Debian
# source patches, which makes this the least-diverged reference of any harness
# here; §726's caveat about Ubuntu's heavily patched coreutils does not bite the
# same way. Recorded rather than assumed.
#
# ## The exit status
#
# `patch` answers 0 when everything applied, 1 when some hunks failed, and 2 for
# trouble. That is the whole of what a script calling `patch` can see, and the
# difference between 0 and 1 is the difference between a clean apply and a tree
# full of `.rej` files, so it is compared on every case.
set -u

DIFF_PROG='patch'
# Every invocation below is bounded, both sides. `patch` searching for a hunk
# with fuzz is a scan over the file for each offset, and a malformed patch is
# exactly the input that makes an implementation loop rather than refuse.
DIFF_NEED=timeout
# shellcheck source=diff-wsl.sh
. "$(dirname "$0")/diff-wsl.sh"

pass=0; fail=0; xfail=0; xpass=0

work=$DIFF_TMP/work
mkdir -p "$work"
cd "$work" >/dev/null || exit 1

# --- the starting tree, built once and copied per case ------------------------
proto=$work/proto
mkdir -p "$proto/a/sub"

printf 'alpha\nbravo\ncharlie\ndelta\n'                 > "$proto/a/base.txt"
printf 'alpha\nbravo\ncharlie\ndelta'                   > "$proto/a/nonl.txt"
printf 'nested\ncontent\nhere\n'                        > "$proto/a/sub/deep.txt"
{ for i in $(seq 1 40); do printf 'line %02d\n' "$i"; done; } > "$proto/a/long.txt"
# Indented with a TAB, where ws.patch below is built against a copy indented
# with four SPACES. This is the fixture `-l` exists for: without the flag the
# hunk must be REFUSED, with it the hunk must APPLY.
printf 'start\n\tindented a b\nend\n'                     > "$proto/a/ws.txt"
# Already carries the change applied.patch makes, so applying that patch to it
# trips the reversed/already-applied detection. This is the only shape `-N`
# changes the answer for.
printf 'alpha\nbravo\nCHANGED\ndelta\n'                   > "$proto/a/applied.txt"
# Indented with TABS in the lines the hunk only uses as CONTEXT, against a
# patch that spells them with spaces. ws.txt above cannot catch a context-line
# rewrite, because the only line it differs on is the one the hunk changes
# anyway -- a fixture that cannot distinguish the two answers.
printf '\tctx one\nchangeme\n\tctx two\n'                 > "$proto/a/wsctx.txt"
# FUZZ FIXTURES. A hunk with three context lines either side of the change,
# against targets that differ ONLY in the context lines fuzz is supposed to
# ignore. A fixture for a loose comparison has to perturb the parts it claims
# are irrelevant, or it is testing the strict path -- ws.txt above did not, and
# that is how a context-line rewrite got past it.
#
# Named for what is wrong with each, since the fuzz level GNU needs follows
# from that: outermost leading only (fuzz 1), outermost at BOTH ends (still
# fuzz 1, because the budget is per end), two leading and one trailing
# (fuzz 2), and the removed line itself (never, at any -F).
printf 'start\nXXXX\nctx2\nctx3\ntarget\nctx4\nctx5\nctx6\nend\n'  > "$proto/a/fz.txt"
printf 'start\nXXXX\nctx2\nctx3\ntarget\nctx4\nctx5\nYYYY\nend\n'  > "$proto/a/fzboth.txt"
printf 'start\nXXXX\nZZZZ\nctx3\ntarget\nctx4\nctx5\nYYYY\nend\n'  > "$proto/a/fz2.txt"
printf 'start\nctx1\nctx2\nctx3\nWRONG\nctx4\nctx5\nctx6\nend\n'   > "$proto/a/fzrem.txt"
# OFFSET fixtures: the same hunk, matching EXACTLY, but not where its header
# says. Padding pushes it later; dropping `start` pulls it earlier, which is
# the case that reads `(offset -1 lines)` -- PLURAL, because GNU's test is
# `n == 1` rather than `abs(n) == 1`.
printf 'P\nstart\nctx1\nctx2\nctx3\ntarget\nctx4\nctx5\nctx6\nend\n'    > "$proto/a/off1.txt"
printf 'P\nQ\nstart\nctx1\nctx2\nctx3\ntarget\nctx4\nctx5\nctx6\nend\n' > "$proto/a/off2.txt"
printf 'ctx1\nctx2\nctx3\ntarget\nctx4\nctx5\nctx6\nend\n'             > "$proto/a/offneg.txt"
# A ZERO-CONTEXT insertion: `diff -U0` of an added line gives `@@ -1,0 +2 @@`,
# old_count 0, so there is no context and the position cannot come from a
# match. That is the shape whose reported position was one too low.
printf 'a\nb\nc\n'                                                     > "$proto/a/ins.txt"
# A file the patches will not touch, so a side that rewrote the whole tree is
# caught rather than merely a side that got one file wrong.
printf 'untouched\n'                                    > "$proto/a/keep.txt"

# A file that is NOT valid UTF-8: byte 0351 -- Latin-1 'e-acute' -- sits in a
# comment, exactly where one turns up in real source. Nothing about a patch
# requires the file to be text in any particular encoding, and GNU applies
# this without remark.
#
# This build refused it outright until 2026-09-14, and refused it at the
# *patch* file, before any target was opened:
#
#     patch: **** Can't open patch file u.patch : stream did not contain
#           valid UTF-8
#
# The cause was `fs::read_to_string` in three places and a `String`-typed
# hunk spine behind them. One Latin-1 byte in a comment made a file
# unpatchable. See known-issues.md ->
# B-PATCH-REFUSES-EVERY-FILE-THAT-IS-NOT-VALID-UTF-8.
printf 'alpha\ncaf\351 comment\ncharlie\ndelta\n'        > "$proto/a/latin1.txt"

# --- the patches, produced by GNU diff ----------------------------------------
mk=$work/mk
mkdir -p "$mk"
cp "$proto/a/base.txt" "$mk/base.txt"
printf 'alpha\nbravo\nCHANGED\ndelta\n'                 > "$mk/base.new"
printf 'alpha\nbravo\ncharlie\ndelta\nadded\n'          > "$mk/base.append"
cp "$proto/a/nonl.txt" "$mk/nonl.txt"
printf 'alpha\nbravo\nCHANGED\ndelta'                   > "$mk/nonl.new"
cp "$proto/a/long.txt" "$mk/long.txt"
{ for i in $(seq 1 40); do
    case $i in 5|35) printf 'CHANGED %02d\n' "$i" ;; *) printf 'line %02d\n' "$i" ;; esac
  done; }                                               > "$mk/long.new"
cp "$proto/a/sub/deep.txt" "$mk/deep.txt"
printf 'nested\nCHANGED\nhere\n'                        > "$mk/deep.new"
# Four SPACES: what ws.patch's context line will say, against a target that
# uses a tab.
printf '    ctx one\nchangeme\n    ctx two\n'             > "$mk/wsctx.txt"
# One original and one revision serve all four fuzz patches; only the labels
# differ, so each names the target it is meant for.
printf 'start\nctx1\nctx2\nctx3\ntarget\nctx4\nctx5\nctx6\nend\n'  > "$mk/fz.old"
printf 'start\nctx1\nctx2\nctx3\nCHANGED\nctx4\nctx5\nctx6\nend\n' > "$mk/fz.new"
printf '    ctx one\nCHANGED\n    ctx two\n'              > "$mk/wsctx.new"
printf 'alpha\nbravo\ncharlie\ndelta\n'                   > "$mk/applied.old"
printf 'alpha\nbravo\nCHANGED\ndelta\n'                   > "$mk/applied.new"
printf 'a\nb\nc\n'                                        > "$mk/ins.old"
printf 'a\nX\nb\nc\n'                                     > "$mk/ins.new"
printf 'start\n    indented a b\nend\n'                 > "$mk/ws.txt"
printf 'start\nCHANGED\nend\n'                          > "$mk/ws.new"

# `diff` exits 1 when the files differ, which is the normal case here, so its
# status is deliberately not checked -- only that it wrote something.
patches=$work/patches
mkdir -p "$patches"

# Unified, with `a/` and `b/` prefixes so the strip level matters.
( cd "$mk" && /usr/bin/diff -u --label x/a/base.txt --label y/a/base.txt \
    base.txt base.new ) > "$patches/u.patch" || true
# The high byte lands in a CONTEXT line, so it is copied through rather than
# rewritten -- the case that proves nothing decodes on the way past.
cp "$proto/a/latin1.txt" "$mk/latin1.txt"
printf 'alpha\ncaf\351 comment\nCHANGED\ndelta\n'        > "$mk/latin1.new"
( cd "$mk" && /usr/bin/diff -u --label x/a/latin1.txt --label y/a/latin1.txt \
    latin1.txt latin1.new ) > "$patches/latin1.patch" || true
( cd "$mk" && /usr/bin/diff -c --label x/a/base.txt --label y/a/base.txt \
    base.txt base.new ) > "$patches/c.patch" || true
( cd "$mk" && /usr/bin/diff base.txt base.new ) > "$patches/n.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/base.txt --label y/a/base.txt \
    base.txt base.append ) > "$patches/append.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/long.txt --label y/a/long.txt \
    long.txt long.new ) > "$patches/long.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/ws.txt --label y/a/ws.txt \
    ws.txt ws.new ) > "$patches/ws.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/applied.txt --label y/a/applied.txt \
    applied.old applied.new ) > "$patches/applied.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/wsctx.txt --label y/a/wsctx.txt \
    wsctx.txt wsctx.new ) > "$patches/wsctx.patch" || true
( cd "$mk" && /usr/bin/diff -U0 --label x/a/ins.txt --label y/a/ins.txt \
    ins.old ins.new ) > "$patches/ins.patch" || true
for fzname in fz fzboth fz2 fzrem off1 off2 offneg; do
    ( cd "$mk" && /usr/bin/diff -u --label "x/a/$fzname.txt" --label "y/a/$fzname.txt" \
        fz.old fz.new ) > "$patches/$fzname.patch" || true
done
( cd "$mk" && /usr/bin/diff -u --label x/a/nonl.txt --label y/a/nonl.txt \
    nonl.txt nonl.new ) > "$patches/nonl.patch" || true
# Two deep path components, so -p0, -p1 and -p2 all land somewhere different.
( cd "$mk" && /usr/bin/diff -u --label x/y/a/sub/deep.txt --label y/z/a/sub/deep.txt \
    deep.txt deep.new ) > "$patches/deep.patch" || true
# A patch that creates a file, and one that deletes it.
printf 'brand\nnew\n' > "$mk/created"
( cd "$mk" && /usr/bin/diff -u --label /dev/null --label y/a/created.txt \
    /dev/null created ) > "$patches/create.patch" || true
( cd "$mk" && /usr/bin/diff -u --label x/a/keep.txt --label /dev/null \
    "$proto/a/keep.txt" /dev/null ) > "$patches/delete.patch" || true
# A patch whose context no longer matches: the hunk is for a file that has moved
# on. This is what produces a `.rej`, and with `-F` what fuzz is for.
printf 'alpha\nDIFFERENT\ncharlie\ndelta\n'             > "$mk/drift.txt"
( cd "$mk" && /usr/bin/diff -u --label x/a/base.txt --label y/a/base.txt \
    drift.txt base.new ) > "$patches/drift.patch" || true
# A ZERO-CONTEXT insertion. `diff -U0` is the only shape in which a unified
# hunk removes nothing, and `old_count == 0` means the header names the line
# to insert AFTER rather than the first line it replaces. Nothing else here
# uses -U0, so a whole 64-of-64 run said nothing about it -- ours put the
# added line one row too high until 2026-09-12, and only the retirement of
# `userspace/patch` surfaced it: a todo.txt entry recorded the identical
# off-by-one, fixed in the crate that was about to be deleted and never in
# the one that survived.
( cd "$mk" && /usr/bin/diff -U0 --label x/a/base.txt --label y/a/base.txt \
    base.txt base.new ) > "$patches/u0.patch" || true
# Not a patch at all.
printf 'this is not a patch\nnor is this\n'             > "$patches/garbage.patch"
printf ''                                               > "$patches/empty.patch"
# A truncated hunk: the header promises four lines and two arrive.
printf -- '--- x/a/base.txt\n+++ y/a/base.txt\n@@ -1,4 +1,4 @@\n alpha\n-bravo\n' \
                                                        > "$patches/truncated.patch"

# --- comparing a whole tree ---------------------------------------------------
# Sorted, one line per entry, with type, mode and a content hash. `cksum` rather
# than the bytes so a long file does not drown the report, and the mode because
# `patch` is expected to preserve it and a backup is expected to inherit it.
snap() {
  ( cd "$1" && find . -mindepth 1 \( -type f -o -type d -o -type l \) -print \
      | LC_ALL=C sort \
      | while IFS= read -r e; do
          if [ -d "$e" ]; then
            printf 'd %s %s\n' "$e" "$(stat -c '%a' "$e")"
          elif [ -L "$e" ]; then
            printf 'l %s -> %s\n' "$e" "$(readlink "$e")"
          else
            printf 'f %s %s %s\n' "$e" "$(stat -c '%a' "$e")" "$(cksum < "$e")"
          fi
        done )
}

run_side() {
  local dir=$1 side=$2; shift 2
  ( cd "$dir" && diff_run timeout -k 2 30 \
      env LC_ALL=C.UTF-8 PATH="$bindir/$side" patch "$@" )
}

# `$1` is the patch file (absolute), the rest are `patch`'s arguments. stdin is
# the patch when no `-i` is given, which is how `patch` is normally driven.
compare() {
  local pfile=$1 use_stdin=$2; shift 2
  local o_dir g_dir o_out g_out o_err g_err o_rc g_rc
  o_dir=$(mktemp -d); g_dir=$(mktemp -d)
  cp -a "$proto/." "$o_dir/"; cp -a "$proto/." "$g_dir/"
  o_err=$(mktemp); g_err=$(mktemp)
  local o_bin g_bin; o_bin=$(mktemp); g_bin=$(mktemp)

  if [ "$use_stdin" = yes ]; then
    run_side "$o_dir" ours "$@" <"$pfile" >"$o_bin" 2>"$o_err"; o_rc=$?
    run_side "$g_dir" gnu  "$@" <"$pfile" >"$g_bin" 2>"$g_err"; g_rc=$?
  else
    run_side "$o_dir" ours "$@" </dev/null >"$o_bin" 2>"$o_err"; o_rc=$?
    run_side "$g_dir" gnu  "$@" </dev/null >"$g_bin" 2>"$g_err"; g_rc=$?
  fi

  o_out=$(od -An -c <"$o_bin"); g_out=$(od -An -c <"$g_bin")
  local o_msg g_msg o_tree g_tree
  o_msg=$(cat "$o_err"); g_msg=$(cat "$g_err")
  o_tree=$(snap "$o_dir"); g_tree=$(snap "$g_dir")
  rm -f "$o_bin" "$g_bin" "$o_err" "$g_err"
  rm -rf "$o_dir" "$g_dir"

  if [ "$o_out" = "$g_out" ] && [ "$o_rc" = "$g_rc" ] \
     && [ "$o_msg" = "$g_msg" ] && [ "$o_tree" = "$g_tree" ]; then
    AGREED=yes
  else
    AGREED=no
  fi
  # The tree is the part most likely to hold the answer, so it is printed even
  # when the difference is elsewhere -- a wrong message with a right tree and a
  # right message with a wrong tree are very different findings.
  REPORT=$(printf '  ours (rc=%s): %s {%s}\n    tree: %s\n  gnu  (rc=%s): %s {%s}\n    tree: %s' \
    "$o_rc" "$(printf '%s' "$o_out" | tr -s ' \n' ' ')" "$(printf '%s' "$o_msg" | tr '\n' '|')" \
    "$(printf '%s' "$o_tree" | tr '\n' '|')" \
    "$g_rc" "$(printf '%s' "$g_out" | tr -s ' \n' ' ')" "$(printf '%s' "$g_msg" | tr '\n' '|')" \
    "$(printf '%s' "$g_tree" | tr '\n' '|')")
}

report() {
  local label="$1"
  if [ "$AGREED" = yes ]; then
    pass=$((pass+1))
    [ -n "${VERBOSE:-}" ] && printf 'OK   %s\n' "$label"
  else
    fail=$((fail+1))
    printf 'DIFF %s\n%s\n' "$label" "$REPORT"
  fi
  return 0
}

# The patch arrives via `-i`, and STDIN IS CLOSED. That is not a stylistic
# choice: when GNU patch cannot find the file to patch it asks "File to patch:"
# on stdin, and if stdin is the patch it eats the rest of the patch as answers.
# The harness's first run hit exactly that and reported 65 differences that were
# all the same mistake. `-i` plus `</dev/null` needs no option either side might
# lack, and GNU then reads EOF and skips the hunk deterministically.
run_case() {
  local p=$1; shift
  compare "$patches/$p" no -i "$patches/$p" "$@"
  report "patch -i $p $*"
}
# The other way in: the patch on stdin. Reserved for cases that apply cleanly,
# since those are the ones that cannot reach the prompt.
run_stdin() {
  local p=$1; shift
  compare "$patches/$p" yes "$@"
  report "patch $* < $p"
}
xfail_case() {
  local why=$1 p=$2; shift 2
  compare "$patches/$p" yes "$@"
  if [ "$AGREED" = yes ]; then
    xpass=$((xpass+1))
    printf 'XPASS patch %s < %s -- expected to differ (%s) and did not\n' "$*" "$p" "$why"
  else
    xfail=$((xfail+1))
    [ -n "${VERBOSE:-}" ] && printf 'xfail patch %s < %s (%s)\n' "$*" "$p" "$why"
  fi
  return 0
}

# --- the three patch formats, applied straight --------------------------------
run_case u.patch -p1
run_case u0.patch -p1
run_case c.patch -p1
run_case n.patch a/base.txt
run_case append.patch -p1
run_case long.patch -p1
run_stdin u.patch -p1
run_stdin c.patch -p1

# --- strip levels -------------------------------------------------------------
run_case deep.patch -p0
run_case deep.patch -p1
run_case deep.patch -p2
run_case deep.patch -p3
run_case u.patch -p0
run_case u.patch -p2
run_case u.patch -p99
run_case u.patch
run_case u.patch -p abc

# --- naming the target explicitly ---------------------------------------------
run_case u.patch -p1 a/base.txt
run_case u.patch a/base.txt
run_case n.patch a/nosuch.txt
run_case u.patch -p1 a/keep.txt

# --- reverse, and already-applied ----------------------------------------------
run_case u.patch -p1 -R
run_case u.patch -p1 --reverse
run_case drift.patch -p1
run_case drift.patch -p1 -N
run_case drift.patch -p1 --forward
run_case drift.patch -p1 -F 3
run_case drift.patch -p1 --fuzz=3
run_case drift.patch -p1 -f
run_case drift.patch -p1 --force

# --- dry run, which must leave the tree exactly as it was ----------------------
run_case u.patch -p1 --dry-run
run_case drift.patch -p1 --dry-run
run_case u.patch -p1 --dry-run -R

# --- backups and rejects --------------------------------------------------------
run_case u.patch -p1 -b
run_case u.patch -p1 --backup
run_case drift.patch -p1 -b
run_case drift.patch -p1 -r myrejects
run_case drift.patch -p1 --no-backup-if-mismatch
run_case u.patch -p1 -Z

# --- quiet and verbose ----------------------------------------------------------
run_case u.patch -p1 -s
run_case u.patch -p1 --quiet
run_case u.patch -p1 --silent
run_case drift.patch -p1 -s
# `-v` IS `--version`, not verbose. Measured, because the name says the
# opposite and the sibling utilities in this tree reinforce the wrong
# reading: `strings -v` prints a version and `strings -V` does too, while
# `patch -V` is `--version-control` and takes an argument, and `patch -h`
# is not an option at all. So this case differs for the same reason
# `--version` does, and is counted with it rather than as a failure.
xfail_case "our version string, not the GNU project's" u.patch -p1 -v
run_case u.patch -p1 --verbose

# --- output redirection and directory -------------------------------------------
run_case u.patch -p1 -o out.txt
run_case u.patch -p1 --output=out.txt
run_case u.patch -p1 -d a
run_case u.patch -p0 -d a
run_case u.patch -p1 --directory=a

# --- creating and deleting files -------------------------------------------------
run_case create.patch -p1
run_case delete.patch -p1
run_case delete.patch -p1 -E
run_case delete.patch -p1 --remove-empty-files

# --- the no-newline marker, which `diff` gets wrong on both sides -----------------
run_case nonl.patch -p1
run_case nonl.patch -p1 -b

# --- whitespace -------------------------------------------------------------------
run_case u.patch -p1 -l
run_case u.patch -p1 --ignore-whitespace
# `-l` WHERE IT CHANGES THE ANSWER. The case above runs on a fixture whose
# target and patch agree about whitespace, so the flag makes no difference to
# it -- which is exactly why it went on passing for as long as the flag was
# parsed and then read by nothing. These three do not have that property: the
# target is indented with a tab and the patch with four spaces.
run_case ws.patch -p1 -l
# `-l` must not REWRITE what it loosely matched. The context lines here are
# tab-indented in the target and space-indented in the patch, and GNU leaves
# the target's tabs alone -- only the line the hunk actually changes is
# rewritten. Emitting the patch's spelling instead reindents the file silently.
run_case wsctx.patch -p1 -l
# `-F`/fuzz. Ours had a constant named `max_fuzz` that meant SLIDE DISTANCE,
# and no fuzz at all, so before this we refused hunks GNU applies -- a
# divergence rather than a missing flag, and one no case here could see
# because none of them perturbed a context line.
run_case fz.patch -p1
run_case fz.patch -p1 -F0
run_case fz.patch -p1 -F1
run_case fz.patch -p1 --fuzz=1
# Both ends wrong is still fuzz 1: the budget is per end, not per hunk.
run_case fzboth.patch -p1
# Two leading and one trailing needs fuzz 2, which is the default...
run_case fz2.patch -p1
# ...so -F1 must refuse it. This is the case that pins the default at 2.
run_case fz2.patch -p1 -F1
# The CONTROL, and the one that matters most: fuzz never excuses a REMOVED
# line. If this ever starts applying, fuzz has been let loose on lines the
# hunk is about to delete, and the patch would silently destroy content it
# never matched.
run_case fzrem.patch -p1 -F3
# OFFSET. A hunk that matches exactly but not where its header says still
# reports itself, and GNU backs the file up for it -- the same
# `--backup-if-mismatch` default that covers fuzz. Before this, ours reported
# the position the HEADER named rather than the one it landed on, and said
# nothing at all unless `--verbose` was given.
run_case off1.patch -p1
run_case off2.patch -p1
# The plural quirk: this one reads `(offset -1 lines)`.
run_case offneg.patch -p1
# ...and suppressed, which is the control for the backup half.
run_case off1.patch -p1 --no-backup-if-mismatch
# A ZERO-CONTEXT INSERTION under --verbose. The existing --verbose case above
# is a CHANGE hunk, which reports the same number under either formula, so it
# could not see that `old_start + offset` is one too low for an insertion:
# GNU says `Hunk #1 succeeded at 2.` for `@@ -1,0 +2 @@` and we said 1.
run_case ins.patch -p1 --verbose
run_case ins.patch -p1
run_case ws.patch -p1 --ignore-whitespace
# ...and without the flag the same patch must be refused, by both sides alike.
# This is the half that fails if `-l` is ever wired on by default.
run_case ws.patch -p1
# `-N/--forward` on an ALREADY-APPLIED patch, which is the only case it changes.
# Without the flag GNU asks two questions it then answers itself; with it, it
# asks neither and says so on one line. The no-flag case is the control: it must
# keep its four lines, so a `-N` wired on by default is caught here.
run_case applied.patch -p1
run_case applied.patch -p1 -N
run_case applied.patch -p1 --forward
# ...and the `-R` form, where the detection reads "Unreversed" instead. This
# pair uses u.patch against the UNPATCHED base.txt on purpose: `-R` against a
# file that already carries the change applies cleanly and never reaches the
# detection at all, so the obvious spelling of this case tests nothing. The
# two-probe is what caught that -- with `-N` forced inert, the applied.patch
# `-R` cases did not budge.
run_case u.patch -p1 -R
run_case u.patch -p1 -R -N

# --- input that is not a patch -----------------------------------------------------
# A target and a patch that are both valid files and neither of which is
# valid UTF-8. Both sides must leave byte 0351 exactly where it was -- and
# the tree comparison, not the streams, is what checks that.
run_case latin1.patch -p1
run_case latin1.patch -p1 --dry-run
run_case latin1.patch -p1 -R

run_case garbage.patch -p1
run_case empty.patch -p1
run_case truncated.patch -p1
run_case garbage.patch
run_case empty.patch

# --- refusals -----------------------------------------------------------------------
run_case nosuch.patch -p1
run_case u.patch -p1 --nosuchoption
run_case u.patch -p1 -Q

# --- the two whose text is ours ------------------------------------------------------
xfail_case "our help text, not the GNU project's" empty.patch --help
xfail_case "our version string, not the GNU project's" empty.patch --version

printf '\n%d passed, %d differed, %d differ on purpose' "$pass" "$fail" "$xfail"
if [ "$xpass" -gt 0 ]; then
  printf ', %d NO LONGER differ (update the harness)' "$xpass"
fi
printf '\n'
[ -n "${DIFF_SKIPPED:-}" ] && printf 'skipped:%s\n' "$DIFF_SKIPPED"
[ "$fail" = 0 ] && [ "$xpass" = 0 ]
