#!/usr/bin/env python3
"""Tests for `scripts/prune-build-trees.py`.

Why this exists
---------------

`prune-build-trees.py` deletes directories. Everything it gets wrong is
expensive in one of two directions, and they pull against each other:

* too eager -- it removes a tree another lane is building into, or a source
  directory that merely starts with the letters "target";
* too timid -- it reports a volume as tidy while a build tree nothing has
  touched for a week sits on it, which is the failure that filled a 1.9 TB
  volume to 1.2 MB free on 2026-08-20 and broke a workspace gate with
  `ld: final link failed: No space left on device`.

The safety gates are tested here because "it looked like a build tree" is not
the standard the script claims to hold itself to -- it claims a positive
identification from cargo's own `CACHEDIR.TAG` signature, plus a git check,
plus the sanctioned list. Each of those is one `if` away from being skipped.

`last_build_time` gets the most attention because it is the one piece of new
logic with a *counter-intuitive* rule: it deliberately ignores the top level of
the tree. Cargo rewrites `.rustc_info.json` there whenever it merely probes the
compiler, so a `cargo metadata` run in a directory that forgot to set
`CARGO_TARGET_DIR` makes a five-day-old tree look like it was built into
seconds ago. That is not a hypothetical -- it is exactly what the stale 121.8 GB
`target` in the lane-C worktree did, which is why the naive reading is asserted
against here rather than merely avoided.

Run:  python scripts/test-prune-build-trees.py
Exit: 0 all passed, 1 one or more failed.
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import sys
import tempfile
import time
from pathlib import Path

HERE = os.path.dirname(os.path.abspath(__file__))

DAY = 86400.0


def load_module():
    """Import prune-build-trees.py, whose hyphen makes it un-importable by name."""
    path = os.path.join(HERE, "prune-build-trees.py")
    spec = importlib.util.spec_from_file_location("prune_build_trees", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load %s" % path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


FAILURES = []


def check(name, cond, detail=""):
    if cond:
        print("  ok    %s" % name)
    else:
        print("  FAIL  %s %s" % (name, detail))
        FAILURES.append(name)


def make_tree(parent, mod, name="target", built_days_ago=0.0, probed_now=False):
    """A directory shaped like one cargo made.

    `built_days_ago` backdates the *profile* subdirectories, which is where a
    real build writes. `probed_now` additionally drops a fresh
    `.rustc_info.json` at the top level, reproducing a `cargo metadata` that ran
    without `CARGO_TARGET_DIR` set -- the thing that disguises a stale tree.
    """
    path = Path(parent) / name
    (path / "debug").mkdir(parents=True, exist_ok=True)
    (path / "release").mkdir(exist_ok=True)
    (path / "CACHEDIR.TAG").write_text(
        mod.CACHEDIR_SIGNATURE + "\n# generated by cargo\n", encoding="utf-8"
    )
    stamp = time.time() - built_days_ago * DAY
    for sub in ("debug", "release"):
        os.utime(path / sub, (stamp, stamp))
    if probed_now:
        (path / ".rustc_info.json").write_text("{}", encoding="utf-8")
    return path


# ---------------------------------------------------------------- identification


def test_the_signature_is_what_identifies_a_build_tree(mod, tmp):
    """Name alone must not be enough, in either direction."""
    real = make_tree(tmp, mod, name="target-real")
    check("a tree carrying cargo's signature is recognised",
          mod.is_cargo_build_tree(real))

    # A source directory that happens to be called `targets/`. Deleting this
    # is the worst thing the script could do, and the only thing standing in
    # the way is the tag.
    impostor = Path(tmp) / "targets"
    (impostor / "src").mkdir(parents=True)
    (impostor / "src" / "lib.rs").write_text("fn main() {}", encoding="utf-8")
    check("a source directory named like a target is not recognised",
          not mod.is_cargo_build_tree(impostor))

    # A tag whose signature line is wrong -- e.g. some other tool's cache.
    wrong = Path(tmp) / "target-wrongtag"
    wrong.mkdir()
    (wrong / "CACHEDIR.TAG").write_text("Signature: not-cargo\n", encoding="utf-8")
    check("a CACHEDIR.TAG with a different signature is not recognised",
          not mod.is_cargo_build_tree(wrong))

    # The signature must be on the *first* line, per the spec cargo follows.
    late = Path(tmp) / "target-latetag"
    late.mkdir()
    (late / "CACHEDIR.TAG").write_text(
        "# a comment first\n" + mod.CACHEDIR_SIGNATURE + "\n", encoding="utf-8"
    )
    check("a signature that is not on the first line is not recognised",
          not mod.is_cargo_build_tree(late))

    missing = Path(tmp) / "target-notag"
    missing.mkdir()
    check("a directory with no CACHEDIR.TAG is not recognised",
          not mod.is_cargo_build_tree(missing))


# -------------------------------------------------------------------- staleness


def test_a_compiler_probe_does_not_make_a_stale_tree_look_fresh(mod, tmp):
    """The regression test for the 121.8 GB tree that hid in plain sight.

    The tree was last built into on 2026-08-15 and reported as current on
    2026-08-20, because something had run cargo in the worktree root without
    `CARGO_TARGET_DIR` set and cargo had rewritten `.rustc_info.json`. Both
    readings are asserted here: the naive one to show it really is fooled, and
    the real one to show `last_build_time` is not.
    """
    now = time.time()
    tree = make_tree(tmp, mod, name="target-stale", built_days_ago=5.0,
                     probed_now=True)

    age = mod.age_days(mod.last_build_time(tree), now)
    check("a tree built into 5 days ago is reported as ~5 days old",
          age is not None and 4.9 < age < 5.1, "got %r" % (age,))

    naive = mod.age_days(tree.stat().st_mtime, now)
    check("the top-level mtime really is fooled by the probe (control)",
          naive is not None and naive < 0.1,
          "control is meaningless if this is not ~0, got %r" % (naive,))


def test_a_tree_built_into_today_is_not_stale(mod, tmp):
    now = time.time()
    tree = make_tree(tmp, mod, name="target-fresh", built_days_ago=0.0)
    age = mod.age_days(mod.last_build_time(tree), now)
    check("a tree built into today is ~0 days old",
          age is not None and age < 0.01, "got %r" % (age,))
    check("and is labelled 'today'", mod.age_label(age).strip() == "today",
          "got %r" % (mod.age_label(age),))


def test_the_newest_subdirectory_wins(mod, tmp):
    """Two targets in one tree: one abandoned, one current. Not stale."""
    now = time.time()
    tree = make_tree(tmp, mod, name="target-mixed", built_days_ago=30.0)
    fresh = tree / "x86_64-pc-windows-gnu"
    fresh.mkdir()
    os.utime(fresh, (now, now))
    age = mod.age_days(mod.last_build_time(tree), now)
    check("a tree with one current target is not reported as old",
          age is not None and age < 0.01, "got %r" % (age,))


def test_an_unreadable_or_empty_tree_is_unknown_never_old(mod, tmp):
    """`None` must not be confused with "very old" -- that would delete it."""
    now = time.time()
    empty = Path(tmp) / "target-empty"
    empty.mkdir()
    (empty / "CACHEDIR.TAG").write_text(mod.CACHEDIR_SIGNATURE + "\n",
                                        encoding="utf-8")
    check("a tree with no subdirectories has no build time",
          mod.last_build_time(empty) is None)
    check("an unknown build time is an unknown age",
          mod.age_days(None, now) is None)
    check("and is labelled 'never built', not a number",
          mod.age_label(None).strip() == "never built",
          "got %r" % (mod.age_label(None),))

    gone = Path(tmp) / "target-does-not-exist"
    check("a missing directory has no build time (no exception)",
          mod.last_build_time(gone) is None)


def test_age_is_never_negative(mod, tmp):
    """Clock skew must not print a negative age."""
    now = time.time()
    future = make_tree(tmp, mod, name="target-future", built_days_ago=-2.0)
    age = mod.age_days(mod.last_build_time(future), now)
    check("a tree stamped in the future reads as 0 days, not negative",
          age is not None and age == 0.0, "got %r" % (age,))


# ------------------------------------------------------------------ sanctioning


def test_every_lane_sanctions_the_cargo_default(mod, _tmp):
    """`target` is what an unset CARGO_TARGET_DIR produces.

    If a lane did not sanction it, a plain `cargo build` would have its output
    classed as stray and deleted by the next `--prune` -- including one still
    running. Being on the list is what makes the *default* safe; staleness is
    the separate question of whether it is still wanted.
    """
    for lane, allowed in sorted(mod.SANCTIONED.items()):
        check("lane %s sanctions the default `target`" % lane,
              "target" in allowed, "got %r" % (sorted(allowed),))


def test_the_lanes_do_not_share_a_scratch_tree(mod, _tmp):
    """Beyond `target`, no two lanes may claim the same name.

    The script only ever prunes the worktree it runs in, so a collision is not
    immediately destructive -- but the sanctioned lists are also the documented
    convention, and two lanes told to use one name is how the eleven ad-hoc
    trees started.
    """
    seen = {}
    for lane, allowed in sorted(mod.SANCTIONED.items()):
        for name in sorted(allowed):
            if name == "target":
                continue
            if name in seen:
                check("scratch tree %r is claimed by only one lane" % name,
                      False, "claimed by %s and %s" % (seen[name], lane))
            seen[name] = lane
    check("no scratch tree is claimed by two lanes", True)


def test_human_reports_the_units_the_report_is_read_for(mod, _tmp):
    """"190 GB" is the number that motivates; "204010946560 B" is not."""
    check("bytes stay bytes", mod.human(512) == "512 B",
          "got %r" % (mod.human(512),))
    check("a kilobyte is not printed as 1024 B", mod.human(1024) == "1.0 KB",
          "got %r" % (mod.human(1024),))
    check("121.8 GB is printed in GB",
          mod.human(int(121.8 * 1024 ** 3)) == "121.8 GB",
          "got %r" % (mod.human(int(121.8 * 1024 ** 3)),))
    check("a terabyte is printed in TB", mod.human(1024 ** 4) == "1.0 TB",
          "got %r" % (mod.human(1024 ** 4),))


def test_tree_size_counts_what_is_there(mod, tmp):
    tree = make_tree(tmp, mod, name="target-sized")
    (tree / "debug" / "big.rlib").write_bytes(b"\0" * 8192)
    (tree / "release" / "small.rlib").write_bytes(b"\0" * 100)
    size = mod.tree_size_bytes(tree)
    # The tag file is counted too, so assert a floor rather than equality.
    check("a tree's size includes files in its subdirectories",
          size >= 8292, "got %r" % (size,))
    check("a missing tree measures zero rather than raising",
          mod.tree_size_bytes(Path(tmp) / "target-absent") == 0)


def main():
    mod = load_module()
    tmp = tempfile.mkdtemp(prefix="prune-build-trees-test-")
    print("prune-build-trees.py tests (scratch: %s)" % tmp)
    tests = (
        test_the_signature_is_what_identifies_a_build_tree,
        test_a_compiler_probe_does_not_make_a_stale_tree_look_fresh,
        test_a_tree_built_into_today_is_not_stale,
        test_the_newest_subdirectory_wins,
        test_an_unreadable_or_empty_tree_is_unknown_never_old,
        test_age_is_never_negative,
        test_every_lane_sanctions_the_cargo_default,
        test_the_lanes_do_not_share_a_scratch_tree,
        test_human_reports_the_units_the_report_is_read_for,
        test_tree_size_counts_what_is_there,
    )
    try:
        for test in tests:
            print("%s:" % test.__name__)
            try:
                test(mod, tmp)
            except Exception as exc:  # noqa: BLE001 -- report, don't abort
                # A raised exception is a failure of *that* test and the run
                # continues. These tests create and stat files, so an OSError
                # from the scratch directory is the likeliest way for them to
                # break, and one such failure must not hide the other nine.
                print("  FAIL  %s raised %s: %s"
                      % (test.__name__, type(exc).__name__, exc))
                FAILURES.append(test.__name__)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    if FAILURES:
        print("FAILED: %d of the checks above" % len(FAILURES))
        return 1
    print("PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
