#!/usr/bin/env python3
"""The rule that every program is recorded: `programs.md` lists every binary.

Run: `python scripts/test-program-catalogue.py` (exit 0 = pass, 1 = fail).

design-decisions §1053 is the operator's: "if you make a program, record it
somewhere so everybody knows it exists." `programs.md` is that somewhere --
generated by `scripts/program-catalogue.py` from the workspace itself -- and
this suite is what makes the rule impossible to forget. The boot test runs
every `scripts/test-*.py`, so a lane that adds, removes or re-describes a
program and does not regenerate the catalogue is told so before its next boot,
with the names and the command:

    python scripts/program-catalogue.py

and then commit `programs.md` with the program. It is a generated index, like
`scripts/INDEX.md`: regenerating it is not editing lane B's file.

Three checks, cheapest first:

1. The generator's own self-test, so a broken generator is reported as that
   and not as a stale catalogue.
2. Every binary the workspace builds has a row, and so does every program
   the rootfs recipe's `# PROGRAM:` lines name -- a port, bash or CMake or
   CPython, which is no cargo target -- and every row is one of the two.
   Implied by 3, and checked first anyway because its failure says *which*
   programs, which is the part the person who added one needs.
3. The file is exactly what the generator writes now -- descriptions and the
   on-image column included.
"""

from __future__ import annotations

import contextlib
import importlib.util
import io
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPT = HERE / "program-catalogue.py"

#: Fewer binaries than this means `cargo metadata` answered for something
#: other than this workspace, not that hundreds of programs were deleted.
FLOOR = 300

#: What to do about a failure, one line per entry, printed indented. ASCII
#: only: this is read in boot logs and on consoles that mangle anything else.
REGENERATE = (
    "Regenerate it and commit it with the program:",
    "    python scripts/program-catalogue.py",
    "(design-decisions 1053: every program is recorded in programs.md)",
)


def advise() -> None:
    for line in REGENERATE:
        print(f"        {line}")


def load():
    spec = importlib.util.spec_from_file_location("program_catalogue_under_test", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def listed(text: str) -> set[str]:
    """The program names `programs.md` has rows for: a table row's first
    cell is the name in backticks."""
    return set(re.findall(r"^\| `([^`]+)` \|", text, re.MULTILINE))


def main() -> int:
    catalogue = load()
    failures = 0

    with contextlib.redirect_stdout(io.StringIO()) as said:
        selftest = catalogue.selftest()
    if selftest != 0:
        print(said.getvalue(), end="")
        print("FAIL  program-catalogue.py's self-test -- the generator is "
              "broken, so its verdict below would not mean anything")
        return 1
    print("PASS  program-catalogue.py's self-test")

    progs = catalogue.targets()
    if len(progs) < FLOOR:
        print(f"FAIL  cargo metadata named {len(progs)} binaries; this "
              f"workspace has well over {FLOOR}. The generator read the wrong "
              "workspace, not a smaller one.")
        return 1

    try:
        have = Path(catalogue.OUT).read_text(encoding="utf-8")
    except OSError as err:
        print(f"FAIL  programs.md cannot be read ({err})")
        advise()
        return 1

    # The ports are known from the recipe that stages them, not from cargo
    # (program-catalogue.py's `ports()`); both kinds have rows.
    ported = catalogue.ports()
    built = {p["name"] for p in progs} | {p["name"] for p in ported}
    rows = listed(have)
    missing = sorted(built - rows)
    gone = sorted(rows - built)
    if missing or gone:
        failures += 1
        print("FAIL  programs.md and the workspace disagree about which programs exist")
        if missing:
            print(f"        built but not listed: {', '.join(missing)}")
        if gone:
            print(f"        listed but no longer built: {', '.join(gone)}")
        advise()
    else:
        print(f"PASS  every one of the {len(built)} programs has a row, and every row a program")

    if catalogue.render(progs, ported) != have:
        failures += 1
        print("FAIL  programs.md is not what the generator writes now -- a "
              "description, a name or the on-image column changed")
        advise()
    else:
        print("PASS  programs.md is exactly what the generator writes")

    print()
    if failures:
        print(f"{failures} check(s) FAILED")
        return 1
    print("all program-catalogue checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
