#!/usr/bin/env python3
"""Regression tests for `scripts/fastpy-slateos-bundle.py`.

Run: `python scripts/test-fastpy-slateos-bundle.py` (exit 0 = pass, 1 = fail).
No pytest dependency, like the other suites here: this has to run from a bare
checkout, and the boot test runs every `scripts/test-*.py`.

What is tested is the script's own logic -- which files make the tree, where
they go, what is left out, what `BUNDLE` records, when an existing directory
may be cleared -- against a fake fastpy checkout and a fake llvmlite built in
a temporary directory. The real runtime archive is fastpy's to build and test
(`build_slateos_runtime_archive`, in fastpy's own suite): reaching it from
here would cross-compile a C runtime inside every lane's boot test, into a
directory outside this repository that every lane shares. A stand-in
toolchain whose archive builder writes a fixed file takes its place.

In-process throughout, and starting no other process: the fakes are not git
checkouts, so `git_identity` answers without running git, and the
byte-compile is done by this interpreter.
"""

from __future__ import annotations

import hashlib
import importlib.util
import inspect
import io
import os
import sys
import tempfile
import types
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPT = HERE / "fastpy-slateos-bundle.py"

_FAILURES: list[str] = []


def check(label: str, got: object, want: object) -> bool:
    if got == want:
        print(f"PASS  {label}")
        return True
    print(f"FAIL  {label}")
    print(f"        got:  {got!r}")
    print(f"        want: {want!r}")
    _FAILURES.append(label)
    return False


def load():
    spec = importlib.util.spec_from_file_location("fastpy_slateos_bundle_under_test", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


bundle = load()

#: What the stand-in archive builder writes: an empty `ar` archive.
FAKE_ARCHIVE = b"!<arch>\n"

RUNNING = f"{sys.version_info[0]}.{sys.version_info[1]}"


def write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))
    return path


def fake_fastpy(root: Path, version: str = "0.3.0") -> Path:
    """A fastpy checkout as far as the script looks at one."""
    fastpy = root / "fastpy"
    write(fastpy / "compiler" / "__init__.py", '"""fake fastpy"""\n')
    write(fastpy / "compiler" / "__main__.py", "def main():\n    return 0\n")
    write(fastpy / "compiler" / "codegen.py", "X = 1\n")
    # Not a source: a cache the checkout happens to hold.
    write(fastpy / "compiler" / "__pycache__" / "codegen.cpython-314.pyc", "junk")
    write(fastpy / "pyproject.toml", f'[project]\nname = "fastpy"\nversion = "{version}"\n')
    return fastpy


def fake_llvmlite(root: Path, version: str = "0.47.0") -> Path:
    """An installed llvmlite: the pure half, the binding, and its tests."""
    pkg = root / "site-packages" / "llvmlite"
    write(pkg / "__init__.py", "from ._version import get_versions\n")
    write(pkg / "_version.py",
          "# This file was generated by 'versioneer.py' (0.14)\n\n"
          f"version_version = '{version}'\n"
          "version_full = 'abc'\n"
          "def get_versions(default={}, verbose=False):\n"
          "    return {'version': version_version, 'full': version_full}\n")
    write(pkg / "utils.py", "import os\n")
    write(pkg / "ir" / "__init__.py", "from .types import *\n")
    write(pkg / "ir" / "types.py", "class Type:\n    pass\n")
    write(pkg / "binding" / "__init__.py", "import ctypes\n")
    write(pkg / "binding" / "ffi.py", "import ctypes\n")
    write(pkg / "tests" / "test_ir.py", "pass\n")
    return pkg


def fake_toolchain() -> types.ModuleType:
    """Stands in for fastpy's toolchain: writes the archive it is asked for."""
    module = types.ModuleType("fake_toolchain")

    def build_slateos_runtime_archive(dest):
        dest = Path(dest)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(FAKE_ARCHIVE)
        return dest

    module.build_slateos_runtime_archive = build_slateos_runtime_archive
    return module


def files_under(directory: Path) -> list[str]:
    return sorted(p.relative_to(directory).as_posix()
                  for p in directory.rglob("*") if p.is_file())


def raises(fn, *args) -> str | None:
    """The `BundleError` text `fn(*args)` raises, or None if it returns."""
    try:
        fn(*args)
    except bundle.BundleError as err:
        return str(err)
    return None


# ---------------------------------------------------------------------------
# Finding the inputs
# ---------------------------------------------------------------------------

def test_a_named_checkout_is_used_and_a_wrong_one_refused():
    with tempfile.TemporaryDirectory() as tmp:
        fastpy = fake_fastpy(Path(tmp))
        check("--fastpy names the checkout", bundle.find_fastpy(str(fastpy)), fastpy)
        wrong = Path(tmp) / "not-fastpy"
        wrong.mkdir()
        err = raises(bundle.find_fastpy, str(wrong))
        check("a named directory without compiler/ is refused, not fallen through",
              err is not None and "compiler/__init__.py" in err, True)


def test_fastpy_dir_is_honoured_like_the_fixture_builder():
    with tempfile.TemporaryDirectory() as tmp:
        fastpy = fake_fastpy(Path(tmp))
        saved = os.environ.get("FASTPY_DIR")
        os.environ["FASTPY_DIR"] = str(fastpy)
        try:
            check("$FASTPY_DIR is the checkout when --fastpy is absent",
                  bundle.find_fastpy(None), fastpy)
            os.environ["FASTPY_DIR"] = str(Path(tmp) / "missing")
            check("a wrong $FASTPY_DIR is an error too",
                  raises(bundle.find_fastpy, None) is not None, True)
        finally:
            if saved is None:
                os.environ.pop("FASTPY_DIR", None)
            else:
                os.environ["FASTPY_DIR"] = saved


def test_llvmlite_must_be_the_package_directory():
    with tempfile.TemporaryDirectory() as tmp:
        pkg = fake_llvmlite(Path(tmp))
        check("llvmlite's package directory is accepted",
              bundle.find_llvmlite(str(pkg)), pkg)
        err = raises(bundle.find_llvmlite, str(pkg.parent))
        check("its parent is not -- it has no ir/__init__.py",
              err is not None and "ir/__init__.py" in err, True)


def test_llvmlite_version_is_read_without_importing_it():
    with tempfile.TemporaryDirectory() as tmp:
        pkg = fake_llvmlite(Path(tmp), version="0.47.0")
        check("versioneer's assignment is read", bundle.llvmlite_version(pkg), "0.47.0")
        write(pkg / "_version.py", "def get_versions():\n    return {}\n")
        check("no assignment reads as unknown, not as an error",
              bundle.llvmlite_version(pkg), "unknown")


def test_load_toolchain_wants_the_archive_builder():
    with tempfile.TemporaryDirectory() as tmp:
        fastpy = fake_fastpy(Path(tmp))
        write(fastpy / "compiler" / "toolchain.py", "SLATEOS_TARGET = 'x'\n")
        err = raises(bundle.load_toolchain, fastpy)
        check("a fastpy older than the archive builder is named as such",
              err is not None and "build_slateos_runtime_archive" in err, True)

        # A dataclass, as the real toolchain.py has: `dataclasses` looks the
        # defining module up in sys.modules while it builds the class, so a
        # module loaded by path and not registered fails right here.
        write(fastpy / "compiler" / "toolchain.py",
              "from __future__ import annotations\n"
              "from dataclasses import dataclass\n"
              "WHICH = 'the chosen checkout'\n"
              "@dataclass\n"
              "class PythonInstall:\n"
              "    version: tuple[int, int]\n"
              "def build_slateos_runtime_archive(dest):\n    return dest\n")
        before = set(sys.modules)
        module = bundle.load_toolchain(fastpy)
        check("the chosen checkout's toolchain is the one loaded",
              getattr(module, "WHICH", None), "the chosen checkout")
        check("its dataclasses build",
              module.PythonInstall((3, 12)).version, (3, 12))
        check("loading it binds no `compiler` package in sys.modules",
              sorted(name for name in set(sys.modules) - before
                     if name == "compiler" or name.startswith("compiler.")), [])


# ---------------------------------------------------------------------------
# The tree
# ---------------------------------------------------------------------------

def test_the_tree_holds_what_the_image_needs_and_nothing_else():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        fastpy, pkg, out = fake_fastpy(root), fake_llvmlite(root), root / "out"
        bundle.build(fastpy, pkg, out, "9.99", fake_toolchain())
        check("the files, exactly", files_under(out), [
            "bin/fastpy",
            "usr/lib/fastpy/BUNDLE",
            "usr/lib/fastpy/compiler/__init__.py",
            "usr/lib/fastpy/compiler/__main__.py",
            "usr/lib/fastpy/compiler/codegen.py",
            "usr/lib/fastpy/llvmlite/__init__.py",
            "usr/lib/fastpy/llvmlite/_version.py",
            "usr/lib/fastpy/llvmlite/ir/__init__.py",
            "usr/lib/fastpy/llvmlite/ir/types.py",
            "usr/lib/fastpy/llvmlite/utils.py",
            "usr/lib/x86_64-slateos/libfastpy_rt.a",
        ])
        check("the archive is the toolchain's",
              (out / "usr/lib/x86_64-slateos/libfastpy_rt.a").read_bytes(), FAKE_ARCHIVE)
        check("the sources are copied byte for byte",
              (out / "usr/lib/fastpy/compiler/codegen.py").read_bytes(),
              (fastpy / "compiler" / "codegen.py").read_bytes())
        check("the command is the launcher",
              (out / "bin/fastpy").read_bytes(), bundle.LAUNCHER.encode("ascii"))


def test_bundle_records_what_the_tree_was_built_from():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        fastpy, pkg, out = fake_fastpy(root, "0.3.0"), fake_llvmlite(root, "0.47.0"), root / "out"
        bundle.build(fastpy, pkg, out, "9.99", fake_toolchain())
        fields = dict(
            line.split(": ", 1)
            for line in (out / "usr/lib/fastpy/BUNDLE").read_text(encoding="utf-8").splitlines()
        )
        check("the fields, in order", list(fields), [
            "fastpy", "fastpy-version", "llvmlite", "python", "pyc", "libfastpy_rt.a",
        ])
        check("a directory that is no checkout is `unknown`", fields["fastpy"], "unknown")
        check("fastpy's version is pyproject's", fields["fastpy-version"], "0.3.0")
        check("llvmlite's version is _version.py's", fields["llvmlite"], "0.47.0")
        check("the target Python is recorded", fields["python"], "9.99")
        check("the archive is identified by its hash",
              fields["libfastpy_rt.a"], hashlib.sha256(FAKE_ARCHIVE).hexdigest())


def test_pycs_are_written_for_the_running_python_and_said_missing_otherwise():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        fastpy, pkg = fake_fastpy(root), fake_llvmlite(root)
        out = root / "out"
        said = bundle.build(fastpy, pkg, out, RUNNING, fake_toolchain())
        tag = sys.implementation.cache_tag
        check("this interpreter compiled them", said.startswith("byte-compiled"), True)
        check("every source has its pyc",
              sorted(p.name for p in out.rglob(f"*.{tag}.pyc")),
              sorted(f"{p.stem}.{tag}.pyc" for p in (out / "usr/lib/fastpy").rglob("*.py")))
        pyc = out / "usr/lib/fastpy/compiler/__pycache__" / f"codegen.{tag}.pyc"
        # PEP 552: the flags word after the magic number; bit 0 set means
        # hash-based, bit 1 set means the hash is checked against the source.
        flags = int.from_bytes(pyc.read_bytes()[4:8], "little")
        check("they are checked-hash pycs, valid without the source's mtime",
              flags, 0b11)

        out2 = root / "out2"
        said = bundle.build(fastpy, pkg, out2, "9.99", fake_toolchain())
        check("with no matching Python the report says so",
              said.startswith("NOT byte-compiled"), True)
        check("and no pyc is written", list(out2.rglob("*.pyc")), [])


def test_a_rerun_replaces_the_tree():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        fastpy, pkg, out = fake_fastpy(root), fake_llvmlite(root), root / "out"
        bundle.build(fastpy, pkg, out, "9.99", fake_toolchain())
        stale = write(out / "usr/lib/fastpy/compiler/removed_upstream.py", "gone\n")
        bundle.build(fastpy, pkg, out, "9.99", fake_toolchain())
        check("a file the new tree lacks does not survive into it", stale.exists(), False)


def test_a_directory_it_did_not_make_is_left_alone():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        fastpy, pkg, out = fake_fastpy(root), fake_llvmlite(root), root / "out"
        precious = write(out / "notes.txt", "mine\n")
        err = raises(bundle.build, fastpy, pkg, out, "9.99", fake_toolchain())
        check("a non-empty directory without BUNDLE is refused",
              err is not None and "left alone" in err, True)
        check("and its contents are untouched", precious.read_bytes(), b"mine\n")

        empty = root / "empty"
        empty.mkdir()
        bundle.build(fastpy, pkg, empty, "9.99", fake_toolchain())
        check("an empty directory is used", (empty / "usr/lib/fastpy/BUNDLE").is_file(), True)


def test_the_launcher_runs_the_installed_compiler():
    text = bundle.LAUNCHER
    check("its first line names the image's interpreter",
          text.splitlines()[0], "#!/bin/python3")
    check("it puts the installed compiler first on the path",
          'sys.path.insert(0, "/usr/lib/fastpy")' in text, True)
    check("it is ASCII, as a #! line must be readable before any decoding",
          text.isascii(), True)
    compile(text, "fastpy", "exec")  # raises -- and fails the suite -- if not Python
    check("it is Python", True, True)


def test_main_reports_a_failure_in_one_line_and_exits_1():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        missing = root / "no-fastpy"
        missing.mkdir()
        saved_err = sys.stderr
        sys.stderr = captured = io.StringIO()
        try:
            rc = bundle.main(["--fastpy", str(missing), "--out", str(root / "out")])
        finally:
            sys.stderr = saved_err
        check("a missing checkout exits 1", rc, 1)
        check("with one line naming the problem",
              captured.getvalue().count("\n") == 1
              and captured.getvalue().startswith("fastpy-bundle: "), True)


def main() -> int:
    """Auto-discover `test_*`. The floor is there because a suite that finds
    no tests prints nothing and exits 0, which reads as a pass."""
    tests = [(name, fn) for name, fn in list(globals().items())
             if name.startswith("test_") and callable(fn)]
    if len(tests) < 12:
        print(f"FATAL: found only {len(tests)} tests; the suite has 12. "
              "Discovery is broken, not the code.")
        return 1
    for _, fn in sorted(tests):
        if inspect.signature(fn).parameters:
            print(f"FATAL: {fn.__name__} takes arguments; the runner passes none")
            return 1
        fn()
    print()
    if _FAILURES:
        print(f"{len(_FAILURES)} FAILED: {', '.join(_FAILURES)}")
        return 1
    print(f"all {len(tests)} fastpy-slateos-bundle test groups passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
