//! The measurement itself: TCP connections to a public test server, timed.
//!
//! A run is three phases, one after another, on a thread of its own that
//! reports back as it goes ([`Report`]), waking the window each time:
//!
//! 1. **Latency** -- `probes` TCP connections opened and closed, each timed
//!    from `connect` to established. The handshake is one round trip, so the
//!    time *is* the round trip, measured without any server-side processing
//!    in it. A connection that fails or times out is reported as such: TCP
//!    retransmits a lost packet itself, so what an application can count is a
//!    failed probe, not a lost packet.
//! 2. **Download** -- `connections` connections at once, each asking for the
//!    server's large test file over plain HTTP and counting the bytes that
//!    arrive, until the phase's time is up. A file that ends early is simply
//!    asked for again, so a fast line is never capped by the file's size.
//! 3. **Upload** -- the same, sending: each connection posts a body of
//!    generated bytes to the server's upload address, counting what it
//!    writes. A server that takes no uploads skips the phase and says so
//!    ([`Report::NoUpload`]) rather than reporting zero.
//!
//! The counts are sampled every [`SAMPLE_EVERY`] and reported with the time
//! they were counted over, so the window computes a rate from real elapsed
//! time, not from how often it happened to be woken.
//!
//! Dropping a [`Run`] cancels it: closing the window stops the traffic.

use crate::TestKind;
use std::io::{self, Read, Write};
use std::net::{SocketAddr, TcpStream, ToSocketAddrs};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex, mpsc};
use std::task::Waker;
use std::time::{Duration, Instant};

/// How often the byte counts are reported while bytes move.
pub const SAMPLE_EVERY: Duration = Duration::from_millis(250);

/// How long a latency probe may take before it counts as failed.
pub const PROBE_TIMEOUT: Duration = Duration::from_secs(2);

/// The pause between latency probes, so they are separate samples of the
/// path rather than a burst that measures its own queueing.
pub const PROBE_GAP: Duration = Duration::from_millis(100);

/// How long a transfer connection may take to be established.
pub const CONNECT_TIMEOUT: Duration = Duration::from_secs(5);

/// How long one read or write may block before the connection checks the
/// deadline and the cancel flag again.
const IO_SLICE: Duration = Duration::from_millis(250);

/// The most of a response's head (status line and headers) read before it
/// is taken for something other than HTTP.
const MAX_HEAD: usize = 16 * 1024;

/// The body each upload request declares and sends. Several are sent, one
/// after another, if the phase outlasts one.
const UPLOAD_BODY: u64 = 16 * 1024 * 1024;

/// Where a run sends its traffic.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Endpoint {
    /// The server's name, as its operator publishes it.
    pub host: String,
    pub port: u16,
    /// Path of a large file to download.
    pub download: String,
    /// Path that accepts an upload (an HTTP POST), if the server offers one.
    pub upload: Option<String>,
}

/// How much a run does.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Plan {
    /// Latency probes.
    pub probes: u32,
    /// Connections used at once in each transfer phase.
    pub connections: u32,
    /// How long each transfer phase lasts.
    pub duration: Duration,
}

/// What a run tells the window.
#[derive(Clone, Debug, PartialEq)]
pub enum Report {
    /// One latency probe: the connect time in milliseconds, or `None` when
    /// the connection failed or timed out.
    Probe(Option<f64>),
    /// Bytes moved in the phase under way, and the time since the last
    /// report they were counted over.
    Moved { bytes: u64, over: Duration },
    /// A phase has finished.
    Done(TestKind),
    /// The server takes no uploads, so the upload phase was skipped.
    NoUpload,
    /// The run cannot go on, and why. Nothing follows it.
    Failed(String),
}

/// A run in progress.
pub struct Run {
    cancel: Arc<AtomicBool>,
    reports: mpsc::Receiver<Report>,
}

impl Run {
    /// Start a run against `endpoint`, waking `waker` with each report.
    ///
    /// # Errors
    ///
    /// When the thread the run needs cannot be started.
    pub fn start(endpoint: Endpoint, plan: Plan, waker: Option<Waker>) -> io::Result<Self> {
        let cancel = Arc::new(AtomicBool::new(false));
        let (tx, reports) = mpsc::channel();
        let flag = Arc::clone(&cancel);
        std::thread::Builder::new()
            .name(String::from("speedtest-run"))
            .spawn(move || {
                let tell = |report: Report| {
                    // The window may have closed and dropped the receiver;
                    // then there is nobody to tell, and the cancel flag
                    // (set by that drop) ends the run at its next check.
                    let _ = tx.send(report);
                    if let Some(waker) = &waker {
                        waker.wake_by_ref();
                    }
                };
                run(&endpoint, plan, &flag, &tell);
            })?;
        Ok(Self { cancel, reports })
    }

    /// Stop the run: every connection closes at its next check, within
    /// [`IO_SLICE`] or a probe's timeout.
    pub fn cancel(&self) {
        self.cancel.store(true, Ordering::Relaxed);
    }

    /// Every report that has arrived, oldest first.
    #[must_use]
    pub fn drain(&self) -> Vec<Report> {
        self.reports.try_iter().collect()
    }
}

impl Drop for Run {
    fn drop(&mut self) {
        self.cancel();
    }
}

/// The three phases, in order, reporting through `tell`.
fn run(endpoint: &Endpoint, plan: Plan, cancel: &AtomicBool, tell: &dyn Fn(Report)) {
    // Resolved once, before anything is timed: a name lookup is not the
    // connection's latency.
    let addr = match resolve(endpoint) {
        Ok(addr) => addr,
        Err(why) => return tell(Report::Failed(why)),
    };

    for n in 0..plan.probes {
        if cancel.load(Ordering::Relaxed) {
            return;
        }
        if n > 0 {
            std::thread::sleep(PROBE_GAP);
        }
        let started = Instant::now();
        let ms = TcpStream::connect_timeout(&addr, PROBE_TIMEOUT)
            .ok()
            .map(|_| started.elapsed().as_secs_f64() * 1000.0);
        tell(Report::Probe(ms));
    }
    tell(Report::Done(TestKind::Latency));

    if cancel.load(Ordering::Relaxed) {
        return;
    }
    if let Err(why) = transfer(addr, endpoint, Direction::Down, plan, cancel, tell) {
        return tell(Report::Failed(why));
    }
    tell(Report::Done(TestKind::Download));

    if cancel.load(Ordering::Relaxed) {
        return;
    }
    if endpoint.upload.is_none() {
        tell(Report::NoUpload);
    } else if let Err(why) = transfer(addr, endpoint, Direction::Up, plan, cancel, tell) {
        return tell(Report::Failed(why));
    }
    tell(Report::Done(TestKind::Upload));
}

/// The first address `endpoint`'s host names.
fn resolve(endpoint: &Endpoint) -> Result<SocketAddr, String> {
    (endpoint.host.as_str(), endpoint.port)
        .to_socket_addrs()
        .map_err(|e| format!("cannot find {}: {e}", endpoint.host))?
        .next()
        .ok_or_else(|| format!("{} names no address", endpoint.host))
}

/// Which way the bytes go.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Direction {
    Down,
    Up,
}

/// One transfer phase: `plan.connections` connections moving bytes until
/// `plan.duration` is up, the count reported every [`SAMPLE_EVERY`].
fn transfer(
    addr: SocketAddr,
    endpoint: &Endpoint,
    dir: Direction,
    plan: Plan,
    cancel: &AtomicBool,
    tell: &dyn Fn(Report),
) -> Result<(), String> {
    let moved = AtomicU64::new(0);
    let first_error: Mutex<Option<String>> = Mutex::new(None);
    let started = Instant::now();
    // A duration too long to add is a phase with no time in it, not a panic.
    let deadline = started.checked_add(plan.duration).unwrap_or(started);
    let stop = || cancel.load(Ordering::Relaxed) || Instant::now() >= deadline;

    std::thread::scope(|scope| {
        for _ in 0..plan.connections.max(1) {
            scope.spawn(|| {
                while !stop() {
                    let outcome = match dir {
                        Direction::Down => download_once(addr, endpoint, &stop, &moved),
                        Direction::Up => upload_once(addr, endpoint, &stop, &moved),
                    };
                    if let Err(e) = outcome {
                        if let Ok(mut slot) = first_error.lock() {
                            slot.get_or_insert(e);
                        }
                        // One failed connection is not the phase failing;
                        // but a connection that cannot succeed should not
                        // hammer the server trying.
                        break;
                    }
                }
            });
        }

        let mut last = started;
        let mut reported = 0_u64;
        loop {
            let now = Instant::now();
            let done = now >= deadline || cancel.load(Ordering::Relaxed);
            if !done {
                std::thread::sleep(SAMPLE_EVERY.min(deadline.saturating_duration_since(now)));
            }
            let now = Instant::now();
            let total = moved.load(Ordering::Relaxed);
            tell(Report::Moved {
                bytes: total.saturating_sub(reported),
                over: now.saturating_duration_since(last),
            });
            reported = total;
            last = now;
            if done {
                break;
            }
        }
    });

    if moved.load(Ordering::Relaxed) == 0 && !cancel.load(Ordering::Relaxed) {
        let why = first_error
            .lock()
            .ok()
            .and_then(|mut slot| slot.take())
            .unwrap_or_else(|| String::from("the server sent nothing"));
        return Err(why);
    }
    Ok(())
}

/// The request line and headers for `method` on `path`.
fn request_head(method: &str, path: &str, endpoint: &Endpoint, extra: &str) -> String {
    let host = if endpoint.port == 80 {
        endpoint.host.clone()
    } else {
        format!("{}:{}", endpoint.host, endpoint.port)
    };
    format!(
        "{method} {path} HTTP/1.1\r\nHost: {host}\r\nUser-Agent: SlateOS-SpeedTest/1\r\nAccept: */*\r\n{extra}Connection: close\r\n\r\n"
    )
}

/// A connection with short I/O timeouts, so its loops can look at the clock
/// and the cancel flag between reads.
fn open(addr: SocketAddr) -> Result<TcpStream, String> {
    let stream = TcpStream::connect_timeout(&addr, CONNECT_TIMEOUT)
        .map_err(|e| format!("cannot connect to {addr}: {e}"))?;
    stream
        .set_read_timeout(Some(IO_SLICE))
        .and_then(|()| stream.set_write_timeout(Some(IO_SLICE)))
        .map_err(|e| format!("cannot set up the connection: {e}"))?;
    Ok(stream)
}

/// Whether an I/O error is only a slice running out.
fn is_slice(e: &io::Error) -> bool {
    matches!(
        e.kind(),
        io::ErrorKind::WouldBlock | io::ErrorKind::TimedOut
    )
}

/// Read a response's head, and return what followed it -- the body's first
/// bytes -- once the status says the request succeeded.
fn read_head(stream: &mut TcpStream, stop: &dyn Fn() -> bool) -> Result<Vec<u8>, String> {
    let mut buf = Vec::with_capacity(1024);
    let mut chunk = [0_u8; 1024];
    let end = loop {
        if let Some(at) = buf.windows(4).position(|w| w == b"\r\n\r\n") {
            break at;
        }
        if buf.len() > MAX_HEAD {
            return Err(String::from("the server's reply is not HTTP"));
        }
        if stop() {
            return Ok(Vec::new());
        }
        match stream.read(&mut chunk) {
            Ok(0) => {
                return Err(String::from(
                    "the server closed the connection without answering",
                ));
            }
            Ok(n) => buf.extend_from_slice(chunk.get(..n).unwrap_or_default()),
            Err(e) if is_slice(&e) => {}
            Err(e) => return Err(format!("the connection broke: {e}")),
        }
    };
    let head = buf.get(..end).unwrap_or_default();
    let status_line = head.split(|&b| b == b'\r').next().unwrap_or_default();
    // Printable ASCII only, and bounded: it is said in the window.
    let status: String = status_line
        .iter()
        .take(80)
        .map(|&b| {
            if b.is_ascii_graphic() || b == b' ' {
                char::from(b)
            } else {
                '?'
            }
        })
        .collect();
    let code = status.split(' ').nth(1).unwrap_or_default();
    if !code.starts_with('2') {
        return Err(format!("the server answered \"{status}\""));
    }
    Ok(buf
        .get(end.saturating_add(4)..)
        .unwrap_or_default()
        .to_vec())
}

/// Ask for the test file once, counting what arrives into `moved`, until it
/// ends or `stop` says so.
fn download_once(
    addr: SocketAddr,
    endpoint: &Endpoint,
    stop: &dyn Fn() -> bool,
    moved: &AtomicU64,
) -> Result<(), String> {
    let mut stream = open(addr)?;
    stream
        .write_all(request_head("GET", &endpoint.download, endpoint, "").as_bytes())
        .map_err(|e| format!("cannot send the request: {e}"))?;
    let early = read_head(&mut stream, stop)?;
    moved.fetch_add(early.len() as u64, Ordering::Relaxed);
    let mut buf = vec![0_u8; 64 * 1024];
    while !stop() {
        match stream.read(&mut buf) {
            Ok(0) => return Ok(()),
            Ok(n) => {
                moved.fetch_add(n as u64, Ordering::Relaxed);
            }
            Err(e) if is_slice(&e) => {}
            Err(e) => return Err(format!("the download broke: {e}")),
        }
    }
    Ok(())
}

/// Bytes to upload: a fixed pattern, not zeros, so nothing on the path can
/// make the upload look faster than the line by compressing it.
fn upload_pattern() -> Vec<u8> {
    let mut state = 0x9E37_79B9_u32;
    (0..64 * 1024)
        .map(|_| {
            state ^= state.wrapping_shl(13);
            state ^= state.wrapping_shr(17);
            state ^= state.wrapping_shl(5);
            state.to_le_bytes().first().copied().unwrap_or_default()
        })
        .collect()
}

/// Post one body of [`UPLOAD_BODY`] bytes, counting what is written into
/// `moved`, until it is all sent or `stop` says so.
fn upload_once(
    addr: SocketAddr,
    endpoint: &Endpoint,
    stop: &dyn Fn() -> bool,
    moved: &AtomicU64,
) -> Result<(), String> {
    let Some(path) = &endpoint.upload else {
        return Ok(());
    };
    let mut stream = open(addr)?;
    let extra =
        format!("Content-Type: application/octet-stream\r\nContent-Length: {UPLOAD_BODY}\r\n");
    stream
        .write_all(request_head("POST", path, endpoint, &extra).as_bytes())
        .map_err(|e| format!("cannot send the request: {e}"))?;
    let pattern = upload_pattern();
    let mut sent = 0_u64;
    while sent < UPLOAD_BODY {
        if stop() {
            return Ok(());
        }
        let left = usize::try_from(UPLOAD_BODY.saturating_sub(sent)).unwrap_or(usize::MAX);
        let piece = pattern.get(..pattern.len().min(left)).unwrap_or_default();
        match stream.write(piece) {
            Ok(0) => return Err(String::from("the server stopped taking the upload")),
            Ok(n) => {
                sent = sent.saturating_add(n as u64);
                moved.fetch_add(n as u64, Ordering::Relaxed);
            }
            Err(e) if is_slice(&e) => {}
            Err(e) => return Err(format!("the upload broke: {e}")),
        }
    }
    // The whole body went; the server's answer says whether it was taken.
    read_head(&mut stream, stop).map(|_| ())
}

/// A plain-HTTP test server on a loopback port, for this module's tests and
/// the window's: no test reaches the network.
#[cfg(test)]
pub(crate) mod fake {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::arithmetic_side_effects
    )]

    use super::UPLOAD_BODY;
    use std::io::{self, Read, Write};
    use std::net::{TcpListener, TcpStream};
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::{Arc, Mutex};
    use std::time::{Duration, Instant};

    /// A test server on a loopback port: answers a GET with `body_len` bytes
    /// and a POST by reading its body and saying how much came, and counts
    /// the requests it saw by method.
    pub struct Server {
        pub port: u16,
        pub gets: Arc<AtomicUsize>,
        pub posts: Arc<AtomicUsize>,
        pub heads: Arc<Mutex<Vec<String>>>,
    }

    /// How long one read waits before looking at the clock again.
    pub const READ_SLICE: Duration = Duration::from_millis(100);
    /// How long a connection may go quiet before the server gives up on it.
    ///
    /// A pause is not the end of an upload. This server once stopped at the
    /// first read that waited five seconds, answered, and closed with the rest
    /// of the body unread, so the client's next write was refused (Windows:
    /// "forcibly closed", os error 10054). On a machine busy enough to keep
    /// the client off the processor for five seconds -- a workspace test run
    /// -- that failed tests which were right.
    pub const PATIENCE: Duration = Duration::from_mins(2);

    /// `stream.read`, waiting out any number of [`READ_SLICE`]s with nothing
    /// to read until `deadline`: `Ok(0)` is the other side gone, an error a
    /// real one or the deadline passed.
    fn read_patiently(
        stream: &mut TcpStream,
        buf: &mut [u8],
        deadline: Instant,
    ) -> io::Result<usize> {
        loop {
            match stream.read(buf) {
                Err(e)
                    if matches!(
                        e.kind(),
                        io::ErrorKind::WouldBlock | io::ErrorKind::TimedOut
                    ) && Instant::now() < deadline => {}
                other => return other,
            }
        }
    }

    pub fn server(status: &'static str, body_len: usize) -> Server {
        let listener = TcpListener::bind("127.0.0.1:0").expect("a loopback port");
        let port = listener.local_addr().expect("its address").port();
        let gets = Arc::new(AtomicUsize::new(0));
        let posts = Arc::new(AtomicUsize::new(0));
        let heads = Arc::new(Mutex::new(Vec::new()));
        let (g, p, h) = (Arc::clone(&gets), Arc::clone(&posts), Arc::clone(&heads));
        std::thread::spawn(move || {
            for stream in listener.incoming() {
                let Ok(mut stream) = stream else { continue };
                let (g, p, h) = (Arc::clone(&g), Arc::clone(&p), Arc::clone(&h));
                std::thread::spawn(move || {
                    let _ = stream.set_read_timeout(Some(READ_SLICE));
                    let deadline = Instant::now() + PATIENCE;
                    let mut head = Vec::new();
                    let mut byte = [0_u8; 1];
                    while !head.ends_with(b"\r\n\r\n") {
                        match read_patiently(&mut stream, &mut byte, deadline) {
                            Ok(1) => head.push(byte[0]),
                            _ => return, // a latency probe: connected, then gone
                        }
                    }
                    let head = String::from_utf8(head).unwrap_or_default();
                    h.lock().unwrap().push(head.clone());
                    if head.starts_with("GET") {
                        g.fetch_add(1, Ordering::SeqCst);
                        let reply = format!(
                            "HTTP/1.1 {status}\r\nContent-Length: {body_len}\r\nConnection: close\r\n\r\n"
                        );
                        // One write, head and body together, so the client's
                        // first read holds the body's first bytes -- the case
                        // `download_once` must count and could forget.
                        let mut whole = reply.into_bytes();
                        if status.starts_with('2') {
                            whole.extend(std::iter::repeat_n(7_u8, body_len));
                        }
                        let _ = stream.write_all(&whole);
                    } else {
                        p.fetch_add(1, Ordering::SeqCst);
                        let mut got = 0_usize;
                        let mut buf = vec![0_u8; 65536];
                        while let Ok(n) = read_patiently(&mut stream, &mut buf, deadline) {
                            if n == 0 {
                                break;
                            }
                            got += n;
                            if got as u64 >= UPLOAD_BODY {
                                break;
                            }
                        }
                        let _ = stream.write_all(
                            format!("HTTP/1.1 {status}\r\nContent-Length: 0\r\n\r\n").as_bytes(),
                        );
                    }
                });
            }
        });
        Server {
            port,
            gets,
            posts,
            heads,
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::panic,
        clippy::arithmetic_side_effects
    )]

    use super::fake::server;
    use super::*;

    fn endpoint(port: u16, upload: bool) -> Endpoint {
        Endpoint {
            host: String::from("127.0.0.1"),
            port,
            download: String::from("/big.bin"),
            upload: upload.then(|| String::from("/upload")),
        }
    }

    /// Run to the end, collecting every report.
    fn collect(endpoint: Endpoint, plan: Plan) -> Vec<Report> {
        let run = Run::start(endpoint, plan, None).expect("a run");
        let mut all = Vec::new();
        let give_up = Instant::now() + Duration::from_secs(30);
        loop {
            let got = run.drain();
            let finished = got
                .iter()
                .any(|r| matches!(r, Report::Done(TestKind::Upload) | Report::Failed(_)));
            all.extend(got);
            if finished {
                return all;
            }
            assert!(Instant::now() < give_up, "the run never finished: {all:?}");
            std::thread::sleep(Duration::from_millis(20));
        }
    }

    fn moved(reports: &[Report]) -> u64 {
        reports
            .iter()
            .map(|r| match r {
                Report::Moved { bytes, .. } => *bytes,
                _ => 0,
            })
            .sum()
    }

    const QUICK: Plan = Plan {
        probes: 3,
        connections: 2,
        duration: Duration::from_millis(600),
    };

    /// **A run measures what the server actually moved**: probes that
    /// connected, every byte of every file the server sent (asked for again
    /// when it ended early), an upload the server read, and the three phases
    /// in order.
    #[test]
    fn a_run_measures_what_the_server_moved() {
        let srv = server("200 OK", 256 * 1024);
        let reports = collect(endpoint(srv.port, true), QUICK);

        let probes: Vec<&Option<f64>> = reports
            .iter()
            .filter_map(|r| match r {
                Report::Probe(ms) => Some(ms),
                _ => None,
            })
            .collect();
        assert_eq!(probes.len(), 3);
        assert!(
            probes.iter().all(|p| p.is_some_and(|ms| ms >= 0.0)),
            "{probes:?}"
        );

        let done: Vec<&Report> = reports
            .iter()
            .filter(|r| matches!(r, Report::Done(_)))
            .collect();
        assert_eq!(
            done,
            [
                &Report::Done(TestKind::Latency),
                &Report::Done(TestKind::Download),
                &Report::Done(TestKind::Upload)
            ]
        );
        let latency_done = reports
            .iter()
            .position(|r| *r == Report::Done(TestKind::Latency))
            .unwrap();
        let download_done = reports
            .iter()
            .position(|r| *r == Report::Done(TestKind::Download))
            .unwrap();
        let down = moved(reports.get(latency_done..download_done).unwrap());
        let up = moved(reports.get(download_done..).unwrap());
        let gets = srv.gets.load(Ordering::SeqCst) as u64;
        assert!(gets >= 2, "each connection asked at least once: {gets}");
        // Something was counted, and nothing more than the server sent. How
        // much arrives in the time is the machine's business; that every byte
        // is counted exactly is pinned by `one_request_counts_every_byte`.
        assert!(down > 0, "the download moved nothing");
        assert!(
            down <= gets * 256 * 1024,
            "counted {down}, more than {gets} files hold"
        );
        assert!(up > 0, "the upload moved nothing");

        let heads = srv.heads.lock().unwrap().clone();
        let get = heads.iter().find(|h| h.starts_with("GET")).expect("a GET");
        assert!(get.starts_with("GET /big.bin HTTP/1.1\r\n"), "{get}");
        assert!(
            get.contains(&format!("\r\nHost: 127.0.0.1:{}\r\n", srv.port)),
            "{get}"
        );
        assert!(get.contains("\r\nConnection: close\r\n"), "{get}");
        let post = heads
            .iter()
            .find(|h| h.starts_with("POST"))
            .expect("a POST");
        assert!(post.starts_with("POST /upload HTTP/1.1\r\n"), "{post}");
        assert!(
            post.contains(&format!("Content-Length: {UPLOAD_BODY}\r\n")),
            "{post}"
        );
    }

    /// One request counts every byte of the file, and one upload every byte
    /// of its body -- exactly, with no clock involved.
    #[test]
    fn one_request_counts_every_byte() {
        let srv = server("200 OK", 300_000);
        let addr: SocketAddr = format!("127.0.0.1:{}", srv.port).parse().unwrap();
        let ep = endpoint(srv.port, true);
        let never = || false;
        let moved = AtomicU64::new(0);
        download_once(addr, &ep, &never, &moved).unwrap();
        assert_eq!(moved.load(Ordering::Relaxed), 300_000);
        let sent = AtomicU64::new(0);
        upload_once(addr, &ep, &never, &sent).unwrap();
        assert_eq!(sent.load(Ordering::Relaxed), UPLOAD_BODY);
    }

    /// **The test server waits out a client that goes quiet mid-upload**:
    /// it took the first read that waited as the end of the body, answered,
    /// and closed with the rest unread, so on a busy machine the upload
    /// broke ("forcibly closed", os error 10054) in a test that was right.
    /// Two pauses of three read slices each, and the whole body is taken.
    #[test]
    fn the_test_server_waits_out_a_client_that_goes_quiet() {
        use std::net::TcpStream;
        let srv = server("200 OK", 0);
        let mut stream = TcpStream::connect(("127.0.0.1", srv.port)).unwrap();
        // A server that never answers fails the test rather than hanging it.
        stream
            .set_read_timeout(Some(super::fake::PATIENCE + Duration::from_secs(10)))
            .unwrap();
        let pause = super::fake::READ_SLICE * 3;
        stream
            .write_all(
                format!("POST /upload HTTP/1.1\r\nContent-Length: {UPLOAD_BODY}\r\n\r\n")
                    .as_bytes(),
            )
            .unwrap();
        std::thread::sleep(pause);
        let half = vec![7_u8; usize::try_from(UPLOAD_BODY / 2).unwrap()];
        stream.write_all(&half).unwrap();
        std::thread::sleep(pause);
        stream.write_all(&half).unwrap();
        let mut answer = [0_u8; 15];
        stream.read_exact(&mut answer).unwrap();
        assert_eq!(&answer, b"HTTP/1.1 200 OK", "the server gave up on a pause");
    }

    /// A probe that cannot connect is reported as failed, not timed -- and
    /// with nothing listening, the transfer fails the run in words.
    #[test]
    fn a_probe_that_cannot_connect_is_reported_failed() {
        // A port that was just free: nothing listens on it now.
        let port = std::net::TcpListener::bind("127.0.0.1:0")
            .unwrap()
            .local_addr()
            .unwrap()
            .port();
        let plan = Plan { probes: 1, ..QUICK };
        let reports = collect(endpoint(port, true), plan);
        assert_eq!(reports.first(), Some(&Report::Probe(None)), "{reports:?}");
        assert!(
            matches!(reports.last(), Some(Report::Failed(why)) if why.contains("cannot connect")),
            "{reports:?}"
        );
    }

    /// A server that takes no uploads skips the phase, and says it did --
    /// an upload of zero would be a claim about the line.
    #[test]
    fn a_server_that_takes_no_uploads_skips_the_phase() {
        let srv = server("200 OK", 64 * 1024);
        let reports = collect(endpoint(srv.port, false), QUICK);
        assert!(reports.contains(&Report::NoUpload));
        assert_eq!(
            srv.posts.load(Ordering::SeqCst),
            0,
            "posted to a server with no upload"
        );
        assert_eq!(reports.last(), Some(&Report::Done(TestKind::Upload)));
    }

    /// A server that refuses the file fails the run, in its own words, and
    /// nothing is reported after.
    #[test]
    fn a_refused_download_fails_the_run_in_the_servers_words() {
        let srv = server("404 Not Found", 10);
        let reports = collect(endpoint(srv.port, true), QUICK);
        let Some(Report::Failed(why)) = reports.last() else {
            panic!("the run did not fail: {reports:?}");
        };
        assert!(why.contains("404 Not Found"), "{why}");
        assert!(!reports.contains(&Report::Done(TestKind::Download)));
    }

    /// Cancelling stops a long run well before its time is up.
    #[test]
    fn a_cancelled_run_stops() {
        let srv = server("200 OK", 1 << 20);
        let plan = Plan {
            probes: 1,
            connections: 1,
            duration: Duration::from_secs(20),
        };
        let run = Run::start(endpoint(srv.port, true), plan, None).expect("a run");
        std::thread::sleep(Duration::from_millis(400));
        let started = Instant::now();
        run.cancel();
        let mut seen = Vec::new();
        loop {
            seen.extend(run.drain());
            if seen
                .iter()
                .any(|r| matches!(r, Report::Done(TestKind::Download)))
            {
                break;
            }
            assert!(
                started.elapsed() < Duration::from_secs(5),
                "the download went on after the cancel: {seen:?}"
            );
            std::thread::sleep(Duration::from_millis(20));
        }
    }

    /// Every byte reported was counted over time that really passed: the
    /// intervals add up to the phase, not to how often anyone looked.
    #[test]
    fn the_intervals_add_up_to_the_phase() {
        let srv = server("200 OK", 1 << 20);
        let reports = collect(endpoint(srv.port, false), QUICK);
        let first = reports
            .iter()
            .position(|r| *r == Report::Done(TestKind::Latency))
            .unwrap();
        let last = reports
            .iter()
            .position(|r| *r == Report::Done(TestKind::Download))
            .unwrap();
        let spent: Duration = reports
            .get(first..last)
            .unwrap()
            .iter()
            .map(|r| match r {
                Report::Moved { over, .. } => *over,
                _ => Duration::ZERO,
            })
            .sum();
        assert!(
            spent >= QUICK.duration && spent < QUICK.duration + Duration::from_millis(250),
            "the intervals add up to {spent:?} for a {:?} phase",
            QUICK.duration
        );
    }

    /// The upload's bytes are not all one value, so nothing on the path can
    /// compress them into a faster-looking line.
    #[test]
    fn the_upload_bytes_do_not_compress() {
        let pattern = upload_pattern();
        let distinct = pattern
            .iter()
            .collect::<std::collections::HashSet<_>>()
            .len();
        assert!(distinct > 200, "only {distinct} distinct byte values");
    }
}
