//! The system's name and version strings — one definition, four publishers.
//!
//! The kernel is asked "what system is this?" through more than one door:
//! `uname(2)`, `/proc/sys/kernel/{ostype,osrelease,version}`,
//! `/sys/kernel/{ostype,osrelease,version}`, and the `kernel.ostype` /
//! `kernel.osrelease` sysctl parameters. Every one of those is generated by a
//! different file in this tree, and before this module existed three of the four
//! had their own private copy of the answer. They disagreed: procfs said
//! `Linux` / `6.6.0-slateos`, sysfs said `MintOS` / `0.1.0-dev`, and the sysctl
//! registry said `MintOS` / `0.1.0` — three answers a program could pick between
//! with no way to tell which was authoritative. Lane B found the same shape on
//! its side of the tree (four components, four names) and reported this half in
//! `requests/b-a-sysfs-says-mintos-while-procfs-says-linux.md`.
//!
//! Copying is what produced the divergence, so the fix is to stop copying rather
//! than to re-synchronise the copies: every publisher reads the constants below,
//! and a future one that does not is the only way to reintroduce the bug.
//!
//! ## Why the Linux personality, and why it is not a lie
//!
//! Settled policy — `roadmap-detailed.md` §72 "Version-surface policy",
//! user-directed 2026-06-10. `uname(2)` and the two filesystems that mirror it
//! (`/proc` and `/sys` are Linux inventions; native SlateOS code uses native
//! APIs and never reads them) are **Linux-ABI-only surfaces**, so the only
//! callers are Linux binaries that expect Linux values. Reporting `Linux` tells
//! such a program exactly which Linux personality it is talking to, which is the
//! faithful answer for that ABI rather than a claim about what we are.
//!
//! [`RELEASE`] is the field with teeth. glibc's `__libc_start_main` parses the
//! leading integer triple and aborts the process with "FATAL: kernel too old" if
//! it is below glibc's build-time minimum. `6.6.0-slateos` reads as the 6.6.0
//! baseline we faithfully implement and clears that gate; the old sysfs value
//! `0.1.0-dev` would have failed it, which is why the divergence was worth
//! fixing even though nothing read the sysfs copy yet — the failure mode is a
//! ported program aborting at start-up with no visible cause.
//!
//! ## Where the product name still belongs
//!
//! [`OPERATING_SYSTEM`] is *not* part of `struct utsname` on Linux either: GNU's
//! `uname -o` is a compile-time constant, which is how GNU reports `Linux` for
//! `-s` and `GNU/Linux` for `-o` without contradicting itself. That is the slot
//! the product name belongs in, and it is spelled without a space deliberately —
//! `uname -a` is routinely split on whitespace, so a two-word field silently
//! becomes two fields. Lane B's `userspace/coreutils/src/bin/uname.rs` reached
//! the same spelling independently; this constant matches it byte for byte so
//! the in-kernel shell's `uname` and the ring-3 one cannot disagree.
//!
//! Branding that is *not* an ABI surface — boot banners, the login screen, the
//! HTTP `Server:` header, disk labels — is untouched by this module and stays
//! whatever it was. This is about the four doors that answer the same question.

use crate::serial_println;

/// `uname(2)` `sysname`, and `…/kernel/ostype`.
pub const SYSNAME: &str = "Linux";

/// `uname(2)` `release`, and `…/kernel/osrelease`.
///
/// Must keep a leading `MAJOR.MINOR` at or above glibc's minimum — see the
/// module docs. Changing the `6.6` prefix can abort every dynamically linked
/// glibc program on the image at start-up.
pub const RELEASE: &str = "6.6.0-slateos";

/// `uname(2)` `version`, and `…/kernel/version`.
///
/// Linux puts the build counter, config summary and build date here. We report
/// the counter and SMP marker only: a build date would make the string differ
/// between two kernels built from identical sources, which turns a byte-equality
/// check between publishers into a flake.
pub const VERSION: &str = "#1 SMP";

/// `uname(2)` `machine`. The only target this kernel builds for.
pub const MACHINE: &str = "x86_64";

/// The operating system as distinct from the kernel ABI it presents — GNU
/// `uname -o`. Not a `struct utsname` field on Linux either; see the module docs
/// for why it is one word.
pub const OPERATING_SYSTEM: &str = "SlateOS";

// ---------------------------------------------------------------------------
// Self-test
// ---------------------------------------------------------------------------

/// Check the two properties of these strings that a caller can be broken by.
///
/// Deliberately *not* a test that the constants equal themselves — a check like
/// that passes by construction and would only re-encode the literals a fifth
/// time. The cross-publisher agreement is checked where the publishers are, by
/// [`crate::fs::sysfs::self_test`], which compares generated bytes rather than
/// constants and so also catches a generator that stops reading this module.
pub fn self_test() {
    serial_println!("[uname] Running self-test...");

    // 1. The glibc start-up gate. `__libc_start_main` parses the leading
    //    integer triple of `release` and aborts the process with "FATAL: kernel
    //    too old" if it is below glibc's build-time minimum, so a bad value
    //    here kills every dynamically linked glibc program on the image at a
    //    point far from this file. Parse it the way glibc does.
    let mut parts = RELEASE.split(['.', '-']);
    let major: u32 = parts.next().and_then(|s| s.parse().ok()).unwrap_or(0);
    let minor: u32 = parts.next().and_then(|s| s.parse().ok()).unwrap_or(0);
    assert!(
        major > 6 || (major == 6 && minor >= 6),
        "release {RELEASE} parses as {major}.{minor}, below the 6.6 baseline"
    );
    serial_println!("[uname]   release {} parses as {}.{}: OK", RELEASE, major, minor);

    // 2. Whitespace. `uname -a` prints the fields space-separated and callers
    //    routinely split it on whitespace, so a two-word field silently becomes
    //    two fields and shifts everything after it. `VERSION` is the documented
    //    exception — `#1 SMP` has a space on real Linux too, and anything
    //    parsing `uname -a` already knows the version field is the ragged one.
    for f in [SYSNAME, RELEASE, MACHINE, OPERATING_SYSTEM] {
        assert!(
            !f.contains(char::is_whitespace),
            "uname field {f:?} would split into two fields in `uname -a`"
        );
    }
    serial_println!("[uname]   single-token fields: OK");

    serial_println!("[uname] Self-test PASSED");
}
